### ISSUE TITLE
no Email notifications after uploads to shared folder for users

### ISSUE THREAD

**Issue by randomnickname1337** [nextcloud/groupfolders#101]
Hi, 
is here any possibility to get notification, when something in group folder was changed ? 
For example: when I upload file to group folder, users in group with rights to this folder get automatically email notification ?

**Comment by davideapvd** [comment]
I've implemented something similar extending 
`OCA\FilesDownloadActivity\Activity\Listener::readFile`  and generating another share event picking users in the admin group (fine in my case but you are asking to pick users of that group folder instead).

If this solution is implemented upstream I'm also interested.

**Comment by randomnickname1337** [comment]
this feature will be great , especially in shared group folders .... 
Im not able to make this on NEXTCLOUD Level ... 

My solution: 
Im using linux script and if some files are never as X hours it sends me email ... Not cleanest and best solution but it works ... :D

**Comment by Nils160988** [comment]
This feature so far works for shared folders, if you are not using the groupfolder app. Must be Nextcloud 13.0.1
I think, it should be working like this for the groupfolders as well, but I am not sure, I filed a bug against the activity app: https://github.com/nextcloud/activity/issues/244

**Comment by randomnickname1337** [comment]
Im using Group Folder App - Different User rights , in different sub folders ... 
and I can confirm , it not works .. Im still on 12.0.x because after update to 13.0 i had more problems, so Im waiting with update... 

Email Notification after activity is for me must have ... so as I said , at the moment doing bash script this job ...

**Comment by squalo80** [comment]
Repost also on this issue.
On NextCloud 13.0.4 updated this morning i cannot see mail notification if any files or folders are create or updated INSIDE a shared folder.
Seems also that if you are inside a group and the folder is shared to the group instead the user you don't receive notification.

**Comment by randomnickname1337** [comment]
@squalo80 any update here ?

**Comment by squalo80** [comment]
No, seems nothing to mention.

**Comment by randomnickname1337** [comment]
ok, staying at 13.0.1 , not going upgrade NC

**Comment by Nils160988** [comment]
The upgrade doesn't help for this issue, but you should upgrade because of other fixes and it also doesn't break anything.

**Comment by bigcookie** [comment]
Hello randomnickname1337, would you be willing to share your script? I am having the exact same issue and need to send an email to all members of a group an email on changes within the group folders. Thank, regards

**Comment by kokotko1337** [comment]
> Hello randomnickname1337, would you be willing to share your script? I am having the exact same issue and need to send an email to all members of a group an email on changes within the group folders. Thank, regards

sorry i was not here longer time ... if still interested hit me with message

**Comment by bigcookie** [comment]
Hello,

 

not sure if this is the correct way to reach you as I couldnt find any option to send private messages on Github. I am interested and would be glad to hear from you. regards,

 

André

 

 


Gesendet: Montag, 17. September 2018 um 08:14 Uhr
Von: kokotko1337 <notifications@github.com>
An: nextcloud/groupfolders <groupfolders@noreply.github.com>
Cc: bigcookie <bigcookie@fantasymail.de>, Comment <comment@noreply.github.com>
Betreff: Re: [nextcloud/groupfolders] Email notifications after uploads to shared folder for users (#101)



Hello randomnickname1337, would you be willing to share your script? I am having the exact same issue and need to send an email to all members of a group an email on changes within the group folders. Thank, regards


sorry i was not here longer time ... if still interested hit me with message

**Comment by randomnickname1337** [comment]
@bigcookie i send you mail today

**Comment by dexter-pereira** [comment]
@randomnickname1337 can you please send this to me as well? 

Is the NC development team planning to implement this? It seems like an oversight to have the ability to use Group folders but not alert users within that group to new files.

**Comment by dexter-pereira** [comment]
@randomnickname1337 can you please send this to me as well?

Is the NC development team planning to implement this? It seems like an oversight to have the ability to use Group folders but not alert users within that group to new files.

**Comment by bigcookie** [comment]
Hi @dexter-pereira,

based on randomnickname1337 solution, I created the following script. It is not ideal and perfectly written and works with only global variables, but it might help you. You have to check/Change all the variables with CAPITAL letters... and you have to put this on a daily cron job. You might want to change the age to be detected as well...

`#!/bin/bash
# Reads Email addresses from given Nextcloud group
# Checks groupfolder for files newer than 1 day
# Sends email to group members if new files are found
# Enabled by cron
#
# V1.0
# First version
#
# V1.1
# - removed sub function abort script
# - cleanup logging and added flag status to log
# - move NextCloud URL into a variable
# - enable curl verbose mode if verbose is set to true
 
# Variables to change
group="GROUPNAME"
admin="NXTCLD_ADMIN_USERNAME"
admin_pw="NXTCLD_ADMIN_PW"
verbose=true # switches echo output off/on
log_enabled=true # enables/disables logging
sendemail=true # for debugging reasons: you can disable email sending
v1_url="https://NXTCLD_IP_or_DAMAIN/ocs/v1.php" # path to your v1.php
groupfolder="/PATH_TO_FOLDER_TO_CHECK_WITH_TRAILING_SLASH/"
 
# mail params
smtp_server="smtp://IP:PORT" # expects TLS, if not, you have to change the mail command below
smtp_user="SMTP_AUTH_USER"
smtp_from="SMTP_FROM_EMAIL"
smtp_pw="SMTP_AUTH_USER_PASSWORD"
mail_subject="SUBJECT FOR EMAIL"
mailtemplate="FILE_WITH_EMAIL_BODY_TEMPLATE" # txt file with email body template. list of new files will be added to this text at the bottom
 
# no need to change beyond here
mailtext="final_email.txt" # filename for cobined email: body from txt-file plus list of newly added files
logfile="sendmail.log"
filelist="new_files.txt"
group_xml="groupdetails.xml"     # tmp file to store the group information
members_xml="groupmembers.txt" # tmp file to store the list of group members
member_tmp="memberdetails.tmp"          # tmp file to store detailed member information
age=1440   # max age in minutes. 1440=1 day
members=() # array of group members
emails=()  # array of found email addresses
curl_verbose=""
######################
# Sub Routines
######################
function log() {
# function to enable echo output and logging.
  ${verbose} || echo "$@"
  ${log_enabled} && echo "$@" >> "${logfile}"
  return 0
}
 
function checkfornewfiles() {
# function checks folder for new files, generates filelist and provides return value indicating new files found or not
  # if list exist, delete it, start fresh
  [ -f "${filelist}" ] && rm "${filelist}"
  find "${groupfolder}" -type f -mmin -${age} -printf "%P\n" > "${filelist}"
  # if list exist and size >0, great, return 0, else return 1
  [ -s "${filelist}" ] && return 0 || return 1
  return 2
}
 
function generateemail() {
# generate final emal text by combining template with filelist.
  cat ${mailtemplate} > "${mailtext}"  
  log "New files found:"
  while read -r line; do
    echo "  - ${line}" >> "${mailtext}"
    log "  - ${line}"
  done < "${filelist}"
  log ""
  return 0
}
 
function cleanup() {
# final cleanup - delete all temporary files and finalize log
  [ -f "${group_xml}" ] && rm "${group_xml}"
  [ -f "${members_xml}" ] && rm "${members_xml}"
  [ -f "${member_tmp}" ] && rm "${member_tmp}"
  [ -f "${mailtext}" ] && rm "${mailtext}"
  [ -f "${filelist}" ] && rm "${filelist}"
  log ""
  return 0
}
 
function send_emails() {
# send email to each user
  local count=0
  for email in ${emails[@]}; do
    mail -s "${mail_subject}" -S ttycharset=iso-8859-1 -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp="${smtp_server}" -S from="${smtp_from}" -S smtp-auth-user="${smtp_user}" -S smtp-auth-password="${smtp_pw}" ${email} < "${mailtext}"
    if [ $? == 0 ]; then
      log "SUCCESS: Email ${count} sent to ${emails[${count}]}"
    else
      log "ERROR  : Email ${count} failed to send to ${emails[${count}]}"
    fi
    ((count+=1))
  done
  return 0
}

######################
# Main
######################
 
# create parameter for curl in case echo output is disabled.
${verbose} && curl_verbose="-s"
 
# Start logging and initiate log section
log ""
log `date`
log "--------------------------------------"

${verbose} && log "Echo output disabled"
${sendemail} || log "Email sending disabled!"
${log_enabled} || log "Logging disabled!"
 
# Check if there are new files and create email body if yes, else stop
checkfornewfiles
[ $? == 1 ] && log "No new files found! No email notification sent!" && exit 0
generateemail
 
# Get Group information with members list
curl ${curl_verbose} ${v1_url}/cloud/groups/${group} -H "OCS-APIRequest: true" -u ${admin}:${admin_pw} -X GET > ${group_xml}
 
# Extract member names and save them temporarily, read them into an array
xmlstarlet sel -t -v '//element' -n "${group_xml}" > "${members_xml}"
while read -r line; do
  members+=("${line}")
done < "${members_xml}"
 
# Foreach found group member, get the email address and store it in an array
for member in ${members[@]}; do
  curl ${curl_verbose} ${v1_url}/cloud/users/${member} -H "OCS-APIRequest: true" -u ${admin}:${admin_pw} -X GET > ${member_tmp}
  emails+=(`xmlstarlet sel -t -v '//email' -n "${member_tmp}"`)
done
# For each found Email-address send the emails
${sendemail} && send_emails
# clean-up, delete temporary files
cleanup
exit 0`

**Comment by dexter-pereira** [comment]
@bigcookie Thanks for this!

**Comment by noresistence** [comment]
Are there any plans to implement this? Is this an issue of groupfolders or of the activities app?

**Comment by Nils160988** [comment]
Have a look at https://github.com/nextcloud/activity/pull/190, this might solve this issue.
Hope it will be merged soon!

**Comment by thechonta** [comment]
14.02.2020  and Nextcloud 18.0.1 out, any plans to enable the notification for Groupfolder activitys?

**Comment by go2sh** [comment]
I wanted to fix this, but in master it does not happen. So I feel #797 fixed this?! @nickvergessen I did a quick check with the web interface and mail and both work.

**Comment by nickvergessen** [comment]
Could very much be the case
