### ISSUE TITLE
Advanced permissions do not show

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/groupfolders#1014]
I maybe doing something really wrong or dumb, but I just can not find where to set the advanced permissions.
I have created a groupfolder with readwrite permission for admin group and readonly permission for somegroup group, and added myself ( from admin group ) ad manager of advanced permissions.

I ( admin ) can see the groupfolder in FilesApp, and someone from somegroup can also see the groupfolder in  files app, but I can not find where I can add advanced permissions to allow one user from somegroup write to that folder.
Most screenshots I see appears that it should show in details, but i only see this:

![image](https://user-images.githubusercontent.com/5522389/90567994-6c2ada80-e181-11ea-94c2-c939abe24760.png)

**Comment by vhalfar** [comment]
Hi @jsalatiel, try to clear cache and hard reload browser, had same issue and this solved my problem.

**Comment by fschrempf** [comment]
I don't think this is solved, see #894.

**Comment by juliushaertl** [comment]
Repoened https://github.com/nextcloud/groupfolders/issues/894 and closing this one as a dupliate
