### ISSUE TITLE
Unable to share subfolders of group folders when using external default storage

### ISSUE THREAD

**Issue by davideapvd** [nextcloud/groupfolders#102]
Hello,
I’m using nextcloud 13.0.0 and groupfolders app, I’ve configured in config.php a default s3 storage

```
array (
    'class' => 'OC\\Files\\ObjectStore\\S3',
    'arguments' => 
    array (
      'bucket' => 'SOMEBUCKETbBB',
      'autocreate' => true,
      'key' => 'SOMEKEY',
      'secret' => 'SOMESECRET',
      'hostname' => 's3-eu-central-1.amazonaws.com',
      'region' => 'eu-central-1',
    ),
  ),

```
I’ve created a group folder where I have sharing and writing permission, if I create and share a subfolder with another user or group, that other user can’t see the newly shared folder.
No error is logged.

Sharing via link works.

**Comment by levonti** [comment]
I have same issue with S3 Primary storage, Nextcloud 16.0.4, Group Folders 4.1.0
If user open direct link, error log:
`Nextcloud[13088]: {index} {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":[{"file":"\/var\/www\/html\/apps\/files\/lib\/Controller\/ViewController.php","line":141,"function":"redirectToFile","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["781820"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"showFile","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["781820"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"showFile"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"showFile"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\ViewController","showFile",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"fileid":"781820","_route":"files.viewcontroller.showFile"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"fileid":"781820","_route":"files.viewcontroller.showFile"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"fileid":"781820","_route":"files.viewcontroller.showFile"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/f\/781820"]},{"file":"\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/apps\/files\/lib\/Controller\/ViewController.php","Line":327,"CustomMessage":"--"}
Nextcloud[13118]: {index} {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":[{"file":"\/var\/www\/html\/apps\/files\/lib\/Controller\/ViewController.php","line":141,"function":"redirectToFile","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["781794"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"showFile","class":"OCA\\Files\\Controller\\ViewController","type":"->","args":["781794"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"showFile"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\ViewController"},"showFile"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\ViewController","showFile",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"fileid":"781794","_route":"files.viewcontroller.showFile"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"fileid":"781794","_route":"files.viewcontroller.showFile"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"fileid":"781794","_route":"files.viewcontroller.showFile"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/f\/781794"]},{"file":"\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/apps\/files\/lib\/Controller\/ViewController.php","Line":327,"CustomMessage":"--"}`

**Comment by fschrempf** [comment]
Is this still a problem? If yes, is it even related to the external S3 storage? #55 looks like a similar problem but not related to external storage.

**Comment by pierreozoux** [comment]
we are using group folders with s3, and I think this has been fixe.

feel free to reopen.
