### ISSUE TITLE
The "Add extended permission rule" list does not display the required users.

### ISSUE THREAD

**Issue by sdenisb** [nextcloud/groupfolders#1032]
Problem when using a group folder assigned to a group of users with more than 500 members (the domain users group). You can't grant extended rights to a user. When you enter a user in the search field, it doesn't find them.

![image](https://user-images.githubusercontent.com/5466924/92096346-71be2c80-eddf-11ea-8000-80142c770d7c.png)

![image](https://user-images.githubusercontent.com/5466924/92096631-cbbef200-eddf-11ea-92cb-f73be4c1498b.png)

**Comment by Daksol** [comment]
When you enable Advanced Permissions you put the name of a Group (sometimes an individual) into the "Advanced Permissions" box. Doing that DOES NOT grant any file or folder permissions. Rather, if you add "SomeAdminGroup" to Advanced Permissions it means that in the related folders that members of "SomeAdminGroup" are permitted to provide additional permissions for files and folders.

Take a look at this example. Probably simpler than what you want, but might be helpful.

https://github.com/nextcloud/groupfolders/issues/1060#issuecomment-747070912

**Comment by pierreozoux** [comment]
looks like the question was answered, feel free to reopen.
