### ISSUE TITLE
Create recursive GroupFolders with API

### ISSUE THREAD

**Issue by ChR-iSz** [nextcloud/groupfolders#1047]
Hello,

It is possible to create Folders recursive with Subfolder with one API call ?

Like: FolderA/FolderB/FolderC

Greets from Germany...

**Comment by ChR-iSz** [comment]
Any feedback ?

**Comment by reimh** [comment]
Try three mointpoints like: 
FolderA - with GroupA allowed (read)
FolderA\FolderB -  - with GroupA allowed (read)
FolderA\FolderB\FolderC  - with GroupA allowed (read, write, ...)

**Comment by ChR-iSz** [comment]
Hello Reimh,

yes, i know, but my question was, can i create recursive Groupfolders with **one** API call ?
In your example i need three Ajax requests, right ? in my example, all three folders have the same group restrictions (rw)

**Comment by reimh** [comment]
I'm sorry. You are right. Setting 'groups' and 'permissions' causes much more api calls.

**Comment by ChR-iSz** [comment]
Okay, thanks.

**Comment by fschrempf** [comment]
> It is possible to create Folders recursive with Subfolder with one API call ?

No, I don't think that's currently possible. If you want this, please open an issue to request that feature and/or send a PR if possible.
