### ISSUE TITLE
Groupfolders takes too much space

### ISSUE THREAD

**Issue by D4rk5t0rM** [nextcloud/groupfolders#1054]
Hi,

I'm running Nextcloud on a server with limited storage, looking at the disk usage the groupsfolder takes up +/-5GB for only +/-2.5GB of files. The folder `/NextcloudData/__groupfolders/versions/` takes almost as much space as the folder `/NextcloudData/__groupfolders/1/` where I'm guessing the real files are stored. 

Can I delete the `/NextcloudData/__groupfolders/versions/` folder without corrupting files and is there a way to disable version control, I'm not in need of this feature.

**Comment by user-501** [comment]
I also have this issue the group folders usage is 30 gb and the versions over 100g

**Comment by user-501** [comment]
would a quota limit on the group folder also restrict the versions size?

**Comment by srhogg** [comment]
We see the same thing...9GB of files, and 19GB of versions.

I like the feature of versions, but I could do with a way to manage the size as well, as we have had a server run out of space because of this.

**Comment by pierreozoux** [comment]
Looks related to the version app and not group folder.

Ill close it, and recommend to open it there.
(Feel free to reopen if you feel otherwsise)

**Comment by fschrempf** [comment]
@D4rk5t0rM @user-501 @srhogg 

I think what you are seeing is the default behavior of the [versions app documented here](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_versioning.html). If you want to disable versioning completely, you should be able to do this by disabling the versions app or setting `'versions_retention_obligation' => 'disabled'` in the config.

According to the docs the versions app should respect the quota for the user and I would expect, that for groupfolders it should respect the groupfolder's quota. If you feel like that is not the case please open a new issue for this.

Also note that the groupfolder docs list this OCC command that might be interesting: `occ groupfolders:expire → trigger file version expiration`.
