### ISSUE TITLE
Compatible with Collaborative Labels

### ISSUE THREAD

**Issue by Oz246** [nextcloud/groupfolders#106]
Hello,

Is group_folder compatible with Collaborative Labels?

Automatic File Labeling does not work. And when tagging by hand the file does not delete it

**Comment by PhantomPhreak** [comment]
I would like to have this feature to for setting retention policy

**Comment by igloo777** [comment]
+1 to comment of @PhantomPhreak. It's basic feature to reduce disorder in Group folders.

**Comment by Vince4Git** [comment]
+1 does not work with Nextcloud 14.0.3 and Files automated tagging  1.4.0

**Comment by icewind1991** [comment]
automated tagging should work with groupfolders master (should be released within a week or 2)

**Comment by DecaTec** [comment]
Unfortunately this still does not work on a fresh install of NC 16.

**Comment by milu-milu** [comment]
Still not working on a NC 18 and Collaborative tags 1.8.0 and Files automated tagging 1.8.0.
