### ISSUE TITLE
Create group folder, assign an LDAP group ... not showing in "Files"

### ISSUE THREAD

**Issue by ledufakademy** [nextcloud/groupfolders#1072]
Hello,

how can i debug this issue ?

Edit : 
i recreate the same group folder BUt with a local group (not an ldap group) : then the group folder show up to users of this 
 local group.

Another question : i copy the backup files from CLI to this new group folder data/__groupfolders/11/
==> response , need occ files:scan --all

**Comment by pierreozoux** [comment]
Does this group has only one user? There is a similar issue when the group has only one user.

**Comment by pierreozoux** [comment]
Looks like you found a solution :)
