### ISSUE TITLE
Crash when Nextcloud is updated to 19.0.4

### ISSUE THREAD

**Issue by nebulade** [nextcloud/groupfolders#1074]
After updating Nextcloud to version 19.0.4, it cannot start up since this addon causes the following crash:
```
Oct 09 10:51:51 PHP Fatal error: Interface 'OCA\Files_Trashbin\Trash\ITrashBackend' not found in /app/data/apps/groupfolders/lib/Trash/TrashBackend.php on line 39
```
Not sure if this is on the radar already. I am not a Nextcloud expert but it looks like the internal interface/api has changed?

**Comment by CHazz** [comment]
7.0.1 broke everythiting .. include command OCC .. 
`The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OCA\GroupFolders\Command\Trashbin\Cleanup::__construct(), 0 passed in /var/www/cloud/lib/private/Console/Application.php on line 224 and exactly 3 expected in /var/www/cloud/apps/groupfolders/lib/Command/Trashbin/Cleanup.php:49
Stack trace:
#0 /var/www/cloud/lib/private/Console/Application.php(224): OCA\GroupFolders\Command\Trashbin\Cleanup->__construct()
#1 /var/www/cloud/lib/private/Console/Application.php(136): OC\Console\Application->loadCommandsFromInfoXml(Array)
#2 /var/www/cloud/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/cloud/occ(11): require_once('/var/www/cloud/c...')`

**Comment by loelkes** [comment]
See #1073

**Comment by pierreozoux** [comment]
Ill consider that #1073 fixes it. Feel free to reopen if it didnt
