### ISSUE TITLE
Grant wider permissions to subfolders for specific users

### ISSUE THREAD

**Issue by floatingpurr** [nextcloud/groupfolders#1085]
Short story: I have the following directories:

```
    foo
    |__bar
    |__other_stuff
```

As recommended here https://github.com/nextcloud/server/issues/23380#issuecomment-707194006, I'm trying to harness groupfolders to share the folder `foo` with `groupA` (read only) and the folder `bar` with `userA` with **write permission**. I want `userA` to be able to modify only `bar` and not `other_stuff`. NB: `userA` belongs to `groupA`.

I created the groupfolder `foo` granting read permission for `groupA`. However, I cannot grant write permission on `bar` for `userA` (since `userA` belongs to `groupA`, I guess).

Is there a way to do that?

**Comment by pierreozoux** [comment]
Did you try with acl? You should be able to do that.

**Comment by floatingpurr** [comment]
Do you mean the standard sharing system of nextcloud? I was trying groupfolder to get rid of this problem of the standard sharing mechanism (https://github.com/nextcloud/server/issues/23380#issue-719422708)

**Comment by fschrempf** [comment]
> Is there a way to do that?

Yes, there is. Please see:

* https://github.com/nextcloud/groupfolders#advanced-permissions
* https://github.com/nextcloud/groupfolders/issues/655#issuecomment-960823463

Please let me know if this is what you need, so I can close this issue. Thanks!

**Comment by fschrempf** [comment]
By the way, this behavior is also documented in the README:

> Denied permissions configured for the group folder itself cannot be overwritten to "allow" permissions by the advanced permission rules.

I'm assuming this is resolved by referencing the necessary information. Please feel free to comment, reopen or create a new issue if you think otherwise. Thanks!
