### ISSUE TITLE
Granular Permissions

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/groupfolders#109]
As it is right now, it's all or none. I would like it if we could get granular permissions to a group granted access. RWX, or the extent of options available akin to sharing of a folder.

As it stands now, I have no way of providing read-only access to these folders.

**Comment by brorfred** [comment]
This would be a really useful functionality. My main need would be able to control delete. I.e. only the person uploading a file can delete it by default.

**Comment by icewind1991** [comment]
Providing read only access is already possible

![](https://raw.githubusercontent.com/nextcloud/groupfolders/master/screenshots/permissions.png)
