### ISSUE TITLE
Display "members" of a group folder

### ISSUE THREAD

**Issue by coder-hugo** [nextcloud/groupfolders#1093]
It would be nice if there would be a way that everybody could see who is allowed to access a specific group folder. I'm the admin of a nextcloud installation that uses several group folders. I've got multiple times requests from people who want to know exactly this as they were unsure where to store some confidential documents. To answer this I have to check first the groups which are allowed to access the folder and afterwards I have to look who is a member of these groups. It would be quiet helpful if everybody just could see this in the details of a group folder.

**Comment by coder-hugo** [comment]
@ZeikoFr I don't see how this should help. The real world is a bit more complicated than your example there are not just 4 persons. There are about 100 persons in different groups (department/team based) that have access to the nextcloud. By just naming a folder SECRET a person who is allowed to access this folder doesn't know who else (group or user) is allowed to access this folder as well.

**Comment by ZeikoFr** [comment]
Oh okay I did not clearly understood your question.

Well maybe the organization of the groups in NC is not clear enough if people need to ask you this, I'm managing multiple instance for a total of about 1k users and I never got this type of questions. 

IMO giving the possibility to each user to see who can access a folder might be a good idea but only if it's an option and not mandatory.

If you can found multiples admins who need this feature you might have enough voice to make a feature request, or if you have an enterprise licence contact directly Nextcloud.

**Comment by pierreozoux** [comment]
What if you name the top group folder with the name of the group?

Then it becomes obvious?

**Comment by Sohalt** [comment]
> What if you name the top group folder with the name of the group?

This is a hack at best. It's mixing up 2 different things (the name of the folder, which should ideally be descriptive of its contents, and the access rights). Also it has to be done manually by an admin, which is an error prone thing. What if you change the groups that the folder is shared with? What if you have the folder shared with multiple groups?

**Comment by pierreozoux** [comment]
closing in favor of https://github.com/nextcloud/groupfolders/issues/975
