### ISSUE TITLE
Error when accessing ACLs of a group folder that has a non-existend group

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/groupfolders#1096]
1) Create some groups
2) Create group folder with those groups
3) Delete one of the groups

Expected: code catches the missing one and proceeds

Actual: https://github.com/nextcloud/groupfolders/blob/72cc6b505c50e2af9069f2149ed49b2a31d05991/lib/Folder/FolderManager.php#L231-L235 throws an exception because a method is called on `null`.

**Comment by ChristophWurst** [comment]
cc @juliushaertl

**Comment by ChristophWurst** [comment]
Actually a duplicate of https://github.com/nextcloud/groupfolders/issues/633

**Comment by jngrb** [comment]
I propose to fix this issue as implemented in my pull request #1395 . Besides this backend issue, my PR also fixes an issue interpreting the data in the frontend (src/components/SharingSidebarView.vue).
