### ISSUE TITLE
Color incompatibility

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/groupfolders#11]
It seems inconsistent with style. I think, can be integrated with [theme application](https://github.com/nextcloud/server/tree/master/apps/theming)?

![fireshot screen capture 018 - dosyalar - datarals _ verinin guvenli saklama noktasi - datarals_com_apps_files__dir _ fileid 2](https://cloud.githubusercontent.com/assets/297968/26105921/bc3f2056-3a4c-11e7-8c1c-8246c810f6d9.png)

**Comment by icewind1991** [comment]
Fixed with 642833fe8c88b0dfc325e47f1f4f36bbc54921ca
