### ISSUE TITLE
Can't delete encrypted group folder on S3 bucket.

### ISSUE THREAD

**Issue by jkroepke** [nextcloud/groupfolders#111]
Hi,

our default file backend is a AWS S3 configured via `$CONFIG['objectstore']`. We also enabled serversided encryption on the nextcloud instance.

Creation and upload files into a group folder works fine, but I can't delete group folder.

Error message:

[Thu May 03 19:28:53.361043 2018] [php7:notice] [pid 1642] [client 10.130.4.1:52416] [owncloud][index][3] Exception: {"Exception":"BadMethodCallException","Message":"path needs to be relative to the system wide data folder and point to a user specific file","Code":0,"Trace":"#0 \\/var\\/www\\/html\\/lib\\/private\\/Encryption\\/Keys\\/Storage.php(253): OC\\\\Encryption\\\\Util->getUidAndFilename('\\/__groupfolders...')\\n#1 \\/var\\/www\\/html\\/lib\\/private\\/Encryption\\/Keys\\/Storage.php(169): OC\\\\Encryption\\\\Keys\\\\Storage->getFileKeyDir('', '\\/__groupfolders...')\\n#2 \\/var\\/www\\/html\\/lib\\/private\\/Files\\/Storage\\/Wrapper\\/Encryption.php(306): OC\\\\Encryption\\\\Keys\\\\Storage->deleteAllFileKeys('\\/__groupfolders...')\\n#3 [internal function]: OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->rmdir('__groupfolders\\/...')\\n#4 \\/var\\/www\\/html\\/apps\\/files_trashbin\\/lib\\/Storage.php(273): call_user_func_array(Array, Array)\\n#5 \\/var\\/www\\/html\\/apps\\/files_trashbin\\/lib\\/Storage.php(208): OCA\\\\Files_Trashbin\\\\Storage->doDelete('__groupfolders\\/...', 'rmdir')\\n#6 \\/var\\/www\\/html\\/lib\\/private\\/Files\\/View.php(1148): OCA\\\\Files_Trashbin\\\\Storage->rmdir('__groupfolders\\/...')\\n#7 \\/var\\/www\\/html\\/lib\\/private\\/Files\\/View.php(346): OC\\\\Files\\\\View->basicOperation('rmdir', '\\/__groupfolders...', Array)\\n#8 \\/var\\/www\\/html\\/lib\\/private\\/Files\\/Node\\/Folder.php(338): OC\\\\Files\\\\View->rmdir('\\/__groupfolders...')\\n#9 \\/var\\/www\\/html\\/custom_apps\\/groupfolders\\/lib\\/Controller\\/FolderController.php(75): OC\\\\Files\\\\Node\\\\Folder->delete()\\n#10 [internal function]: OCA\\\\GroupFolders\\\\Controller\\\\FolderController->removeFolder(1)\\n#11 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#12 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\GroupFolders\\\\Controller\\\\FolderController), 'removeFolder')\\n#13 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\GroupFolders\\\\Controller\\\\FolderController), 'removeFolder')\\n#14 \\/var\\/www\\/html\\/lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\GroupFolder...', 'removeFolder', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\/var\\/www\\/html\\/lib\\/private\\/Route\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#17 \\/var\\/www\\/html\\/lib\\/base.php(999): OC\\\\Route\\\\Router->match('\\/apps\\/groupfold...')\\n#18 \\/var\\/www\\/html\\/index.php(37): OC::handleRequest()\\n#19 {main}","File":"\\/var\\/www\\/html\\/lib\\/private\\/Encryption\\/Util.php","Line":235}

nextcloud version: 13.0.2 using [docker.io/nextcloud:stable](https://hub.docker.com/_/nextcloud/)

**Comment by icewind1991** [comment]
Using groupfolders with encryption is not supported.

The upcoming groupfolders release that will come with NC15 will properly disable encryption for group folders.

**Comment by samcgarry** [comment]
I'm seeing the same error on NextCloud 18 (on docker with S3 primary storage). I also have server-side encryption enabled.

Is there a way to exclude group folders from encryption?

```
{"reqId":"CXQLwaJIpHlMcZGSOhAH","level":3,"time":"2020-02-17T14:42:57+00:00","remoteAddr":"10.255.0.2","user":"admin","app":"index","method":"DELETE","url":"/index.php/apps/groupfolders/folders/10","message":{"Exception":"BadMethodCallException","Message":"path needs to be relative to the system wide data folder and point to a user specific file","Code":0,
"Trace":[{"file":"/var/www/html/lib/private/Encryption/Keys/Storage.php","line":254,"function":"getUidAndFilename","class":"OC\\Encryption\\Util","type":"->","args":["/__groupfolders/10"]},
{"file":"/var/www/html/lib/private/Encryption/Keys/Storage.php","line":170,"function":"getFileKeyDir","class":"OC\\Encryption\\Keys\\Storage","type":"->","args":["","/__groupfolders/10"]},
{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php","line":309,"function":"deleteAllFileKeys","class":"OC\\Encryption\\Keys\\Storage","type":"->","args":["/__groupfolders/10"]},
{"function":"rmdir","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":["__groupfolders/10"]},
{"file":"/var/www/html/apps/files_trashbin/lib/Storage.php","line":184,"function":"call_user_func","args":[[{"cache":{"__class__":"OC\\Files\\Cache\\Cache"},"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OC\\Files\\Storage\\Wrapper\\Encryption"},"rmdir"],"__groupfolders/10"]},
{"file":"/var/www/html/apps/files_trashbin/lib/Storage.php","line":119,"function":"doDelete","class":"OCA\\Files_Trashbin\\Storage","type":"->","args":["__groupfolders/10","rmdir"]},
{"file":"/var/www/html/lib/private/Files/View.php","line":1162,"function":"rmdir","class":"OCA\\Files_Trashbin\\Storage","type":"->","args":["__groupfolders/10"]},
{"file":"/var/www/html/lib/private/Files/View.php","line":348,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["rmdir","/__groupfolders/10",["delete"]]},
{"file":"/var/www/html/lib/private/Files/Node/Folder.php","line":393,"function":"rmdir","class":"OC\\Files\\View","type":"->","args":["/__groupfolders/10"]},
{"file":"/var/www/html/custom_apps/groupfolders/lib/Controller/FolderController.php","line":94,"function":"delete","class":"OC\\Files\\Node\\Folder","type":"->","args":[]},
{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"removeFolder","class":"OCA\\GroupFolders\\Controller\\FolderController","type":"->","args":[10]},
{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\GroupFolders\\Controller\\FolderController"},"removeFolder"]},
{"file":"/var/www/html/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\GroupFolders\\Controller\\FolderController"},"removeFolder"]},
{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\GroupFolders\\Controller\\FolderController","removeFolder",
{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"10","_route":"groupfolders.Folder.removeFolder"}]},
{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"10","_route":"groupfolders.Folder.removeFolder"}]},
{"file":"/var/www/html/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},
{"id":"10","_route":"groupfolders.Folder.removeFolder"}]},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/groupfolders/folders/10"]},
{"file":"/var/www/html/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Encryption/Util.php","Line":235,"CustomMessage":"--"},
"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36","version":"18.0.0.10"}
```
