### ISSUE TITLE
GroupFolder indexing issue with ElasticSearch

### ISSUE THREAD

**Issue by j03h** [nextcloud/groupfolders#113]
Im trying to index with ElasticSearch the content of GroupFolder.

Every is fine, but the index is created only for the first user in the user group allowed to interact with this GroupFolder.

The rest of users cant search inside the index because the index is not ceated for him!

Index External Drives is activated.

**Comment by joergmschulz** [comment]
This should be resolved - at least here, it is.

**Comment by ZeikoFr** [comment]
Hi @j03h is this issue still relevant ?

Sadly I do not have the possibility to test this specific issue but an update could bring the attention of other people on the issue to replicate and possibly fix it.

**Comment by fschrempf** [comment]
According to @joergmschulz this is resolved and I will close this now. If there still is some problem here, please create a new issue and reproduce with the latest release. Thanks!
