### ISSUE TITLE
Groupfolders Admin menu, contingent and advanced options not visible

### ISSUE THREAD

**Issue by roadrunnerjb** [nextcloud/groupfolders#1134]
Hi,

we have some folders with lots of groups for a specific group folder. The list is so long that the other attributes are only visable when scrolling. Is it possible to use a multiline filed for groups to limit the column width ?

NC Version is 19.0.4 Groupfolders Version is 7.1.1

**Comment by fschrempf** [comment]
This has been fixed by #1705 and was backported to stable, though NC 21 and 22 haven't seen a release that includes this, yet (see #1833).
