### ISSUE TITLE
dev: how to derive groupfolder name from filecache ?

### ISSUE THREAD

**Issue by Rello** [nextcloud/groupfolders#114]
Hello,

Audioplayer is indexing audio files also within group folders. To offer the user a category of "folders" to select their files, the "name" from the filecache table is used.

but this equals to the ID of the folder
`__groupfolders/1 => name = 1`

The given title is used in table `group_folders`. but where is the link between these to?
I assume `filecache-name = group_folders-folder_id` but how can I recognize in filecache, that it is actually a group folder? mime type e.g. does not help here

**Comment by skjnldsv** [comment]
Hey @Rello :)
It's been a long time since you try to get help on our nextcloud irc, but you always ask stuff when no one is around :(

I'll suggest you ask during the day or before 20h (GMT+2), otherwise it's hard, especially since you disconnect :)

**Comment by Rello** [comment]
@icewind1991 any suggestion?

**Comment by icewind1991** [comment]
You should not attempt to get it from the database but use the filesystem api so it will work no matter where the files come from

**Comment by Rello** [comment]
Hello @icewind1991 
can you advice on how to do that? In PHP i am getting a NODEs object (File-id of a folder).
How do I get the group-folder name with this? Can you suggest on the class usage here?

**Comment by icewind1991** [comment]
If you have the node you can just use the filename

**Comment by fschrempf** [comment]
I assume this has been resolved with the advice given above.
