### ISSUE TITLE
Using occ groupfolders:list throws unhandled exception

### ISSUE THREAD

**Issue by AlexG-78** [nextcloud/groupfolders#1145]
Hi,
im on NC 20.0.2 using the latest groupfolders 8.1.1. 
OS: Debian 10, Apache 2.4, php-fpm

When I'm using the command sudo -u www-data php ./occ groupfolders:list
The list of groupfolders is displayed but it also throws an error in the console:

`An unhandled exception has been thrown:
TypeError: Return value of "OCA\GroupFolders\Command\ListCommand::execute()" must be of the type int, "null" returned. in /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php:261
Stack trace:
#0 /var/www/html/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(OCA\GroupFolders\Command\ListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#6 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#7 {main}%`
If needed I can provide more information. Any help is much appreciated.

**Comment by ChristophWurst** [comment]
Tracked in https://github.com/nextcloud/groupfolders/issues/1153
