### ISSUE TITLE
App disabled after Ubuntu Snap updates and server reboots

### ISSUE THREAD

**Issue by PaulNokel** [nextcloud/groupfolders#1152]
Hi,

when the Snap updated Nextcloud to 20.0.1 all the Group Folders where missing. The solution was easy, the App was just disabled. Today I rebooted the server to install pending updates and the same thing happened again. Digging in the logs I found the following message:
`{"reqId":"LqZnJDK6ieOh3SPHheTa","level":3,"time":"2020-11-22T13:14:01+00:00","remoteAddr":"127.0.0.1","user":"discord-362064221153787904","app":"no app in context","method":"PROPFIND","
url":"/remote.php/dav/files/discord-362064221153787904/","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCA\\GroupFolders\\AppInfo\\Application! Class OCA\\GroupFolders\\AppInfo\\Application does not exist","Code":0,"Trace":[{"file":"/snap/nextcloud/24051/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\GroupFolders\\AppInfo\\Application"]},{"file":"/snap/nextcloud/24051/htdocs/lib/private/ServerContainer.php","line":156,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\GroupFolders\\AppInfo\\Application",true]},{"file":"/var/snap/nextcloud/24051/nextcloud/extra-apps/groupfolders/appinfo/app.php","line":5,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\GroupFolders\\AppInfo\\Application"]},{"file":"/snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php","line":289,"args":["/var/snap/nextcloud/24051/nextcloud/extra-apps/groupfolders/appinfo/app.php"],"function":"require_once"},{"file":"/snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php","line":171,"function":"requireAppFile","class":"OC_App","type":"::","args":["groupfolders"]},{"file":"/snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::","args":["groupfolders"]},{"file":"/snap/nextcloud/24051/htdocs/apps/dav/lib/AppInfo/Application.php","line":113,"function":"loadApps","class":"OC_App","type":"::","args":[["dav"]]},{"file":"/snap/nextcloud/24051/htdocs/lib/private/AppFramework/Bootstrap/Coordinator.php","line":168,"function":"boot","class":"OCA\\DAV\\AppInfo\\Application","type":"->","args":[{"__class__":"OC\\AppFramework\\Bootstrap\\BootContext"}]},{"file":"/snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php","line":191,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["dav"]},{"file":"/snap/nextcloud/24051/htdocs/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::","args":["dav"]},{"file":"/snap/nextcloud/24051/htdocs/remote.php","line":152,"function":"loadApps","class":"OC_App","type":"::","args":[["filesystem","logging"]]}],"File":"/snap/nextcloud/24051/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php","Line":115,"CustomMessage":"**App groupfolders threw an error during app.php load and will be disabled: Could not resolve OCA\\GroupFolders\\AppInfo\\Application! Class OCA\\GroupFolders\\AppInfo\\Application does not exist**"},"userAgent":"Mozilla/5.0 (Macintosh) mirall/2.6.0stable (build 20190927) (Nextcloud)","version":"20.0.1.1"}`

I was not able to find a similar issue, so the problem might be related to my specific setup? Has someone experienced something similar and found a solution?

**Comment by pierreozoux** [comment]
Did you find a solution for your issue?

Looks like an isolated case.

**Comment by pierreozoux** [comment]
I saw similar issues that have been fixed since then, Ill close, but feel free to reopen.
