### ISSUE TITLE
User with no right to delete a file can permanently delete file in the trash

### ISSUE THREAD

**Issue by ZeikoFr** [nextcloud/groupfolders#1157]
Hi I currently have an issue with the trashbin of Nextcloud, this is my structure 

GroupFolder
|
 => Main Folder
|
=> SubFolder
|
=> File.txt

If user1 as Read/Write/Create permission and is NOT allowed to delete a file in SubFolder then the user cannot delete the file.txt.

BUT if a user2 with delete permission delete file.txt then user1 can go in the trash and restore/delete permanently the file.

Is it possible to avoid this ? I want user1 to not be able to restore or permanently delete the files in trashbin.

**Comment by fschrempf** [comment]
Somehow related to #1258
