### ISSUE TITLE
Dashboard/Recommended Files/no Files shown from Groupfolders

### ISSUE THREAD

**Issue by CoreTechnologyAG** [nextcloud/groupfolders#1158]
Hello
Actually we use a lot of group folders to share documents.
In the new dashboard NC20 (Nextcloud 20.0.2) there is a widgets called “recommended files”. Realy cool.
This widgets doesn’t show changed/added files from groupfolders.
It shows only changed/added files from user file location.

Cool would be an integration of local user files and groupfolder.

Or is there any other widgets which supports this or does it need a special group folder configuration?

Thanks
Ritzo

[Link to help.nextcloud.com Issue:](https://help.nextcloud.com/t/dashboard-recommended-files-no-files-shown-from-groupfolders/99389)

**Comment by joshtrichards** [comment]
See nextcloud/recommendations#341

But also I suspect this may no longer be an issue, since the recent files has been re-implemented (e.g. nextcloud/server#26322)

I don't have time to test today, but feel free to do so and report back.

**Comment by joshtrichards** [comment]
Confirmed working in my test bed. Previous comments apply.
