### ISSUE TITLE
Images in group folders are not shown in gallery

### ISSUE THREAD

**Issue by bpollet** [nextcloud/groupfolders#1163]
Images in group folder are not shown in photo galleries even if we explicitaly share them with other users or same group

Using latest version 8.2.0 and nextcloud 20.0.2.1

**Comment by ZeikoFr** [comment]
Hi,

I have a test instance to update today in 20.0.2, same with the group folder, I will try to replicate the issue.

Can you provide me some screenshot so I can clearly see what's the problem ?

**Comment by bpollet** [comment]
Hello. Thanks for you reply.

Here is the groupfolder configuration:
![image](https://user-images.githubusercontent.com/65547301/101020901-71186c00-356f-11eb-8e7e-71bac8493fd2.png)
my group folder is "Partage"

All my images are in this folder in subfolder "Images"
![image](https://user-images.githubusercontent.com/65547301/101021159-d53b3000-356f-11eb-8b4d-0f695a91e755.png)

None of my pictures are available in the gallery app
![image](https://user-images.githubusercontent.com/65547301/101021264-fbf96680-356f-11eb-8985-1c2937dbcfe1.png)

**Comment by bpollet** [comment]
I also tried to explicitally share the "Photos" folder with a user which is already in the group
![Vero](https://user-images.githubusercontent.com/65547301/101025185-81cbe080-3575-11eb-8ced-29a2bc5541bd.PNG)

And this user still doesn't see the pictures in the gallery app:
![VeroGallery](https://user-images.githubusercontent.com/65547301/101025227-93ad8380-3575-11eb-9f38-188def642971.PNG)

**Comment by ZeikoFr** [comment]
Hi @bpollet  after my test this is my conclusion : 

"your photos" => Pictures that are in the personnal space of a user

To see the pictures that are in a groupe folder please go to "Shared albums" where an album with the name of the group folder will contain all picture from the group folder

In your specific case the path to go to the pictures is the following : Shared pictures => Partage => Photos => Loisirs => Astronomie => Best_of

This need some clicks but at the end you should be able to acces the correct pictures

Et voilà comme on dit chez nous ;)

**Comment by bpollet** [comment]
Hello, thanks for your reply.
Yes it works using shared album.

I found a ticket on the gallery app about the feature I was asking for:
https://github.com/nextcloud/photos/pull/398

It sounds like it will be corrected/implemented soon :)

Merci beaucoup!

**Comment by ZeikoFr** [comment]
@bpollet As the PR you linked is already merged, maybe you should open another issue is the photos repository to ask about this specific feature.

Be free to close this issue if it's okay for you
