### ISSUE TITLE
`occ groupfolders:scan` : scan only a specific folder like `occ files:scan --path`

### ISSUE THREAD

**Issue by flowzen1337** [nextcloud/groupfolders#1168]
Hi,

currently i use
`#occ groupfolders:scan <folder_id> → trigger a filescan for a group folder`
`occ groupfolders:scan 104`

for scanning a groupfolder, but what i want is to scan only a exact given path:

`#occ groupfolders:scanpath <path> → trigger a filescan for a group folder specific path`
`occ groupfolders:scanpath 104/my/uploads/ → trigger a filescan for a group folder specific path`

So that only the "104/my/uploads" is scanned and not the whole groupfolder with id "104" as it takes very long if there are many files/folders in it that are already known.

Is that possible somehow?

Thanks in advance! 👍 

Cheers

**Comment by ZeikoFr** [comment]
sudo -u www-data php occ groupfolders:scan 104/my/uploads/

Regards

**Comment by ZeikoFr** [comment]
hi @flowzen1337 Does my previous command help you ?

If so be free to close the issue

**Comment by flowzen1337** [comment]
> hi @flowzen1337 Does my previous command help you ?
> 
> If so be free to close the issue

Will check tomorrow as i don’t have a computer around at the Moment and close it if it works, thanks in advance :-) cheers

**Comment by flowzen1337** [comment]
Seems good, working like expected :-) Thanks for the help here! Cheers -> closed

**Comment by flowzen1337** [comment]
Sorry, i have to reopen it, the problem is that the scan command doesnt scan the given directory only, it seems it scans the full Groupfolder:

For example:
- [ Working fast ]
- **GroupfolderID**: 102
- **Path**: /foobar/one/to/three/
- **Containing File:** test.csv
- **Note**: Containing only one path with only one file - scanning is fast:
`root@server:/var/www/html/nextcloud/data/__groupfolders/102# find .`
`.`
`./foobar`
`./foobar/one`
`./foobar/one/two`
`./foobar/one/two/three`
`./foobar/one/two/three/test.csv`

- **CMD:** `sudo -u www-data php /var/www/html/nextcloud/occ groupfolders:scan "102/foobar/one/two/three"`
`+---------+-------+--------------+`
`| Folders | Files | Elapsed time |`
`+---------+-------+--------------+`
`| 5       | 1     | 00:00:00     |`
`+---------+-------+--------------+`


But when there are already many files and paths in the folder the scanning seems to scan all files inside the groupfolders instead of just the given path:

- [ Working Slow ]
- **GroupfolderID:** 104
- **Path:** /Unsorted/Files/Peter/2020-2021/2020-12-09/Test_B_Subdir/"
- **Containing File:** test_b.csv
- **listing:** `ls -l 104/Unsorted/Files/Peter/2020-2021/2020-12-09/Test_B_Subdir/`
`insgesamt 0`
`-rw-r--r-- 1 root root 0 Dez  7 14:01 test_b.csv`
- **Note**: Containing many paths and files but only the direct path to a subdir with one file is given to occ command - scanning is slow and output shows it scans much more files and directorys:
`root@server:/var/www/html/nextcloud/data/__groupfolders/104# find . | wc -l`
`565`
- **CMD:** `sudo -u www-data php /var/www/html/nextcloud/occ groupfolders:scan "104/Unsorted/Files/Peter/2020-2021/2020-12-09/Test_B_Subdir/"`
`+---------+-------+--------------+`
`| Folders | Files | Elapsed time |`
`+---------+-------+--------------+`
`| 416     | 122   | 00:01:13     |`
`+---------+-------+--------------+`

As you can see in the output it scanned 416 folders with 122 files and took over a minute instead of just scanning the given directory and the files included :-(

**Comment by Zegorax** [comment]
Is there any timeline about this feature?

**Comment by steffenclemens** [comment]
Hi @flowzen1337 @Zegorax, I needed the same feature so I created a pull request. You can specify the path with `-p` and add `--shallow` if you don't want to scan recursively, like you can do with `files:scan`. You still need to specify the folder id. Check it out, if you like: https://github.com/nextcloud/groupfolders/pull/2232

**Comment by solracsf** [comment]
Hi @flowzen1337 ✋ maybe you can test https://github.com/nextcloud/groupfolders/pull/2232 and provide feedback?
