### ISSUE TITLE
Show name of user that upload a file to group folder in web interface

### ISSUE THREAD

**Issue by brorfred** [nextcloud/groupfolders#117]
I would be extremely useful if the name of the user that uploaded a file is shown in the webinterface. 
<img width="1280" alt="screen shot 2018-05-11 at 11 56 07" src="https://user-images.githubusercontent.com/832870/39934008-84ef2baa-5512-11e8-9ab4-4816a2624ffd.png">

**Comment by spackmat** [comment]
Would also be useful to show the users that shared a file.

**Comment by fschrempf** [comment]
This should be possible using the activity app and enabling `activity_use_cached_mountpoints` as described [here](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/activity_configuration.html#activities-in-groupfolders).

**Comment by fschrempf** [comment]
So as said above this should be possible via the activity app and I don't see how this feature request is related to groupfolders in any way, as sharing and uploading files is not limited to groupfolders. So you should probably open an issue in the server repository if you think the UI should be enhanced.
