### ISSUE TITLE
Can't share with LDAP groups anymore

### ISSUE THREAD

**Issue by IsabellaCaspari** [nextcloud/groupfolders#1180]
Since about one week ago I cannot share group foulders with other ldap groups anymore. 
Sharing with individuell ldap useres works fine. However sharing with ldap groups does not. 

I can search and select the specified ldap group and confirm sharing. 
However the group foulder will not show up in the account of useres within the selected ldap group. 

Any idea?

**Comment by miloskroulik** [comment]
What version are you using (on what Nextcloud version?). On groupfolders v7.1.1 and NC19 it seems to be working fine...

**Comment by pierreozoux** [comment]
@IsabellaCaspari can you tell us the versions of Nc and the app, and any log if you have.

**Comment by pierreozoux** [comment]
It reminds me of another issue that has since been fixed, Ill close as resolved, but feel free to reopen if it is still a bug for you.
