### ISSUE TITLE
What good are the OCC and OCS API commands if they require Folder Id?

### ISSUE THREAD

**Issue by functioneer** [nextcloud/groupfolders#1183]
The groupfolders OCC and OCS API commands require the Folder Id instead of Folder Name.
For example, to share a Group Folder with a group, you need to know the Folder Id.
occ groupfolders:group <folder_id> <group_name> [-d|--delete] [write|share|delete]
For the OCS API, you also need to know the Group Id in addition to the Folder Id.
POST apps/groupfolders/folders/$folderId/groups

We are trying to write our own PHP scripts to create an online form for our users to create a Group Folder and then share it with a group.    So the user will enter a new Group Folder name and an existing Group Name to share.    We will be running the OCC commands on the server via the PHP script (which in turn runs C program running the nextcloud.occ commands as root).   We cannot use OCS API because our NextCloud Admin accounts are 2FA enabled.

Is it possible to have a new  occ groupfolders:group  command that accepts the Group Folder name instead of the Group Folder Id?  
It will be very difficult programmatically to get the Folder Id from the occ groupfolders:list command.
Or maybe a OCC command to return the Folder Name given the Folder Id?

Thank you very much

**Comment by fschrempf** [comment]
> We are trying to write our own PHP scripts to create an online form for our users to create a Group Folder and then share it with a group. So the user will enter a new Group Folder name and an existing Group Name to share. We will be running the OCC commands on the server via the PHP script (which in turn runs C program running the nextcloud.occ commands as root). We cannot use OCS API because our NextCloud Admin accounts are 2FA enabled.

I think it is a bad idea to do this via OCC. This is what the OCS API is made for. Why don't you create an API user without 2FA and use this to create/share the folder?

**Comment by icewind1991** [comment]
> Is it possible to have a new occ groupfolders:group command that accepts the Group Folder name instead of the Group Folder Id?

No because the folder name is not unique

> It will be very difficult programmatically to get the Folder Id from the occ groupfolders:list command.

```
occ groupfolders:list --output json
```
