### ISSUE TITLE
Log is full with ERROR: 'LogicException: $path is a integer' 

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/groupfolders#1184]
follow up on: https://github.com/nextcloud/server/issues/24785
Server: Debian 10.6 / NGINX 1.19.6 / PHP 7.4.13 / MariaDB 10.5.8

As suggested by @kesselb in https://github.com/nextcloud/server/issues/19010#issuecomment-576683752 I installed the patch and created a new folder by the `groupfolder`-app. Hope this will help to debug.

Here are the results of the internal log:
```
LogicException: $path is a integer: 205

0. /var/www/nextcloud/lib/private/Files/Node/Folder.php - line 62:
   OC\Files\Node\Node->isValidPath()

1. /var/www/nextcloud/lib/private/Files/Node/Folder.php - line 163:
   OC\Files\Node\Folder->getFullPath()
 
2. <<closure>>
    OC\Files\Node\Folder->newFolder()
 
3. /var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php - line 66:
   call_user_func_array()

4. /var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php - line 146:
   OCA\GroupFolders\Helper\LazyFolder->__call()

5. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php - line 185:
   OCA\GroupFolders\Helper\LazyFolder->newFolder()

6. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php - line 122:
   OCA\GroupFolders\Mount\MountProvider->getFolder()

7. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php - line 88:
    OCA\GroupFolders\Mount\MountProvider->getMount()

8. <<closure>>
    OCA\GroupFolders\Mount\MountProvider->OCA\GroupFolders\Mount\{closure}("*** sensiti ... *")

9. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php - line 86:
    array_map()

10. /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php - line 109:
     OCA\GroupFolders\Mount\MountProvider->getMountsForUser()

11. /var/www/nextcloud/lib/private/Files/Filesystem.php - line 452:
     OC\Files\Config\MountProviderCollection->addMountForUser()

12. /var/www/nextcloud/lib/private/Files/Filesystem.php - line 377:
     OC\Files\Filesystem::initMountPoints()

13. /var/www/nextcloud/lib/private/legacy/OC_Util.php - line 322:
     OC\Files\Filesystem::init()

14. /var/www/nextcloud/lib/base.php - line 1007:
      OC_Util::setupFS()

15. /var/www/nextcloud/index.php - line 37:
     OC::handleRequest()
```

**Comment by jotoeri** [comment]
Hi all, hey @juliushaertl @kesselb 

i have some similar issue currently with the regularly occuring error `Trying to access array offset on value of type int at /var/www/nextcloud/lib/private/Files/Node/Node.php#328`, (which is most probably the error headline here, too, even if not named. 🙈 )

I now traced the issue a bit, looking into where the folder_id comes from. And i think i found the root issue for this error on groupfolders:
While the groupfolders-app uses integers as `folder_id` (down to db, including auto-increment), the same `folder_id` is used as folder-name in the backend. This works well, if the id is explicitely converted or is concattenated with a string, but if the folder is accessed directly with `folder_id`, then folder-operations are called with an integer.
However, having folder-operations called with foldername as string seems reasonable to me. A solution has to be found here in the app imo.

Possible ways to solve this:
- Cast every call to folder-operations as string. Hard to maintain, and if not really taking care, one will run again and again into this issue.
- Cast the folder-id right after DB, beeing still able to use auto-increment on DB, but using strings all over the app.
- Change the folder_id of groupfolders globally to string (including DB-migrations). Best way would probably be to use hashes in future, still existing folders should be able to remain as is with a `folder_id="25"` This would indeed need a quick look through the whole app, changing the type where explicitely specified. **This is imo the most future-failsafe and clean way.**

How do you think about?

Greets,
Jonas :)
