### ISSUE TITLE
TypeError: Argument 4 passed to OCA\GroupFolders\Versions\GroupVersion::__construct()

### ISSUE THREAD

**Issue by trvrcr** [nextcloud/groupfolders#1186]
TypeError: Argument 4 passed to OCA\GroupFolders\Versions\GroupVersion::__construct() must be of the type int, float given, called in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 66

NC 20.0.4
php7.4
MariaDB 10.3

**Comment by pierreozoux** [comment]
Do you have user error? or just server error?

**Comment by trvrcr** [comment]
> Do you have user error? or just server error?

what do you mean with user error?
The error is on the server so it is certainly a server error.

I already updated to version NC 21.0.0.18 and the problem is persisting

**Comment by pierreozoux** [comment]
I mean, if there is just an error in the log, and no strange behavior for the end user, the priority of fixing this error is lower than end user errors. You see what I mean?

**Comment by trvrcr** [comment]
I see what you mean, I have not yet encountered any problems in the user space that can be linked to this.
Just want to make you aware of the issue.
I'm also willing to test out any propositions to fix the issue.

(I already tried fixing it by changing the code and requesting float instead of Int but that created another error)
With a little coaching I might help fix the issue...

**Comment by pierreozoux** [comment]
I'm not the php person, just trying to help triage the issues here :)

**Comment by trvrcr** [comment]
Maybe you can redirect to the correct person

**Comment by trvrcr** [comment]
Still present in version 21.0.4

**Comment by joshtrichards** [comment]
This code no longer exists as of #2543.

If this issue still exists today it'll manifest itself differently, if at all. I'm going to close this out.

Out of curiosity, were you perhaps running NC on a 32-bit platform at the time of your report?

**Comment by trvrcr** [comment]
It was running on 32-bit at a certain time but I upgraded to 64bit.
I cannot recall if it was before or after the upgrade of the system.
Will keep an eye on if it still persists/manifests in another way.
