### ISSUE TITLE
Groupfolders deactivates on its own

### ISSUE THREAD

**Issue by Sick-Andrew** [nextcloud/groupfolders#119]
We had this issue for the first time about 4-5 days ago, although we have used NC and GF for about 6 weeks now.
The GroupFolders plugin deactivated itself somewhen over night.

There are no entries in the log but of course all the files and folders are deleted from the clients.
As we have some really huge files in there thats really annoying.
After activating the plugin we struggle a lot because NC is run on a shared hosting environment so you have have to force the clients to synchronize due to the amount of clients and file sizes.
We run NC 13.0.2, Groupfolders 1.2.0

Does anyone know why this keeps happening?

**Comment by vasyugan** [comment]
I have just seen the same. After an update, the groupfolders app was suddenly inactive, although there was no incompatibility, and what makes matters worse is that for all of my users who were online during the time that the app was inactive, the desktop sync client has wiped out all the sychronized group folders resulting in about 90 users having to download between 10 and 50 gigabytes of data AGAIN, even though they haven't changed. This now happened the second time.

**Comment by loelkes** [comment]
Same here. I have NC 18.0.2 and on the web interface the App shows Version 3.0.0 and deactivates as soon as you activate it. **But** in the background, Version 6.0.3 is active and running and everyone uses it.

With ```occ app:list``` I get:
```
Enabled:
...
  - groupfolders: 6.0.3
...

Disabled:
...
  - groupfolders_3-0-0.backup
...
```

Removing the folder ```groupfolders_3-0-0.backup``` from ```apps/``` in the ```www```directory solved that problem for me.

**Comment by pierreozoux** [comment]
Do you still have the issue? At least there is aworkaround. I'll tag it as stale.

**Comment by vasyugan** [comment]
I haven't seen it in a while.

**Comment by Sick-Andrew** [comment]
GF 5.0.8 on NC17 works fine so far.
