### ISSUE TITLE
Groupfolder admin page is blank

### ISSUE THREAD

**Issue by maiolif** [nextcloud/groupfolders#1198]
Steps to reproduce: after upgrading to version 20.0, the groupfolder admin page is blank. From OCC everything seems working properly

**Comment by mozdi** [comment]
Same for me on 20.0.4.
I restarted nextcloud after installing Group Folders but this didn´t fix it.

**Comment by maiolif** [comment]
Any idea?

**Comment by mozdi** [comment]
Today I switched from docker image nextcloud:fpm with nginx to nextcloud:latest (running with apache) and its working fine now.
I assume that there was some missconfiguration within my nginx config file.

Hope that helps :)

**Comment by TheMBeat** [comment]
Same for me on 20.0.4 since 20.0.0.

**Comment by maiolif** [comment]
> Today I switched from docker image nextcloud:fpm with nginx to nextcloud:latest (running with apache) and its working fine now.
> I assume that there was some missconfiguration within my nginx config file.
> 
> Hope that helps :)

Thanks, I can try, I am also using nginx. no data is lost in that case?

**Comment by jeffrson** [comment]
nextcloud 20.0.5, group folders 8.2.0 - still blank

**Comment by jeffrson** [comment]
I just reinstalled my instance (not yet production, but soon...) and apps. The problem occurs after I installed [nextbackup](https://github.com/pbek/nextbackup). Disabling it again brings group folders back.

**Comment by pbek** [comment]
Fixed in Nextbackup now: https://github.com/pbek/nextbackup/issues/48#issuecomment-761537157
Please update Nextbackup (in case that ways anyone else's problem too) and test again.

**Comment by maiolif** [comment]
> Fixed in Nextbackup now: [pbek/nextbackup#48 (comment)](https://github.com/pbek/nextbackup/issues/48#issuecomment-761537157)
> Please update Nextbackup (in case that ways anyone else's problem too) and test again.

As commented here: https://github.com/pbek/nextbackup/issues/48#issuecomment-761537157

updating the nextbackup app is solving this issue.

THANKS A LOT
