### ISSUE TITLE
cannot create group folder

### ISSUE THREAD

**Issue by mind22** [nextcloud/groupfolders#12]
I updated today to NC 12 beta 3 and installed group folders. It throws an exception. 

Server log:

Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_group_folders` (`mount_point`) VALUES(?)' with params [null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mount_point' cannot be null

nginx
mariadb 10.0.29
php 7.0

**Comment by gcs-github** [comment]
I just stumbled upon this on NC 15.0.4 + app version 2.0.4. PHP 7.3, nginx, MySQL 5.7

Is there a fix or a workaround?

**Comment by gcs-github** [comment]
This issue subsidized for me after installing a series of official nextcloud apps. I wasn't able to pinpoint which one.
