### ISSUE TITLE
Add ability to remove download from Group Folders by group

### ISSUE THREAD

**Issue by greavette** [nextcloud/groupfolders#120]
Hello,

Currently we have ability for either 'Write' or 'Share' in Group folders. We have a need to share but now allow the downloading of files from a group folder.  The reason for this is because we share PDF documents through our Nextcloud and these are to only be read online and not downloaded.  

Could the Group Folders App allow us to set certain groups to not have a download button available to them when viewing a shared group folder?

Thank you.

**Comment by icewind1991** [comment]
Since reading the file online involves downloading the file this is not possible
