### ISSUE TITLE
Offer to start creating wiki for Group Folders

### ISSUE THREAD

**Issue by Daksol** [nextcloud/groupfolders#1201]
I am now getting good results from use of GroupFolders - but I did not find all aspects to be easy to pick up.

When I look through the issues here I think a percentage of the problems come from not entirely understanding how GF has been set up to work.

So I suggest it would be useful to have some wiki pages where some more detailed documentation, how-to guides etc could be created. **I am happy to create a first batch of such content.**

Right now there is no wiki that I can see.

* Can the admins here confirm they are ok with a wiki being set up
* and maybe create a blank first page which I can clone and update.

Thanks

**Comment by fschrempf** [comment]
I'm not related to any development here, but I can confirm that it is quite difficult to understand how this app is supposed to work, especially the ACL is quite complex and there are plenty of limitations and obscurities. Some more documentation would really help.

**Comment by juliushaertl** [comment]
Great to hear that. We currently have the documentation in the readme, so feel free to prepare pull requests against that. If at some point this gets to large we can always consider moving it into the wiki or a separate docs build in a later step.
