### ISSUE TITLE
Should a deleted file be restoreable?

### ISSUE THREAD

**Issue by n-pat** [nextcloud/groupfolders#121]
Hi,

I tried to restore a file that I deleted in an group folder (using the web interface or/and the windows client).

Is it possible to do that? Does this app work together with the official "Deleted files" or "Versions" NextCloud-App?

Kind regards, Patrick

**Comment by temparus** [comment]
This is currently not supported. See issues #50 and #99.

**Comment by n-pat** [comment]
Sorry for not finding this :-)
Thank you!
