### ISSUE TITLE
SMB external share does not show GroupFolder permissions

### ISSUE THREAD

**Issue by mxhaj79** [nextcloud/groupfolders#1225]
So here it is. I created (mounted) an external folder via SMB share. It is fully visible and I have R/W permissions on it. Next, I created GroupFolder with the name and was hoping it would allow me to control permissions on the SMB share. It does not seem to work, though. Is there any workaround for this limitation?

**Comment by robinhoodhimself** [comment]
Are you stupid?

**Comment by pierreozoux** [comment]
I don't think that the purpose of group folder is to manage permission on the storage backend level (or I didn't understand your question)

I'll close as won't fix, but feel free to reopen if I didn't understand.
