### ISSUE TITLE
Feature request: Make content of group folders shareable

### ISSUE THREAD

**Issue by splashote** [nextcloud/groupfolders#123]
Hello,
I hope it's self explaining, but the option, to make the content of the group folder shareable is needed four our use case and I think it would be a useful option.

At least the admin(s) could be able to do so.

Thanks!

**Comment by icewind1991** [comment]
Sharing should already work fine

**Comment by team-a2** [comment]
Sharing works fine. You just need to activate the checkbox when assigning the group to a group folder.
