### ISSUE TITLE
Add option to disable sharing of group folders

### ISSUE THREAD

**Issue by lhoff94** [nextcloud/groupfolders#1245]
Hi, 

it would be great if there would be the possibility to disable the possibility to share a folder via a Link for group folders.
Im the admin of a nextcloud instance with about 100 users and we use LDAP as a login backend. Also the user groups are managed there. 

I used the template of the nextcloud/server repo to discribe the feature further.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Users use the share feature to "invite" other users into group folders. The access of these users can only be managed by the person who invited them in the first place. 
We are using the LDAP integration to manage user groups and instead of asking the support to move a certain person into a group they just create a share link. 

**Describe the solution you'd like**
Add an option to disable the sharing feature for certain group folders. That could be a checkbox as part of the groupfolder admin overview. 

**Describe alternatives you've considered**
An alternative would be to allow Admins to manage shares created by other people .

**Comment by fschrempf** [comment]
@lhoff94 If I understand your description correctly, you can use the ACL feature to restrict the sharing for users in a specific directory of a groupfolder. Can you please check if this is an acceptable solution?

**Comment by fschrempf** [comment]
I'm assuming this issue is resolved and will close it. Please feel free to reopen, comment or create a new issue if you think this is not correct. Thanks!
