### ISSUE TITLE
Prevent manual creation of duplicate group folders

### ISSUE THREAD

**Issue by PVince81** [nextcloud/groupfolders#1246]
### Steps

1. Create a group folder "one" and assign to the "admin" group
2. Upload a file "a.jpg" into "one"
3. Create another group "one" and assign to the "admin" group
4. Upload a file "b.jpg" into "one"
5. Check listing for "one" folder
6. Check oc_filecache for those two files

### Expected result
Prevent creation of two group folders, or merge them somehow ß

### Actual result
The second group folder overlaps/overlays the first one.
So the listing of the "one" folder only shows "b.jpg" but not "a.jpg".
In oc_filecache we can see both entries with a different group folder id in the path "__groupfolders/$groupfolderId"

### Versions
groupfolders 8.2.0
Nextcloud server 20.0.5

**Comment by PVince81** [comment]
closing as duplicate of https://github.com/nextcloud/groupfolders/issues/681

**Comment by KodoGit** [comment]
Am I missing something? 1246 is closed as duplicate of 681 and 681 is closed as duplicate of 1246

The problem still exists with NC 21.0.4 docker (nextcloud:21-apache) with GF 9.0.3
Just updated from 20.

**Comment by fschrempf** [comment]
> Am I missing something? 1246 is closed as duplicate of 681 and 681 is closed as duplicate of 1246

Yeah this doesn't make sense to me either and the issue is still existing in current master. I reopened #681 to track this.
