### ISSUE TITLE
Can't Create Group Folder via UI

### ISSUE THREAD

**Issue by Bosi1024** [nextcloud/groupfolders#1250]
Hi! 

I seem to be not able to create a new Group Folder via the Nextcloud Web Interface. The following can be observed:

**Logentry:**

```Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_group_folders` (`mount_point`) VALUES(?)' with params [null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mount_point' cannot be null```

The XHR-Request  contains the Key-Value-Pair `mountpoint=test` when try to create a group folder named *test*.

This is the JSON-Response: 

```json
    {
        "ocs":
            {
                "meta":
                    {
                        "status":"ok",
                        "statuscode":100,
                        "message":"OK",
                        "totalitems":"",
                        "itemsperpage":""
                    },
                "data":
                    {
                        "id":3
                    }
            }
    }
```

Sometimes, refreshing th page and trying to create a group folder succeeds.

Creating a group folder from command line works all the time (folder shows up in browser).

I am using NC 20.0.6 (MariaDB, Apache, PHP7.4 on Ubuntu Server 20.10, non-Snap installation).
Browser is Firefox Developer Edition 86.0b3 .

Cheers!

**Comment by Yar4e** [comment]
Same here! Can't create Group Folders from web interface but can create them from cli.
CN 20.0.6, MariaDB 10.4.17, Apache 2.4.43, PHP 7.3.26, Firefox 85.0

**Comment by drdetergent** [comment]
Same problem, seems a browser issue only with Firefox, same operation done with Chromium browser worked fine.

My Firefox settings that are blocking the creation of a shared folder are
-  Privacy & Security = Strict
- Do Not Track = Always
- History = Never remember
- Security Deceptive Content and Dangerous Software Protection = all set

**Comment by pierreozoux** [comment]
looks related to https://github.com/nextcloud/groupfolders/issues/932

do you have an adblocker ?

**Comment by Bosi1024** [comment]
I've no adblocker installed neither are any add-ons. Plain vanilla Firefox with standard security settings.

With Firefox Developer Edition 87.0b9 (64-Bit) it seems to work flawlessly. I created ~10 group folders and each time it worked. Maybe it was a problem with this particular version of Firefox.

**Comment by pierreozoux** [comment]
I'll close in favor of https://github.com/nextcloud/groupfolders/issues/1295
