### ISSUE TITLE
A new group folder deletes exiting ones

### ISSUE THREAD

**Issue by Weberknecht37** [nextcloud/groupfolders#126]
I am recently testing groupfolders for an educational environment. I had an existing folder, we name it "testfolder" with some test-data. Then i used groupfolders to share this folder. Going back to the overview, "testfolder" was empty! I got no warning that this could happen and the deleted files are not in the deleted files folder.

**Comment by Nils160988** [comment]
Duplicate of https://github.com/nextcloud/groupfolders/issues/18

**Comment by marianoju** [comment]
+1

**Comment by icewind1991** [comment]
closing as duplicate

**Comment by NOULeENGINEER** [comment]
How can i get the name of the group folder by the objectid ? i can't find the table that contains this information in the DB. i need this information ASAP
