### ISSUE TITLE
API for permissions not working

### ISSUE THREAD

**Issue by thammerbacher** [nextcloud/groupfolders#127]
NC 13.0.4

I try to set permissions to a groupfolder via API. But it doesn't work. Has anyone ever used this feature? 

I tried the following php code:

$uri = 'https://user:pass@server.com/index.php/apps/groupfolders/folders/test/groups/admin

with 

CURLOPT_POSTFIELDS => 'permissions=00000001'

to add permissions for the admin group in a groupfolder called test.

I also tried to use the groupfolder id (10) instead of test.

It alsway returns a 100 OK but nothing happens!

Other API GET and POST calls work fine.

Can anyone help or post a working example?
Thanks!

**Comment by icewind1991** [comment]
the permissions field should be an integer that is the combination of the permissions constant (e.g. `17` for read and share)

**Comment by icewind1991** [comment]
For a working example, the web interface uses the same api, you can see what requests are being made by it in the browser

**Comment by thammerbacher** [comment]
Thank you! I misinterpreted the documentation. It works fine! Thank you!
