### ISSUE TITLE
Moving a subfolder from a groupfolder cause duplicate files and other issues

### ISSUE THREAD

**Issue by fabrixxm** [nextcloud/groupfolders#128]
I have a groupfolder, named "Group", I create a new subfolder, "test".
There I upload 2 files, "image.jpeg" and "document.docx"

I move the folder "test" out of "Group", in user's root, either by drag-n-drop or by selecting the folder and using the "copy / move" dialog.

I enter in "test" folder now and (after a few reload, some cache mabe?) I see this:
<img width="100%" alt="schermata 2018-06-20 alle 15 13 40" src="https://user-images.githubusercontent.com/309361/41660518-95a40d68-749c-11e8-85e0-fae0351403bd.png">

And opening document.docx (with Collabora) I get this in logs:

Level | App | Message 
-- | -- | -- 
Error | PHP | fopen(/var/www/nextcloud/data/__groupfolders/10/test/document.docx):  failed to open stream: No such file or directory at  /var/www/nextcloud/lib/private/Files/Storage/Local.php#282 

Netcloud 13.0.4
Group folders 1.2.0

**Comment by Cracky5457** [comment]
I just tested this bug and I was able to reproduce it. If you move a SubGroupFolder into the hierarchy of the group folder but not the root it's ok. If you move a subgroup to the root group folder it's corrupted ( for the odt file ) and if you remove the folder the image appears twice. Also if you move the subfolder outside the group folder ( so not the group folder parent but the real root of your nextcloud space ) it's the same issue. 

Exemple : 

I have the group folder

Parent/Child1/Child2/Child3

You can move Child3 into Child1 or Child2 but not in Parent ( you can it will result in corrupted files )

Also you can move Child3 outside of Parent ( directly in the root ) and it's corrupted too.

**Comment by Cracky5457** [comment]
Is this a duplicate of #18 ?

**Comment by icewind1991** [comment]
I can't reproduce this locally

**Comment by Cracky5457** [comment]
I reproduce it on my dev hosted instance. But also locally with my dev environement with nextcloud 13.0.4 and the latest version of group folder.

It's really simple to reproduce.

- You create a groupfolder "TestGroup" : /TestGroup
- Then you create some folder into through the UI : /TestGroup/Child1/Child2/Child3
- In Child3 you put a .jpeg file and a doc/excel file ( or better your create a collaborative doc file with the collabora pugin )
- Then through the UI ( using the breadcrumb ) you move child3 on the root / ( So **outside** the group folder /TestGroup, in your personal root space
- Then you move back child3 into your group folder, play to move it and remove it
- Try to repetively open/close your jpeg / move your folder inside the group folder ( at some points you can t move it )
- Then look inside your folder

<img width="1206" alt="bug1" src="https://user-images.githubusercontent.com/12050544/42690997-a99ffc0c-86a6-11e8-81c3-c2c53ac63e37.png">
<img width="1197" alt="bug2" src="https://user-images.githubusercontent.com/12050544/42690998-a9cfc7f2-86a6-11e8-97dc-8a85234e9b8c.png">
<img width="955" alt="bug3" src="https://user-images.githubusercontent.com/12050544/42690999-a9ed3b34-86a6-11e8-9de3-0dc1b0704d23.png">
<img width="1191" alt="bug4" src="https://user-images.githubusercontent.com/12050544/42691000-aa1e442c-86a6-11e8-95be-54597719f71b.png">

**Comment by sunchezz89** [comment]
I would like to let you know, I had a similar issue, when moving the Group folder from User root, into another folder in user's root.

After this, things break.
Is it enough to reference, or should I open a new one? 
https://github.com/nextcloud/server/issues/10366

**Comment by Cracky5457** [comment]
icewind1991 please investigate on this. I know it's probably an issue difficult to solve,  maybe which have to be solve on nextcloud platform core. But it made groupfolder almost unusable for a serious company.

**Comment by basemod** [comment]
Hi, thank you for this Module.
I have the same issue here, using NC 13.0.4 and Group Folders 1.3.3

**Comment by lievenmoors** [comment]
Same issue here, but still running on NC 13.

Example of what happens here:

- move a folder test containing to files test1 and test2 from one groupfolder to another
- the files appear correctly in the new location
- but in the filecache, there are still remnants for test/test1 and test/test2 under the OLD location, but the parent of those files is the folder "test" in the NEW location. So basically, these files don't have a valid parent anymore.
- the result is that you see the files twice in the Nextcloud web interface. When you try to click on them, the interface refreshes without opening the files.
- the only solution is to delete these remnants from the file cache

**Comment by fschrempf** [comment]
Using NC 21.0.0 and groupfolders 9.0.0 I can't reproduce this issue. Is this still a problem somewhere?

**Comment by pierreozoux** [comment]
I'll close then, feel free to reopen.

**Comment by fabrixxm** [comment]
I'm on NC 20.0.8 with groupfolder 8.2.0 and looks like it is working correctly 👍
