### ISSUE TITLE
Create Group Folder button is inactive

### ISSUE THREAD

**Issue by Windsurfer01** [nextcloud/groupfolders#1295]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Enter a new Group Folder name.
2. Click on 'Create' button.
3.

### Expected behaviour
The new group folder should be created.

### Actual behaviour
Nothing happens.
It is necessary to enter the name and then press <Enter> key.

### Server configuration

**Operating system:**
Linux
**Web server:**
Apache2
**Database:**
MySQL 10
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
20.0.7
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
cPanel and Softaculous
**Signing status:**
<details>
admin
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``
Can't be found. That index.php`is a file, not a folder.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
?
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Magneticdud** [comment]
Me too, I can't create new group folders

**Comment by Windsurfer01** [comment]
Try entering the folder name and then pressing the <return> key.

Don't click on the button.

**Comment by pierreozoux** [comment]
@Magneticdud @Magneticdud the button should work. Do you have any plugin activated in your browser? What if you deactivate them?

**Comment by HumanG33k** [comment]
Same bug here, 
I make some tests and there is strange behavior.  It's look like the issue occurs mainly when there is no existing or first create group folder. 

There is a bunch of warning about jquery and cookies but i not investigate more to check where their come (nextcloud, the instance conf or the app).  
```
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 
```

**Comment by Magneticdud** [comment]
I don't have any plugin or adblocker installed, but firefox is set to maximum strictness for against tracking (which has the desiderate side effect of blocking many ads).

I didn't do many tests in different browsers, but both the button or pressing enter didn't have a result.

**Comment by pierreozoux** [comment]
I could reproduce.

But now it is all the time working and I didn't see any relevant logs, I deactivated and reactived protection.. Wondering..

**Comment by Phaeton20** [comment]
I have the same bug. Apparently it isn't just a bug that it isn't shown i have the folder where the Group folder should go in the nextcloud data but it's empty

**Comment by prismopensource** [comment]
Same problem here when having a content blocker enabled. Using latest Safari Version 14.0.3 with Better Blocker by Ind.ie.

**Comment by spookysys** [comment]
I have this problem on one server but not on the other. No idea what the difference in setup might be, looks to me identical.

I noticed on the (failing) server the Developer Tools show an error 500, and a response that says javascript should be enabled:
![Untitled](https://user-images.githubusercontent.com/6197680/141175579-4ba1b4ea-5b23-4293-ab00-0ed89839e95b.png)

**Comment by spookysys** [comment]
> I have this problem on one server but not on the other. No idea what the difference in setup might be, looks to me identical. The list of group folders doesn’t show anything. When I add folders, they don’t show up.

Not sure if this is related, but when I type "occ groupfolders:list" on the server where it doesn't work, I get:
> {"reqId":"7ojGBiqJ0aWr1J0CPcxq","level":3,"time":"2021-11-11T13:44:35+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Following symlinks is not allowed ('/app/data//core' -> '/app/code/core/' not inside '/app/data/')","userAgent":"--","version":"22.2.0.2"}
> 
> In Local.php line 474:
>                                      
>   Following symlinks is not allowed  
>                                      
> 
> groupfolders:list [--output [OUTPUT]]

While on the server where group folders is working properly, I get proper output with a list of my group folders...

**Comment by joshtrichards** [comment]
This is an old issue and hasn't received any new traffic in ~3 years. I'm going to close it out. I'm guessing whatever this is it's now no longer the case. Is anyone still able to reproduce this behavior today? If so, respond and I'll re-open. Or, better yet since so many things have changed, create a new dedicated Issue. Thanks!
