### ISSUE TITLE
Where is the code which defines that admin user can do of CRUD ?

### ISSUE THREAD

**Issue by zak39** [nextcloud/groupfolders#1297]
Hello everyone ! :smiley: 

I am searching the code line where it is indicated that admin user can do of CRUD on groupfolders only.

I found the IGroupManager.php interface and I saw there is the `isAdmin()` method (to see below). However, I don't know which class implements this interface ?
If there is a container. I don't know where is it.

```php
<?php
	// code

	/**
	 * Checks if a userId is in the admin group
	 * @param string $userId
	 * @return bool if admin
	 * @since 8.0.0
	 */
	public function isAdmin($userId);
```

Can you help me to know where we define that admin user can do of CRUD groupfolders, please ?

Thanks ! :)

**Comment by pierreozoux** [comment]
told me he found a solution.

**Comment by zak39** [comment]
Yes I did !

The choice of Nextcloud is that there is one user and it's **admin**. To limit the scope others users we have to write the `@NoAdminRequired` **annotation** in a multiple-line comment (link : https://docs.nextcloud.com/server/21/developer_manual/basics/controllers.html?highlight=noadminrequired#authentication ) .
