### ISSUE TITLE
Missing release for NC 21 support

### ISSUE THREAD

**Issue by darix** [nextcloud/groupfolders#1305]
master is already at 22
and latest release targets 20

**Comment by sebalis** [comment]
This is hitting me after upgrading a Nextcloud to version 21. The app is no longer active and the group folders are gone. Would be very grateful for a quick resolution.

**Comment by filippolmt** [comment]
if i use enable untested app can problems arise? currently i can't see all my files, the situation is serious !!

**Comment by filippolmt** [comment]
> This is hitting me after upgrading a Nextcloud to version 21. The app is no longer active and the group folders are gone. Would be very grateful for a quick resolution.

if i use enable untested app can problems arise? currently i can't see all my files, the situation is serious !!

**Comment by Lars1963** [comment]
Ditto
cc @rullzer @juliushaertl

**Comment by fondemen** [comment]
A workaround :
```
git clone -b stable21 https://github.com/nextcloud/groupfolders.git
cd groupfolders
make appstore
cd build
tar -xzf groupfolders-8.0.0.tar.gz
```
and then move the extracted groupfolders so that it replaces the existing one in custom_apps folder of nextcloud installation.

**Comment by filippolmt** [comment]
For obvious reasons I had to enable the untested app too, it would seem to be fine, I didn't have any problems

**Comment by robertofabrizi** [comment]
@filippolmt  so just by enabling untested apps the group folders are back and work just fine? Thank you!

**Comment by filippolmt** [comment]
> @filippolmt so just by enabling untested apps the group folders are back and work just fine? Thank you!

yes, I didn't have any problems

**Comment by sebalis** [comment]
I opted for @fondemen’s workaround and it seems to work. Many thanks, I should have read the Makefile …

Of course we’re now running unstable software, for either of these two workarounds. Would still like to ask @rullzer or @juliushaertl for some response – perhaps a recommendation on how to avoid this kind of problem in the future. All those affected by this issue were early adopters of course so we should have been more careful – in my case the thinking had been that the Docker image nextcloud:fpm-alpine would not be switched to version 21 before apps as fundamental as groupfolders would be available. I realise that groupfolders is not bundled with Nextcloud, but maybe it should be, as I said I regard it as rather fundamental.

Could Nextcloud also say when an official release for NC 21 could be expected? Obviously I would like to end this untested state as soon as possible.

**Comment by fondemen** [comment]
I actually was bitten by this issue as I'm using docker for deployment and let `latest` tag to be the default one (my fault, I should have used `stable`). But I think @sebalis is right, I'd be glad groupfolders to be included in Nextcloud directly, as it's (to my opinion) the best way to have files not belonging to someone (that can leave, or change responsibilities), but to an organization.
I've already be bitten by a similar issue when groupfolders migrated from apps to custom_apps...

**Comment by BugDave** [comment]
Any status on this?

**Comment by rubenlopez77** [comment]
Your files still there, just enable untested app and enable it. Your folders and files will show up with no problem.

**Comment by fschrempf** [comment]
> All those affected by this issue were early adopters of course so we should have been more careful – in my case the thinking had been that the Docker image nextcloud:fpm-alpine would not be switched to version 21 before apps as fundamental as groupfolders would be available.

Same here. I wasn't aware that there could be an official release of the server when not all of the important apps offer a release for the new version. Is this really something that is to be expected?

I thought that's one of the reasons why there are "featured" apps which are marked accordingly in the app store. So admins would know these apps are maintained in sync with the server release. But maybe I got that wrong!?

> I realise that groupfolders is not bundled with Nextcloud, but maybe it should be, as I said I regard it as rather fundamental.

Considering other related issues mentioned in #1215 I come to the same conclusion. Groupfolders should either be bundled and maintained together with the server, or the app needs more care to make sure releases are available in time.

**Comment by juliushaertl** [comment]
Sorry for the delay on this one. 9.0.0 has just been released for Nextcloud 21 compatibility: https://github.com/nextcloud/groupfolders/releases/tag/v9.0.0

**Comment by fschrempf** [comment]
@juliushaertl Thanks a lot!

**Comment by Lars1963** [comment]
@juliushaertl Also a big Thank You by me!
