### ISSUE TITLE
API list specific folder by id.

### ISSUE THREAD

**Issue by johndoe7000** [nextcloud/groupfolders#132]
Hello,
I try to get info for a specific groupfolder. Is this possible?

For example...

curl -u XXX:YYY -s -X GET 'https://nextcloud.example.com/index.php/apps/groupfolders/folders?id=3' -H "OCS-APIRequest: true"

or

curl -u XXX:YYY -s -X GET 'https://nextcloud.example.com/index.php/apps/groupfolders/folders/3' -H "OCS-APIRequest: true"

does not work.

**Comment by johndoe7000** [comment]
Or even better...
Create groupfolders not by it's id only but "id+mount_point" like...

234_Shared Group Folder

Take spaces into account!

**Comment by Cracky5457** [comment]
Same here, according to the doc 

apps/groupfolders/folders/$folderId  should work but it's not

apps/groupfolders/folders works well and give me the list of groups with their id that I use as $folderId
