### ISSUE TITLE
InvalidFieldNameException: Unknown column 'size' in 'field list' (oc_group_folders)

### ISSUE THREAD

**Issue by team-a2** [nextcloud/groupfolders#134]
With group_folders 1.2.1 the following problem came up:

https://github.com/nextcloud/fulltextsearch/issues/347
(perhaps not a bug of fulltextsearch)

**Comment by icewind1991** [comment]
please retry with 6643d134cbc8aad70ec42d81bc469559bceaf5e4

**Comment by team-a2** [comment]
Looks like fixed with group_folders 1.2.2
