### ISSUE TITLE
Cannot restore deleted files - nextcloud 21, group folders 9

### ISSUE THREAD

**Issue by caesarcxiv** [nextcloud/groupfolders#1349]
[webdav] Fatal: Error: Call to undefined method OCA\GroupFolders\Trash\TrashBackend::userHasACLAccessToPath() at <<closure>>

 0. /var/www/html/apps/files_trashbin/lib/Trash/TrashManager.php line 65
    OCA\GroupFolders\Trash\TrashBackend->restoreItem(OCA\GroupFolders\Trash\GroupTrashItem {})
 1. /var/www/html/apps/files_trashbin/lib/Sabre/AbstractTrash.php line 94
    OCA\Files_Trashbin\Trash\TrashManager->restoreItem(OCA\GroupFolders\Trash\GroupTrashItem {})
 2. /var/www/html/apps/files_trashbin/lib/Sabre/RestoreFolder.php line 76

**Comment by XueSheng-GIT** [comment]
I'm facing the same issue. Files of group folders cannot be restored (neither by the user who deleted the file, nor the admin of a group folder can restore deleted files). Any workaround?

**Comment by pierreozoux** [comment]
Do you use s3? It looks related to https://github.com/nextcloud/groupfolders/issues/1218

**Comment by XueSheng-GIT** [comment]
I'm not using any external storage, just local storage.

**Comment by caesarcxiv** [comment]
local storage

**Comment by fschrempf** [comment]
@icewind1991 Looks like this has been introduced by 8fcff71449cbf2addd198fb8b7be87ba73af0712. Can you come up with a fix, please?

**Comment by caesarcxiv** [comment]
I applied commit 06966fd and this is the new error when doing a multiple file restore

[PHP] Error: Error: Undefined offset: 2 at /var/www/html/custom_apps/groupfolders/lib/Trash/TrashBackend.php#312 at <<closure>>

0. /var/www/html/custom_apps/groupfolders/lib/Trash/TrashBackend.php line 312
   OC\Log\ErrorHandler::onError(8, "Undefined offset: 2", "/var/www/html/c ... p", 312, {0: "And 3 more  ... "})
1. /var/www/html/apps/files_trashbin/lib/Trash/TrashManager.php line 113
   OCA\GroupFolders\Trash\TrashBackend->getTrashNodeById(OC\User\User {}, 1811881)
2. /var/www/html/apps/files_trashbin/lib/Controller/PreviewController.php line 101
   OCA\Files_Trashbin\Trash\TrashManager->getTrashNodeById(OC\User\User {}, 1811881)
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 218
   OCA\Files_Trashbin\Controller\PreviewController->getPreview(1811881, 128, 128)
4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 127
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Trashb ... {}, "getPreview")
5. /var/www/html/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Trashb ... {}, "getPreview")
6. /var/www/html/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Files_Tras ... r", "getPreview", OC\AppFramework\ ... {}, {_route: "files_ ... "})
7. /var/www/html/lib/base.php line 993
   OC\Route\Router->match("/apps/files_trashbin/preview")
8. /var/www/html/index.php line 37
   OC::handleRequest()

**Comment by icewind1991** [comment]
@caesarcxiv 

can you provide the output of the following sql query

```sql
SELECT path FROM oc_filecache where fileid = 1811881;
```

**Comment by caesarcxiv** [comment]
> @caesarcxiv
> 
> can you provide the output of the following sql query
> 
> ```sql
> SELECT path FROM oc_filecache where fileid = 1811881;
> ```

Output: 
'__groupfolders/55/Partner/Hidden/NotReal/SK/Edits/SR62352.jpg'

**Comment by icewind1991** [comment]
https://github.com/nextcloud/groupfolders/pull/1381 should fix this I think

**Comment by caesarcxiv** [comment]
#1381 did resolve the offset error - here is a new error when restoring in bulk


Fatal | webdav | OCP\Files\NotFoundException: /var/www/html/apps/files_trashbin/lib/Trash/TrashManager.php - line 65:OCA\GroupFolders\Trash\TrashBackend->restoreItem(OCA\GroupFol ... {})/var/www/html/apps/files_trashbin/lib/Sabre/AbstractTrash.php - line 94:OCA\Files_Trashbin\Trash\TrashManager->restoreItem(OCA\GroupFol ... {})/var/www/html/apps/files_trashbin/lib/Sabre/RestoreFolder.php - line 76:OCA\Files_Trashbin\Sabre\AbstractTrash->restore()/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php - line 160:OCA\Files_Trashbin\Sabre\RestoreFolder->moveInto("1eb238d6349 ... 8", "trashbin/tr ... 8", OCA\Files_Tr ... {})/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 612:Sabre\DAV\Tree->move("trashbin/tr ... 8", "trashbin/tr ... 8")/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:Sabre\DAV\Server->emit("method:MOVE", [ Sabre\HTTP ... }])/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:Sabre\DAV\Server->start()/var/www/html/apps/dav/lib/Server.php - line 332:Sabre\DAV\Server->exec()/var/www/html/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()/var/www/html/remote.php - line 167:require_once("/var/www/ht ... p")
-- | -- | --

**Comment by fschrempf** [comment]
This fix hasn't been release, so seeing this issue closed might confuse people. Let's reopen until this has landed.

**Comment by juliushaertl** [comment]
Released with 9.0.1/8.2.1/7.1.2
