### ISSUE TITLE
Huge load on maintenance task related to GP, following upgrade NC19 -> NC20, forcing to disable GP

### ISSUE THREAD

**Issue by pierfu** [nextcloud/groupfolders#1361]
Hi,
a few days after upgrading Nextcloud from 19 to 20.0.7, we had to face a critical issue on a production server, ands it seamed directly related to GroupFolders.

- huge lines in NC log, like ~5.000.000 characters, of failed requests, with :
1/ recurring pattern : An exception occurred while executing 'DELETE FROM \"oc_filecache_extended\" WHERE   \"fileid\" IN (?...?) ' with params [id1,... idN] :\n\nSQLSTATE[HY000]: General error: 7 number of parameters must be between 0 and 65535", ,"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"DELETE FROM \"oc_filecache_extended\" WHERE \"fileid\" IN  (?...?) ",        [19017890,19537170,19459948,18911007,15822686,"And 89981 more entries
2/ GroupFolders appears many times in these huge log lines : {"file":"/var/www/nextcloud/nextcloud-20.0.7/apps/groupfolders/lib/ACL/ACLManager.php","line":75,     "function":"getRootStorageId","class":"OCA\\GroupFolders\\ACL\\ACLManager","type":"->","args":[]}

- problem was solved first times wirth "php occ maintenance:repair", that seamed to kill the job responsible for blocking everything, but never in a long-term way

- the only long-term workaroud was to disable groupfolders completely

So,
- has anyone known similar issue with after upgrade to Nextcloud 20 ?
- could this be a maintenance issue with GroupFolders, which would require too much work to Nextcloud Core at the same time, instead of asking this maintenance with a maximum entries set ?

I join an excerpt of the log.
[tail_-n1_nextcloud_abbr.log](https://github.com/nextcloud/groupfolders/files/6102538/tail_-n1_nextcloud_abbr.log)

**Comment by brtptrs** [comment]
We are seeing similar huge query statements, and many long running mysql requests that often include group-folders.

**Comment by pierfu** [comment]
Hi,
any update on this big issue ?

**Comment by ASerbinski** [comment]
That duplicate is not a duplicate. It involves php unnecessarily/inefficiently processing a long list of files in the trashcan.

**Comment by pierfu** [comment]
Just to be clear, when i pubished this issue, by saying _maintenance issue with GroupFolders_ i did not mean _maintenance mode_ at all, but maintenance task run by cron or whatever.

**Comment by pierreozoux** [comment]
@pierfu do you still have issues? Maybe an update fixed it?

**Comment by pierfu** [comment]
> @pierfu do you still have issues? Maybe an update fixed it?

I got no answer on this issue, and it happened on a big production instance, so the only thing i'm sure about is that i won't take that risk to just try and mybe break everything. Sorry :/

Is this extension planned on beeing merged in Nextcloud core ? I can see on https://apps.nextcloud.com/apps/groupfolders that Nextcloud GMBH is now editor. That could maybe help on maintaining this app more efficiently.

**Comment by pierreozoux** [comment]
What do you mean nextcloud core?
It is part of the supported app:
https://docs.nextcloud.com/server/latest/admin_manual/installation/apps_supported.html

So if you have support with Nextcloud GMBH, they will gladly help you.

**Comment by pierfu** [comment]
Thanks for your answer.
By core I mean not-an-app.

I missed this supported-apps page, and this possibility of asking support to Nextcloud GMBH.
But from what i undersand in pricing presentation, the only way of having quick support garanty (quick or not, what does mean : "Reaction time: 1h, 4h, 12h or 24h" ??), is Premium plan, but i definitly can't afford "100 users for €95.50/user/year" cost.
And your suggestion means that you can't rely on this Github issues, not really.

So i can't just try again GP and see if it crashes.
The really big problem with this app is that it changes data management too deeply : one cannot just try it, make GP shares, and disable it, because shares are not managed as they are in the core way.
I spent hours with my client on re-creating shares that were managed by GP, especially link shares.

**Comment by pierreozoux** [comment]
I understand.
You could "duplicate" this instance in an other env to try.
And yes, the "community" support is for Home users mainly, it is not recommended to run big production instance without support or knowing what you are doing.
(But i'm not representing Nc here, I'm just part of the community, not an employee, and what I'm saying comes from my experience of Nextcloud communication)

**Comment by pierfu** [comment]
Thanks Pierre,
we already have a staging instance, mainly for validating NC updates, but we never experienced nor could reproduce the issue on staging, surely because of scale and load difference.
So for now, i honestly can't recommend to re-enable GP, mainly because :
- i had no technical answer on the issue
- GP changes NC too deeply to be easy to enable/disable.

I think we can close even if not resolved.

**Comment by pierreozoux** [comment]
There is a somehow related issue here:
https://github.com/nextcloud/groupfolders/issues/1215

As you want feel free to close or not, your call :)
(I think it is good to keep this issue open, it is documenting the current state of this app, but this is only my opinion :) )

**Comment by pierfu** [comment]
OK, il leave it opened.

**Comment by solracsf** [comment]
This was mainly fixed by https://github.com/nextcloud/groupfolders/commit/57cf15155fb42732642bcf6af244ffc078a742ef
Queries are now made in chunks to avoid that `General error: 7 number of parameters must be between 0 and 65535`
