### ISSUE TITLE
Size Calculation incorrect with stacked Groupfolders

### ISSUE THREAD

**Issue by ksteinb** [nextcloud/groupfolders#1365]
We stack groupfolders, because we need a special setup with ACL's (some groups need higher rights inside subfolders, which is not possible otherwise)

We discovered that in some cases the size calculation will be incorrect. This seems to be dependent on the internal Groupfolder ID.

See this example:

Groupfolders:

a   (contains nothing than other groupfolders)
a/AA   contains data
a/BB   contains data

The size for "a"  will be calculated correctly in this case:

ID  Groupfolder

1   a
2   a/AA
3   a/BB

It will be shown as Zero in this case:

ID  Groupfolder

1  a/AA
2  a/BB
3  a

So probably in this case just the content of "a" will be calculated, not the sub - groupfolders

The second case could happen if  after the creation of "a" some other unrelated groupfolder was deleted, then its ID would be reused for subfolders, nothing that the creator of the groupfolders could see in the WEB GUI

**Comment by provokateurin** [comment]
I was not able to reproduce this, @ksteinb can you check if this still exists?

**Comment by provokateurin** [comment]
Please re-open if it is still the case.
