### ISSUE TITLE
Move - how to handle existing targets skip or overwrite

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/groupfolders#1376]
NC 20.0.8
existing targets cause an error / information message for each existing target
(I just got some 300 ...) 
and the files remain in the source folder 
this means that this creates duplicates and no way to automatically clean up.

The user should be able to select what to do 

- overwrite
- skip (meaning to remain with duplicates)

probably it should also distinguish between 

- identical file - typically images
- altered file  - very often documents.

**Comment by provokateurin** [comment]
This does not sound Groupfolder specific and we also have conflict handling, so please open an issue in server instead if you are still facing problems with this.
