### ISSUE TITLE
Deleted files not showing in trash

### ISSUE THREAD

**Issue by spralexx** [nextcloud/groupfolders#1379]
Steps to reproduce:

1. Have a Nextcloud version 20.0.8 or 21.0.0 (have not tested other versions)
2. Install Groupfolder App
3. Create groupfolder with full permissions for a single group (have not tested with multiple groups)
4. Sign in with a user (User1) belonging to the group with permissions for the newly created groupfolder
5. Create a subfolder within the groupfolder and share it with a different user.
6. Sign in with that user (User2)
7. Create a subfolder in the shared folder
8. Share this subfolder by link with only upload permissions
9. Use independent Browser to upload a file via shared link
10. As User2 delete the uploaded file.

Expected behavior:
The deleted file appears in both thrashbins of User1 and User2

Actual behavior:
The deleted file only appears in the trashbin of User1

**Comment by jospoortvliet** [comment]
Trashbin is now added to Groupfolders. https://github.com/nextcloud/server/pull/49265
