### ISSUE TITLE
number sign (#) in Groupfolder names

### ISSUE THREAD

**Issue by SchnitZel01** [nextcloud/groupfolders#1382]
Hey,

I had a weird bug, where advanced permissions couln't be saved when I added a new rule. Turns out the Problem was that the Name of the folder was "#101 test". I then created a folder "101 test" without the number sign and every thing worked as expected.

How to reproduce:
-create a folder which starts with "#"
-enable advanced permissions
-add a new advanced permission to the folder via the share window
-reload page
-added advenaced permission is gone

I'm not very experienced with programming but my guess is that there is some escape missing when using a number sign, the number sign terminates the string for the folder's name prematurely und tries to run the rest as code (similar to how SQL injection or cross-site-scripting works). I'm not 100% sure about it, it's rather just a hunch.

Not really a huge problem we now just use folder names without a number sign. Still it boggled my mind for hours until I found the Problem.

If my hunch is right I guess it shouln't be hard to fix this.

Cheers!

SchnitZel

**Comment by pierreozoux** [comment]
Duplicate of https://github.com/nextcloud/groupfolders/issues/925
