### ISSUE TITLE
Place group folders to extra item in left menu and exclude them from main view

### ISSUE THREAD

**Issue by rarapost** [nextcloud/groupfolders#139]
Now, all group folders are placed into main file's application, therefore they are mixed with its content (another folders, files ... etc). 

It would be great to exclude group folders from content of all files and create an extra left-side menu item (called - for example "Group folders" or something like that).

Even better, it could be an option at each folder in admin configuration, which will tell whether the folder should be placed into common files content, or into separated left-menu item.

**Comment by XueSheng-GIT** [comment]
Stumbled over this by accident. Part of this issue seems to be fixed with latest releases (e.g. 27.1.1): There's a separate category for groupfolders within the left sidebar. But all groupfolders are still shown within the default files overview (which is fine for me, but is part of this issue).

**Comment by joshtrichards** [comment]
Done. The balance was completed in nextcloud/server#44455

**Comment by cbrnr** [comment]
Sorry for reviving this old issue, but what if I wanted to hide group folders on my local machine when using a sync client? I don't think that the original problem is solved for this use case, so it would still be useful if I could move them.

**Comment by provokateurin** [comment]
Please open an issue in https://github.com/nextcloud/desktop instead.
