### ISSUE TITLE
OCC for Manage advanced permissions

### ISSUE THREAD

**Issue by dxniel7402** [nextcloud/groupfolders#1390]
Hello people,
I would like to implement the following:

I have a "master folder" in which all subfolders are structured down. However, these subfolders are person-related and should only be visible and editable for the authorized persons including the admin -> This also means that those who do not have authorization should not even see the folder.
I was able to implement the whole thing very successfully, without problems, but with a lot of click work on the web interface.

**Now I want to automate the whole thing:**
1. create a user in Nextcloud
2. create a personal subfolder in the "master folder"
3. assign authorization

The first point has already worked without problems -> the new user is created correctly and added to the group accordingly.
The second point also worked, but I create the folders via `mkdir` and then execute the command `occ files:scan --all`. The folder is already visible for all in the "Master Folder".

Now we come to the third and last point:
I absolutely can't figure out how to create the appropriate Manage advanced permissions on command line level.

The whole group should not be able to see the folder, except the selected persons. I can't find any commands to do this without using the web interface...

I really hope that you can help me somehow, otherwise I will soon be busy with clicking only ...

**Comment by fschrempf** [comment]
For steep 2 you should probably use `occ groupfolders:create <name>` and for step 3 `occ groupfolders:permissions` should do the job. Did you try these commands? Both are listed in the [README](https://github.com/nextcloud/groupfolders#command-line-configuration-via-occ).

**Comment by jngrb** [comment]
Yes, you can use these CLI commands.
First, set up a new folder
`occ groupfolders:create $folderName`
Then, allow a certain group to use it:
`occ groupfolders:group $folderId admin write delete` and maybe
`occ groupfolders:group $folderId $othergroup write`
Finally, enable advanced permissions (ACL) and allow someone to define it (here group 'admin' again):
`occ groupfolders:permissions $folderId -e` and
`occ groupfolders:permissions $folderId -m -g admin`
Now, you can edit the ACL,
`occ groupfolders:permissions -g admin -- $folderId $path +read +write +create +delete +share` and maybe
`occ groupfolders:permissions -g $othergroup -- $folderId $path +read -write -create -delete -share`
but I find it very cubersome to do so.

I'd prefer, if a remote access for the ACLs would be implemented. There is alraedy an issue for that: #1256

**Comment by fschrempf** [comment]
I'm closing this due to missing feedback from the author.
