### ISSUE TITLE
Make it usable through the API

### ISSUE THREAD

**Issue by nikaro** [nextcloud/groupfolders#14]
Hello,

This is the app i needed to manage my groups folders! So thank you :smile: 

It would be even better if it could be managed through the API. But i'm not familiar enough with Nextcloud code to do it myself…

Here is the documentation which should tell us how to make it: https://docs.nextcloud.com/server/12/developer_manual/core/externalapi.html

There not much information in the doc, so here are how some apps seem to handle it:

* Server Info
  * https://github.com/nextcloud/serverinfo/blob/master/appinfo/routes.php
  * https://github.com/nextcloud/serverinfo/blob/master/lib/Controller/ApiController.php
* News
  * https://github.com/nextcloud/news/blob/master/appinfo/routes.php
  * https://github.com/nextcloud/news/blob/master/lib/Controller/ApiController.php
* Notes
  * https://github.com/nextcloud/notes/blob/master/appinfo/routes.php
  * https://github.com/nextcloud/notes/blob/master/controller/notesapicontroller.php

Thank you :-)

**Comment by LukasReschke** [comment]
@icewind1991 Thoughts on adding some small OCS calls here and change the web frontend to use OCS as well? :)

**Comment by nikaro** [comment]
@LukasReschke in not familiar with Nextcloud code (and i'm more Python than PHP) but do you have some documentation (and/or code examples) to recommends if i want to try to do it by myself ?

**Comment by patrick-stickler-csc-fi** [comment]
Being able to automate the creation of group folders, associating them with groups, and defining their quotas would be essential for us to use this in our particular application, so we both want to add our vote/request to providing at least the minimal essential functionality to do this as well as will be following this space very closely to see how this develops. This app is looking very very promising and addresses what is surely a very common need for many communities. Cheers.

**Comment by icewind1991** [comment]
The next release is usable trough an ocs api.
