### ISSUE TITLE
Why advanced permissions rules apply to every folders?

### ISSUE THREAD

**Issue by nicolaspetitjean** [nextcloud/groupfolders#1408]
Hello,
I’m trying to understand how Group Folder works. I have one Group Folder and 2 subfolders:
```
TEST
├── dir1
├── dir2
```
My only requirement is that users in group can only read content. But if I add an advanced permissions rule to dir2 (allowing one user to write in folder dir2), the new rule apply to dir1 as well !! In other words, my user can write in both dir1 and dir2, is that the expected behavior ? We can’t add a specific rule in a sub folder ?
Thanks.

**Comment by fschrempf** [comment]
No this is definitely not expected. Did you check if the user can really write to both directions, or if it's just the UI that shows wrong permissions? For the latter there is an issue that might be causing this: #1378.

**Comment by nicolaspetitjean** [comment]
It is worth than that. The user can't write at all, even into the folder dir2. I'm using Nextcloud 21.

**Comment by fschrempf** [comment]
So now I'm confused. First you claim "my user can write in both dir1 and dir2" and then "The user can't write at all, even into the folder dir2". Can you give a step by step explanation of how to reproduce the error and what you expect to see and what you are actually seeing, please?

**Comment by nicolaspetitjean** [comment]
1. I create a new Group Folder TEST with two sub dirs : dir1 et dir2
2. I have 2 users : user1 & user2. user1 has full access to TEST. user2 do not have any access yet
3. I add a new rule to dir2 to allow user2 to access (read and write) only dir2:  [screen-1.jpg](https://i.ibb.co/CHxyrp4/screen-1.jpg)
4. The UI shows the new rule for dir2 (it is what we want) but also for dir1 (it is not expected)
5. But user2 have only read access: [screen-2.jpg](https://i.ibb.co/gPPKWrj/screen-2.jpg)

Is it more clear ? Thank you.

**Comment by jngrb** [comment]
I think this is only the representation bug #1378 , please see my step-by-step bug report there: https://github.com/nextcloud/groupfolders/issues/1378#issuecomment-809653767
Does the workaround, to close the sidebar with "x" help?

Also, if you need an immediate fix, you can try my patch: #1406
