### ISSUE TITLE
Group folder showing in file explorer but not in admin section

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/groupfolders#141]
Environment:
============
NC 13.0.4, Group Folders 1.2.0
Ubuntu 16.0.4, Nginx, Mysql

Description:
==========
Group folder exists but does not appear in the admin section. See video attached.
There is a group folder called "operation", it can be seen in the file explorer, but it does not show in the admin section. 
Furthermore, when trying to create a new group folder with the same name, the system does not reject the attempt. After creating this new operation folder again, it does not show again. When creating it a second time, it finally shows in the list.

There is no JS error in the developer console.

https://cloud.nextcloud.com/s/yQ6kWsoWJoertmD

**Comment by icewind1991** [comment]
Can you check in the network inspector what the reply is of the `https://example.com/apps/groupfolders/folders` request when you load the groupfolder settings

**Comment by mathiasconradt** [comment]
@icewind1991 I don't have access to this instance anymore, it's an offline NC instance when I was on-site. I need to ask them.
