### ISSUE TITLE
Allow management delegation of groupfolders

### ISSUE THREAD

**Issue by StCyr** [nextcloud/groupfolders#1413]
Hi,

Company Arawa has identified a customer need where it is requested that non-NC admins are able to manage groupfolders (to simplify workflows and lower the load on IT staff).

After discussion with @jancborchardt and @juliushaertl it appears that NC would accept a change where access restrictions to groupfolders' REST API's would be managed in the same way as what's done in https://github.com/nextcloud/impersonate.

I'll send you a PR implementing this change in the next coming days.

Cc: @zak39 @fifh

# Alternate solution

During the discussion, @juliushaertl mentionned the possibility to rather create a stable PHP API  for groupfolders (which could then be used by any application regardless of the user's admin rights), but this solution has been dismissed for now and the implications of implementing it haven't been thought much.

**Comment by fschrempf** [comment]
See #1722 for an up-to-date implementation by @CarlSchwan using the new admin delegation API in NC23.

**Comment by szaimen** [comment]
Should be done
