### ISSUE TITLE
🎯 📚 📕  FAQ ➕ KNOWN ISSUES

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/groupfolders#1414]
### Potential Security Issues

- #1057 (**Potential leak of sensitive information**)

### General

- ~~Currently, **using encryption on group folders is not supported**. All files stored within a group folder will be stored unencrypted. See https://github.com/nextcloud/groupfolders/issues/912 for more information.~~
- Avoid special characters in group folder names as there are **[know issues with this](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22hot%20spot%3A%20filename%20handling%22%20label%3Abug)**.
- Some parts of the **UI (admin or user)** [need to be fixed/improved](https://github.com/nextcloud/groupfolders/labels/ui).
- **Syncing group folders with desktop clients** [has some flaws](https://github.com/nextcloud/groupfolders/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+client+sync%22+label%3Abug). 
- Integration with other apps and features is [not as good as we'd like](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3Aintegration+label%3Abug)
- [UX for **ACL ("Advanced Permissions")** is still to be improved](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+acl%22+label%3Abug)
- [**Trash handling** doesn't work properly with groupfolders](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+trashbin%22+label%3Abug+)
- **Sharing** of directories inside a group folder can lead to [all kinds of problems](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+sharing%22+label%3Abug+). 
- There are [unresolved bugs related to **visibility and application of quotas**](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+quota%22+label%3Abug+).
- There are [unresolved bugs related to **searching in group folders**](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+search%22+label%3Abug+)
- There is an issue with file ids not being static which can lead to invalidation of share links: #1468

### What about nested groupfolders?

Creating subfolders in a group folder that are group folders themselves (e. g. `Docs/Engineering`, `Docs/Marketing`) is supported, but the root group folder (e. g. `Docs`) will not be automatically created. This can be solved by also creating the root folder as a separate group folder.

### How do desktop clients handle groupfolders?

In Client applications, group folders will appear as external storage and may need to be explicitly addressed for download.

**Comment by jtrees** [comment]
Thanks so much for this issue. I was going to give the app a go but after seeing this, decided not to.

**Comment by jospoortvliet** [comment]
Just went over all of these and - many of the searches are empty or have only 1 issue left. Basically, this post is by now so outdated I don't think it helps anyone. Well, other than scaring people from using Groupfolders - which might not be perfect, but does what it should do for the vast majority of users. So counter productive.

**Comment by alexanderdd** [comment]
> many of the searches are empty or have only 1 issue left

@jospoortvliet I clicked randomly on these, and they have many results:
- https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+acl%22+label%3Abug
- https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+trashbin%22+label%3Abug+
- https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+sharing%22+label%3Abug+

maybe update the post to remove the empty searches/one result searches? change the title/wording so it is less counterproductive? well or keep it closed, I don't have strong feelings about it

**Comment by provokateurin** [comment]
Many of them are not even triaged properly. I think it's fine to have this issue closed, as it indeed sounds much worse than the current situation actually is.
