### ISSUE TITLE
Orphan file records from DB are not cleaned

### ISSUE THREAD

**Issue by Emi94** [nextcloud/groupfolders#143]
When moving a folder out of a groupfolder, the DB records of the files inside the folder that's been moved are not deleted/cleaned from DB. I don't know if this is intended and these are records are supposed to be deleted by background jobs, but the records are still there after 2 days. I also tried to clean those records by running "occ files:scan" and "occ files:cleanup", but that didn't fix it either. This makes me believe that orphan files from groupfolders are not detected by nextcloud.

One user reported that after moving a folder out of a groupfolder, he's still seeing the folder inside the groupfolder but with a size of 0 KB (probably because the files are not in the groupfolder anymore, just the DB records). Although I couldn't reproduce this, only what I described in the first paragraf.

**Comment by Emi94** [comment]
After a few days it seems that the orphan DB records have been automatically cleaned. But still, when I run  "occ files:scan" and "occ files:cleanup", shouldn't that clean the DB?

As for the other issue with files still being in the groupfolder after the move, seems I understood it wrong. It's actually another issue that I've seen it's already reported. Sorry for the confusion.

**Comment by mvbenthem** [comment]
You probably want to use the maintenance:repair command as that cleans and updates the database.
See: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/occ_command.html#maintenance-commands

**Comment by ZeikoFr** [comment]
Hi @Emi94 Is the issue still relevant or is it fix in more recent version of NC ?

**Comment by fschrempf** [comment]
As there was no more feedback, I will close this as stale. @Emi94 If you think this is still a problem, please open a new issue. Thanks!

**Comment by Emi94** [comment]
Sorry, somehow I missed the question from December. The issue is quite old now and I don't remember having that problem again, so I guess it's ok to be closed.
