### ISSUE TITLE
Quota Dashboard Widget

### ISSUE THREAD

**Issue by diemelone** [nextcloud/groupfolders#1447]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Hard to keep track how full a groupfolder is

**Describe the solution you'd like**
dashboard widget which diesplays the quota, maybe even the dropdown list from the settings page

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by dmgeurts** [comment]
This would definitely help in managing group folders!

**Comment by provokateurin** [comment]
Not sure if this is about admins or normal users, but for both of them we already have issues (not a dashboard widget but still an overview): https://github.com/nextcloud/groupfolders/issues/1736 (admins) https://github.com/nextcloud/groupfolders/issues/44 (users).
