### ISSUE TITLE
ACL ignored on a subfolder when parent folder is accessed via share

### ISSUE THREAD

**Issue by annievoss** [nextcloud/groupfolders#1452]
when a parent folder within a groupfolder is shared to a user who doesn't have read permissions on a subfolder, the subfolder ist readabale when the user accesses the parent folder via the share. If the user navigates through the folder structure to that specific folder, the ACL works and the subfolder is not visible.

### Structure of data pane:
Groupfolder
  --Parent folder --> This folder ist shared
    ----subfolder --> this folder has read denied via ACL
Parent folder (shared by admin)

### Steps to reproduce
1. in a group folder create a parent folder and in there a subfolder
2. deny read permissions of the subfolder for a group
3. share the parent folder with a user of that group
4. let the user access the subfolder via groupfolder structure and via share

### Nextcloud version
19.0.9

**Comment by fschrempf** [comment]
@annievoss I don't think this is a bug. The ACL rules only apply within groupfolders. As soon as you decide to share a file or directory and someone accesses it via the share, the permissions of the share apply. What would you expect? Where is the issue?

**Comment by annievoss** [comment]
I expect the acl rules apply on the file/folder itself, not on the way of accessing it. Maybe similar to the file permissions on linux etc.

**Comment by fschrempf** [comment]
I think this is out of scope and it's just not how this app is intended to work. If the ACL permissions would be applied to the file/directory regardless of the access method, then there would be no way to make use of traditional sharing within a groupfolder.

Maybe what you are looking for is something like the [File Access Control App](https://docs.nextcloud.com/server/latest/admin_manual/file_workflows/access_control.html).

If you want to use groupfolders you can also just restrict users from creating shares via ACL. That way everyone would be forced to access via groupfolder.
