### ISSUE TITLE
Creating directory in groupfolder fails with more than one group assigned

### ISSUE THREAD

**Issue by aleadco** [nextcloud/groupfolders#1457]
### Description
After upgrading to NC21.01 there are errors in creating and deleting folders in groups with more than one group assigned.

### Steps to reproduce
1. Create group folder and authorize only one group at first.
2. Create content within the folder, it will not be a problem now.
3. Authorize a second group to access the group folder. At this point, when you try to create a folder it says that it could not be created and the same happens if you want to delete something that is already created.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**Ubuntu 18.04

**Web server:**Apache2 FPM

**Database:**MySQL 8.0

**PHP version:**8

**Nextcloud version:** 21.01

**Updated from an older Nextcloud/ownCloud or fresh install:**No

**Where did you install Nextcloud from:**tar

**Comment by maltepost** [comment]
Same problem here.

**Comment by Lars1963** [comment]
here also

**Comment by fschrempf** [comment]
@maltepost Please stop posting to issues without adding anything to the discussion. Use :+1: on the top post instead. Thanks!

**Comment by Lars1963** [comment]
Can this error from the logs have anything to do with this issue? 

`Error | TypeError: Unsupported operand types: int & array

/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 74:OC\Files\Cache\Wrapper\CachePermissionsMask->formatCacheEntry()

/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php - line 170:OC\Files\Cache\Wrapper\CacheWrapper->get()

<<closure>>OCA\GroupFolders\Versions\VersionsBackend->OCA\GroupFolders\Versions\{closure}("*** sensiti ... *")

/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php - line 169:array_map()

/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 64:OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()

/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 58:OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()

/var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php - line 40:OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()

/var/www/nextcloud/lib/private/BackgroundJob/Job.php - line 52:OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()

oder /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php - line 59:OC\BackgroundJob\Job->execute()/var/www/nextcloud/cron.php - line 128:OC\BackgroundJob\TimedJob->execute() `

**Comment by maltepost** [comment]
> @maltepost Please stop posting to issues without adding anything to the discussion. Use 👍 on the top post instead. Thanks!

ok, but I already described the issue in detail before here: https://github.com/nextcloud/groupfolders/issues/1453

**Comment by Lars1963** [comment]
> > @maltepost Please stop posting to issues without adding anything to the discussion. Use 👍 on the top post instead. Thanks!
> 
> ok, but I already described the issue in detail before here: #1453

Well to me it seems, this are 2 different issues. 🤔

**Comment by joshtrichards** [comment]
Unable to reproduce today. And this report hasn't seen any traffic >3 years. Presumed fixed.
