### ISSUE TITLE
l18n question for "build/bundle.js"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/groupfolders#15]
On line 6 you will see "q("Wrong offset!")"

What does "Wrong offset" means?

Is it necessary to translate this string? If so it would be good to improve the string.

**Comment by comradekingu** [comment]
"Adjustment parameter" would probably have an easier time being understood.
What it is that needs to be aligned matters to what kind of "offset"-word one would use.

**Comment by rakekniven** [comment]
> Is it necessary to translate this string?
Or is just for developers

**Comment by icewind1991** [comment]
It is not needed to translate this string.

I think there is a conflict somewhere between the minify/build system this app uses for it's javascript and our translation scripts that cause it to find a number of invalid strings in the code

**Comment by rakekniven** [comment]
So it would be good to fix such issues otherwise translators are working on such strings without a need. Reopened.

**Comment by comradekingu** [comment]
For the prospective user, it would be nice to know what "font" translates to.
The mouseover could be the BB-code equivalents.

**Comment by rakekniven** [comment]
Hello @icewind1991 tbh I do not know how to fix this. Maybe @MorrisJobke knows?

**Comment by MorrisJobke** [comment]
Not really ... which files should be excluded, @icewind1991 ?

**Comment by icewind1991** [comment]
everything in `build`

**Comment by icewind1991** [comment]
Fixed with https://github.com/nextcloud/docker-ci/commit/8d37cda1f0be3a67767f9089998d4ccbb9f2bbe6
