### ISSUE TITLE
Anyone can set advanced permissions

### ISSUE THREAD

**Issue by edolzan** [nextcloud/groupfolders#1502]
As soon as I enable advanced permissions on a folder, anyone in any of the groups with access can edit advanced permissions, even if I specify only a specific group that should be able to do this. Am I missing something?

**Comment by julian70400** [comment]
I did not understand how it works..

**Comment by fschrempf** [comment]
@edolzan Can you please use the issue template and provide exact steps to reproduce the problem?

**Comment by fschrempf** [comment]
I can't reproduce this with NC 21.0.0 and GF 9.0.2.

**Comment by freumichCH** [comment]
Same here
Cant reproduce with latest NC21. 
Can we mark this issue as stale?

**Comment by fschrempf** [comment]
I will close this as stale. Please create a new issue if the problem persists and use the template to provide information.
