### ISSUE TITLE
Allow to restrict file modification/deletion to creator of file/folder

### ISSUE THREAD

**Issue by nursoda** [nextcloud/groupfolders#1509]
In collaboration, it would be a nice feature to be able to set ACL permissions for a directory so that _all_ members can create and write folders and files. But _only the creator and the group admin_ should be able to modify their files or delete them.

### Example
I have a groupfolder for collaboration since members of that working group come and go. That way, files aren't deleted when they leave, and there's no issue when the group coordinator changes or the sharer of the (non-groupfolders) folder leaves the group.

Within that groupfolder, I have restricted subfolders using ACL. One of them is for meetings. Within a meeting, all participants shall be able to upload/add files (like presentations and other documents). One person (or multiple) take minutes saved in a file (like Word or Markdown).

My initial request would protect such files (presentation, minutes) from being modified/deleted by "normal" group members while organizers and the original author may modify it easily.

**Comment by fschrempf** [comment]
> @nursoda Is this really a groupfolders thing? I think this issue should better be in the general server repo, shouldn't it?

@nursoda I also see this request unrelated to the groupfolders app in the first place. Please check the [server repo](https://github.com/nextcloud/server/issues) for any related issues and create a new one there if necessary.

**Comment by nursoda** [comment]
OK, I respect your decision since I did not elaborate when asked to in 2019. However, let me describe the use case and reconsider:

I have a groupfolder for collaboration since members of that working group come and go. That way, files aren't deleted when they leave, and there's no issue when the group coordinator changes or the sharer of the (non-groupfolders) folder leaves the group.

Within that groupfolder, I have restricted subfolders using ACL. One of them is for meetings. Within a meeting, all participants shall be able to upload/add files (like presentations and other documents). One person (or multiple) take minutes saved in a file (like Word or Markdown).

My initial request would protect such files (presentation, minutes) from being modified/deleted by "normal" group members while organizers and the original author may modify it easily.

I doubt that this is a server repo issue as long as I am using a group folder. Or is it?

**Comment by fschrempf** [comment]
@nursoda As you were referring to "shares" in your request I was assuming you are talking about the sharing feature that is unrelated to groupfolders. With your detailed explanation it is clear now, that you are referring to the ACL permissions. I updated your initial post to make this clearer.

**Comment by fschrempf** [comment]
> But _only the creator and the group admin_ should be able to modify their files or delete them.

As far as I can see the latter is possible. You can set the ACL permissions to deny "write", but allow "create". That way only members of the "admin group" can edit or delete files.

The former (also allow editing for the creator of the file) is not implemented and I don't know if/how this could be done.

**Comment by provokateurin** [comment]
> The former (also allow editing for the creator of the file) is not implemented and I don't know if/how this could be done.

That is not possible as files in Groupfolders have no owner/creator.
