### ISSUE TITLE
Export acl details on API

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/groupfolders#1530]
Export ACL details on WEB API 
with occ command we can find ACL detail using 
occ groupfolders:permissions

But not with api :/ or maybe i'm doing something wrong

Best regards

**Comment by fschrempf** [comment]
The `apps/groupfolders/folders` endpoint should return the ACL permissions for all folders. See also the [README](https://github.com/nextcloud/groupfolders#api) and [these issues](https://github.com/nextcloud/groupfolders/labels/api).

Please use the issue template when you open a new issue in the future!
