### ISSUE TITLE
Show owner of files in groupfolder

### ISSUE THREAD

**Issue by wiegell** [nextcloud/groupfolders#1562]
Somewhat related to https://github.com/nextcloud/groupfolders/issues/975, but i would like to know who is owning (or who uploaded) the individual files in a group folder (not only who has access)

Right now there is only a "shared symbol" where the avatar usually goes, and the owner is not shown in details either.
I have a home NAS with a photo group folder, where i would like to make it apparent who uploaded each photo.

**Comment by freumichCH** [comment]
Technically groupfolders and their data is owned by the system after upload. 
You can basically check these infos over the activity tab on the detail screen. 

you can imaging that the implementation of this feature needs a lot of changes on the server side due uploader name does not be a part of the nc_filecache table

**Comment by fschrempf** [comment]
I'm tempted to close this as "won't fix". As @freumichCH already mentioned, the files in a groupfolder don't have an owner. And I don't think that the information about who uploaded a file is stored anywhere. So I don't see how this could be implemented.

**Comment by CarlSchwan** [comment]
I agree with @fschrempf. Group folders have as owners a group and not a single user and we don't store who has uploaded a file.
