### ISSUE TITLE
Groupfolders, advanced permissions not working

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/groupfolders#1578]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a groupfolder with advanced permissions and assign an admin group
2. Set a group containing user B to have read only rights to the groupfolder
3. As a member of the admin group, give user B more rights to a subfolder in the groupfolder

### Expected behaviour
User B should have the override rights to the subfolder, so write and/or delelte

### Actual behaviour
User B has the default rights inherited from his group

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
Apache

**Database:**
Postgres

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Group folders version:**
9.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 20.0

**Where did you install Nextcloud from:**
tar/gz

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
AD

### Client configuration
**Browser:**
Firefox and Chrome

**Operating system:**
Linux and Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No log entries during the operation:
{"reqId":"Djj65PG35v5eaSBSkLso","level":2,"time":"2021-06-27T09:27:44+00:00","remoteAddr":"192.168.1.40","user":"admin","app":"impersonate","method":"POST","url":"/index.php/apps/impersonate/user","message":"Changing to user 28BB1CCC-F7C2-4972-9965-72B34724411C","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.1.1"}
```
</details>

#### Browser log
As admin:
![nc_adminpermissions](https://user-images.githubusercontent.com/1763477/123539621-f72e1700-d73a-11eb-91d1-935c7668083d.png)

As user:
![nc_userpermissions](https://user-images.githubusercontent.com/1763477/123539631-02814280-d73b-11eb-859e-102584662fe5.png)

**Comment by Pytal** [comment]
This is expected behaviour as Group permissions take precedence over Advanced permissions, closing in favour of proposal #655
