### ISSUE TITLE
Not enough space available

### ISSUE THREAD

**Issue by kroerig** [nextcloud/groupfolders#158]
Nextcloud: 13.0.5
Groupfolders: 1.2.2

I've set quota to 1GB for a group folder. Since the update to NC 13.0.5 users cannot upload files any more.

With setting quota to unlimited it works.

Popup states: -1471882B used
(On the filesystem it is only 24MB)

Maybe same as https://github.com/nextcloud/groupfolders/issues/98

**Comment by ZeikoFr** [comment]
Hi @kroerig This issue seem fixed now, can you confirm ?

**Comment by kroerig** [comment]
yes.
