### ISSUE TITLE
Last modification timestamp is updated to present time when checking for modifications (launched by Nextcloud Desktop)

### ISSUE THREAD

**Issue by Freeedim** [nextcloud/groupfolders#1580]
I use the app "Group folders". Since I upgraded to Nextcloud Hub 21.0.2 (from 20.0.5) and Group Folders 9.0.2 (from the version that was up-to-date when Hub 20.0.5 was), the group folders that I created with that app have their last modification timestamp updated to present time when Nextcloud Desktop indicates that they are being checked for modification.

It has massive implications in my case since Nextcloud Desktop will always infer that all the group folders need to be downloaded because newer on Nextcloud Hub. And once done, Nextcloud Desktop will launch a new verification for additional modifications on the remote (Nextcloud Hub) group folders, which will have again their last modification updated etc. It's killing my data plan and producing thousands of conflicts at each round.

The problem did not exist before the update.

### Steps to reproduce
1. Set up a group folder with the app "Group Folders" in the setting page of Nextcloud Hub 21.0.2, as an admin user.
2. Synchronise that folder with Nextcloud Desktop 3.1.1 on Debian
3. Watch in a web browser in the Files app how the group folders (only them, not their regular subfolders or other regular folders) get "few seconds ago" as their last modification time after Nextcloud Desktop has mentioned them as being checked for modifications on the remote platform.

### Expected behaviour
The folders should keep their last modification date and time while they are just checked for modification.

### Actual behaviour
the group folders (only them, not their regular subfolders or other regular folders) get "few seconds ago" as their last modification time after Nextcloud Desktop has mentioned them as being checked for modifications on the remote platform.

### Server configuration
Nextcloud Hub 21.0.2 on a rented VPS offering PaaS (no access to Nextcloud Hub's configuration or file system)
Nextcloud Desktop 3.1.1 on Debian
No encryption at rest or E2EE
Apps enabled:
- Accessibility
- Activities for shared files downloads, visible to all admins
- Activity
- Analytics
- Auditing/logging
- Brute-force settings
- Calendar
- Collaborative tags
- Comments
- Contacts
- Contacts interactions
- Dashboard
- Data request
- Deck
- Deleted files
- Federation
- File access control
- File sharing
- First run wizard
- Flow notifications
- Forms
- **Group folders**
- Log reader
- Monitoring
- Nextcloud announcements
- Notes
- Notifications
- Password policy
- PDF viewer
- Photos
- Privacy
- Recommendations
- Retention
- Right-click
- Share my mail
- Support
- Suspicious loggin
- Talk
- Tasks
- Text
- Theming
- Update notification
- Usage survey
- User status
- Versions
- Video player
- Weather status

**Comment by juergen852** [comment]
I  think, I have the same problem on NC 28.0.6 and Groupfolders 16.0.7.
![grafik](https://github.com/nextcloud/groupfolders/assets/33433306/a2604972-5723-4ca4-8b3a-083f96f34ca5)

**Comment by provokateurin** [comment]
@juergen852 your problem is likely a different problem, please open a separate issue.
The original issue is quite old and nobody else seems to have the problem, so closing for now. Please re-open if this is still relevant for you.
