### ISSUE TITLE
Nextcloud 22 support

### ISSUE THREAD

**Issue by kleener** [nextcloud/groupfolders#1598]
Hi,
When is the support for Nextcloud 22 coming?
The beta is from 18 June.
Alternatively, is the functionality also available with circles?

**Comment by maiolif** [comment]
nextcloud project is adding many and many features but core features are not working 100%. Like having a car with beautiful infotainment but gear shift is not working and motor is slow. Why releasing a new major version when the last 2 are still not working? I am confused.

**Comment by pReya** [comment]
Groupfolders works without problems for me, after upgrading to Nextcloud 22. I still agree, that it should be updated in the App Store to show compatibility for everyone.

**Comment by wipeonline** [comment]
How do you get groupfolders working in Nextcloud 22, without groupfolder app? Are you using the beta Version of groupfolder App?

**Comment by pgassmann** [comment]
> How do you get groupfolders working in Nextcloud 22, without groupfolder app? Are you using the beta Version of groupfolder App?

You can enable the untested app anyway. Go to Apps and then to Disabled apps. url: `/settings/apps/disabled`

**Comment by Fail-Unsafe** [comment]
Is this really working? I experienced the exact same problem when unintentionally upgrading the Docker image. I also re-enabled the app and the group folders reappeared but it seems to be impossible to create new groups?

**Comment by nursoda** [comment]
Personally, I'd try to switch to beta, install groupfolders 10beta and switch back to release rather than using the app intended for NC21 and override its version.

**Comment by dienteperro** [comment]
Is it better to user Group folders or External storage with a local-filesystem-server-stored folder?

**Comment by kleener** [comment]
Does the file system also support permissions with Nextcloud groups? Then it would be a good alternative.

**Comment by dienteperro** [comment]
> Does the file system also support permissions with Nextcloud groups? Then it would be a good alternative.

No, External storage is quite more rudimentary. That's a +1 for Group folders! (ACLs)

**Comment by small1** [comment]
A bump on this one. It would be good if there would be a final  nc22 release of this app.

**Comment by Lars1963** [comment]
@ChristophWurst Bump: stabel is now 22.1.0 and rc is 22.1.1

**Comment by AndyScherzinger** [comment]
> Well I'm surprised. 22.1.1, still not working. 

@enoch85 https://github.com/nextcloud/groupfolders/releases/tag/v10.0.0-beta1 should be working and afaik @juliushaertl is working on the stable release atm.

**Comment by kleener** [comment]
There is an updated version, very nice. Thank you

**Comment by kleener** [comment]
There is an updated version, very nice. Thank you

**Comment by AndyScherzinger** [comment]
All the praise goes to @juliushaertl here!
