### ISSUE TITLE
Files app thinks deleted Group Folders still exist

### ISSUE THREAD

**Issue by sunjam** [nextcloud/groupfolders#165]
Nextcloud 13.0.5

Files app thinks that Group Folders I've deleted from the admin panel still exist.  Users are not able to create new folders with the same names as they "already exist."

**Comment by clesmian** [comment]
Is it possible that this is linked to this problem? 
The answer gives a pretty good idea of the underlying problem and a possible solution. In short it says that groupfolders does not clean up the database entries very good after it does something

https://github.com/nextcloud/server/issues/4786#issuecomment-430556202

**Comment by ZeikoFr** [comment]
Hi @sunjam Is this issue still revelant or is it fixed in NC18/19/20 ?

**Comment by sunjam** [comment]
Unsure, as I gave up on group folders

**Comment by fschrempf** [comment]
I'm closing this as stale issue and assume that this is not a problem anymore. If this problem still persists and someone can observe it on the latest release, please create a new issue. Thanks!
