### ISSUE TITLE
No more groups list in admin pannel appears since upgrade to 1.3.0

### ISSUE THREAD

**Issue by jacestk** [nextcloud/groupfolders#166]
Nextcloud 13.0.5
Groupfolder 1.3.0 (Just after upgrading in 1.3.0!)

This happens only on IE11!
When you are clicking in "groups folders" in setup list, nothing appears :( There is only a white page in the right side (where should appears all the created groups)

Here is the console error:
![image](https://user-images.githubusercontent.com/1270552/43756428-af658b1a-9a25-11e8-9471-dbc248b5ff53.png)

Here is what happends on screen:
![image](https://user-images.githubusercontent.com/1270552/43756449-d412d602-9a25-11e8-9c72-91809e28649f.png)

I'm gonna downgrade the version.

**Comment by icewind1991** [comment]
Can you see if you experience the same problem with a different browser?

**Comment by jacestk** [comment]
I said it was only on IE11, it is working fine on Firefox/chrome. We cannot  use anything else than IE11 because we are on a locked network with domain AD SSL. (I have made an app that let you open office files through WebDAV connection like with Sharepoint. 
Version 1.2.2 was working like a charm.

**Comment by jacestk** [comment]
hum? closed ? Has this been patched? 
Just for your information: IE11 is used by 70% of the business market! Makes it working only on Firefox or Chrome is just not possible if you want NextCloud to grow...
