### ISSUE TITLE
Provide "Everyone" as Usergroup

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/groupfolders#1663]
Hi,

not sure if Bug or Feature Request. Feel free to adjust this.

Once the App is installed I can assign all custom usergroups to folders. Furthermore I can assign the system usergroup "admin" to folders. But I can not assign the "Everyone" group to a folder.

Usecase: I would like to have a folder that *every* user has read access so I can place some overall guideline documents there.

**Comment by danir-de** [comment]
Maybe the [Everyone Group](https://apps.nextcloud.com/apps/group_everyone) can help? Seems to be exactly the feature you're searching for, theoretically it should work with group folders. 
It's not properly translated though.

**Comment by xbluemonkx** [comment]
it probably will. - anyway I think it is confusing, that there are pre-defined groups "admin" and "everyone", but the act differently. one of them (admin) can be used to assign sth. while "everyone" can not be used without that extra app.

**Comment by fschrempf** [comment]
As far as I can see, this is unrelated to the groupfolders app. The app mentioned above provides this feature. If you think this should be part of the core, please open a issue in the [server repo](https://github.com/nextcloud/server/issues). Thanks!
