### ISSUE TITLE
`occ groupfolders:trashbin:cleanup --no-interaction` versus `--force`

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/groupfolders#1689]
### Steps to reproduce
1. Install the latest Nextcloud & groupfolder app
2. delete files in a group folder folder
3. delete the trashbin by using `php occ groupfolders:trashbin:cleanup --no-interaction`

### Expected behaviour
The groupfolder trashbin should be deleted.

### Actual behaviour
Nothing is deleted - I´ve to use `php occ groupfolders:trashbin:cleanup` manually with interaction, which is working.

### Server configuration

**Operating system:** debian 11

**Web server:** nginx 1.21.3

**Database:** mariadb 10.5.12

**PHP version:** 7.4.24

**Nextcloud version:** (see Nextcloud admin page) 22.2.0

**Group folders version:** 10.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** release github

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Saml

### Client configuration
**Browser:** Chrome 

**Operating system:** Windows 11

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no log generated
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no log generated
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by CarlSchwan** [comment]
You need to use --force.

@icewind1991 Did you choose to use --force because of a specific reason instead of using the default `--no-interaction`?

**Comment by fschrempf** [comment]
I'd vote for adding support for `--no-interaction` and keep `--force` for compatibility.
