### ISSUE TITLE
show used space as column

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/groupfolders#1735]
Hi,

at the moment the space used by a group folder can only be seen by hovering over the quota dropdown. This is a little annoying if you want to have a quick overview. it would be nice if the current used space would be shown in a separate column

**Comment by fschrempf** [comment]
Would you please open a new issue and use the issue template with the proper information? Thanks!
You don't need to fill the whole template. Only keep the parts that are relevant.

**Comment by xbluemonkx** [comment]
thanks for the feedback: new ticket over here https://github.com/nextcloud/groupfolders/issues/1736 - hope this is what you were requesting.

**Comment by fschrempf** [comment]
Thanks! You removed the "How To" note, which I added back now. The rest looks good.
