### ISSUE TITLE
Log ACL permission changes to audit log

### ISSUE THREAD

**Issue by PVince81** [nextcloud/groupfolders#1744]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
ACL permission changes are not written to the audit log. It seems we're already doing that for regular shares and also change of permissions for shares.

**Describe the solution you'd like**
To be able to get a trail of who changed what permissions, we should log ACL permission changes to the audit log.

**Comment by PVince81** [comment]
As far as I understood how the admin_audit app works, this would require triggering hooks from the groupfolders app and catching them in the admin_audit app to log matching messages.

I'm not sure if there's a way to trigger a generic/custom hook to tell the app to log an audit message.

**Comment by fschrempf** [comment]
@PVince81 Would be nice if you could use the issue template next time (I updated your post accordingly), as we are also asking other reporters to use it. Thanks!

**Comment by joshtrichards** [comment]
Fixed in #1917
