### ISSUE TITLE
Fix compatibility with dark theme

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/groupfolders#1749]
![image](https://user-images.githubusercontent.com/59488153/141526304-a91ac892-80ce-4eb2-95ec-0bed10f22543.png)

**Comment by fschrempf** [comment]
@andyxheli Please use the issue template and provide a proper description. A screenshot is good, but not enough. And also please check for existing issues next time. It looks like we already have this covered in #1135. Closing as duplicate.

**Comment by andyxheli** [comment]
@fschrempf Sorry about that. Thank you for letting me know.

**Comment by fschrempf** [comment]
> Sorry about that. Thank you for letting me know.

Never mind, thanks for the feedback!
