### ISSUE TITLE
Moved files don't appear to be moved

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/groupfolders#176]
I moved files from the parent group folder into a child group folder.

The file still appears at the parent level, but not really.  Something is strange with the file that is supposed to be moved; no metadata, but I can still view the file when clicked.

Also, the child folder doesn't get folder size updated.

**Comment by Cracky5457** [comment]
Probably duplicated of https://github.com/nextcloud/groupfolders/issues/128

**Comment by icewind1991** [comment]
Closing as duplicate
