### ISSUE TITLE
Latest releases are missing on the GitHub release page

### ISSUE THREAD

**Issue by fschrempf** [nextcloud/groupfolders#1765]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Visit the [GitHub releases page](https://github.com/nextcloud/groupfolders/releases) and look for the latest releases

### Expected behaviour
All released versions that are already tagged should have a release and a changelog assigned.

### Actual behaviour
Releases 10.0.0 and 11.0.0 are tagged, but have no release assigned.

**Comment by fschrempf** [comment]
@juliushaertl Can you fix this and/or explain the workflow for releasing? Thanks!

**Comment by juliushaertl** [comment]
Releases are published via https://github.com/nextcloud-releases/groupfolders/releases these days. 

The main entrypoint for getting a release would actually be apps.nextcloud.com where no matter where the releases are hosted, the actual release archives are linked for the individual apps.

**Comment by fschrempf** [comment]
@juliushaertl Thanks for explaining. I don't see the reason for the separate release repos, but I'm sure there is one ;)

Still I would like to reopen this as it is not clear for the average user why the releases are outdated in the main repo. I will propose a change for the README to add this info. And would you agree to remove the existing releases from this repo to avoid confusion, or do you think this is harmful as we lose some info about old releases?

**Comment by danir-de** [comment]
I absolutely agree to @fschrempf . 
I understand that it's useful to have releases in a central place, but "this is not how Git(Hub) works" and it confuses the hell out of me that release notes to the releases made in this repo are located somewhere else.
