### ISSUE TITLE
Trash lists files that should not be accessible to users (regardless of ACL)

### ISSUE THREAD

**Issue by svenseeberg** [nextcloud/groupfolders#1766]
### Steps to reproduce
1. Create directory in Groupfolder with ACLs that do not allow user X (that has access to the group folder in general) to read/see the files
2. Create a file in the newly created directory and remove it
3. Log in as user X and to got the deleted files / trash bin
4. The deleted file, that should not be visible to the user, is listed in the trash bin (though the content is not readable)

### Expected behavior
Files that are usually not visible to users should not be listed in the trash bin. 

### Actual behavior
The hidden files reveal their filenames and paths. This can reveal very sensitive information stored in file names and paths, which are visible in the mouse over tool tip.

### Server configuration

**Operating system:** Debian Buster

**Web server:** Nginx 1.14.2

**Database:** MariaDB 10.3.31

**PHP version:** PHP 7.3

**Nextcloud version:**  22.1.3

**Group folders version:** 10.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** SAML

### Client configuration
**Browser:** all browsers

**Operating system:** all OS

**Comment by fschrempf** [comment]
It seems like restoring a file without permissions was recently fixed in #1739 (not released yet), but I guess listing the file in the trashbin and seeing the filename and path is still possible without read permissions.

@CarlSchwan I guess this is not yet covered by your recent fixes, right?

**Comment by svenseeberg** [comment]
Sorry, we may have mixed up some Nextcloud versions or had a problem with upgrades and this is probably fixed. But it would be super awesome, if someone can confirm that this is fixed. It could not find a corresponding issue.

**Comment by CarlSchwan** [comment]
There was a similar bug a long time ago but it wws fixed more than 2 years ago. Are you sure that you got this bug in nc22? I couldn't reproduce it and the code checks the permission already.

**Comment by svenseeberg** [comment]
Yes, our follow tests come to the same conclusion. So we probably made a mistake in our first test.
