### ISSUE TITLE
Classes not Found

### ISSUE THREAD

**Issue by hallo1142** [nextcloud/groupfolders#1789]
### Steps to reproduce
1. Not sure but it looks like it happened after updating to version 10.0.0

### Expected behaviour
All Folderls should load normally

### Actual behaviour
The file page can't load anymore

### Server configuration

**Operating system:** Debian 11

**Web server:** NGINX

**Database:** MySQL

**PHP version:** 8.0

**Nextcloud version:** (see Nextcloud admin page) 22.2.3

**Group folders version:** 10.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated.

**Where did you install Nextcloud from:** Install Script

**Are you using external storage, if yes which one:** local/s3/smb/sftp/... Only the normal data directory

**Are you using encryption:** yes/no no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/... no

### Client configuration
**Browser:** Firefox/Brave

**Operating system:** Windows 10

### Logs
![grafik](https://user-images.githubusercontent.com/26180623/144070366-7d205aaf-022f-4241-a305-6051e3bb78b1.png)

**Comment by Herobr1ne** [comment]
Same Problem here :(

**Comment by Herobr1ne** [comment]
Hey, sorry for beeing dumb but what you mean with Backtrace?

**Comment by CarlSchwan** [comment]
> Hey, sorry for beeing dumb but what you mean with Backtrace?

There is no dumb question :)

If you are using loggreader, you can expend the log entries like this:

![image](https://user-images.githubusercontent.com/23653902/144282990-0e0b8d74-3367-4325-9a39-f9a3256b59f6.png)

If you are not, go to data/nextcloud.log and copy the lines that include 'Could not resolve folderManager' and 'Could not resolve OCA\GroupFolders/Folder/FolderManager.php'

This should give me the execution flow that leads to the error and help me figure out what went wrong :)

**Comment by Herobr1ne** [comment]
So you mean this?
![raw (1)](https://user-images.githubusercontent.com/33431587/144289149-393cd609-eba2-4840-877a-f280c44dbd84.png)

**Comment by CarlSchwan** [comment]
yes exactly, thanks!

**Comment by Herobr1ne** [comment]
https://paste.steven-arnold.eu/oxusarorop.json

**Comment by Herobr1ne** [comment]
Hey, after the Update to Nextcloud 23.0.0 its Working.

**Comment by joshtrichards** [comment]
The next time this occurs, try restarting FPM (or Apache if using mod_php) right after completing the upgrade. May just be NC autoloading/caching issue.
