### ISSUE TITLE
Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found

### ISSUE THREAD

**Issue by rso42** [nextcloud/groupfolders#1812]
Just upgraded NC from 22.2.3 to 23.0.0.10 with groupfolders 11.1.0 and now get constant errors after upgrade:

NC log
```
Fatal	no app in context	Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found

occ error message
An unhandled exception has been thrown:
Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in XXXXX/apps/groupfolders/lib/Versions/VersionsBackend.php:38
```

I see a fix back in 2019 for a similar error message:
https://github.com/nextcloud/groupfolders/commit/fa87c7164d01fa4732fcbbc4b498cb4b2926b42e

**Comment by j0inty** [comment]
You need to enable/install the "files_versions" app, too.

```console
root@host:/var/wwww/cloud.myhost.net/htdocs $ sudo -u www-data -g www-data -- php -f nextcloud/occ app:enable files_versions
```

**Comment by gwolf** [comment]
However, be aware that files_versions must be enabled _before_ attempting to upgrade! occ dies before the upgrade can be attempted...

**Comment by wiegell** [comment]
I got through update and was able to get rid of error by enabling file versions in web gui

**Comment by CarlSchwan** [comment]
if you could test https://github.com/nextcloud/groupfolders/pull/1849, this would be awesome :)

**Comment by clawoflight** [comment]
Huh, I'm using snapshots (ZFS user), so I don't have versions enabled. Thanks for the PR :)

**Comment by vnourdin** [comment]
Hi :wave: 
I wanted to disable the `files_versions` app but as pointed out in this issue, it's not possible with `groupfolders`.
Is there any way to disable it without breaking `groupfolders` ?
I haven't found in the doc information about this dependency.
Thanks a lot :pray:
