### ISSUE TITLE
Argument #1 ($id) must be of type int, string given

### ISSUE THREAD

**Issue by guystreeter** [nextcloud/groupfolders#1818]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. `php occ groupfolders:group 1 Family write`

### Expected behaviour
Should give Family write access to group folder 1

### Actual behaviour

```
An unhandled exception has been thrown:
TypeError: OCA\GroupFolders\Folder\FolderManager::getFolder(): Argument #1 ($id) must be of type int, string given, called in /var/www/html/custom_apps/groupfolders/lib/Command/Group.php on line 68 and defined in /var/www/html/custom_apps/groupfolders/lib/Folder/FolderManager.php:213
Stack trace:
#0 /var/www/html/custom_apps/groupfolders/lib/Command/Group.php(68): OCA\GroupFolders\Folder\FolderManager->getFolder('1', 2)
#1 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\GroupFolders\Command\Group->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OCA\GroupFolders\Command\Group), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/console.php(99): OC\Console\Application->run()
#8 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

### Server configuration

**Operating system:**

Nextcloud 23 docker image

**Web server:**

apache

**Database:**

mariadb

**PHP version:**

8.0.13

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud Hub II (23.0.0)

**Group folders version:**

11.1.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

fresh

**Where did you install Nextcloud from:**

docker

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

No

### Client configuration

N/A

**Comment by CarlSchwan** [comment]
Fixed with https://github.com/nextcloud/groupfolders/pull/1814. I will look into doing a release shortly, in the meantime you can try applying the patch locally manually
