### ISSUE TITLE
Creating advanced folder permission rules no longer works for non-admin users

### ISSUE THREAD

**Issue by kaskicc** [nextcloud/groupfolders#1834]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create groups `Test Admins`, `Test Users`
2. Create group folder `Test` and give full permissions to both groups (read/write/share/delete)
3. Give advanced permissions to the group `Test Admins`.
4. Create a new user `testuser` with membership in the groups `Test Admins`, `Test Users`
5. As the new user, navigate to the group folder in the files app and try to add an advanced permission rule, e.g. by typing `test`
6. The group/users list always stays empty, no matter what/how much is typed (providing the group name directly/without auto-completion leads to the same result).
7. Now give delegated admin rights to the group `Test Admins` (alternative: add the user to the instance wide admin group)
8. Try again to add advanced permission rules to the previously created group folder, now the list shows the expected entries ("Test Admins", "Test Users").

### Expected behaviour
For users that have advanced permissions on a group folder, the returned list should contain all groups with at least read permissions to that group folder. This should work independent from whether the user has admin/delegated admin rights in the Nextcloud instance.

### Actual behaviour
The returned group list is empty, unless the user has instance wide admin rights or delegated admin rights for the group folder settings.

### Server configuration

**Operating system:** Debian 11

**Web server:** Nginx

**Database:** Postgresql

**PHP version:** 7.4

**Nextcloud version:**  23.0.0

**Group folders version:** 11.1.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** manual from official website

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Social Login Plugin / OICD

### Client configuration
**Browser:** Firefox 94.0.2

**Operating system:** Debian 11

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
   "reqId":"XXX",
   "level":0,
   "time":"2021-12-21TXX:XX:XX+XX:XX",
   "remoteAddr":"XXX",
   "user":"testuser",
   "app":"no app in context",
   "method":"GET",
   "url":"/apps/groupfolders/folders/1097/search?format=json&search=te",
   "message":"Logged in user must be an admin, a sub admin or gotten special right to access this setting",
   "userAgent":"XXX",
   "version":"23.0.0.10",
   "exception":{
      "Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotAdminException",
      "Message":"Logged in user must be an admin, a sub admin or gotten special right to access this setting",
      "Code":403,
      "Trace":[
         {
            "file":"XXX/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php",
            "line":97,
            "function":"beforeController",
            "class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware",
            "type":"->"
         },
         {
            "file":"XXX/lib/private/AppFramework/Http/Dispatcher.php",
            "line":118,
            "function":"beforeController",
            "class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher",
            "type":"->"
         },
         {
            "file":"XXX/lib/private/AppFramework/App.php",
            "line":157,
            "function":"dispatch",
            "class":"OC\\AppFramework\\Http\\Dispatcher",
            "type":"->"
         },
         {
            "file":"XXX/lib/private/Route/Router.php",
            "line":302,
            "function":"main",
            "class":"OC\\AppFramework\\App",
            "type":"::"
         },
         {
            "file":"XXX/lib/base.php",
            "line":1006,
            "function":"match",
            "class":"OC\\Route\\Router",
            "type":"->"
         },
         {
            "file":"XXX/index.php",
            "line":36,
            "function":"handleRequest",
            "class":"OC",
            "type":"::"
         }
      ],
      "File":"XXX/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php",
      "Line":175,
      "CustomMessage":"Logged in user must be an admin, a sub admin or gotten special right to access this setting"
   },
   "id":"XX"
}
```
</details>

**Comment by fschrempf** [comment]
This seems to work with NC 22 and GF 10.0.0, so I suspect a regression in NC 23, GF 11.x.

**Comment by akupovih** [comment]
NextCloud 23.0.0
Group Folder 11.1.0

I found an error in the session trace 
"Failed to l search results for groupfolder ACL"
https://mynextcloudhost/apps/groupfolders/js/groupfolders-sharing.js?v=eb23481670f30b7e3a4f

**Comment by fschrempf** [comment]
@CarlSchwan Could it be a regression caused by the introduction of admin delegation? Something like [`canManageACL`](https://github.com/nextcloud/groupfolders/blob/master/lib/Folder/FolderManager.php#L293) not working properly, etc.?

**Comment by CarlSchwan** [comment]
> @CarlSchwan Could it be a regression caused by the introduction of admin delegation? Something like [`canManageACL`](https://github.com/nextcloud/groupfolders/blob/master/lib/Folder/FolderManager.php#L293) not working properly, etc.?

very probably. I'll see if I can quickly fix this tomorrow morning otherwise it will have to wait for new year
