### ISSUE TITLE
PHP-Error in Log after quota change

### ISSUE THREAD

**Issue by RailsViceRoads** [nextcloud/groupfolders#187]
**Behaviour:** I have set the quota of three existing group folders from _unlimited_ to 5 and 10 GB. After this I found three corresponding error messages in the NC-log:

`current() expects parameter 1 to be array, boolean given at /[myhome]/www/cloud/apps/groupfolders/lib/Controller/FolderController.php#170`

**NC-Version:** 13.0.5.2
**Groupfolders Version:** 1.3.3
**PHP-Version:** 7.1.10

**Comment by yepecece** [comment]
I have the same error.

Any idea? this happens only since I updated to NC 13.0.5.2

NC-Version: 13.0.5.2
Groupfolders Version: 1.3.3
PHP-Version: 7.1.10

**Comment by Krakra97** [comment]
I have the same problem.
When I want to create oder change Group Folder settings, I will get every time this errors.

NC - Version: 14
Groupfolders 1.3.3
PHP-Version: 7.2

**Comment by soundmagic** [comment]
I have the same problem.
When I want to create oder change Group Folder settings, I will get every time this errors.

NC - Version: 14.0.1.1
Groupfolders 1.3.3
PHP-Version: 7.1.22

**Comment by PhantomPhreak** [comment]
Same problem with group folders.

NC - Version: 14.0.3
Groupfolders 1.3.3
PHP-Version: 7.1.18

Do anybody from Nextcloud dev's team checking this issues?

**Comment by kroerig** [comment]
Same problem here.

NC - Version: 14.0.3
Groupfolders 1.3.3
PHP-Version: 7.0.32

**Comment by fri-sch** [comment]
I'm seeing the same issue.

NC - Version: 14.0.3
Groupfolders 1.3.3
PHP-Version: 7.2.11

**Comment by PpaiSanchez** [comment]
Same problem here.

**Comment by kokotko1337** [comment]
i got those errors in log but quota is working ...

**Comment by landryb** [comment]
I think it's unrelated to quota change, as just modifying a groupfolder name is enough to trigger this error log. Same here btw wth 14.0.3, groupfolders 1.3.3 & php 7.2.11. The code failing was added in 67d3fcdb for #142

**Comment by TP75** [comment]
This issue can be triggered regularily by administering group folders e.g., name change to a group folder.

Repeatedly the **same issue** _since former:_
  NC-Version: 13.0.5
  Groupfolders Version: 1.3.2
_until today_
  NC-Version: 13.0.7
  Groupfolders Version: 1.3.3
  PHP-Version: 7.0.30

Apparently **unrelated to quota change**. However, may be still related to other unknown quota issues.

**Comment by victorbw** [comment]
Same problem here.

NC - Version: 14.0.3
Groupfolders 1.3.3
PHP-Version: 7.0.32
