### ISSUE TITLE
Write access for specific subfolders only

### ISSUE THREAD

**Issue by dan-nkl** [nextcloud/groupfolders#19]
I love the development of this app! It's the part which was missing in Nextcloud.

With the upcoming group based write access to groupfolders there should also be implemented an option to give write access only in a certain subfolder of a groupfolder.

### Example for the problem:
We have a "Teamfolder"

And this groups:
- Team
- Marketing
- Management

Team should have only read access to the teamfolder while the management has full access to the groupfolder. At the same time I need to give the Marketing write access to a subfolder (corporate-templates) inside of the groupfolder.

The option to splitt up the folders would work but this is just messing up the structur and clarity.
So maybe instead of "declaring" a folder name we could enter a path to make it possible to set different write permissions for subfolders.

**Comment by icewind1991** [comment]
configuring subfolders is out of scope of this app imo.

> So maybe instead of "declaring" a folder name we could enter a path to make it possible to set different write permissions for subfolders. 

Should already be possible, you'll have to make sure the parent folder exists though
