### ISSUE TITLE
File versioning broken for groupfolders

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/groupfolders#1901]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a groupfolder
2. Create a file (e.g. "Document-version-test.odt", could also be a markdown file).
3. Enter some text to the file. Wait a couple of minutes and do another edit.

### Expected behaviour
After edit of file, the old (previous) file version shall be saved and available (timestamp of the previous edit).
File versions shall be listed in the order newest (top) to oldest (bottom).

### Actual behaviour
After edit of file, a version is created with the current timestamp (instead of the timestamp of the last edit which was done before).
The order of file versions is oldest (top) to newest (bottom).
When creating a file outside of a groupfolder, versions are created as expected (timestamps and order of versions). When moving the file from outside the groupfolder to a groupfolder, versions are lost (same issue?).

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache/2.4.52 (Ubuntu)

**Database:** mysql Ver 15.1 Distrib 10.3.32-MariaDB

**PHP version:** 7.4.27

**Nextcloud version:** 23.0.2

**Group folders version:** 11.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** originally owncloud

**Where did you install Nextcloud from:** official homepage

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 97.0

**Operating system:** Ubuntu 20.04

### Logs

No errors are logged!

**Comment by mehdivoid** [comment]
I updated to 23.0.2
Group folders version: 11.1.2
Operating system: Ubuntu 20.04.3 LTS
PHP version: 7.4.3
Mysql  Ver 8.0.28

before updrading the version app was disabled and i got this error when I updated do version 23.0.2:

Error: Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /home/data/public_html/apps/groupfolders/lib/Versions/VersionsBackend.php:38
Stack trace:
#0 /home/data/public_html/lib/composer/composer/ClassLoader.php(571): include()
#1 /home/data/public_html/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /home/data/public_html/apps/groupfolders/lib/AppInfo/Application.php(99): spl_autoload_call()
#4 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#5 /home/data/public_html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#6 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#7 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#8 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#9 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\AppFramework\DependencyInjection\DIContainer->query()
#10 /home/data/public_html/apps/groupfolders/lib/AppInfo/Application.php(94): OC\AppFramework\Utility\SimpleContainer->get()
#11 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(160): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}()
#12 /home/data/public_html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#13 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(127): Pimple\Container->offsetGet()
#14 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(457): OC\AppFramework\Utility\SimpleContainer->query()
#15 /home/data/public_html/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#16 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(56): OC\ServerContainer->query()
#17 /home/data/public_html/apps/groupfolders/lib/Command/Trashbin/Cleanup.php(52): OC\AppFramework\Utility\SimpleContainer->get()
#18 [internal function]: OCA\GroupFolders\Command\Trashbin\Cleanup->__construct()
#19 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(106): ReflectionClass->newInstanceArgs()
#20 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#21 /home/data/public_html/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#22 /home/data/public_html/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#23 /home/data/public_html/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#24 /home/data/public_html/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#25 /home/data/public_html/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#26 /home/data/public_html/console.php(98): OC\Console\Application->loadCommands()
#27 /home/data/public_html/occ(11): require_once('/home/data/publ...')

When I enabled the version app, this error disappeared

**Comment by XueSheng-GIT** [comment]
> before updrading the version app was disabled and i got this error when I updated do version 23.0.2:

> When I enabled the version app, this error disappeared

Thanks for your comment, but I don't get the relation to the issue described in this bug report!?
Did you try to reproduce the steps mentioned in the initial report?

**Comment by mehdivoid** [comment]
Sorry. I have deleted my comment.

**Comment by XueSheng-GIT** [comment]
Thanks for the merged pull. After testing it does only fix half of this issue.
First part was about wrong timestamp of shown versions (which is not fixed yet). 
Second about order of versions (which is fixed now). 

More in detail about first part of the issue:
File versioning in groupfolders:
1. Create a file (initial version) 
2. do a change after a day
3. The old version (initial version) is shown with current timestamp of edit, instead of the timestamp of the initial version (which it refers to). 

Doing the same outside if a groupfolder:
1. Create a file (initial version) 
2. do a change after a day
3. The old version (initial version) is shown with timestamp of initial version (as expected)

Hope that explanation is understandable. If not, just let me know.

**Comment by XueSheng-GIT** [comment]
@juliushaertl should I create a new issue about that missing first part described? Or must this issue be reopened?

**Comment by juliushaertl** [comment]
Yes, a separate one would be appreciated, sorry I missed that when reading through the ticket.

**Comment by XueSheng-GIT** [comment]
> Yes, a separate one would be appreciated, sorry I missed that when reading through the ticket.

Separate issue created: https://github.com/nextcloud/groupfolders/issues/2055

**Comment by natoponen** [comment]
Hello, @juliushaertl the same issue affects me. When are you planning to make a release with this fix?
