### ISSUE TITLE
Permissions not respected when copying entire group folders

### ISSUE THREAD

**Issue by os-ai** [nextcloud/groupfolders#1906]
### How to use GitHub
> * Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
> * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
> * Subscribe to receive notifications on status change and new comments.

### Description
Using advanced permissions. When copying-pasting a Group folder via the web interface to another folder, the permissions are not respected, where a user without read access to certain subfolders can download the entire Group folder with all data.

Example, a user may have the following permissions:

### Steps to reproduce
1. Create a group folder with a user with default read only access for a user. Create additional subfolders and assign a user advanced permissions as follows. 
Group folder (read-only)
|--- Folder 1 (read-only)
|--- Folder 2 (**no access**)
|--- Folder 3 (full access)

2. When a user views the Group folder via the web, the following will appear: 

 Group folder (read-only)
|--- Folder 1 (read-only)
|--- Folder 3 (full access)

Example - view of the user: 
![1  User's View of the Group Folder](https://user-images.githubusercontent.com/78890482/155660042-b85d1056-752c-43c4-b8eb-3b5de0f9cef8.PNG)

3. When a user clicks download the Group folder, the folders as above in (2) will be downloaded. 👍
 
4. When a user clicks "copy" the entire Group folder via the web interface and saves the folder to another destination, the following occurs ❌

### Expected behaviour
 Only the following folders are copied: 

Group folder (read-only)
|--- Folder 1 (read-only)
|--- Folder 3 (full access)

### Actual behaviour
All the folders/files of the entire group folder are copied

Group folder (read-only)
|--- Folder 1 (read-only)
|--- Folder 2 (**no access**)
|--- Folder 3 (full access)

Example - all group subfolders & contents are copied files to the user's target folder:
![1  View After Copying the Group Folder elsewhere](https://user-images.githubusercontent.com/78890482/155660126-fdd70303-be72-42be-a153-4528226b3489.PNG)

### Server configuration

**Operating system:** Linux 5.11.0-1028-aws x86_64

**Web server:** Ubuntu 20.04.4 LTS (GNU/Linux 5.11.0-1028-aws x86_64)

**Database:** 10.5.5-MariaDB-1:10.5.5+maria~bionic-log mariadb.org binary distribution

**PHP version:** PHP 7.4.3

**Nextcloud version:** 22.2.5

**Group folders version:**  10.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official nextcloud 

**Are you using external storage, if yes which one:** No. Using object storage on S3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10 Pro 21H2

### Logs

No error message or any errors logged.

**Comment by fschrempf** [comment]
Thanks for the report. I can't reproduce this on NC22 and NC23. I suspect it might be related to using S3 as storage backend!?

**Comment by os-ai** [comment]
> Thanks for the report. I can't reproduce this on NC22 and NC23. I suspect it might be related to using S3 as storage backend!?

Data is stored on the s3 backend as individual objects (without any hierarchy) with ID numbers assigned to them. Nextcloud gives instructions what objects to pull. I doubt it may due to the backend... Could it be due to the older version of the group folder app?
Hope someone else can reproduce this issue.

**Comment by os-ai** [comment]
I'm still able to reproduce this issue with NC version 22.2.6, by clicking "copy" the entire root "Test" group folder via the web interface, and saving it to another destination.

**Comment by nickvergessen** [comment]
This is solved now: https://github.com/nextcloud/security-advisories/security/advisories/GHSA-cq8w-v4fh-4rjq
