### ISSUE TITLE
Cannot delete self created folders in a group folder

### ISSUE THREAD

**Issue by gadric** [nextcloud/groupfolders#1924]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create an group folder with all permissions
2. Create a single folder in the created group folder
3. Copy some files there
4. Delete folder

### Expected behaviour
Folder is deleted

### Actual behaviour
Error message saying that the folder cannot be deleted. 

### Server configuration

**Operating system:** Debian 11

**Web server:** Apache 2.4.52

**Database:** MariaDB 10.5

**PHP version:** 7.4

**Nextcloud version:** 23.02

**Group folders version:**  11.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated. 

**Where did you install Nextcloud from:** As appliance from ncp

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 99

**Operating system:** Linux Mint 

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
":"YiTDz9uWnRtF8yNaq3IhBAAAAEQ","level":4,"time":"2022-03-06T14:23:11+00:00","remoteAddr":"172.17.0.1","user":"suze","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/suze/Fotos/asdf","message":"Failed to move groupfolder item to trash","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"23.0.2.1","exception":{"Exception":"Exception","Message":"Failed to move groupfolder item to trash","Code":0,"Trace":[{"file":"/data/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":102,"function":"moveToTrash","class":"OCA\\GroupFolders\\Trash\\TrashBackend","type":"->"},{"file":"/data/nextcloud/apps/files_trashbin/lib/Storage.php","line":202,"function":"moveToTrash","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->"},{"file":"/data/nextcloud/apps/files_trashbin/lib/Storage.php","line":125,"function":"doDelete","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/data/nextcloud/lib/private/Files/View.php","line":1171,"function":"rmdir","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/data/nextcloud/lib/private/Files/View.php","line":350,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/data/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":309,"function":"rmdir","class":"OC\\Files\\View","type":"->"},{"file":"/data/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/data/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/data/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/data/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/data/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/data/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/data/nextcloud/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/data/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/data/nextcloud/remote.php","line":166,"args":["/data/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/data/nextcloud/apps/groupfolders/lib/Trash/TrashBackend.php","Line":207,"CustomMessage":"--"}}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by gaellafond** [comment]
I would like to add that this bug also occurs when the folder is empty.

1. Create a single folder in a group folder
2. Delete the folder

The following error message appears: `Error deleting file "NEW_FOLDER".`

NextCloud version 22
Group Folders version 10.0.0 and 10.0.2

**Comment by gadric** [comment]
I fixed the issue by deleting and creating the group folders
