### ISSUE TITLE
GroupFolder Create via API not working

### ISSUE THREAD

**Issue by emilianocapasso** [nextcloud/groupfolders#1939]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a POST request to URL/apps/groupfolders/folders via Postman with mountpoint=foldername
2. Send POST
3. tried also with posting a JSON { "mountpoint" : "foldername" } instead of form-urlencoded

### Expected behaviour
Tell us what should happen

Groupfolder should be created

### Actual behaviour
Tell us what happens instead

Folder list sent as response and no folder created
![image](https://user-images.githubusercontent.com/26569178/160887642-62139b78-f5c0-4cd8-888c-1e322e3c067c.png)

**Comment by CarlSchwan** [comment]
Hello the following code works for me:

```bash
curl -u 'admin:admin' -H "OCS-APIRequest: true" -X POST 'http://nextcloud.local/index.php/apps/groupfolders/folders' -F 'mountpoint=my-folder' -v
```

**Comment by emilianocapasso** [comment]
thanks. the whole thing was just the lack ok "index.php".
