### ISSUE TITLE
[Bug]: Deleted files not being held in trashbin

### ISSUE THREAD

**Issue by D34DC3N73R** [nextcloud/groupfolders#1940]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

I recently updated to Nextcloud 23.0.3 and my recycle bin is now empty. I have previously had 365 days of retention, but now I can’t keep deleted files for more than a handful of minutes (until cron runs). I’m using 9.3TB of an available 37TB, so I don’t think it’s storage related. I can see the activity showing the file was created and deleted, but the file is immediately removed from "Deleted Files" when cron runs. Files deleted from normal user folders are retained. 

 In my config.php, retention is set to 365 days.
`'trashbin_retention_obligation' => '365, auto',`

My user has the default 50% of available space trashbin size.
```
occ trashbin:size --user=my_user
default (50% of available space)
```

Available space
<img width="684" alt="image" src="https://user-images.githubusercontent.com/9123670/160933022-c55b2335-0e02-4b1b-8ba0-0e8521c25e06.png">

Activity shows creation and deletion
<img width="218" alt="image" src="https://user-images.githubusercontent.com/9123670/160928102-1fb90c94-4e7f-49ff-9fa8-3c2db654729f.png">

File initially shows in "Deleted Files"
<img width="538" alt="image" src="https://user-images.githubusercontent.com/9123670/160928348-f17e2c3c-d10d-4337-bd3f-1f829b64c349.png">

The deleted file from group folders is missing, files deleted from non group folders remain
![image](https://user-images.githubusercontent.com/9123670/160930639-1bc56a12-4415-4c15-9f0c-c9758f2f6444.png)

More information: https://help.nextcloud.com/t/deleted-files-not-being-held-in-recycle-bin/136424

### Steps to reproduce
1. Use Nextcloud 23.0.3, group folders 11.1.2, and in my case unlimited quota for the group folder (not sure if that's required to reproduce)
2. Set trashbin_retention_obligation to 30 days (or anything longer than cron schedule)
3. Upload file to the group folder
4. Delete file from the group folder
5. Call cron, or wait for cron to run
6. File is no longer present in "Deleted Files"

### Expected behaviour
Files deleted in group folders should adhere to the trashbin_retention_obligation set in config.php

### Actual behaviour
Files are removed from recycle bin when cron runs

### Server configuration

**Operating system:** 
unRAID 6.9.2

**Web server:** 
nginx/1.20.2

**Database:**
MySQL 10.5.15

**PHP version:**
7.4.26

**Nextcloud version:** (see Nextcloud admin page)
23.0.3

**Group folders version:**
11.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
unraid community apps

**Are you using external storage, if yes which one:** 
no external storage

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no external backend

### Client configuration
**Browser:**
Chrome Version 99.0.4844.82

**Operating system:**
unRAID 6.9.2

### Logs

contains sensitive data, will PM upon request

#### Web server error log
<details>
<summary>Web server error log</summary>

```
contains sensitive data, will PM upon request
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
contains sensitive data, will PM upon request
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
chrome console log
[chrome-console-1648674732087.log](https://github.com/nextcloud/groupfolders/files/8384105/chrome-console-1648674732087.log)
```
</details>

**Comment by CarlSchwan** [comment]
@D34DC3N73R Thanks for the report. This should be fixed with https://github.com/nextcloud/groupfolders/pull/1951
