### ISSUE TITLE
occ files:scan all => PHP Fatal error:  Cannot use OCP\Constants as Constants because the name is already in use in  nextcloud/custom_apps/groupfolders/lib/Command/ACL.php on line 35

### ISSUE THREAD

**Issue by MrColumbo** [nextcloud/groupfolders#1943]
### Server configuration

**Operating system:**
Turnkey LXC Container with php 7.4 (based on debian) running in proxmox

**Web server:**
apache2

**Database:**
mariad
**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
23.03
**Group folders version:**
11.1.12
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated ....coming from at least nextcloud 22 or earlier

**Where did you install Nextcloud from:**
updated a turnkey nextcloud lxc container

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

### Client configuration
**Browser:**
the issue is on cli .....but i noticed i can not access the app list anymore as well

**Operating system:**

### Logs
since the issue is on cli i a not sure if any logs are needed

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

I do a 

sudo -u www-data php occ groupfolder:scan 1

and I get 

PHP Fatal error:  Cannot use OCP\Constants as Constants because the name is already in use in /fileshare/nextcloud/custom_apps/groupfolders/lib/Command/ACL.php on line 35
{"reqId":"m7Rm49wgs8fuqA18zOzn","level":3,"time":"2022-04-03T14:48:47+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Cannot use OCP\\Constants as Constants because the name is already in use at /fileshare/nextcloud/custom_apps/groupfolders/lib/Command/ACL.php#35","userAgent":"--","version":"23.0.0.10"}

the bad thing is that even happens when I do this

sudo -u www-data php occ apps:disable groupfolder

....and here the same

sudo -u www-data php occ files:scan all
PHP Fatal error:  Cannot use OCP\Constants as Constants because the name is already in use in /fileshare/nextcloud/custom_apps/groupfolders/lib/Command/ACL.php on line 35
{"reqId":"SWWH2JiFKrdDJW6Qqccm","level":3,"time":"2022-04-03T14:49:59+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Cannot use OCP\\Constants as Constants because the name is already in use at /fileshare/nextcloud/custom_apps/groupfolders/lib/Command/ACL.php#35","userAgent":"--","version":"23.0.0.10"}

I noticed that there are some closed bugs with exactly the same error message but this seems to be a new issue since the old bugs are closed and I am running on the latest non beta version

**Comment by MrColumbo** [comment]
By the way ....in an older issue (same error) it was recommended to just remove the 35 in that file.

When I do this an run the command again I get this error

Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.

Cannot create "data" directory
This can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/23/go.php?to=admin-dir_permissions

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /fileshare/nextcloud/lib/private/Console/Application.php:164
Stack trace:
#0 /fileshare/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#1 /fileshare/nextcloud/occ(11): require_once('/fileshare/next...')

....i do not believe that permissions are wrong and the file is there .ocdata

**Comment by joshtrichards** [comment]
According to your error and what I assume was a typo (v11
1.12 was never a valid release but v11.1.1 was) you were running the unlatched version.  Line 35's duplicate reference to `Constants` did not exist in releases added that. It would have been impossible to get an error about line 35 unless you were still running an older release. 

Closing since this is almost certainly addressed now.
