### ISSUE TITLE
Compatibility with Nextcloud 24

### ISSUE THREAD

**Issue by waja** [nextcloud/groupfolders#1985]
Hi there,

nextcloud was [released](https://nextcloud.com/blog/nextcloud-hub-24-is-here/) recently. The app is not compatible at the moment.

Thanks, Jan.

**Comment by harryscollar** [comment]
Updated to NC24 not realising group folders not compatible now over half my files have disappeared.

I assume (hope) they're on our server somewhere.

Is there a way to manually get them back or will a pending update soon reinstate the missing folders?

**Comment by CarlSchwan** [comment]
https://github.com/nextcloud/groupfolders/pull/1986 :)

**Comment by harryscollar** [comment]
> #1986 :)

Phew ;-)

**Comment by CarlSchwan** [comment]
And this just got released https://apps.nextcloud.com/apps/groupfolders. I'll also do a release for nc 22 and nc23 later today
