### ISSUE TITLE
Groupfolders broken in Nextcloud 24.0

### ISSUE THREAD

**Issue by kinimoas** [nextcloud/groupfolders#1990]
### Steps to reproduce
1. Run Groupfolder with Nextcloud 23.0.4
2. Install update to Nextcloud 24.0.0 from the stable channel
3. Update Groupfolder to Version 12.0

### Expected behaviour
Group folders should be available as before

### Actual behaviour
- Configuration for Groupfolders disappeared
- Groupfolders are not visible
- occ groupfolders:list  results in "There are no commands defined in the "groupfolders" namespace. "

### Server configuration

**Operating system:**
Debian Linux

**Web server:**
apache2

**Database:**
Postgres

**PHP version:**
PHP 7.4.28

**Nextcloud version:** (see Nextcloud admin page)
24.0

**Group folders version:**
12.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 23.0.4

**Where did you install Nextcloud from:**
stable channel

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
LDAP

### Client configuration
**Browser:**
Firefox

**Operating system:**
Debian

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors listed
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Keyword groupfolder only appears in this message in the last few hours (before the update):

Updater::checkAppStoreApp: Checked for update of app \"groupfolders\" in appstore","userAgent":"--","version":"23.0.4.1"
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 [globals.js:62:15](webpack:///nextcloud/core/src/globals.js)
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.

b) The network log
c) ...
```
</details>

**Comment by h0tw1r3** [comment]
Appears to be related to this change

https://github.com/nextcloud/groupfolders/commit/72d114370f3d54e1c58e6ca998017fc970117c89

**Comment by h0tw1r3** [comment]
After restarting php-fpm service I no longer receive the error. Something with opcache?

**Comment by CarlSchwan** [comment]
Does anyone have a log file with some entries? Could you try `occ app:enable groupfolders`

**Comment by kinimoas** [comment]
./occ app:enable groupfolders
groupfolders 12.0.0 enabled

./occ groupfolders:list 
+-----------+-------------------------+-----------------------------------------------+-------+----------+----------------------+-----------------------------+
| Folder Id | Name                    | Groups                                        | Quota | Size     | Advanced Permissions | Manage advanced permissions |
+-----------+-------------------------+-----------------------------------------------+-------+----------+----------------------+-----------------------------+
| 1         | GroupA Folder         | GroupA: read, write, share, delete           | 5 GB  | 1.7 GB   | Disabled             |                             |


```

so ether the app:enable or an apache2 service restart (In the meanwhile I corrected some settings due to a opcache-Warning (visible on index.php/settings/admin/overview) follwed by a service restart did the trick.

Thanks for your time an thoughts.

I was not able to restart the php-fpm service.

```
sudo service php-fpm status
Unit php-fpm.service could not be found.

ps -A | grep fpm 
```
shows no result

```
There are still no log entries with the keyword groupfolder on my system.
