### ISSUE TITLE
v12.0.0 is available at app store but not as release at GitHub

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/groupfolders#1991]
On 5th of may 2022 the app store offered v12.0.0 which looks adapted to server v24 but there is no tag / release at GitHub.

**Comment by rakekniven** [comment]
Hello @CarlSchwan , you did the last releases at GitHub. Do you have a minute to maintain it? Thanks.

**Comment by CarlSchwan** [comment]
Oh sorry forgot to push the tag to the nextcloud repo qnd not just nextcloud-release

**Comment by CarlSchwan** [comment]
Pushed :) https://github.com/nextcloud/groupfolders/tags

**Comment by rakekniven** [comment]
Great! Will you do a release as well or should I?

**Comment by rakekniven** [comment]
Done it.
