### ISSUE TITLE
Automatically create groupfolder if given foldername doesn't exist

### ISSUE THREAD

**Issue by dan-nkl** [nextcloud/groupfolders#20]
If entering a foldername that doesn't exist, just create a new groupfolder with that name.

Or maybe give out an error so you know that you have to create a folder manually first or check the spelling.

**Comment by jospoortvliet** [comment]
Ah, there's some weird overlap here with existing folders. Let me file an issue.

**Comment by dan-nkl** [comment]
I don't think that this issue has something to do with the overlap. 
I just mean that the app should automatically create a folder if a folderbame is entered at the groulfolder menu which doesn't already exist.

**Comment by dan-nkl** [comment]
Ups.. There is no bug like this.. My fault..
