### ISSUE TITLE
[Bug]: Group Folders reports "Not Enough Free Space" when uploading using web interface - but not if synched

### ISSUE THREAD

**Issue by richp10** [nextcloud/groupfolders#2000]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Using docker installed: nextcloud:24-fpm-alpine

Using Group Folders, I can add a file using synched folders, but uploading via the web interface fails with a not enough free space error. 

I can succesfully create a new text document using the web interface, but it shows the error message as well as completing the task. 

### Steps to reproduce

1. Created a Group Folder, with Quota of 5GB, permissions given for a group of which I am a member. 
2. Check folder appears on synched drive and I can succesfully add file - which syncs. 
3. BUT, using the web interface, I try and upload a file - which fails with "Not Enough Free Space"
4.  I then try creating a new text document in the folder, using the web interface. 
5. Again, I get the error message - but the text document is created

### Expected behavior

I should be able to upload a file to a group folder using the web interface - and not just using the synched directory on my computer. 

If I use the web interface to create a new text document, I should be able to do that without an error message

### Installation method

Official Docker image

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
I am using the official docker image and it does not have sudo
```

### List of activated Apps

```shell
Deck
Group Folders

Nothing else
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"fjWnknB2BDyLf6pq8ne0","level":2,"time":"2022-05-17T16:28:45+00:00","remoteAddr":"81.136.17.100","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":""}
{"reqId":"fjWnknB2BDyLf6pq8ne0","level":2,"time":"2022-05-17T16:28:45+00:00","remoteAddr":"81.136.17.100","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":""}
{"reqId":"3rchJkT82HUdaNyHKCwL","level":2,"time":"2022-05-17T16:28:49+00:00","remoteAddr":"81.136.17.100","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":""}
{"reqId":"3rchJkT82HUdaNyHKCwL","level":2,"time":"2022-05-17T16:28:49+00:00","remoteAddr":"81.136.17.100","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":""}
```

### Additional info

Possibly relevent - I am proxying via nginx and it is possible this is creating a problem, the following is relevent section of nginx site config. 

 add_header 'Access-Control-Allow-Origin' 'https://next.blah.co.uk';
   client_max_body_size 30M;
   server_tokens off;
   index index.php;
   root  /usr/share/nginx/html/nextcloud;

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        location = / {
                if ( $http_user_agent ~ ^DavClnt ) {
                    return 302 /remote.php/webdav/$is_args$args;
                }
        }

        location ^~ /.well-known {
                location = /.well-known/carddav { return 301 /remote.php/dav/; }
                location = /.well-known/caldav  { return 301 /remote.php/dav/; }
                location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
                location /.well-known/pki-validation    { try_files $uri $uri/ =404; }
                return 301 /index.php$request_uri;
        }

        # set max upload size
        fastcgi_buffers 64 4K;

        # Enable gzip but do not remove ETag headers
        gzip on;
        gzip_vary on;
        gzip_comp_level 4;
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json applicatio

        add_header Referrer-Policy "no-referrer" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Download-Options "noopen" always;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Permitted-Cross-Domain-Policies "none" always;
        add_header X-Robots-Tag "none" always;
        add_header X-XSS-Protection "1; mode=block" always;

        location ~ ^\/(?:build|tests|config|lib|3rdparty|templates|data)\/ {
            deny all;
        }

        location ~ ^\/(?:\.|autotest|occ|issue|indie|db_|console) {
            deny all;
        }

        location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+)\.php(?:$|\/) {
                root   /var/www/html/;
                include fastcgi_params;
                fastcgi_pass next.blah.co.uk;
                include /etc/nginx/vhost.d/next.blah.co.uk_location;
        }

        location ~ \.(?:css|js|svg|gif|png|jpg|ico|wasm|tflite|map|mp4|webm|jpeg|bcmap|ttf|html|woff2?$)$ {
            try_files $uri /index.php$request_uri;
                expires            7d;
                sendfile           on;
                sendfile_max_chunk 1m;
                tcp_nopush         on;
                tcp_nodelay        on;
                keepalive_timeout  65;
                access_log         off;
                add_header Cache-Control "public";
                access_log off;

            location ~ \.wasm$ {
                default_type application/wasm;
            }
        }

**Comment by joshtrichards** [comment]
No idea why you experienced this. I can't find any similar reports nor reproduce this behavior. It would be a fairly serious showstopper for groupfolders if it was commonplace. Are you still able to reproduce this behavior?

The `Not enough free space` only gets shown in the front-end (Web UI) if a 507 (insufficient space) is sent by the back-end under any scenario I'm aware of. I would expect you to see something logged.

**Comment by provokateurin** [comment]
Given the age of the report and that nobody else has experienced it I will close this for now, but please re-open if you still have this problem.
