### ISSUE TITLE
sharing a Document in a groupfolder with a NON Member of the Group

### ISSUE THREAD

**Issue by RolandGuttek** [nextcloud/groupfolders#2044]
### Steps to reproduce
1. Share a Document from a Groupfolder with a NON Member
2. This nonmember opens it with for example Onlyoffice and makes changes
3. he cant save the changes, 
4. same procedure with a groupmember can be saved

### Expected behaviour
changes should be saves

### Actual behaviour
changes are not saved

### Server configuration

**Operating system:**
Linux 5.4.0-121-generic x86_64

**Web server:**

**Database:**
Typ: mysql
Version: 10.5.16

**PHP version:**
8.0.20

**Nextcloud version:** (see Nextcloud admin page)
24.0.2

**Group folders version:**
12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated Docker from V23

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no

### Client configuration
**Browser:**
firefox, edge, 

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by urz-hgw** [comment]
We are experiencing the same issue.
We are using Nextcloud version 23.0.2 and groupfolders version 11.1.5

**Comment by CarlSchwan** [comment]
@juliushaertl might know what is going on here

**Comment by juliushaertl** [comment]
This should be fixed by https://github.com/nextcloud/server/pull/33804 and https://github.com/nextcloud/server/pull/34001
