### ISSUE TITLE
Deleted files/folders keep returning

### ISSUE THREAD

**Issue by fuzunspm** [nextcloud/groupfolders#2049]
### Actual behaviour
Whenever a file or folder deleted from a groupfolder, it keeps re-appear. I tried rescan all files, remove trash from cli but no help. I'm not getting any error or warning about this issue. 

### Server configuration

**Operating system:** Fedora 34 (Server Edition) x86_64

**Web server:** nginx

**Database:** mysql

**PHP version:** PHP 7.4.30

**Nextcloud version:** (see Nextcloud admin page) 23.0.4

**Group folders version:** 11.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Are you using external storage, if yes which one:**  NO

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox/Safari/Brave

**Operating system:** Ubuntu 20.04.4 LTS x86_64

**Comment by tholler3012** [comment]
Same problem here

**Comment by jogo81** [comment]
We have the same Problem here.
When our customer deletes folders or files through the desktop client (Windows) they appear deleted in her synced folder but, they're still there on her colleague's computer and the server.

**Comment by JohnWalkerx** [comment]
> We have the same Problem here.
> When our customer deletes or moves folders through the desktop client (Windows) they appear deleted in her synced folder, but they're still there on her colleague's computer and the server.

I have 2 instances running. On my production instance the sync with the desktop client works. But on my test instance it's the same behavior like you described.
Also new files will not be synced.

I need to put a little more research into this.

**Comment by lockdlock** [comment]
I have the same problem.
However, when I deleted the groupfolder using the command line, the following error was identified
`#0 [internal function]: OCA\Files_Reader\Hooks::OCA\Files_Reader\{closure}()`
, so I deleted the Files_Reader app and and groupfolder did not come back .

**Comment by kdoteu** [comment]
Did you guys tried to use ```occ files:repair-tree```? this worked for me - for a similar error

**Comment by fuzunspm** [comment]
```
sudo -u nginx php occ files:repair-tree
Found 0 file entries with an invalid path
```

**Comment by JohnWalkerx** [comment]
> I have 2 instances running. On my production instance the sync with the desktop client works. But on my test instance it's the same behavior like you described.
Also new files will not be synced.

I tested again on my test instance where I had problems before.
Server-version: 25.0.2 Client: 3.6.2
Now everything works fine. Don't know if the upgrade to Nextcloud 25 or something else fixed it. :thinking:

**Comment by be-engineer** [comment]
I have upgraded to 25.0.7. There is still such a problem that the two folders deleted before will reappear on the web and mobile app. After being deleted again, they will reappear the next time I open them

**Comment by fuzunspm** [comment]
We have more than 1000s of folders, I understand your temporary fix but it's not acceptable

**Comment by Fmstrat** [comment]
There seems to be very little information in this thread to debug. Could everyone put specifics of their use case? I'll go first:

- Group folders
    - `Company` [Readable by `Company` group]
        - `Software Administration` [R/W/D by `Software Admin` group]

- Problem:
    - User is part of `Company` and `Software Administration` group
    - Create file on Desktop to sync: `/Company/Software Administration/Test.md`
    - File syncs to Nextcloud fine
    - Delete file on Desktop
    - Nextcloud syncs, file re-appears on Desktop
    - Delete file in Web interface, file disappears in web
    - Force Desktop client to sync, file remains on Desktop
    - Delete file from Desktop, file is finally gone for good

- Expectation
    - Deleting file on Desktop deletes from Web as well instead of re-appearing on Desktop
    - Deleting file on Web also deletes from Desktop

**Comment by joshtrichards** [comment]
@fuzunspm I see some of the others that have joined this issue mention the desktop client. Your original report does not. Are Desktop clients involved or just the Web UI client?

**Comment by jospoortvliet** [comment]
A bunch of fixes were recently done to groupfolders in the desktop client. Re-open if this still happens - but pretty sure this is fixed in latest Nextcloud & client.
