### ISSUE TITLE
Report number of files for each folder via `occ groupfolders:list`

### ISSUE THREAD

**Issue by mjsaarin** [nextcloud/groupfolders#2056]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I would like to able to see how many files are stored in each of group folders when I issue occ groupfolders:list. It would be sufficient if the information were available on JSON output only.

**Describe alternatives you've considered**

Alternate solution would be to write a separate script that would pull the information form the database. 

**Additional context**

More like motivation from my side. We recently had an issue where database filled the db server storage when someone uploaded a huge number of files. That is why I would like to be able to monitor the growth of the number of files.  If I noticed a (steep) increase I might be able to contact the user and suggest some better solution.

**Comment by miaulalala** [comment]
If I understand this correctly, the issue isn't neccessarily even the amount of files but the size? Maybe the command could display the folder size instead?

**Comment by mjsaarin** [comment]
The folder sizes are reported already. The number of files is the key issue here because for every file there are several lines in database.

**Comment by provokateurin** [comment]
I don' think this is something we want to support. If you need monitoring of the number of files (not only for groupfolders but in general), please interface with the storage or the database to query these numbers.
