### ISSUE TITLE
Sync/access issue with a subfolder shared to a remote nextcloud instance

### ISSUE THREAD

**Issue by Kdecherf** [nextcloud/groupfolders#2085]
### Steps to reproduce
1. Create a groupfolder `foo` on instance A
2. Create a folder `bar` within it and share it with a remote user on instance B
3. Create/copy/modify files in the `bar` folder from instance B

### Expected behaviour
I have a group folder on nextcloud instance A which is named `Foo'bar`, I shared a subfolder with a remote user on nextcloud instance B who accepted it.

### Actual behaviour

When I edit files from instance B (_from either web client or Notes android app in this specific case_) fatal errors appear on the webdav part with a stack shown below.

Old version may still appear on instance B for a moment but modifications seems to be saved correctly on instance A.

On instance B several `OCP\Files\StorageNotAvailableException` are thrown when I try to access to these files.

I'm not sure if these errors are related or if there are several issues there.

### Server configuration

**Operating system:**
Linux (official docker image)

**Web server:**
nginx (fpm)

**Database:**
PostgreSQL 12

**PHP version:** 

**Nextcloud version:**
24.0.5

**Group folders version:**
12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 23

**Where did you install Nextcloud from:**
official docker image (fpm variant)

**Are you using external storage, if yes which one:**
local

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Firefox 104

**Operating system:**
Linux

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[webdav] Fatal: TypeError: OCA\GroupFolders\Folder\FolderManager::canManageACL(): Argument #2 ($user) must be of type OCP\IUser, null given, called in /var/www/html/custom_apps/groupfolders/lib/DAV/ACLPlugin.php on line 66 at <<closure>>

 0. /var/www/html/custom_apps/groupfolders/lib/DAV/ACLPlugin.php line 66
    OCA\GroupFolders\Folder\FolderManager->canManageACL(3, null)
 1. /var/www/html/custom_apps/groupfolders/lib/DAV/ACLPlugin.php line 178
    OCA\GroupFolders\DAV\ACLPlugin->isAdmin("/kevin.decherf/ ... d")
 2. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\GroupFolders\DAV\ACLPlugin->propPatch("*** sensitive parameters replaced ***", Sabre\DAV\PropPatch {})
 3. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1263
    Sabre\DAV\Server->emit("propPatch", ["*** sensitive  ... }])
 4. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 373
    Sabre\DAV\Server->updateProperties("*** sensitive parameters replaced ***")
 5. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropPatch(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 6. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:PROPPATCH", [Sabre\HTTP\Requ ... }])
 7. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
 9. /var/www/html/apps/dav/appinfo/v1/publicwebdav.php line 117
    Sabre\DAV\Server->exec()
10. /var/www/html/public.php line 80
    require_once("/var/www/html/a ... p")

PROPPATCH /public.php/webdav/Todo.md
from 192.168.x.x at 2022-09-09T18:01:47+00:00
```
</details>

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by CarlSchwan** [comment]
Hello @Kdecherf, I created this pull request that should solve the bug in your log https://github.com/nextcloud/groupfolders/pull/2098

Could you test it? There might be more issues hidden by the first crash.

**Comment by Kdecherf** [comment]
@CarlSchwan awesome, I'll give it a try in the coming days
