### ISSUE TITLE
Group calenders functionality

### ISSUE THREAD

**Issue by neufeind** [nextcloud/groupfolders#2095]
It would be nice to also have calendars on group-level. Does it make sense to integrate that into "group folders" or as a separate plugin?
Having calendars on the group-level makes sure they do not belong to just one user (which might get deleted one day).

**Comment by CarlSchwan** [comment]
Yeah I agree this would be a good feature and something often requested. The implementaiton for that would need to live in Server since this is where the entire caldav backend is implemented. 

This would require rather large changes and is currently not planned (but we accept PR for this feature)
