### ISSUE TITLE
Ask for confirmation when deleting group folders

### ISSUE THREAD

**Issue by Rocreex** [nextcloud/groupfolders#21]
I have noticed that you can very easily delete group folders, just by accident. There is no confirmation message when pressing the delete button in the menu. This is especially critical since there is no way to restore the folder (like with ordinary shared folders). Is it possible to at least have some password confirmation before deleting group folders?

**Comment by jospoortvliet** [comment]
You mean a recipient can remove a group folder they have been given access to? I don't see any ability for a user to delete a group folder, only the admin can do that from the configuration... If he/she does that by clicking the trash I guess it would be on purpose.

But perhaps an older version allowed users to delete it - this is currently not possible in 1.0.2 ;-)

**Comment by icewind1991** [comment]
Fixed with dc071adf4fbbe2c5c644aa4358ced7c232ecee7b
