### ISSUE TITLE
"Users/groups that can manage" wording doesn't appear in Transifex and so cannot be translated

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/groupfolders#2131]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Everything is described in this issue's title.
And so this wording remains in English in my French UI.
#### See the screenshots : 
**UI :** 
![2022-10-13_11-53](https://user-images.githubusercontent.com/33763786/195565811-f736b99f-6a98-452d-b55e-04f76eadaa8a.png)
**Transifex :** 
![2022-10-13_11-54](https://user-images.githubusercontent.com/33763786/195565826-c54bbc87-8523-412d-8188-653c0fad2bb4.png)

### Server configuration

Operating system: Linux 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64

Webserver: nginx/1.23.1 (fpm-fcgi)

Database: mysql 10.5.17

PHP version: 8.0.22

Nextcloud version: 23.0.7 Enterprise - 23.0.7.3

Group folders version: 11.1.5

Updated from an older Nextcloud/ownCloud or fresh install: Older

Where did you install Nextcloud from: Regular web installer

Are you using external storage, if yes which one: No

Are you using encryption: no

Are you using an external user-backend, if yes which one: no

### Client configuration
Browser: Firefox 105.0.2
Operating system: Ubuntu 20.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Can be provided if necessary
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Can be provided if necessary
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Can be provided if necessary
```
</details>

**Comment by Jerome-Herbinet** [comment]
Still occurs with the last GF release (in NC 29)

**Comment by provokateurin** [comment]
Fixed by https://github.com/nextcloud/groupfolders/pull/3191
