### ISSUE TITLE
No ACL in groupfolders share menu

### ISSUE THREAD

**Issue by artem-aa** [nextcloud/groupfolders#2148]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Fresh install from VM script on ubuntu LTS 22.04
2. Enable group folders, create one with advanced permissions

### Expected behaviour
ACL interface in Share menu

### Actual behaviour
ACL interface in Share menu

### Server configuration

 ubuntu LTS 22.04
nextcloud installed from VM script
**Nextcloud version:** 25.0.0

**Group folders version:** 13.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Browser:** Any

**Operating system:** Windows 10

### Logs

In latest version I steel can manage ACL throught occ commands and ACL applyed correctly. 

If I instal vm with key "--not-latest" I get version 24 and I can see interface for ACL in web

**Comment by nursoda** [comment]
Same here. In my case a migrated-from-24 instance. Already existing ACL rules are applied but one cannot edit any rule in 25.0.0 using GroupFolders 13.0.0. Might by an NC or a GF issue.

**Comment by nitatech** [comment]
The same.
After upgrade to 25 ACL interface in Share menu consist of write, share, delete in Groups & No any permitssions in Advanced permissions

**Comment by XueSheng-GIT** [comment]
Can confirm for NC25 and groupfolders 13. DOM tree for groupfolders is empy.
![groupfolder_empty_DOM](https://user-images.githubusercontent.com/4077683/197605626-b4477a87-0fb0-4560-b8ff-35aa6cd605e9.png)

**Comment by svenseeberg** [comment]
> Same here. In my case a migrated-from-24 instance. Already existing ACL rules are applied but one cannot edit any rule in 25.0.0 using GroupFolders 13.0.0. Might by an NC or a GF issue.

Adding to this: existing ACLs still apply, it is just not possible to view or change them.

**Comment by robertsoldaat** [comment]
> The same.
> After upgrade to 25 ACL interface in Share menu consist of write, share, delete in Groups & No any permissions in Advanced permissions

Same here after upgrading to NC 25 with GroupFolders 13.0.0

**Comment by RickStinson** [comment]
Same here on a fresh NC25 installation

**Comment by fschrempf** [comment]
Please stop posting without adding information to the issue and use the +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Thanks!

**Comment by CarlSchwan** [comment]
I'll try to investigate that Monday. For me it worked last time I tried and it is in my todo list before doing a release.

**Comment by svenseeberg** [comment]
Something else I noticed that could be related: I created a new Group Folder and activated the advanced permissions. It seems that the advanced permissions are available when adding a user or a group. However, the changes in the GUI are not shown at all when looking at the permissions of the groupfolder with occ. That means the added user or group are not even listed in the advanced permissions table with `occ groupfolders:permissions 2`

**Comment by fschrempf** [comment]
We will keep this open until the fix from #2168 is released, so people hopefully stop asking and opening new issues.

**Comment by PVince81** [comment]
@CarlSchwan can you release it ?

**Comment by laarisyko** [comment]
Is it possible to change the advanced rules via OCC in the meantime, until this issue is fixed by an official update?

**Comment by fschrempf** [comment]
> Is it possible to change the advanced rules via OCC in the meantime, until this issue is fixed by an official update?

Yes, see: https://github.com/nextcloud/groupfolders#configuring-advanced-permissions-trough-occ.

**Comment by CarlSchwan** [comment]
Fixed with 13.1.0 that I just released
