### ISSUE TITLE
user quota and folder quota.

### ISSUE THREAD

**Issue by quentingosset** [nextcloud/groupfolders#215]
hello, 
I wonder if with your extension, the management of the quota of the file is in parallel with the user quota, I explain myself. I would like example creates a group called COMPANY X that has different folder such as "MARKETING / IT / ..." the folder administrator creates users and assigns users to the specific file. 
I would like to know: when I put a folder quota to 5Gb and I assign the folder to the user Y who has a basic quota of 0, the user has permission to upload 5GB to the folder or is the 0GB limit blocking this opportunity?

**Comment by XA21X** [comment]
I have been using it in the way you've described, with zero user quotas, solely using group folders, although I just encountered #217. I'm not sure when it broke; I only recently upgraded to Nextcloud 14 from 13 and have previously observed other users uploading large files via the desktop client.

**Comment by icewind1991** [comment]
Any files uploaded to a group folder will not be counted as part of the regular quota
