### ISSUE TITLE
add support for automated tagging

### ISSUE THREAD

**Issue by neeral85** [nextcloud/groupfolders#216]
please add support for https://github.com/nextcloud/files_automatedtagging

**Comment by maghog** [comment]
Any plan for this? It would be a huge improvement to be able to use tagging for group folders.

**Comment by icewind1991** [comment]
This seems to work with the latest master

**Comment by maghog** [comment]
> This seems to work with the latest master

NC 15?

**Comment by icewind1991** [comment]
of this app
