### ISSUE TITLE
Chunked upload fails when user quota is zero

### ISSUE THREAD

**Issue by XA21X** [nextcloud/groupfolders#217]
### Steps to reproduce
1. Set user quota to zero.
2. Set group folder quota to unlimited.
3. Upload a file approximately >10MB (?, haven't discovered threshold) into the group folder.

### Expected behaviour
Upload progress bar should display and proceed as normal. I expect everything to work as long as the file size is lesser than the configured max upload limit i.e. 511 MB.

### Actual behaviour
Upload fails _silently_.

However, _if_ the user quota is increased such that it is non-zero but still lesser than the file size, the upload fails with a message like 'insufficient quota'.

The error logs indicate that for a small file, it is `PUT` into the group folder directly. Whereas for larger files requiring chunked transfer, it uses `MKCOL` to create a temporary folder in the _user_'s directory where the quota is zero. But this shouldn't matter, because as soon as the transfer finishes, it is moved to the group folder and does not require quota from the user.

I haven't had time to investigate this, but I believe that either the temporary chunked uploads should go into some private part of the group folder OR have some way of bypassing the user quota when it is not intended for the user's storage. 

### Server configuration

**Operating system**: NixOS 18.03

**Web server:** Nginx 1.15.0

**Database:** PostgreSQL 10.4

**PHP version:** 7.2.10

**Nextcloud version:** 14.0.0

### Logs

These logs are the results from attempting to upload two files. The first 400 KB file succeeds, but the 46 MB file fails silently.

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[10/Oct/2018:13:23:38 +0000] "PUT /remote.php/webdav/Media%20Team/3301NotesUpToWeek7.pdf HTTP/1.1" 201 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
[10/Oct/2018:13:23:38 +0000] "PROPFIND /remote.php/dav/files/user/Media%20Team/3301NotesUpToWeek7.pdf HTTP/1.1" 207 1180 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
[10/Oct/2018:13:23:40 +0000] "MKCOL /remote.php/dav/uploads/redacted_user/web-file-upload-52c30823b4db590f0bad4e304c8d22e8-1539177818306 HTTP/1.1" 403 243 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
[10/Oct/2018:13:23:40 +0000] "DELETE /remote.php/dav/uploads/redacted_user/web-file-upload-52c30823b4db590f0bad4e304c8d22e8-1539177818306 HTTP/1.1" 404 248 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
10/Oct/2018:13:23:33 +0000 "PUT /remote.php" 201
10/Oct/2018:13:23:38 +0000 "PROPFIND /remote.php" 207
10/Oct/2018:13:23:40 +0000 "MKCOL /remote.php" 403
10/Oct/2018:13:23:40 +0000 "DELETE /remote.php" 404
```
</details>

**Comment by XA21X** [comment]
Just tested with the desktop client and I'm getting the same result:
`The item is not synced because of previous errors: Error transferring https://redacted_host/remote.php/dav/uploads/redacted_user/1623990491 - server replied: Forbidden (Could not create directory //1623990491)`. I highly suspect something's changed in Nextcloud 14, although my installation hasn't been tested with large files since the upgrade, until now that is.

**Comment by xinux4d** [comment]
Hello,

You can change the chunk size during the upload :

In your databases :

_INSERT INTO oc_appconfig (appid, configkey, configvalue) VALUES (‘files’, ‘max_chunk_size’, ‘524288000’);_

(to modify to 500 Mb files)

**Comment by proxyconcept** [comment]
Should be fixed with this commit https://github.com/nextcloud/server/commit/0fb070b5b4ea19a7319dd3753eb13a285dc89f90 (see https://github.com/nextcloud/server/issues/11485)

**Comment by XA21X** [comment]
@xinux4d Thanks for providing a potential workaround, although I ended up provisioning a small personal quota instead for the short term.

@proxyconcept Applied and can confirm it's working! :)
