### ISSUE TITLE
User for Groupfolder cannot delete files

### ISSUE THREAD

**Issue by pypeaday** [nextcloud/groupfolders#2179]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Setup a Groupfolder with User A
2. Give User B all the access to the Groupfolder
3. User A can right click files and see "delete" as an option but User B can only delete _folders_ but not any files within those folders (there's no "delete" option in the right-click menu)

### Expected behaviour
When any user with delete permissions right-clicks a file in a Groupfolder they should have the option to delete it

### Actual behaviour
There is no 'delete' option in the menu except for User A

### Server configuration

**Operating system:** Ubuntu 22.04.1, Docker 20.10.17 (API: 1.41), Docker image nextcloud:20

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.26

**Nextcloud version:** 20.0.14

**Group folders version:**

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh docker pull

**Where did you install Nextcloud from:** Docker

**Are you using external storage, if yes which one:** local but unrelated to this issue

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** I don't think so

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 22.04.1

### Logs

I have no errors or logs - I simply don't see the "delete" option for files when logged in as a user with full access to a Groupfolder, but when I'm logged in as the user that made the Groupfolder I can delete files

**Comment by fschrempf** [comment]
Nextcloud 20.0.14 is EOL (see https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule). Can you please update to a maintained version and then check if the error persists? Please open a new issue if that's the case. Thanks!
