### ISSUE TITLE
issues with first sync of group folders

### ISSUE THREAD

**Issue by pat95st** [nextcloud/groupfolders#218]
Steps to reproduce:
1. Create a group folder
2. Establish a new connection in one Nextcloud Client instance on Windows or MacOS with a user inside the group you have created the group folder for
3. Check if the folder is available on your local machine using Windows Explorer or Finder on MacOS

In my case, the group folders were not visible. I then opened the Client configuration and there was a message that all group folders are too big to be synchronized - even if the folders were empty. After clicking on "synchronize all", it started working as expected.

Since this issue only occurs with group folders and not with normal folders, I assume that this may be related to a bug inside "group folders". Also some of the other users on our Nextcloud instance reported this issue to me.

**Comment by icewind1991** [comment]
Are you using server side encryption by any chance?

**Comment by ZeikoFr** [comment]
Hi @pat95st is this issue still relevant or can it be closed ?

**Comment by fschrempf** [comment]
As there was no more feedback from the author and this is quite old, I will close this as stale. If someone still observes this issue on the latest release, please create a new issue. Thanks!
