### ISSUE TITLE
Compatibility issues when Updating to NC 24 & 25

### ISSUE THREAD

**Issue by McSh4dow** [nextcloud/groupfolders#2192]
Hi! 

First of all here are our current specs.

OS: Ubuntu 20.04.5
Web server: apache2
PHP version: 7.4.3
Nextcloud version: 23.0.11
Group folders version: 11.1.6
HTTP/HTTPS: HTTPS

We tried to update NC twice to 24.0.7 and once to 25.0.1 from 24.0.7 but there are different issues coming up.

During the NC update process (via WebGUI - Settings - Update) some apps were checked for compatible versions and group folders is listed. After updating to 24.0.7 group folders 12.0.2 have been installed but it has been deactivated because it says the app is not compatible.

![image](https://user-images.githubusercontent.com/74724634/203835061-a85d5e85-8f2e-446e-bd92-e5cd6794b997.png)

That's the complete opposite because it was listed as compatible.

After checking the apps, group folders is already enabled - again the complete opposite.

After updating to 25.0.1 from 24.0.7 the same issue appeared, also there now was a bug in the overview of users and groups:
![image](https://user-images.githubusercontent.com/74724634/203832641-4ac188c8-5dc7-4b81-b323-340f7848b6b0.png)

In the end we rolled back to 23.0.11 because we don't want to risk anything on this productive system.

Did anyone have the same issue? If so, how did you resolve this?

We are thankful for any help.

Thanks and best wishes,
McSh4dow

**Comment by magix2** [comment]
I encounter similar problems. I upgraded to NC25 and during the process got the warning that group folders are disabled and now I only get a blank screen when opening NC in a browser, unless I activate the maintenance mode. In that case, I can see the the maintenance mode screen.

**Comment by magix2** [comment]
Running occ upgrade worked for me. Everything appears to work again. Apparently the upgrade did not go through the other time.

**Comment by thekk1** [comment]
I see several issues with groupfolders app and NC24:
- Delete/Restore with trash app not working properly. The process run inifity and it says the operation failed but after reload the site it is deleted/restored
- Desktop app as sync problems (conflicting files) with group folders. Even after reset the desktop synced files.
- Working with WebDAV mounts in Windows throws sync errors also. Users lost their Work.

Again, a forced, non tested update of nextcloud makes my work week longer. Thank you, guys!

**Comment by joshtrichards** [comment]
In general, app upgrade management and compatibility issues are `server` matters (it handles all those checks and reporting): https://github.com/nextcloud/server/issues

The other matter (Web UI) does not appear to be the case today.

Closing this out.
