### ISSUE TITLE
Cannot read in a shared folder put by other users

### ISSUE THREAD

**Issue by noccio** [nextcloud/groupfolders#22]
nextcloud 12.0.0 on Linux
I created a shared folder but the users cannot read files from the other and I get this error

`Messaggio: Unexpected server response (500) while retrieving PDF "https://nasone/nextcloud/remote.php/webdav/Familiari/Anna%20Libera/Vacanze%202017/Accademia%20Livorno/Allegato%201.pdf".`

**Comment by PoGo606** [comment]
Same here, I'm using backend encryption.

**Comment by jospoortvliet** [comment]
Encryption is not supported with Group Folders.

**Comment by putt1ck** [comment]
Can we close this as wontfix and/or invalid? Seems related to #40 & #10
