### ISSUE TITLE
issues with Collabora Code on office documents inside group folders

### ISSUE THREAD

**Issue by pat95st** [nextcloud/groupfolders#220]
Hello,

I'm facing an issue with opening collabora for files inside all of my group folders when trying to access through the Nextcloud iOS app on my iPad. My general setup:
- Ubuntu 18.04 LTS
- Apache2 webserver
- Nextcloud 14.0.3
- Group folders 1.3.3
- Collabora Online 3.0.1
- Docker version 18.06.1-ce
- Collabora Code 3.4

All works fine if I use Collabora inside the iOS app when I'm working on some private documents or documents and folders shared via the "normal" way. When I try to open an office document inside a group folder through the Nextcloud App on my iPad, I get an "Internal Server Error".

I have checked my Nextcloud Log and found the following entry for each request to Collabora that i have sent through my iPad:

{"reqId":"kYtvSBTrBmvf9uUJC9mA","level":2,"time":"2018-10-25T17:17:43+00:00","remoteAddr":"[MY_IPV6]","user":"--","app":"no app in context","method":"GET","url":"\/index.php\/apps\/richdocuments\/direct\/Qi4p9goYpIeJYpV0oppLQ6T8SLtj1iIHcEDFfmdQ4LPBykhblPd700VK87ij1KUv","message":"Generating token for SaveAs without editoruid","userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.22.4","version":"14.0.3.0"}
{"reqId":"kYtvSBTrBmvf9uUJC9mA","level":3,"time":"2018-10-25T17:17:43+00:00","remoteAddr":"[MY_IPV6]","user":"--","app":"index","method":"GET","url":"\/index.php\/apps\/richdocuments\/direct\/Qi4p9goYpIeJYpV0oppLQ6T8SLtj1iIHcEDFfmdQ4LPBykhblPd700VK87ij1KUv","message":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"file":"[PATH_TO_MY_NEXTCLOUD]apps\/richdocuments\/lib\/Controller\/DirectViewController.php","line":95,"function":"getToken","class":"OCA\\Richdocuments\\TokenManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"[PATH_TO_MY_NEXTCLOUD]lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"show","class":"OCA\\Richdocuments\\Controller\\DirectViewController","type":"->","args":["Qi4p9goYpIeJYpV0oppLQ6T8SLtj1iIHcEDFfmdQ4LPBykhblPd700VK87ij1KUv"]},{"file":"[PATH_TO_MY_NEXTCLOUD]lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DirectViewController"},"show"]},{"file":"[PATH_TO_MY_NEXTCLOUD]lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Richdocuments\\Controller\\DirectViewController"},"show"]},{"file":"[PATH_TO_MY_NEXTCLOUD]lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Richdocuments\\Controller\\DirectViewController","show",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"token":"Qi4p9goYpIeJYpV0oppLQ6T8SLtj1iIHcEDFfmdQ4LPBykhblPd700VK87ij1KUv","_route":"richdocuments.directView.show"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"token":"Qi4p9goYpIeJYpV0oppLQ6T8SLtj1iIHcEDFfmdQ4LPBykhblPd700VK87ij1KUv","_route":"richdocuments.directView.show"}]},{"file":"[PATH_TO_MY_NEXTCLOUD]lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"token":"Qi4p9goYpIeJYpV0oppLQ6T8SLtj1iIHcEDFfmdQ4LPBykhblPd700VK87ij1KUv","_route":"richdocuments.directView.show"}]},{"file":"[PATH_TO_MY_NEXTCLOUD]lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/richdocuments\/direct\/Qi4p9goYpIeJYpV0oppLQ6T8SLtj1iIHcEDFfmdQ4LPBykhblPd700VK87ij1KUv"]},{"file":"[PATH_TO_MY_NEXTCLOUD]index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"[PATH_TO_MY_NEXTCLOUD]apps\/richdocuments\/lib\/TokenManager.php","Line":133,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (iOS) Nextcloud-iOS\/2.22.4","version":"14.0.3.0"}

I assume that the problem may be the user name that is sent, when the iPad App tries to open this file inside the group folder.

Actually, I'm not sure, if this is an error related to the Group folders app. It may also be related to Collabora or the iPad app.

Thanks for having a look.

**Comment by PpaiSanchez** [comment]
Same problem here.

**Comment by dvaerum** [comment]
Can also confirm that this is a problem

**Comment by icewind1991** [comment]
Can you test if https://github.com/nextcloud/server/pull/12708 fixes the problem for you

**Comment by dvaerum** [comment]
> Can you test if [nextcloud/server#12708](https://github.com/nextcloud/server/pull/12708) fixes the problem for you

I have look at it again and it turns out I did a mistake. I have mounted a drive directly into nextcloud's group folder and forgot to add the mount in fstab, so it wasn't mounted after reboot.
I ended up here because of bad error message :sweat_smile: so maybe that need to be improved :smiley:

**Comment by wiswedel** [comment]
I guess this issue can be closed since there hasn't been an update for about a year.
Feel free to re-open if the issue still persists.
