### ISSUE TITLE
Group Admin

### ISSUE THREAD

**Issue by DrEVILish** [nextcloud/groupfolders#221]
As a GroupAdmin/Full Admin I should be able to share my file with a Group I administer without being a member of the Original group.

User - GPAdmin - shares a folder group-wide.
GPAdmin being a member of the group is now visible to all the users in the group and people can share files and folders with this user.
GPAdmin should be a token User for the group to have group-wide shares.

**Comment by icewind1991** [comment]
Closing as duplicate of https://github.com/nextcloud/groupfolders/issues/35

**Comment by DrEVILish** [comment]
This isn't a duplicate issue.
