### ISSUE TITLE
Future of the groupfolders app (Nextcloud 15 and following)

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/groupfolders#224]
It would be nice to know if there is some further development planned for this app by anyone at this moment. There is no sign despite from "rumours" by @RuudschMaHinda giving hope for NC 15.

I know that you focus on the stuff what your customers pay for, which is totally fine. If this app is not actively developed any more, people should know, because there are some bugs or missing features which highly impact the usability of this app in contrast to "regular" shared folders even when taking into account the nice administration of group and user permission for groupfolders here.

Mainly, these open bugs/features (Notifications #112, Trashbin #99, Versioning #50) make me personally think to move back from groupfolders to a special administrative account which creates shared folders for groups.
So I would like to know if anything regarding these issues is planned by anyone, so that I do not unnecessarily uninstall this app and set up shared folders a week before these things are implemented ;)

**Comment by Nils160988** [comment]
Do you have any suggestions how I could easily "migrate" from groupfolders to shared folders without having to resync everything?

**Comment by Nils160988** [comment]
Thank you for your suggestions, It might help some people as well.
It might also be possible to enable single-user mode for the task to ensure, no one is using the instance.

**Comment by icewind1991** [comment]
Versioning and trashbin support for groupfoldes will be released together with NC15 (it was mostly core server limitations that prevented it from working), activity notifications will require future work.

We're currently looking into if we want to make groupfolders part of the "officially" supported product which will hopefully give me some more time to work on it. My time doesn't grow on trees though so everybody is more then welcome to help and send pull requests.

**Comment by icewind1991** [comment]
(versions and trashbin support has been pushed to master a few days ago, so you can test it out in combination with the latest NC15 rc)

**Comment by RuudschMaHinda** [comment]
Your time is very much appreciated. Thank you!

And I think everybody here understands that doing this besides other projects can't be your primary focus right now either. Fingers crossed on this feature making it to core! You deserve to be recompensated for your work.
Thanks again.

**Comment by Nils160988** [comment]
I did not want to criticize you or your work here. I really appreciate the progress made with nextcloud and all the apps. Having groupfolders in core would be awesome.

My only suggestion was to communicate some kind of schedule or when you are planning to have features ready. 

Tested latest master with 15 RC1 and versions and trashbin works, great work!
Thanks a lot!

**Comment by team-a2** [comment]
Are there any news on the status of the development of activity notifications for groupfolders?
Would be great to use the feature soon!
