### ISSUE TITLE
Wrong server name on pictures when sending emails

### ISSUE THREAD

**Issue by lolotiti06** [nextcloud/groupfolders#2248]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have an activity on group foldfers
2.
3.

### Expected behaviour
The user joining some groups receive an email with some pictures. The issue is that pictures link is based on the real server name and not the nextcloud server name. I have my nextcloud behind a WAF. The real server name cannot be reached from the internet.

### Actual behaviour
Pictures have the wrong link.

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Group folders version:**

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by joshtrichards** [comment]
Are you saying this *only* happens with files involve group folders, but non-group folder activities have the correct server/URL?

I presume this isn't limited to groupfolders, so it may be a config matter: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#overwrite-cli-url

If you're still experiencing this, send a screenshot so we know which email.
