### ISSUE TITLE
Access denied when opening files from shared group folder

### ISSUE THREAD

**Issue by klada** [nextcloud/groupfolders#225]
When sharing an entire group folder through the normal user interface (share link) the permissions are broken/not checked correctly. The link is working for displaying the contents, but when opening a file I always get **access denied**.

**Steps to reproduce:**

1. Create a new groupfolder and add a group with sharing permission
2. Swith to the normal user UI, where the group folder now shows up
3. Open the share dialog for the newly created group folder and create a share link with "write permissions".
4. Create a new text file `test.txt` in the group folder
5. Open a different browser/private window and use the share link
6. You can see the test file `test.txt` in the directy listing. Click on the file.
7. You now get **access denied** → this is wrong

When sharing a subfolder from within the group folder the share links are working as expected. This only applies when sharing the entire group folder.

**Versions:**

- Nextcloud 14.0.3
- Groupfolder 1.3.3
- Collabora 3.0.5

**Comment by icewind1991** [comment]
I can't reproduce this issue, opening files from a link-shared groupfolder works as expected

**Comment by klada** [comment]
I think it has to do with Collabora. Did you try it with Collabora enabled?

**Comment by icewind1991** [comment]
Ok, I can confirm this behavior with Collabora
