### ISSUE TITLE
Sharing breaks after some time - oc_filecache at fault

### ISSUE THREAD

**Issue by Thoro** [nextcloud/groupfolders#226]
Hello

we have a issue with sharing group folders, after some time they just break and the Client is unable to open the share, and a FailedStorage error is thrown.

I tracked down the issue to the following, but I'm not sure where to look why it happens:

All the shares with issues, have duplicate entries in the oc_filecache table and the oc_share entry is referencing the wrong oc_filecache entry and therefore it won't work.

I have two storage (oc_storage) paths, where one contains the groupfolders and the other doesn't (1 and 778).

Has anyone experience where to start looking for the issue? It seems that the whole file structure was duplicated based on the db entries.

**Comment by ZeikoFr** [comment]
Hi @Thoro do you still have this issue ? I know it's been 2 years but it might be still relevant

**Comment by fschrempf** [comment]
As there was no more feedback from the author and this is quite old, I will close this as stale. If someone still observes this issue on the latest release, please create a new issue. Thanks!
