### ISSUE TITLE
GF 13.1.1 on 26.0.0.3 beta3: Cannot create a new (standard) TEXT file within a group folder

### ISSUE THREAD

**Issue by nursoda** [nextcloud/groupfolders#2267]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install NC 26 beta3 and Group Folders 13.1.1 (NOT marked compatible with NC26!, so needs to be overridden)
2. Create (a) group folder(s)
3. Create a standard text file in any location outside group folder → works fine
4. Create a standard text file inside a group folder → doesn't work, yields user error notification and writes to nextcloud.log

![20230215_163832](https://user-images.githubusercontent.com/8425483/219077772-5a03d708-8499-4e91-b3cd-c3dfc31dbb8a.png)
![20230215_163928](https://user-images.githubusercontent.com/8425483/219077959-64a3d023-a5ab-4300-be54-1bf4d8f812fc.png)

### Expected behaviour
A new version should work in 26.

### Actual behaviour
* User notification "Could not create file from template" (my back-translation DE→EN)
* OCP\\Files\\NotPermittedException in the log

### Server configuration
**Operating system:** Arch Linux
**Web server:** NGINX
**Database:** MariaDB
**PHP version:** 8.1.5
**Nextcloud version:** 26.0.0.5 (=beta3)
**Group folders version:** 13.1.1
**Updated or fresh install:** fresh install
**Where did you install Nextcloud from:** ZIP
**Are you using external storage:** local
**Are you using encryption:** no
**Are you using an external user-backend:** no

### Client configuration
**Browser:** Firefox 110
**Operating system:** Arch Linux
#### Web server error log
irrelevant

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
  "reqId": "TtqQdTfni9MVjb5fEp3S",
  "level": 3,
  "time": "2023-02-15T15:22:08+01:00",
  "remoteAddr": "192.168.1.2",
  "user": "USER",
  "app": "no app in context",
  "method": "POST",
  "url": "/ocs/v2.php/apps/files/api/v1/templates/create",
  "message": "Could not create path",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0",
  "version": "26.0.0.5",
  "exception": {
    "Exception": "OCP\\Files\\NotPermittedException",
    "Message": "Could not create path",
    "Code": 0,
    "Trace": [
      {
        "file": "/FOLDER/lib/private/Files/Template/TemplateManager.php",
        "line": 162,
        "function": "newFile",
        "class": "OC\\Files\\Node\\Folder",
        "type": "->"
      },
      {
        "file": "/FOLDER/apps/files/lib/Controller/TemplateController.php",
        "line": 57,
        "function": "createFromTemplate",
        "class": "OC\\Files\\Template\\TemplateManager",
        "type": "->"
      },
      {
        "file": "/FOLDER/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 230,
        "function": "create",
        "class": "OCA\\Files\\Controller\\TemplateController",
        "type": "->"
      },
      {
        "file": "/FOLDER/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 137,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/FOLDER/lib/private/AppFramework/App.php",
        "line": 171,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/FOLDER/lib/private/Route/Router.php",
        "line": 298,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/FOLDER/ocs/v1.php",
        "line": 63,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/FOLDER/ocs/v2.php",
        "line": 23,
        "args": [
          "/FOLDER/ocs/v1.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/FOLDER/lib/private/Files/Node/Folder.php",
    "Line": 197,
    "message": "Could not create path",
    "exception": {},
    "CustomMessage": "Could not create path"
  }
}
```
</details>

#### Browser log
irrelevant

**Comment by solracsf** [comment]
Test with Test with https://github.com/nextcloud/groupfolders/releases/tag/v14.0.0

**Comment by nursoda** [comment]
In the affected instance and with the above steps as precondition (a group folder created with 13.1.1 on a NC 26.0.0beta1 instance), just updating to GF 14 does not solve the issue. But creating a new group folder after updating to GF 14 does work as expected. Thus, I assume that if one does not use the unsupported 13.1.1 on NC26 but updates to GF 14 while migrating from NC25 to NC26, this issue should not be triggered at all.
