### ISSUE TITLE
Nextcloud 25 : No more consumed quota view

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/groupfolders#2276]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Make sure your instance version is 25.0.x
2. Make sure that some of your GF aren't empty
3. Go to GF settings
4. See that, instead of before, you cannot see anymore the used quota with a colored block inside the quota size indicator.

### Expected behaviour (everyting fine until Nextcloud 24)
![215473903-01ae3490-7a23-4ee7-bfa2-fc67a415ef4d](https://user-images.githubusercontent.com/33763786/220647508-c27e30b6-018e-4f34-a47f-6882f9c2b958.png)

### Actual behaviour (not displayed anymore since Nextcloud 25)
![215473850-5c37f403-24af-452c-b808-a0a9c98da7bf](https://user-images.githubusercontent.com/33763786/220647533-6042e738-2201-4767-82ac-0d747dd19dc8.png)

### Note : 
I've recently made an PR (#2244) but I'm not very sure that it will fix it.  Anyway, I think this issue has to be solved because knowing how much quota space is used for every GF is important. 

### Server configuration

**Operating system:** Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 10.3.38

**PHP version:** 8.1.15

**Nextcloud version:** 25.0.3 - 25.0.3.2

**Group folders version:** 13.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** from an older version

**Where did you install Nextcloud from:** We installer

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Firefox 110

**Operating system:** Ubuntu 20.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Can be provided if necessary
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Can be provided if necessary
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Can be provided if necessary
```
</details>

**Comment by koelle25** [comment]
I also noticed this. Very annoying.

One thing to add: If you hover with the mouse over it, it displays you the space currently in use:
![2023-03-29_10-40](https://user-images.githubusercontent.com/915514/228477487-88115212-7ecf-41df-bffc-0023d1ef9d62.png)

But it should nevertheless be displayed as before in NC24 I think. It provides a better overview and also Users of Touch devices won't easily, if at all, be able to enable the hover popup.

**Comment by solracsf** [comment]
Closed by https://github.com/nextcloud/groupfolders/pull/2244
