### ISSUE TITLE
Tarball not attached to releases anymore

### ISSUE THREAD

**Issue by ariep** [nextcloud/groupfolders#2278]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

Release 11.1.6 (13 October, 2022) is the last release that included the `groupfolders.tar.gz` asset as part of the release. Releases since then (12.0.3, 13.1.1, 14.0.0) do not have that tarball anymore. I think this is unintentional, as there is still a [part of the github workflow](https://github.com/nextcloud/groupfolders/blob/1f81fdc32e9856ec5e6ff2e8c0c4248b3642e1c3/.github/workflows/appstore-build-publish.yml#L150) that tries to attach it to the release.

This breaks our automated nextcloud deployment system which pulls tarballs of nextcloud apps from github (in order to be able to do version pinning of apps).

**Comment by fschrempf** [comment]
Nowadays the releases are handled in a separate namespace (`nextcloud-releases`). It seems like [over there](https://github.com/nextcloud-releases/groupfolders/releases) the tarballs are still available. See this issue for more information: https://github.com/nextcloud/groupfolders/issues/1765.
