### ISSUE TITLE
Group folder "XYZ" is full, files can no longer be updated or synchronised while Quota is Unlimited

### ISSUE THREAD

**Issue by Galileon-venta** [nextcloud/groupfolders#2291]
After the latest Nextcloud Upgrade (25.0.4) i wrongly get the Message Group folder "XYZ" is full, files can no longer be updated or synchronised for all my Folders while the Quota is set to unlimited.

### Expected behaviour
I should be able to Upload new Files to my Groupfolders.

### Actual behaviour
I am not allowed to Upload new Files.

### Server configuration

**Operating system:** Debian Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0.28

**Nextcloud version:** 25.0.4

**Group folders version:** 13.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 24

**Where did you install Nextcloud from:** Official Homepage

**Are you using external storage, if yes which one:** N/A

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Latest Browsers tested (Opera, Firefox, Chrome Canary)

**Operating system:** Windows 10

**Comment by Galileon-venta** [comment]
A Server Reboot did fix the Issue for about 5 Minutes now... it is actually a problem with the System Drive for the Folder being full; I guess you just rely on the Nextcloud base internal quota functions? Then it's an issue that the reporting on their End is not correct.

**Comment by joshtrichards** [comment]
Correct
