### ISSUE TITLE
Combining groups to give access only to people who need it

### ISSUE THREAD

**Issue by Akhun-Delar** [nextcloud/groupfolders#2295]
It would be nice if it's possible to combine multiple groups, so that if you're in group X + Y, you get access to a folder, but not if you're only in one of them.

For example, you have Finance and HR, but only some of the staff should be given access to the folder shared between the departments.

**Comment by provokateurin** [comment]
Not something we are going to implement in Groupfolders. Please just make a group that contains the relevant people from the other two groups.
