### ISSUE TITLE
Not seeing the permissions pane

### ISSUE THREAD

**Issue by jsfrederick** [nextcloud/groupfolders#23]
Just installed Group folders app on my Nextlcoud 12.0.0.29 instance.  I do not see the permissions pane ( as shown in the Readme file).  When I click on the edit button to edit a group, I don't see the Write and Share check boxes.  What am I missing?  I installed it via the Nextcloud Apps dialog.

**Comment by AceSlash** [comment]
Same issue here, is the github version different from the App one?

**Comment by jsfrederick** [comment]
I just looked in the App store and that version is dated April 26th.  Looks like the current update on Github is dated June 2017.  Must not have made it to the app store yet.

**Comment by icewind1991** [comment]
Version with permissions isn't released yet, hopefully somewhere this week

**Comment by jsfrederick** [comment]
Ok, that sounds good.  How do we upgrade?  Is it a seamless process?  I don't want to lose the folders that I've already built.

Thanks!

**Comment by jsfrederick** [comment]
Notified that a new version of Groupfolders was available today.  Installed it and now I do see the permissions pane.  It all works GREAT.

Thanks!!
