### ISSUE TITLE
[Feature parity] Version naming/deletion

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/groupfolders#2310]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Version naming/deletion was introduced with Nextcloud Hub 4 (v26). See https://github.com/nextcloud/server/pull/35160. But this Feature is disabled if groupfolders app is activated!

**Describe the solution you'd like**
Groupfolders should be extended to feature version naming/deletion, same as on the default nextcloud storage.

**Describe alternatives you've considered**
Disabling groupfolders makes it possible to use version naming/deletion on the default storage, but then you'll loose the groupfolder features.

**Additional context**
n/a

**Comment by AndyXheli** [comment]
Same issue

**Comment by Jerome-Herbinet** [comment]
@artonge are you aware of that ? Is this issue in the right place ; should it be moved to the "server" project ?
... that said is it's really related to the following feature : [#35160](https://github.com/nextcloud/server/pull/35160)

**Comment by artonge** [comment]
Group folder as well as S3 versioning have their own versioning backends, so we need to adapt the feature for those backends. Hence the restriction when those apps are enabled.

Not sure how much work this would require, and this is not planned yet, so if anyone wants to jump on it, fell free :)
