### ISSUE TITLE
Group folders has disapeared since my nextcloud has been upgraded in 26

### ISSUE THREAD

**Issue by aknauss** [nextcloud/groupfolders#2312]
Hi,

Since my Nextcloud has been upgraded to version 26, Group Folders don't work. All my group folders has disapeared.
Nobody can see theses folders, even in admin parameters

Thanks for your help.
Franck

**Comment by aknauss** [comment]
However, in commandline I see them with : php ./occ groupfolders:list

**Comment by koelle25** [comment]
You should look under https://yourcloud/index.php/settings/apps/disabled if it was disabled.

Maybe the groupfolders app isn't yet tested and released for NC26.

Nevertheless, if it is disabled, you can enable it there anyway and check if everything works as before.

That said, you should ALWAYS make sure that all the apps you need are already available for the new NC version before upgrading.

**Comment by aknauss** [comment]
Hi,

App is enable but it doesn't work.
Sorry, I thought that this app work with new version...

Le mer. 29 mars 2023 à 10:38, Kevin Köllmann ***@***.***> a
écrit :

**Comment by aknauss** [comment]
In logs, I have theses errors "Could not boot groupfolders: Class \"OCA\\GroupFolders\\Mount\\MountProvider\" not found""

**Comment by aknauss** [comment]
ok it's works now.
* Firstly I disabled and uninstall app.
Install again and activating app.
Also change opcache.interned_strings_buffer on my php.ini from 8Mb to 16 Mb.
Restart Php-fpm and now it's working perfectly.

**Comment by joshtrichards** [comment]
> However, in commandline I see them with : php ./occ groupfolders:list

If this worked, then it was likely a PHP caching issue. Just restart FPM next time. Should be sufficient.
