### ISSUE TITLE
Enable administrators to add circles to a groupfolder

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/groupfolders#2322]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Users can't administrate groupfolders from a user management perspective.
<img width="923" alt="Circles_Groupfolder" src="https://user-images.githubusercontent.com/1315170/231141650-5d7a98d6-2331-4afd-b7ed-d9696f6372c4.png">

**Describe the solution you'd like**
So groupfolders should allow to not just assign groups to a groupfolder but also circles (which are user maintained). As a first step the just need to be able to be added to a groupfolder, they don't need to be available for the advanced permission section. The goal is to give a circles admin / owner to ability to do the user management for that groupfolder.

* [x] nextcloud/groupfolders#2349
* [x] nextcloud/groupfolders#2350
* [x] nextcloud/groupfolders#2351
* [ ] nextcloud/related_resources#217

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by fschrempf** [comment]
See #34 and #813 for related issues

**Comment by skjnldsv** [comment]
- [ ] Needs `getAllVisibleCircles` https://github.com/nextcloud/groupfolders/blob/135389641520fa03e001d0122758ef9ff75c6eab/lib/Controller/DelegationController.php#L54-L74
