### ISSUE TITLE
List groupfolders in the left sidebar menu

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/groupfolders#2323]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It is hard to get a complete overview of all group-folders

**Describe the solution you'd like**
Provide an easy way to list all group-folders a user has access to. 
* "flat" like "Favorites" with a single menu item listing all groupfolders or
* see https://github.com/nextcloud/groupfolders/issues/2323#issuecomment-1503513223 - Directly below "Shares"

<img width="407" alt="2023-04-11 15_19_51-Shares - Nextcloud – Mozilla Firefox" src="https://user-images.githubusercontent.com/1315170/231177350-01b018a6-c267-4e61-adb6-4db528598c41.png">

whatever is easier to do.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by AndyScherzinger** [comment]
@jancborchardt any particular position in the left sidebar for the groupfolders menu item(s)

**Comment by jancborchardt** [comment]
> Either "flat" like "Favorites" with a single menu item listing all groupfolders or

From a design point this would be best, as there is no other instance where we list actual folders in the left navigation.

> @jancborchardt any particular position in the left sidebar for the groupfolders menu item(s)

Directly below "Shares" as they are related. :)

**Comment by AndyScherzinger** [comment]
![20230418_110803](https://user-images.githubusercontent.com/1315170/232994844-d49126ac-4f98-4c65-adfb-65e569cf4dbb.png)

@jancborchardt this is how the mobile app will (kind of) display it according to @tobiasKaminsky.
So basically listing all group-folders and their location. Should we also do it like that or simply sow the folders? Having in mind that multi-line items are not accessible in a table I tend to say let's just display the folders, single line, just the name no additional location info. What do you think?

Info needed for @skjnldsv to implement the actual listing part.

**Comment by jancborchardt** [comment]
On mobile we should do it with the subline since it’s a very nice indicator and it’s not an accessibility issue there (as it’s not a table).
On web it’s ok if it has no subline to work with accessibility requirements. :)

**Comment by skjnldsv** [comment]
> On web it’s ok if it has no subline to work with accessibility requirements – also it’s fine because e.g. favorites has no subline either. :)

if you want I can add a column to display the location of the groupfolder :)

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/233097284-8ad46f96-cfe8-4740-8523-12dd6f56d479.png)

**Comment by AndyScherzinger** [comment]
I'd leave it out for now since the same could then also be seen as applicable to favorites view, so I would keep it consistent with that one.

**Comment by jancborchardt** [comment]
Would agree with @AndyScherzinger to keep it out – instead it would be better to keep it consistent with others and show modified date in that column. :)

**Comment by AndyScherzinger** [comment]
Any Screenshots to prevent last minute polishing so Jan and Nimisha can take a look?
@skjnldsv

**Comment by skjnldsv** [comment]
Same thing as above without the extra column :)
