### ISSUE TITLE
scaling issue when creating many groupfolders ?

### ISSUE THREAD

**Issue by landryb** [nextcloud/groupfolders#233]
For a specific usecase testing i'm creating 3k groupfolders via the API, assigning access to the same group. Ie more or less in a for loop in python code using requests module:

```
curl  -XPOST -H "OCS-APIREQUEST: true" -u admin https://xxx/apps/groupfolders/folders -dmountpoint=dirX
curl  -XPOST -H "OCS-APIREQUEST: true" -u admin https://xxx/apps/groupfolders/folders/$newgroupfolderid/groups -dgroup=groupA
```
what's interesting is that at the beginning of my loop (when, say, 500 folders were already created) the time spent on each request was around 0.9s, while after 1800 folders were created (and still running) the same requests take between 2.5 and 3s, after 2000 folders between 3 and 3.3s..

To me, it should be constant-time...

My guess is that *something* depends on the amount of existing groupfolders, maybe rescanning `$datadir/__groupfolders/` at each operation ? Will do the same test by creating 3k subfolders in a regular folder.. and have a look at the code to figure out where the bottleneck can be.

i dunno if that's to be expected, if that many folders is beyond what anyone tested, or if things can be improved, but that's a bit worrying.

**Comment by landryb** [comment]
This scaling issue affects any subsequent API call/folder/file creation/deletion.

If i have 4 groupfolders, creating 200 subfolders in a shared folder (or in a regular user folder) takes 20s, deleting them takes 30s.

If i create 500 groupfolders, creating the first groupfolders take 0.4s, creating the 500th groupfolder takes 0.8s.

Now that i have 504 groupfolders, creating 200 subfolders in a single groupfolder  (or in a regular user folder)  took 180s, deleting them took 190s. This is not acceptable performance-wise...

**Comment by mhincapie** [comment]
Thank you for this post. We are having the same issue. @landryb did you ever find a solution or any response?

**Comment by landryb** [comment]
i changed my way of doing things and only use 3 groupfolders, in which i create 500 dirs that i share to groups.
