### ISSUE TITLE
Extended permission entries not readable in light theme

### ISSUE THREAD

**Issue by koelle25** [nextcloud/groupfolders#2331]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Switch to light theme (if not already enabled)
2. Open the Groupfolder admin settings
3. See that entries in the extended permissions field are not readable

### Expected behaviour
Entries in the extended permissions field(s) should be readable. The following is a screenshot of the dark theme where it looks good:
![2023-04-14_10-58](https://user-images.githubusercontent.com/915514/231998450-aa22f7e3-daed-4d76-89b9-7bdae11ad757.png)

### Actual behaviour
Entries are not readable as the text color seems to be (almost) the same as the background color. See this screenshot:
![2023-04-14_10-59](https://user-images.githubusercontent.com/915514/231998610-8e164af9-7e60-451d-a3f3-8e5646112f5b.png)

### Server configuration

**Nextcloud version:** 25.0.5

**Group folders version:** 13.1.2

### Client configuration
**Browser:** Firefox 112.0

**Operating system:** Linux Mint 21

**Comment by XueSheng-GIT** [comment]
This seems to be fixed on NC 27.0.1 and groupfolders 15.0.1.

**Comment by fschrempf** [comment]
Fixed in https://github.com/nextcloud/groupfolders/pull/2335.
