### ISSUE TITLE
Some strings not passed to transifex for translation

### ISSUE THREAD

**Issue by solracsf** [nextcloud/groupfolders#2372]
See screenshot:
![image](https://user-images.githubusercontent.com/12234510/236679898-619483b6-18ea-4ff1-90e2-61190749729f.png)

Altough some of them exist, see:
https://github.com/nextcloud/groupfolders/blob/1c4acdb0545655551865b5b829916836156051e9/src/settings/App.tsx#L405
or
https://github.com/nextcloud/groupfolders/blob/1c4acdb0545655551865b5b829916836156051e9/src/settings/QuotaSelect.tsx#L100

**Comment by provokateurin** [comment]
Fixed in https://github.com/nextcloud/groupfolders/pull/3191
