### ISSUE TITLE
Icon disobeys theming

### ISSUE THREAD

**Issue by megaxlr** [nextcloud/groupfolders#24]
![image](https://user-images.githubusercontent.com/8215278/27626737-715a4d72-5be9-11e7-8f31-a3af45942689.png)
Example 1. A group folder used in Example 2.

![image](https://user-images.githubusercontent.com/8215278/27626822-c35090e6-5be9-11e7-9e42-0c9201524ff2.png)
Example 2. A default shared folder and a group folder. Observe how the color differs between the two

Group folder icon disobeys Nextcloud color support as seen in Example 1. 

version: `1.0.2`

Steps to reproduce: 
1. Set the main color to something (Distinctly) different from the default and wait for it to apply. (Black in example images).
2. Create a group folder.
3. Go back to Files view.
4. Observe how Group folder icon is still in the default blue. 

Expected result: 
Group folder icon should change based on the theme color. (Black in example 2.)

Actual result: 
Group folder does not apply the theme color. 

Related to #11?

**Comment by icewind1991** [comment]
This is already fixed in master as noted in #11
