### ISSUE TITLE
Groupfolder items should point into the files app

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/groupfolders#2402]
not navigate deeper into a groupfolder - list is considered "flat"

i.e.
<img width="475" alt="2023-05-23 14_40_30-Files - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/groupfolders/assets/1315170/f3896f5f-dcaa-4b8a-94e4-66245bd98464">

it points to:
```
https://your.cloud/apps/files/groupfolders?dir=/Project%20Saphire
```
while it should point to:
```
https://your.cloud/index.php/apps/files?dir=/Project%20Saphire
```

So the view only servers as a "link list" into the files app to then enable a user to interact with the groupfolder and its content.

**Comment by maximelehericy** [comment]
how will this behave with nested groupfolders ?

**Comment by AndyScherzinger** [comment]
@skjnldsv can you answer that question of Maxime?

**Comment by skjnldsv** [comment]
> how will this behave with nested groupfolders ?

Groupfolders within Groupfolders?
If so we list them all next to each others I think, so it doesn't change much.

**Comment by maximelehericy** [comment]
Indeed, this is the behavior on t-p.nc.c
@skjnldsv do you think it would be feasible to display:
- either nested groupfolders (GF1 and GF2, and under GF1 you would find GF1.1, GF1.2...)
- either the whole mount point GF1, GF1/GF1.1, GF1/GF1/GF1.2 ...

?

**Comment by maximelehericy** [comment]
BTW, its great to see this entry appearing, some of my customers will be very happy about that !!!
