### ISSUE TITLE
switch between naming modes, for a physical folder

### ISSUE THREAD

**Issue by dem36rus** [nextcloud/groupfolders#2410]
Hello,

Tell me if there is an opportunity to somehow add switching between naming modes 

as they wrote in this topic #108

it may be useful for many this option, I use “CIFS” for maindir and “OCC scan:file”. for interacting with files, webdav is not suitable for my tasks, because the problem is related to large files. the numbers in the name are inconvenient and bad, I am ready to donate funds to patreon to the person who will fix it, "Folder Id" +..+"Name" will completely satisfy my needs, I'm ready for performance degradation by clicking this switch. can also add a OCC command to match the real name
Help me, and thank you if you respond.

**Comment by provokateurin** [comment]
Not possible as already explained in https://github.com/nextcloud/groupfolders/issues/108#issuecomment-442119858
