### ISSUE TITLE
Group folder naming convention change from "__groupfolders/[1]" to "__groupfolders/[group folder name]"

### ISSUE THREAD

**Issue by sunnyd24** [nextcloud/groupfolders#2430]
At the moment all group folders are created under:
`$CONFIG["datadirectory"]/__groupfolders/[index-number]/sub-folder-name/file-name`

but expect to see:
`$CONFIG["datadirectory"]/__groupfolders/[group-folder-name]/sub-folder-name/file-name`

Here is my data directory config:
`--env NEXTCLOUD_DATADIR="/mnt/nc_data"`

Ubuntu mount of Windows Samba Share:
`//192.168.1.50/H/NextCloud_Data /mnt/nc_data cifs rw,mfsymlinks,seal,credentials=/etc/storage-credentials,uid=33,gid=0,file_mode=0770,dir_mode=0770 0 0`

**It would like to request a feature to show the **"group folder name"** instead of the **"group folder index number"**.**

Let me give an example. This is the current state for different group folders:

```
__groupfolders/
├── 1
│   └── America
│       └── abc.jpg
├── 2
│   └── America
│       └── def.mp4
└── 3
│   └── Appointments
│       └── ghi.pdf
```

The following arrangement would be so much better for easy identification of group folders using a file explorer (for example in windows where data directory is linked to a separate hard drive):

```
__groupfolders/
├── Home Photos
│   └── America
│       └── abc.jpg
├── Home Videos
│   └── America
│       └── def.mp4
└── Health
│   └── Appointments
│       └── ghi.pdf
```

Currently, I cannot see the difference between **group folder index 1 and 2** as they have the same sub-folder **"America"**, so having the **"index number folder"** labelled as the **"group folder name"**, then I could see the difference between the **"Home Photos"** and **"Home Videos"**, see above for suggested naming convention update for solution.

I don't believe there is an alternative to this issue as I have no way to amend the nextcloud data directory mapping for group folder from a **"index number"** to chosen **"group folder name"**.

**Comment by fschrempf** [comment]
I don't think browsing the raw filesystem is something that is considered as a valid use-case in NC development. Therefore I think this is out of scope. If anyone thinks differently, please let me know.

> I don't believe there is an alternative to this issue as I have no way to amend the nextcloud data directory mapping for group folder from a "index number" to chosen "group folder name".

You should be able to use the REST API or the WebDAV API to find out which mountpoint is mapped to each ID. See https://github.com/nextcloud/groupfolders#apis.
