### ISSUE TITLE
scan does not update web view

### ISSUE THREAD

**Issue by ste101** [nextcloud/groupfolders#2431]
`groupfolders:scan 1 -v` shows the file copied via cronjob but the file list does not get updated if reloading the browser.
It works with `files:scan` in normal folders.

Nextcloud 26.0.2.1
PHP 8.2.6

**Comment by ste101** [comment]
Still not working in 27.0.2

**Comment by ste101** [comment]
Still not working in 27.1.3

**Comment by ste101** [comment]
Also not working in 16.0.6

**Comment by joshtrichards** [comment]
I can't reproduce this nor have we had any similar reports. 

It works for me both in the parent and in sub-folders. Please provide more details about your setup if you're still experiencing this.
