### ISSUE TITLE
500 error  Argument 5 passed to OCA\GroupFolders\Mount\MountProvider::getMount() must implement interface OCP\Files\Cache\ICacheEntry, null given

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/groupfolders#244]
I get this error when I try to log in as a user that has a groupfolder shared to him:

Type: TypeError
Code: 0
Message: Argument 5 passed to OCA\GroupFolders\Mount\MountProvider::getMount() must implement interface OCP\Files\Cache\ICacheEntry, null given, called in /nas1/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php on line 63
File: /nas1/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php
Line: 67

Trace
#0 /nas1/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php(63): OCA\GroupFolders\Mount\MountProvider->getMount(7, '/guy/files/Guyt...', 31, -3, NULL, Object(OC\Files\Storage\StorageFactory))
#1 [internal function]: OCA\GroupFolders\Mount\MountProvider->OCA\GroupFolders\Mount\{closure}(Array)
#2 /nas1/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php(64): array_map(Object(Closure), Array)
#3 /nas1/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php(103): OCA\GroupFolders\Mount\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
#4 /nas1/www/nextcloud/lib/private/Files/Filesystem.php(446): OC\Files\Config\MountProviderCollection->addMountForUser(Object(OC\User\User), Object(OC\Files\Mount\Manager))
#5 /nas1/www/nextcloud/lib/private/Files/Filesystem.php(375): OC\Files\Filesystem::initMountPoints('guy')
#6 /nas1/www/nextcloud/lib/private/legacy/util.php(307): OC\Files\Filesystem::init('guy', '/guy/files')
#7 /nas1/www/nextcloud/lib/base.php(986): OC_Util::setupFS()
#8 /nas1/www/nextcloud/index.php(42): OC::handleRequest()
#9 {main}

Groupfolders 2.0.0, Nextcloud 14.0.4.2 on Ubuntu 18.04 (PHP 7.2), Postgres Database

**Comment by gvansanden** [comment]
Manual downgrade to 1.3.3 fixes all issues.
The share I had created before installing 2.0.0 was also not affected

**Comment by icewind1991** [comment]
This should be fixed with the just released 2.0.1
