### ISSUE TITLE
"CustomMessage":"Could not boot groupfolders: Class \"OCA\\GroupFolders\\Mount\\MountProvider\" not found

### ISSUE THREAD

**Issue by pchevali** [nextcloud/groupfolders#2441]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. From Version 26.0.2, Upgrade to version 27.0.0
2. Upgrade Apps
3. Try to use group folders as with version 26

### Expected behaviour
The group folders should appear in files and in configuration of group folders

### Actual behaviour
The group folders don't appear although they are still on the disk and were there before

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 27.0.0

**Group folders version:**15.0.0

**Updated from an older Nextcloud**

**Where did you install Nextcloud from: **Docker

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox

**Operating system:** Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"1ehDrrdAcnbXtBic5zIm","level":4,"time":"2023-06-23T14:29:09+00:00","remoteAddr":"192.168.128.1","user":"admin","app":"no app in context","method":"GET","url":"/apps/logreader/poll?lastReqId=xR2oSvNRCLVL5vcusYTC","message":"Could not boot groupfolders: Class \"OCA\\GroupFolders\\Mount\\MountProvider\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0","version":"27.0.0.8","exception":{"Exception":"Error","Message":"Class \"OCA\\GroupFolders\\Mount\\MountProvider\" not found","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":171,"function":"OCA\\GroupFolders\\AppInfo\\{closure}","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php","line":122,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":138,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCA\\GroupFolders\\Mount\\MountProvider"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":488,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\GroupFolders\\Mount\\MountProvider"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":466,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\GroupFolders\\Mount\\MountProvider"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":65,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\GroupFolders\\Mount\\MountProvider"]},{"file":"/var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php","line":225,"function":"get","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\GroupFolders\\Mount\\MountProvider"]},{"file":"/var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php","line":215,"function":"getMountProvider","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":45,"function":"OCA\\GroupFolders\\AppInfo\\{closure}","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php","line":50,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->","args":[["Closure"]]},{"file":"/var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php","line":214,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->","args":[["Closure"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\GroupFolders\\AppInfo\\Application","type":"->","args":[["OC\\AppFramework\\Bootstrap\\BootContext"]]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":437,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["groupfolders"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->","args":["groupfolders"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":126,"function":"loadApps","class":"OC\\App\\AppManager","type":"->","args":[["dav"]]},{"file":"/var/www/html/apps/dav/lib/AppInfo/Application.php","line":209,"function":"loadApps","class":"OC_App","type":"::","args":[["dav"]]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\DAV\\AppInfo\\Application","type":"->","args":[["OC\\AppFramework\\Bootstrap\\BootContext"]]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":437,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":["dav"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":216,"function":"loadApp","class":"OC\\App\\AppManager","type":"->","args":["dav"]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":126,"function":"loadApps","class":"OC\\App\\AppManager","type":"->","args":[[]]},{"file":"/var/www/html/lib/base.php","line":1044,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php","Line":101,"message":"Could not boot groupfolders: Class \"OCA\\GroupFolders\\Mount\\MountProvider\" not found","exception":[],"CustomMessage":"Could not boot groupfolders: Class \"OCA\\GroupFolders\\Mount\\MountProvider\" not found"},"id":"6495ac357679f"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by joshtrichards** [comment]
Try restarting your web (and, if applicable, fpm) container(s).

How did you upgrade? Did you upgrade the container image then restart the container or do a web-based update/upgrade?

**Comment by joshtrichards** [comment]
Closing as stale and a likely duplicate of #2302 (and others). See my prior comment to fix yourself. It's not really an app-level issue, but a known issue with app management in `server`.
