### ISSUE TITLE
Recurrent DB requests and high load of mariadb cpu consumption since NC27

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/groupfolders#2445]
### Steps to reproduce
1. Set up NC27 with groupfolders apps and some folders in it
2. Observe the process list of the DB server
3. See a lot of requests concerning oc_group_folders and oc_group_folders_groups tables

### Expected behaviour
Database CPU load should be "normal"

### Actual behaviour
High load of CPU on the database server and the mariadb process list shows recurrent database requests on oc_groupfolder tables :

![image](https://github.com/nextcloud/groupfolders/assets/6248852/be9f8c4d-8520-4098-949c-818c72880e42)

CPU is >300% and nextcloud UI is slow.
Server was updated to 27.0.0 two days ago. 

### Server configuration

**Operating system:**
Debian 11

**Web server:**
Apache 2.4.56

**Database:**
mariadb  Ver 15.1 Distrib 10.5.19-MariaDB

**PHP version:**
8.2

**Nextcloud version:** (see Nextcloud admin page)
27.0.0

**Group folders version:**
15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
upgrade from stable channel

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
LDAP (Active Directory)

### Client configuration
**Browser:**
Firefox 102.11

**Operating system:**
Debian 11 / Xfce

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no relevant log here.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no relevant log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
not relevant as it's a server side problem
```
</details>

**Comment by ArtificialOwl** [comment]
This should already lighten the request, if you are willing to patch your Circles app to test https://github.com/nextcloud/circles/pull/1324

**Comment by provokateurin** [comment]
@Mer0me can you check if this problem still persists? If so please re-open the issue.

**Comment by Mer0me** [comment]
> @Mer0me can you check if this problem still persists? If so please re-open the issue.

I'm not using group folders app anymore.
