### ISSUE TITLE
Internal Server Error after upgrade Groupfolders to 2.0.0

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/groupfolders#245]
Nextcloud server 14.0.4.2
Ubuntu 16.04.5
php 7.0.32
Apache 2.4.18
PostgreSQL 9.5.14
Groupfolders 2.0.0

sudo -u www-data php occ app:disable groupfolders
PHP Fatal error:  Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /var/www/html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 37

**Comment by JanUrlaub** [comment]
Please check #240

**Comment by lvarnava** [comment]
Many thanks!
Error fixed after update to 2.0.1
