### ISSUE TITLE
groupfolders 2.0.1 breaks "logging" view of Admin NC Web GUI and maybe more

### ISSUE THREAD

**Issue by TP75** [nextcloud/groupfolders#246]
@icewind1991

Unfortunately, the closing of #240 may be premature and there seems to be a continuing issue with **groupfolders 2.0.1** apparently:

see [migration of NC from 13.0.7 to 14.0.4.2 grabs group folders 2.0.1 but results in a frozen and defunct protocol window](https://github.com/nextcloud/groupfolders/issues/240#issuecomment-446280638) ...

**Comment by john-2000** [comment]
Yes I am seeing the same, it breaks nextclouds news-updater process.

PHP Fatal error:  Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 37....

After deinstalling groupfolders 2.0.1 the error was eliminate

**Comment by TP75** [comment]
also see [TypeError: Upgrading to groupfolders 2.0.0+ breaks FTS #417](https://github.com/nextcloud/fulltextsearch/issues/417#issue-389800742)

**Comment by icewind1991** [comment]
@TP75 what do you mean by "protocol window"?

Additionally, can you try enabling [debug mode](https://docs.nextcloud.com/server/14/developer_manual/general/debugging.html#debug-mode) and see if that gives a stacktrace

**Comment by TP75** [comment]
@icewind1991
> @TP75 what do you mean by "protocol window"?

The "[logging](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/logging_configuration.html)" view of the Admin page of the Nextcloud Web GUI.  One may have guessed this from the "Level | App | Message | Time" header text mentioned in the original [#240](https://github.com/nextcloud/groupfolders/issues/240#issuecomment-446280638) comment.

My apologies.  Obviously, I used a misleading word as false friend to "Protokollierung" in the German (DE) GUI translation.

**Comment by TP75** [comment]
I am a little confused and maybe I missed something.

I set `debug` to `true` in `/config/config.php` to enable debugging:
```
<?php
$CONFIG = array (
    'debug' => true,
    ... configuration goes here ...
);
```
Several activities after the reboot of the VM happend as follows:

1. setting maintenance on and off
1. `systemctl reload apache2`
1. download and enable groupfolders 2.0.1 from NC Web GUI
1. logging in and out from different browsers with both admin and user accounts
1. establishing two group folders and managing `| Group | Write | Share | Delete |`  parameters from NC Web GUI
1. making and deleting different subfolders and files from NC Web GUI
1. unsetting and setting all boxes in the "logging" view from NC Web GUI
1. make a failed login
1. browsed around NC GUI views as admin and user by different browsers

There is a new folder tree available in the nextcloud data like:
`drwxr-x---  4 www-data www-data     4096 Dez 12 18:05 __groupfolders`

The group folders i.e. the subfolders and files below `__groupfolders` are accessible via the NC Web GUI acc to the set of group parameters.

The listing i.e. `ls -l` of the log file gives: 
`-rw-r-----  1 www-data www-data     2459 Dez 12 18:22 nextcloud.log`

The log file shows it's content (with artificial header line and the IP addresses sanitised) as:
```
### nextcloud.log - NC version '14.0.4.2' - 2018-12-12 17:54 - debugging starts here ###

{"reqId":"HitOXJZA1SIe1KMKAwtd","level":3,"time":"2018-12-12T17:17:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Interface 'OCA\\Files_Versions\\Versions\\IVersionBackend' not found at \/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Versions\/VersionsBackend.php#37","userAgent":"--","version":"14.0.4.2"}
{"reqId":"WOiaXzk5segJPZvWRiq9","level":2,"time":"2018-12-12T17:19:15+00:00","remoteAddr":"ip.ip.ip.ip","user":"--","app":"core","method":"POST","url":"\/index.php\/login","message":"Login failed: 'admin' (Remote IP: 'ip.ip.ip.ip')","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"14.0.4.2"}
{"reqId":"gACs43EDRSA7LPvHT5Ik","level":3,"time":"2018-12-12T17:22:53+00:00","remoteAddr":"ip.ip.ip.ip","user":"admin","app":"index","method":"GET","url":"\/favicon.ico","message":{"Exception":"Exception","Message":"The requested uri(\/favicon.ico) cannot be processed by the script '\/nextcloud\/index.php')","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":930,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Request.php","Line":742,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"14.0.4.2"}
{"reqId":"UfJwCquPnqba7uQibEbp","level":3,"time":"2018-12-12T17:22:53+00:00","remoteAddr":"ip.ip.ip.ip","user":"admin","app":"index","method":"GET","url":"\/favicon.ico","message":{"Exception":"Exception","Message":"The requested uri(\/favicon.ico) cannot be processed by the script '\/nextcloud\/index.php')","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":930,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Request.php","Line":742,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"14.0.4.2"}
```

Besides the a.m. explicit settings of all log levels in the pop-up of the "logging" view of the NC Web GUI the _config.php_ configuration file seems to be unchanged and reads:
```
<?php
$CONFIG = array (
  'debug' => true,
 ... configuration goes here ...
  'loglevel' => 2,
 ... configuration goes here ...
```
The listing i.e. `ls -l` of the configuration file gives: 
`-rw-r-----  1 www-data www-data  1183 Dez 12 18:01 config.php`

However, the log file _nextcloud.log_ remains empty otherwise and not any activites are listed in the "activities" view of the NC Web GUI. I would presume that e.g. _login_ and _log-out_ activities should be logged. I cannot eliminate any misunderstandings but would call the logging and "logging" view broken until further advice.

**Comment by uweplonus** [comment]
Still the same error as in #240. For me the error occurs during a cron run.

**Comment by TP75** [comment]
NC14 [groupfolders](https://github.com/nextcloud/groupfolders)

  * [Docs](https://docs.nextcloud.com/server/14/admin_manual/contents.html) » [Server configuration]() » [Logging configuration](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/logging_configuration.html#logging-configuration)
  * [Docs](https://docs.nextcloud.com/server/14/developer_manual/index.html) » [General contributor guidelines](https://docs.nextcloud.com/server/14/developer_manual/general/index.html) » [Debugging](https://docs.nextcloud.com/server/14/developer_manual/general/debugging.html#debug-mode)

Please be aware we will be going invasive again...

@icewind1991
> Please try with [e5a4e01](https://github.com/nextcloud/groupfolders/commit/e5a4e010b5deaf33795b4ede6fb4aac02caca592)

Thank you and I will give it a try.

[GitHub help: Which remote URL should I use?](https://help.github.com/articles/which-remote-url-should-i-use/)

We see the seven characters from the SHA (the unique identifier) of the a.m. commit given as `e5a4e01`

The resp. full SHA is: `e5a4e010b5deaf33795b4ede6fb4aac02caca592`

To revisit the commit from outside the GitHub domain and/or to download a ZIP archive of the specific commit via an internet browser from the GitHub button "clone or download" pop-up view one should use the resp. URL as:
https://github.com/nextcloud/groupfolders/tree/e5a4e010b5deaf33795b4ede6fb4aac02caca592

Proposedly, one could use the [GNU Wget](https://wiki.debian.org/wget) tool on the [command line interface (CLI)](https://wiki.debian.org/CommandLine) to download the archive from GitHub like:
```
$ wget -q https://github.com/nextcloud/groupfolders/archive/e5a4e010b5deaf33795b4ede6fb4aac02caca592.zip -O groupfolders_e5a4e01.zip
```

However, the able [NC 14 developer](https://docs.nextcloud.com/server/14/developer_manual/general/devenv.html) would use a version of [Git](https://wiki.debian.org/UsingGit) to [checkout](https://git-scm.com/docs/git-checkout) the specific commit into the preferred local [clone](https://git-scm.com/docs/git-clone) of the a.m. repository with steps like:
```
$ git clone https://github.com/nextcloud/groupfolders.git

$ git checkout e5a4e010b5deaf33795b4ede6fb4aac02caca592
```

The current task would be to make a backup copy of the current `apps/groupfolders` contents before the tries.  To look further into the [groupfolders](https://github.com/nextcloud/groupfolders) issue one has to copy [e5a4e01](https://github.com/nextcloud/groupfolders/commit/e5a4e010b5deaf33795b4ede6fb4aac02caca592) into the `apps/groupfolders` folder.

I will make the appropriate changes to the now experimental NC 14 instance and seek to come back later with any findings of my tries.

**Comment by TP75** [comment]
Lots of entries in the logging.  This should be filtere somehow, I presume.  What should I look for in the log file?
NC mail was tested and is working but no `PHP Stack trace` email received.

There was an announcement of the available **groupfolders 2.0.2** and I did the update.

Afterwards I got the b.m. _info_ message (besides many _debug_ messages) in the logging:
``` 
GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 10148 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 150:

    GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\H ... l}, { errno: 28, ... 0})

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 103:

    GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php - line 43:

    GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\H ... {}, GuzzleHttp\H ... l}, GuzzleHttp\H ... {})

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 28:

    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensiti ... *", "*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 51:

    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php - line 37:

    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 30:

    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 70:

    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 59:

    GuzzleHttp\RedirectMiddleware->__invoke("*** sensiti ... *", "*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php - line 67:

    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 277:

    GuzzleHttp\HandlerStack->__invoke("*** sensiti ... *", "*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125:

    GuzzleHttp\Client->transfer("*** sensiti ... *", "*** sensiti ... *")

    /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131:

    GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, { verify: "/ ... }})

    /var/www/nextcloud/lib/private/Http/Client/Client.php - line 161:

    GuzzleHttp\Client->request("get", "https://app ... n", { verify: "/ ... e})

    /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 106:

    OC\Http\Client\Client->get("https://app ... n", { timeout: 1 ... }})

    /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 170:

    OC\App\AppStore\Fetcher\Fetcher->fetch("\"2018-08-2 ... "", "[{\"id\":\" ... ]")

    /var/www/nextcloud/settings/Controller/AppSettingsController.php - line 191:

    OC\App\AppStore\Fetcher\Fetcher->get()

    /var/www/nextcloud/settings/Controller/AppSettingsController.php - line 184:

    OC\Settings\Controller\AppSettingsController->getAllCategories()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OC\Settings\Controller\AppSettingsController->listCategories()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "listCategories")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 118:

    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "listCategories")

    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OC\\Setting ... r", "listCategories", OC\AppFramew ... {}, { _route: "s ... "})

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})

    /var/www/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "s ... "})

    /var/www/nextcloud/lib/base.php - line 987:

    OC\Route\Router->match("/settings/apps/categories")

    /var/www/nextcloud/index.php - line 42:

    OC::handleRequest()
```

@icewind1991  Thanks for the effort.  What are we looking for now?

**Comment by huste** [comment]
I am getting the error message from nextcloud's cron.php
PHP Fatal error:  Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /home/huste/ncl/apps/groupfolders/lib/Versions/VersionsBackend.php on line 37

**Comment by TP75** [comment]
After updating to **groupfolders 2.0.2** my findings are the following.

1. the "logging" view is responsive again
1. checking the `nextcloud.log` log file via the command line showed the below entries filtered by [error levels](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/logging_configuration.html) i.e. `"level":0 .. 4` tags and only after the timestamp of the update:

- _debug_ - `"level":0` - tons of debug messages
- _info_ - `"level":1` - just the one `GuzzleHttp\Exception\ConnectException: cURL error 28` of the a.m. info message
- _warn_ - `"level":2` - none
- _error_ - `"level":3` - none
- _fatal_ - `"level":4` - none

The _info_ message can be called an outside context problem:
> [[Solved] GuzzleHttp Exception when I try to see my Apps](https://help.nextcloud.com/t/solved-guzzlehttp-exception-when-i-try-to-see-my-apps/23218/2)
Our appstore at apps.nextcloud.com encountered some issues, those have been fixed now and such errors should not appear anymore. 

Besides the debug messages (maybe good stuff for developers but mostly irrelevant to the admin) there is **no error left** relevant after updating to **groupfolders 2.0.2**, I would conclude.

---

N.B.
The a.m. filtering via the [command line](https://wiki.debian.org/CommandLine) could use [Grep](https://help.ubuntu.com/community/grep) commands like:

- counting all _debug_ messages i.e. all message lines with the `"level":0` tag
```
$ grep -F '"level":0' -c nextcloud.log
```
- listing the message lines with the `"level":1` tag i.e. the _info_ messages
```
$ grep -F '"level":1' nextcloud.log
```
The option `-F` could be called redundant in this specific example but ensures searching for just the given string and avoids a search for a [regular expression](https://wiki.ubuntuusers.de/grep/) instead.

---

Good to know _one can seemlessly update an app even after a patch_. However, I certainly agree with @pgassmann https://github.com/nextcloud/groupfolders/issues/247#issuecomment-447685251 and would hope for general improvements accordingly.

Nevertheless I would like to thank @icewind1991 for the timely support and advice. I highly appreciate the efforts and time put into a free and open source app like _Group folders_ in collaboration between mainly @icewind1991 and the other contributors.

Problem solved and issue closed.

**Comment by huste** [comment]
Thanks for this fix, the errors on my installation seem gone with 2.0.2
