### ISSUE TITLE
Repeated errors in cron regarding missing interface IVersionBackend

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/groupfolders#247]
### Steps to reproduce
Let the NC instance run for some time and wait for cron to get called.

### Expected behaviour
No errors are generated.

### Actual behaviour
From time to time, this error is sent via email to me:

```PHP Fatal error:  Interface 'OCA\Files_Versions\Versions\IVersionBackend' not found in /srv/http/nextcloud/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 37
PHP Stack trace:
PHP   1. {main}() /srv/http/nextcloud/nextcloud/cron.php:0
PHP   2. OC\BackgroundJob\JobList->getNext() /srv/http/nextcloud/nextcloud/cron.php:117
PHP   3. OC\BackgroundJob\JobList->buildJob() /srv/http/nextcloud/nextcloud/lib/private/BackgroundJob/JobList.php:213
PHP   4. OC\Server->query() /srv/http/nextcloud/nextcloud/lib/private/BackgroundJob/JobList.php:265
PHP   5. OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback() /srv/http/nextcloud/nextcloud/lib/private/ServerContainer.php:116
PHP   6. OC\AppFramework\DependencyInjection\DIContainer->query() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php:453
PHP   7. OC\AppFramework\DependencyInjection\DIContainer->resolve() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:119
PHP   8. OC\AppFramework\DependencyInjection\DIContainer->buildClass() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:98
PHP   9. OC\AppFramework\DependencyInjection\DIContainer->query() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:68
PHP  10. OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php:424
PHP  11. OC\AppFramework\DependencyInjection\DIContainer->query() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php:453
PHP  12. OC\AppFramework\DependencyInjection\DIContainer->resolve() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:119
PHP  13. OC\AppFramework\DependencyInjection\DIContainer->buildClass() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:98
PHP  14. ReflectionParameter->getClass() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:58
PHP  15. spl_autoload_call() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:58
PHP  16. Composer\Autoload\ClassLoader->loadClass() /srv/http/nextcloud/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php:58
PHP  17. Composer\Autoload\includeFile() /srv/http/nextcloud/nextcloud/lib/composer/composer/ClassLoader.php:322
PHP  18. include() /srv/http/nextcloud/nextcloud/lib/composer/composer/ClassLoader.php:444
```

At least it seems NC to be still working, but I cannot verify this exactly.

### Further remarks
This seems to be related to #240, #241, #245, and #246.

Unfortunately, the behaviour is not deterministic. I get mails from PHP complaining about not finding the interfaces at various different points in time every 1-2 days now. 

## Server configuration detail

**Operating system:** Linux 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64

**Webserver:** Apache/2.4.37 (Unix) OpenSSL/1.1.1 mod_fcgid/2.3.9 (fpm-fcgi)

**Database:** mysql 10.1.37

**PHP version:** 

7.2.12
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, apcu, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, curl, exif, gd, iconv, intl, ldap, mysqli, odbc, pdo_mysql, soap, zip, apc, Phar, mailparse, Zend OPcache, xdebug

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older version (14.0.1)

**Where did you install Nextcloud from:** Nextcloud homepage/ZIP archive

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - apporder: 0.6.0
 - bookmarks: 0.14.3
 - bruteforcesettings: 1.2.0
 - calendar: 1.6.4
 - checksum: 0.4.1
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dashboard: 5.0.1
 - dav: 1.6.0
 - deck: 0.5.1
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_external: 1.5.0
 - files_frommail: 0.1.1
 - files_markdown: 2.0.5
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - flowupload: 0.0.8
 - gallery: 18.1.0
 - groupfolders: 2.0.1
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - metadata: 0.8.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - ocsms: 2.0.2
 - password_policy: 1.4.0
 - passwords: 2018.12.0
 - phonetrack: 0.3.9
 - previewgenerator: 2.0.0
 - provisioning_api: 1.4.0
 - quota_warning: 1.3.0
 - richdocuments: 3.0.5
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - spreed: 4.0.2
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - twofactor_totp: 1.5.0
 - updatenotification: 1.4.1
 - user_usage_report: 1.1.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_reader
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "www2.wolf-stuttgart.net",
        "nextcloud.christian-wolf.click"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/www2.wolf-stuttgart.net\/nextcloud",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "stable",
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

**Operating system:** 

## Logs
No logs were found except for the mail content above.

Nextcloud: 14.0.4
Group folders: 2.0.1

**Comment by icewind1991** [comment]
Can you test it with https://github.com/nextcloud/groupfolders/commit/e5a4e010b5deaf33795b4ede6fb4aac02caca592

**Comment by christianhauff** [comment]
Commit e5a4e01 works for me! (NC 14.0.4)

**Comment by himpierre** [comment]
Using commit https://github.com/nextcloud/groupfolders/commit/e5a4e010b5deaf33795b4ede6fb4aac02caca592 now. Let's see what happens.

**Comment by christianlupus** [comment]
@icewind1991 I know git but I am unsure how to test my NC instance with a development version of the app. Disable the app, putting NC into maintenance mode, moving the old app folder out of the way and cloning the git repo at the appropriate location, then closing mangement mode and reenabling the app?
Or is there more/less to be done? How do I get back on track with the automatic upgrades within NC?

**Comment by icewind1991** [comment]
You can download the commit as a patch by putting ".patch" after the commit url: https://github.com/nextcloud/groupfolders/commit/e5a4e010b5deaf33795b4ede6fb4aac02caca592.patch

and then apply it with

```
patch -p1 < e5a4e010b5deaf33795b4ede6fb4aac02caca592.patch
```

**Comment by TP75** [comment]
> You can download the commit as a patch

Thanks and good to know for the try. I will add this advice to my [#246 commentary](https://github.com/nextcloud/groupfolders/issues/246#issuecomment-447306865) earlier of today.

However, this does not answer the question of "how to get back on track with the automatic upgrades within NC", I presume.

**Comment by icewind1991** [comment]
if you patch the app it should still get automated updates

**Comment by TP75** [comment]
> if you patch the app it should still get automated updates

Groupfolder 2.0.2 is availbale.  Apparently one can seemlessly update even after the a.m. patch operation. Nice.

**Comment by pgassmann** [comment]
Thank you @icewind1991 for developing this app. Your efforts and time put into a free and open source app are much appreciated.
It is though difficult to see the differences between the releases, because there is no updated Changelog. Could you update this file? It could help answering questions like: What features do I lose by downgrading to 1.3.0? What did change in the new versions, how could this affect my setup?
I'm waiting for the two bugs for version 2+ to be closed before I update again. You released two patch versions without closing the bugs. It seems that this is because of missing structures to prerelease a new version for testing, so I don't blame you.
For Nextcloud in general I wish though for better Quality Assurance and release testing with some common setups. So that problems like this one can be avoided for the general user. Are there any plans in this regard?

**Comment by christianlupus** [comment]
> You can download the commit as a patch by putting ".patch" after the commit url: https://github.com/nextcloud/groupfolders/commit/e5a4e010b5deaf33795b4ede6fb4aac02caca592.patch
> 
> and then apply it  [...]

I was not aware, that you meant only the changes introduced in this single commit to be the solution. Sorry, my fault.

After the update to 2.0.2 it seems the patch to be embedded in the regular release anyways. Is this correct?

**Comment by icewind1991** [comment]
yes
