### ISSUE TITLE
TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser

### ISSUE THREAD

**Issue by proserver1** [nextcloud/groupfolders#2473]
since last update:

Updated 19 hours ago
(now: Tue Jul 18 03:02:05 PM CEST 2023)
Nextcloud 26 	14.0.3

cronjobs throw errors:

<details>
TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in /srv/foobar/nextcloud-26.0.3/apps_custom/groupfolders/lib/Mount/MountProvider.php on line 206 and defined in /srv/foobar/nextcloud-26.0.3/apps_custom/groupfolders/lib/ACL/ACLManagerFactory.php:37
Stack trace:
#0 /srv/foobar/nextcloud-26.0.3/apps_custom/groupfolders/lib/Mount/MountProvider.php(206): OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager()
#1 /srv/foobar/nextcloud-26.0.3/apps_custom/groupfolders/lib/Versions/VersionsBackend.php(172): OCA\GroupFolders\Mount\MountProvider->getMount()
#2 /srv/foobar/nextcloud-26.0.3/apps_custom/groupfolders/lib/Versions/GroupVersionsExpireManager.php(68): OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()
#3 /srv/foobar/nextcloud-26.0.3/apps_custom/groupfolders/lib/Versions/GroupVersionsExpireManager.php(59): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
#4 /srv/foobar/nextcloud-26.0.3/apps_custom/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php(43): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
#5 /srv/foobar/nextcloud-26.0.3/lib/public/BackgroundJob/Job.php(78): OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
#6 /srv/foobar/nextcloud-26.0.3/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#7 /srv/foobar/nextcloud-26.0.3/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#8 /srv/foobar/nextcloud-26.0.3/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#9 {main}
</details>

happens on all instances
PHP 8.1.2-1ubuntu2.13

**Comment by DavidMndz** [comment]
I confirm the error is present in Nextcloud 27.0.0 as well.

**Comment by gregoa** [comment]
Maybe related to #2464 …

**Comment by BJKle** [comment]
This is unrelated to OS and NC Version. I have it it different instances.

**Comment by julian70400** [comment]
Same here, Nextcloud 26.0.3, since new version of Group Folder.

**Comment by alphasixtyfive** [comment]
Same issue after updating to 26.0.3. No issues have been reported by the users though.

**Comment by solracsf** [comment]
Can you replace (at `/apps/groupfolders/lib/Mount/MountProvider.php`)

```
public function getMount(
    int $id,
    string $mountPoint,
    int $permissions,
    int $quota,
    ?ICacheEntry $cacheEntry = null,
    IStorageFactory $loader = null,
    bool $acl = false,
    IUser $user = null,
    ?ACLManager $aclManager = null
): ?IMountPoint {
```

by 

```
public function getMount(
    int $id,
    string $mountPoint,
    int $permissions,
    int $quota,
    ?ICacheEntry $cacheEntry = null,
    IStorageFactory $loader = null,
    bool $acl = false,
    ?IUser $user = null,
    ?ACLManager $aclManager = null
): ?IMountPoint {
```

So from `IUser $user = null,` to `?IUser $user = null,`

and see if this helps?

**Comment by rkl110** [comment]
:

> Can you replace (at `/apps/groupfolders/lib/Mount/MountProvider.php`)
> 
> ```
> public function getMount(
>     int $id,
>     string $mountPoint,
>     int $permissions,
>     int $quota,
>     ?ICacheEntry $cacheEntry = null,
>     IStorageFactory $loader = null,
>     bool $acl = false,
>     IUser $user = null,
>     ?ACLManager $aclManager = null
> ): ?IMountPoint {
> ```
> 
> by
> 
> ```
> public function getMount(
>     int $id,
>     string $mountPoint,
>     int $permissions,
>     int $quota,
>     ?ICacheEntry $cacheEntry = null,
>     IStorageFactory $loader = null,
>     bool $acl = false,
>     ?IUser $user = null,
>     ?ACLManager $aclManager = null
> ): ?IMountPoint {
> ```
> 
> So from `IUser $user = null,` to `?IUser $user = null,`
> 
> and see if this helps?

Does not work for occ command haven't tried cron.

**Comment by solracsf** [comment]
Cc @icewind1991

**Comment by ebdavison** [comment]
I can confirm that the above fix does not work for `occ groupfolders:scan`

**Comment by solracsf** [comment]
See https://github.com/nextcloud/groupfolders/pull/2476

**Comment by ebdavison** [comment]
The fix in #2476 works for me with `occ groupfolders:scan`.  Thanks.

**Comment by proserver1** [comment]
fix in https://github.com/nextcloud/groupfolders/pull/2476 works with occ and cron. thank you

**Comment by solracsf** [comment]
Fix has been released.
