### ISSUE TITLE
OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\GroupFolders\Folder\FolderManager! Class "OCA\GroupFolders\Folder\FolderManager" does not exist

### ISSUE THREAD

**Issue by Mike710Shine** [nextcloud/groupfolders#2478]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install the Group folders
2. Activate it

### Expected behaviour
Actually, the app should work as desired.

### Actual behaviour
As soon as the app is active, I only get errors and no user can access their files.

### Server configuration

The official Docker image

**Database: mariaDB 10.11.4**

**PHP version:  8.2.7**

**Nextcloud version: 27.0.0** (see Nextcloud admin page)

**Group folders version: 15.0.1**

**Updated from an older Nextcloud/ownCloud or fresh install: I updated to 27 a few weeks ago and then installed groupfolders today**

**Are you using external storage, if yes which one: external storage ist installed but not used** 

**Are you using encryption:** no

### Client configuration
**Browser: Opera**

**Operating system: Windows 11**

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[no app in context] Fehler: OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\GroupFolders\Folder\FolderManager! Class "OCA\GroupFolders\Folder\FolderManager" does not exist at <<closure>>

 0. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 142
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\GroupFolde ... r")
 1. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 494
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\GroupFolde ... r")
 2. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 466
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\GroupFolde ... r")
 3. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 65
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\GroupFolde ... r")
 4. /var/www/html/apps/groupfolders/lib/AppInfo/Application.php line 103
    OC\AppFramework\Utility\SimpleContainer->get("OCA\\GroupFolde ... r")
 5. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 171
    OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php line 122
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
 7. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 138
    Pimple\Container->offsetGet("OCA\\GroupFolders\\Mount\\MountProvider")
 8. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 488
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\GroupFolders\\Mount\\MountProvider")
 9. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 466
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\GroupFolders\\Mount\\MountProvider")
10. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 65
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\GroupFolders\\Mount\\MountProvider")
11. /var/www/html/apps/groupfolders/lib/AppInfo/Application.php line 225
    OC\AppFramework\Utility\SimpleContainer->get("OCA\\GroupFolders\\Mount\\MountProvider")
12. /var/www/html/apps/groupfolders/lib/AppInfo/Application.php line 215
    OCA\GroupFolders\AppInfo\Application->getMountProvider()
13. /var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 45
    OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensitive parameters replaced ***")
14. /var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php line 50
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn(["Closure"])
15. /var/www/html/apps/groupfolders/lib/AppInfo/Application.php line 214
    OC\AppFramework\Bootstrap\BootContext->injectFn(["Closure"])
16. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 200
    OCA\GroupFolders\AppInfo\Application->boot(["OC\\AppFramewo ... "])
17. /var/www/html/lib/private/App/AppManager.php line 437
    OC\AppFramework\Bootstrap\Coordinator->bootApp("groupfolders")
18. /var/www/html/lib/private/App/AppManager.php line 216
    OC\App\AppManager->loadApp("groupfolders")
19. /var/www/html/lib/private/legacy/OC_App.php line 126
    OC\App\AppManager->loadApps(["dav"])
20. /var/www/html/apps/dav/lib/AppInfo/Application.php line 209
    OC_App::loadApps(["dav"])
21. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 200
    OCA\DAV\AppInfo\Application->boot(["OC\\AppFramewo ... "])
22. /var/www/html/lib/private/App/AppManager.php line 437
    OC\AppFramework\Bootstrap\Coordinator->bootApp("dav")
23. /var/www/html/lib/private/App/AppManager.php line 216
    OC\App\AppManager->loadApp("dav")
24. /var/www/html/lib/private/legacy/OC_App.php line 126
    OC\App\AppManager->loadApps([])
25. /var/www/html/lib/base.php line 1044
    OC_App::loadApps()
26. /var/www/html/index.php line 36
    OC::handleRequest()

POST /index.php/settings/apps/disable
from 79.224.18.178 by ad_mike710shine at 2023-07-20T09:09:16+00:00
```

**Comment by bastikus** [comment]
Same problem, but it was fresh installation NC (official docker image 27.0.0-apache).

**Comment by XueSheng-GIT** [comment]
Looks like https://github.com/nextcloud/groupfolders/issues/2437, which was closed. Reinstall + waiting helped!? Maybe try to completely remove the groupfolders app and reinstall afterwards.

**Comment by bastikus** [comment]
@XueSheng-GIT I tried reinstalling GroupFolders several times and waited... but it didn't help me. Same error...

**Comment by Mike710Shine** [comment]
Is it possible that groupfolders somehow indexes everything and therefore does not work until everything is ready. I just installed it in a test environment and there was also briefly the same error but with the difference that in the test environment only very very little data is available compared to the productive instance.

**Comment by logianer** [comment]
Hi it's me from #2437!
For me, waiting boiled down to many server restarts, docker-compose ups/downs and ignoring it for several days. After many days I said to myself 'eh, why not give it a try?' and without changing anything in the server configuration I activated the app and it just worked (works to this day!)

**Comment by Mike710Shine** [comment]
But I think that can not be the right behavior if you can not use the Nextcloud for days.

**Comment by XueSheng-GIT** [comment]
Just had this on an test instance which I did upgrade from 26.0.4 to 27.0.1. After removing groupfolders and fulltextsearch, rebooting and reinstalling those apps, the error was gone.

**Comment by Mike710Shine** [comment]
Uninstall the app reboot the Nextcloud and reinstall the app works. Very strange why but it works for me. I would rather have a bug than just reboot and everything is fine, very unsatisfactory. The problem is when it occurs again

**Comment by fenris** [comment]
thanks for the temporary solution, the trick works.

**Comment by blizzz** [comment]
The trick is to reset the apcu cache. That's not the fault of the app, but we need some handling around app enabling at least. At least I have repro steps:

1 Clear opcache and apcu
2 Enable integration_openproject
3 Go Admin Settings → OpenProject
4 Go to Files for good measure
5 Enable group folders
6 Go to Files → Repro!
