### ISSUE TITLE
OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given

### ISSUE THREAD

**Issue by antonol68** [nextcloud/groupfolders#2487]
How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Groupfolders
2. Enable it
3. Create a groupfolder 

### Expected behaviour
No errors on Nextcloud log

### Actual behaviour
Error on Nextcloud log every hour, seems after a cron job

### Server configuration

Operating system: Freebsd 13.1-RELEASE-p7

Web server: Nginx 1.24.0

Database: PostgreSQL 13.11

PHP version: 8.2.7

Nextcloud version: 27.0.1

Group folders version: 15.0.1

Updated from an older Nextcloud/ownCloud or fresh install: I updated to 27 a few days ago and then installed groupfolders

Are you using external storage, if yes which one: no

Are you using encryption: no

Are you using an external user-backend, if yes which one: no

### Client configuration
Browser: Firefox 102.13.0esr

Operating system: Debian 12

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[core] Error: TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in /usr/local/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php on line 206 at <<closure>>

0. /usr/local/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 206
   OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager(null, 1)
1. /usr/local/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php line 172
   OCA\GroupFolders\Mount\MountProvider->getMount(1, "/dummyuser/files/TESTE", 31, 10737412742)
2. /usr/local/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 68
   OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles([1,"TESTE",[["Fa ... "])
3. /usr/local/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder([1,"TESTE",[["Fa ... "])
4. /usr/local/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
5. /usr/local/www/nextcloud/lib/public/BackgroundJob/Job.php line 86
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
6. /usr/local/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start(["OC\\BackgroundJob\\JobList"])
7. /usr/local/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start(["OC\\BackgroundJob\\JobList"])
8. /usr/local/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute(["OC\\BackgroundJob\\JobList"], ["OC\\Log"])

```
</details>

**Comment by patman15** [comment]
see https://github.com/nextcloud/groupfolders/issues/2473

**Comment by antonol68** [comment]
@patman15 
That solved the issue tanks
