### ISSUE TITLE
NC25 [cron] TypeError: Argument 1 passed to . . . ::getACLManager() must be an instance of OCP\IUser, null given

### ISSUE THREAD

**Issue by TP75** [nextcloud/groupfolders#2491]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Make normal use of NC 25 instance at your deliberation.
2. Make use of system _cron_ for regular NC housekeeping.
3. Upgrade to NC "25.0.9.2" from earlier version.
4. Optionally upgrade _Group folders App_ from "13.1.3" to "13.1.4"

### Expected behaviour
Silent operation and no error log in protocols.

### Actual behaviour
Silent operation and **error log** (see below) at regular interval in protocols. The interval seems to be twice a day.

### Server configuration

**Operating system:** Linux 5.10.0-23-amd64 x86_64 i.e. _Debian 11.7 bullseye_

**Web server:** Apache2 "2.4.56-1~deb11u2"

**Database:** mysql i.e. MariaDB 10.5.19

**PHP version:** PHP 7.4.33 (intentionally, _legacy version is supported by Debian security team_)

**Nextcloud version:** NC "25.0.9.2"

**Group folders version:** "13.1.3" and "13.1.4"

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from NC "25.0.8"

**Where did you install Nextcloud from:** Nextcloud offical sources / NC Updater

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Excerpt from raw:
```
{"reqId":"RLfDhVCSGXWqeDuaFrWN","level":3,"time":"2023-07-22T11:35:01+02:00","remoteAddr":"","user":
"--","app":"cron","method":"","url":"--","message":"Argument 1 passed to 
OCA\\GroupFolders\\ACL\\ACLManagerFactory::getACLManager() must be an instance of OCP\\IUser, 
null given, called in /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php on line 206",
"userAgent":"--","version":"25.0.9.2", 
. . .
```

Formatted log entry:
```
[cron] Fehler: TypeError: Argument 1 passed to OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager() 
must be an instance of OCP\IUser, null given, called in /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php 
on line 206 at <<closure>>

0. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 206
   OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager()
1. /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php line 172
   OCA\GroupFolders\Mount\MountProvider->getMount()
2. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 68
   OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()
3. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 59
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
5. /var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 43
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
6. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
7. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
8. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
9. /var/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2023-07-22T11:35:01+02:00
```
</details>

Hope this helps.
🌻

**Comment by TP75** [comment]
ref #2487 #2473

Unfortunately, the prior scan of open issues did not show these.
😢

**Comment by fschrempf** [comment]
Duplicate of https://github.com/nextcloud/groupfolders/issues/2473
