### ISSUE TITLE
groupfolders:scan --all inverts files and folders count in report

### ISSUE THREAD

**Issue by saintfrater** [nextcloud/groupfolders#2492]
### Steps to reproduce
1. run occ groupfolders:scan --all
2. look at scan report, counters values for files and folders are inverted for each group folders

### Expected behaviour
inverting counters report's columns

### Actual behaviour
report show irrelevant files and folders counters

### Server configuration

**Operating system:**
Debian GNU/Linux 11 (bullseye) x86_64 

**Web server:**
Apache/2.4.56 (Debian)

**Database:**
mysql  Ver 15.1 Distrib 10.5.19-MariaDB, for debian-linux-gnu (x86_64)

**PHP version:**
PHP 8.1.21 (cli) (built: Jul 16 2023 11:00:45) (NTS)

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 26.0.4

**Group folders version:**
14.0.3 + Fix for issue #2482

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from previous versions

**Where did you install Nextcloud from:**
from nextcloud website

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no

### Client configuration
**Browser:**
Not Relevant (N/R)

**Operating system:**
N/R

### Logs
No error logged

#### Web server error log
N/R

#### Nextcloud log (data/nextcloud.log)
N/R

#### Browser log
N/R

#### Comments and ScreenShots
This bug is more cosmectics than problematics.

Screen Shot result:
![Screenshot from 2023-07-28 09-09-49](https://github.com/nextcloud/groupfolders/assets/13979047/ef37be0a-5b9f-4eac-9b25-87dfd7042f8d)

On this example folder ID 4 contains 2 files and no sub-directory and Folder ID 5 contains 2 Sub-directories with 5 and 1 files

screenshot from production server, I can assure we have more much files than folders :D

![Screenshot from 2023-07-28 09-15-12](https://github.com/nextcloud/groupfolders/assets/13979047/554e27fa-6986-4310-9da3-5b5d2208824d)

**Comment by Bobmorton-TX** [comment]
I can confirm this incorrect count:

+-----------+---------+-------+--------------+
| Folder Id | Folders | Files | Elapsed time |
+-----------+---------+-------+--------------+
| 1         | 20986   | 1930  | 00:00:39     |
| 2         | 0       | 1     | 00:00:00     |
| 3         | 642     | 2     | 00:00:00     |
+-----------+---------+-------+--------------+

while the folder #1 contains

1929 directories, 20981 files

I will check on github if this has been reported now.

**Comment by koelle25** [comment]
I can confirm it's the same problem if using `groupfoldes:scan <id>`:

![Bildschirmfoto vom 2023-09-14 12-05-31](https://github.com/nextcloud/groupfolders/assets/915514/2f4d8491-1936-449e-9e46-6f343cad0369)
