### ISSUE TITLE
occ cron.php return groupfolders error messages

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/groupfolders#2495]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install ground folders
2. run occ cron.php
3.

### Expected behaviour
Tell us what should happen
No error output
### Actual behaviour
Tell us what happens instead
The error messages output like this:

TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in /www/apps.local/groupfolders/lib/Mount/Moun
tProvider.php on line 206 and defined in /www/apps.local/groupfolders/lib/ACL/ACLManagerFactory.php:37                                                                              
Stack trace:                                                                                                                                                                                                   
#0 /www/apps.local/groupfolders/lib/Mount/MountProvider.php(206): OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager()                                                           
#1 /www/apps.local/groupfolders/lib/Versions/VersionsBackend.php(172): OCA\GroupFolders\Mount\MountProvider->getMount()                                                             
#2 /www/apps.local/groupfolders/lib/Versions/GroupVersionsExpireManager.php(68): OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()                                  
#3 /www/apps.local/groupfolders/lib/Versions/GroupVersionsExpireManager.php(59): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()                               
#4 /www/apps.local/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php(43): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()                                    
#5 /www/lib/public/BackgroundJob/Job.php(78): OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
#6 /www/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#7 /www/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#8 /www/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#9 {main}

### Server configuration

**Operating system:**
Debian
**Web server:**
Nginx
**Database:**
Mariadb
**PHP version:**
php8.2
**Nextcloud version:** (see Nextcloud admin page)
26.3
**Group folders version:**
groupfolders: 14.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
SQL

**Comment by tj775** [comment]
We have got the same issues with our own hosted nextcloud. 

**Server configuration**  

**Operating system:**  
Synology (218+) / Linux

**Web server:**  
Apache 2.4

**Database:**  
Mariadb 10

PHP version:
php 8.0

**Nextcloud version: (see Nextcloud admin page)**  
26.0.4

**Group folders version:**  
groupfolders: 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**  
Updated from Nextcloud 26.0.1

**Where did you install Nextcloud from:**  
WebUpdater with CLI Update

**Are you using external storage, if yes which one: local/s3/smb/sftp/...**  
local

**Are you using encryption: yes/no**  
no

**Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/Saml/...** 
no

**Comment by saintfrater** [comment]
I think that you have the same issue please look PR #2482 for "patching" until the official release.

**Comment by johnwmail** [comment]
after applied the PR #2482 , NC still show the same error , when I run php -f cron.php

TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in /www/apps.local/groupfolders/lib/Mount/MountProvider.php on line 206 and defined in /www/apps.local/groupfolders/lib/ACL/ACLManagerFactory.php:37
Stack trace:
#0 /www/apps.local/groupfolders/lib/Mount/MountProvider.php(206): OCA\GroupFolders\ACL\ACLManagerFactory->getACLManager()
#1 /www/apps.local/groupfolders/lib/Versions/VersionsBackend.php(172): OCA\GroupFolders\Mount\MountProvider->getMount()
#2 /www/apps.local/groupfolders/lib/Versions/GroupVersionsExpireManager.php(68): OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles()
#3 /www/apps.local/groupfolders/lib/Versions/GroupVersionsExpireManager.php(59): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder()
#4 /www/apps.local/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php(43): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
#5 /www/lib/public/BackgroundJob/Job.php(78): OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run()
#6 /www/lib/public/BackgroundJob/TimedJob.php(103): OCP\BackgroundJob\Job->start()
#7 /www/lib/public/BackgroundJob/TimedJob.php(93): OCP\BackgroundJob\TimedJob->start()
#8 /www/cron.php(152): OCP\BackgroundJob\TimedJob->execute()
#9 {main}

**Comment by johnwmail** [comment]
Pls reopen it

**Comment by saintfrater** [comment]
@johnwmail as you log show, it seems that you haven't apply the "hot-fix" provided in PR #2482 for your [Stable26].

your line 206 (as shown in your log extract) should not call getACLManager.

please check if the patch is correctly apply, you can look the detailed change [here](https://github.com/nextcloud/groupfolders/pull/2482/files/748f2961c7665e917b2179ac0a3d232676d49d06)

compare with you're instance's source files.

**Comment by johnwmail** [comment]
Is that correct?
![image](https://github.com/nextcloud/groupfolders/assets/1752235/2d1ea854-96d6-42b6-bc8e-62e94f7c672a)
