### ISSUE TITLE
Error logged in Logging Nextcloud 

### ISSUE THREAD

**Issue by sergiupapuc** [nextcloud/groupfolders#2498]
No error in interface, error logged in Logging Nextcloud
TypeError: OCA\GroupFolders\ACL\ACLManagerFactory::getACLManager(): Argument #1 ($user) must be of type OCP\IUser, null given, called in /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php on line 206

**Comment by solracsf** [comment]
Already fixed on the good repo.
