### ISSUE TITLE
Choosing the best way to share group folder resources

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/groupfolders#2516]
Hi! Would you be so kind to recommend (and/or accept the feature request) how to organise better ulitisation of group folders when there is the need to share some of sub-folders with other groups.

Eg, I have several group folders (A,B,C,D...) which are the work folders of respective groups (group A, group B, group C, group D...). At the same time some sub-folders, eg from A1, need to be shared with the "group B", and B2 with "group A" etc. 

Normally, me, as admin, I am not a part of these work group folders. However, in order to make the sharing process easy I add myself to the "group A" and share the sub-folders from User Management page, and afterwards leaving this group. This looks quite awkward, in my opinion, moreover, sometimes it leads to crashing my trash bin.

What to do? How to make the process more consistent? I do not need to have access to the content of group folders, but as admin be able to share the resources upon request or discard that.

**Comment by jospoortvliet** [comment]
Perhaps letting users manage group folders themselves using Circles is a solution. Either way, I'm afraid github is for development discussion, not user questions - private and small business users can ask those on the forums on help.nextcloud.com - if you use Groupfolders at scale, ask support for advice. We're happy to help.
