### ISSUE TITLE
Group Folders has automatically been disabled

### ISSUE THREAD

**Issue by sunnyd24** [nextcloud/groupfolders#2526]
Group Folders has been automatically been disabled without any notification or error showing. 
The only log I can find is linked to 18/08/2023 during a daily borg backup / auto update.
Could be a Nextcloud backup/auto update issue that needs a separate bug report.

### Steps to reproduce
1. Group folders enabled and configured
2. Run borg backup and enable auto update
3. Check logs for error

### Expected behaviour
Group folders should auto update automatically, and re-enable, or if it cannot auto-update, then an error message should be posted to the admin and notified of auto update failure and disabled plugin.

### Actual behaviour
Group folder is trying to update but could not, so **disables** Group folders and does **not** notify the admin.

```[no app in context] Error: Exception: Could not download app groupfolders at <<closure>>

0. /var/www/html/lib/private/Installer.php line 193
   OC\Installer->downloadApp("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
1. /var/www/html/core/Command/App/Update.php line 107
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /var/www/html/3rdparty/symfony/console/Command/Command.php line 298
   OC\Core\Command\App\Update->execute(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
3. /var/www/html/3rdparty/symfony/console/Application.php line 1040
   Symfony\Component\Console\Command\Command->run(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
4. /var/www/html/3rdparty/symfony/console/Application.php line 301
   Symfony\Component\Console\Application->doRunCommand(["OC\\Core\\Command\\App\\Update"], ["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
5. /var/www/html/3rdparty/symfony/console/Application.php line 171
   Symfony\Component\Console\Application->doRun(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
6. /var/www/html/lib/private/Console/Application.php line 211
   Symfony\Component\Console\Application->run(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
7. /var/www/html/console.php line 100
   OC\Console\Application->run()
8. /var/www/html/occ line 11
   require_once("/var/www/html/console.php")

at 2023-08-18T03:09:17+00:00
```

### Server configuration

**Operating system:**
Windows 11
**Web server:**
n/a
**Database:**
n/a
**PHP version:**
n/a
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud AIO v7.0.0 / [Nextcloud Hub 5] (27.0.2)
**Group folders version:**
15.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
n/a
**Where did you install Nextcloud from:**
n/a
**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no
### Client configuration
**Browser:**
Edge
**Operating system:**
Windows or Android
### Logs

```[no app in context] Error: Exception: Could not download app groupfolders at <<closure>>

0. /var/www/html/lib/private/Installer.php line 193
   OC\Installer->downloadApp("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
1. /var/www/html/core/Command/App/Update.php line 107
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /var/www/html/3rdparty/symfony/console/Command/Command.php line 298
   OC\Core\Command\App\Update->execute(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
3. /var/www/html/3rdparty/symfony/console/Application.php line 1040
   Symfony\Component\Console\Command\Command->run(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
4. /var/www/html/3rdparty/symfony/console/Application.php line 301
   Symfony\Component\Console\Application->doRunCommand(["OC\\Core\\Command\\App\\Update"], ["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
5. /var/www/html/3rdparty/symfony/console/Application.php line 171
   Symfony\Component\Console\Application->doRun(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
6. /var/www/html/lib/private/Console/Application.php line 211
   Symfony\Component\Console\Application->run(["Symfony\\Compo ... "], ["Symfony\\Compo ... "])
7. /var/www/html/console.php line 100
   OC\Console\Application->run()
8. /var/www/html/occ line 11
   require_once("/var/www/html/console.php")

at 2023-08-18T03:09:17+00:00
```

**Comment by sunnyd24** [comment]
@joshtrichards Thanks for the update and for noticing that this also impacted `richdocuments`, explains why this wasn't working for me until recently!

I can confirm that re-enabling the group folder app got it working again.

I agree with you that there is nothing to be done at `groupfolders` level, but I reported in case I was not the only one experiencing this issue. 

**However, I would recommend that Nextcloud server or the app send the admin a message in something goes wrong with an app. i.e. A check to see if it was previously enabled and after update has since been disabled and fires a message/notification/email to the admin?
Is this something that could be implemented somewhere in the Nextcloud ecosystem? Any thoughts?**

I will raise a bug report at the apps management page and AIO and link to this for history, if that's ok?

**Comment by joshtrichards** [comment]
Sounds good. Likely some relevant existing issues you can subscribe to / add your ideas to:

- https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+apps+management%22
- https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+install+and+update%22
- https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+apps+management%22+label%3A%22feature%3A+install+and+update%22
