### ISSUE TITLE
occ groupfolders:scan broken: loader argument in getMount not implementing IStorageFactory

### ISSUE THREAD

**Issue by rainerjung** [nextcloud/groupfolders#254]
The groupfolders app 2.0.1 lists groupfolders:scan as an available occ command.

When running

  php /path/to/my/occ groupfolders:scan 10

(10 is some existing groupfolder id) I get:

TypeError: Argument 6 passed to OCA\GroupFolders\Mount\MountProvider::getMount() must implement interface OCP\Files\Storage\IStorageFactory, none given, called in /path/to/my/apps/groupfolders/lib/Command/Scan.php on line 59 and defined in /path/to/my/apps/groupfolders/lib/Mount/MountProvider.php:67
Stack trace:
#0 /path/to/my/apps/groupfolders/lib/Command/Scan.php(59): OCA\GroupFolders\Mount\MountProvider->getMount('10', '/Some-Group', NULL, '1073741274')
#1 /path/to/my/3rdparty/symfony/console/Command/Command.php(251): OCA\GroupFolders\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /path/to/my/core/Command/Base.php(162): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /path/to/my/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /path/to/my/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\GroupFolders\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /path/to/my/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /path/to/my/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /path/to/my/console.php(96): OC\Console\Application->run()
#8 /path/to/my/occ(11): require_once('/path/to/my/...')

When looking at MountProvider.php line 67, the call to getMount() demands a loader argument implementing IStorageFactory, but the issued call to it in Scan.php does not pass such an argument.

Regards,

Rainer

**Comment by rainerjung** [comment]
This issue here is about the occ command for scan not working, but the root cause is like in #253.

**Comment by rainerjung** [comment]
I see that abortIfInterrupted() comes from Base.php in NC 15.

As a workaround I added the following to Scan.php and now occ groupfolders:scan works with NC 14:

        /**
         * Throw InterruptedException when interrupted by user
         *
         * @throws InterruptedException
         */
        protected function abortIfInterrupted() {
                if (!function_exists('pcntl_signal')) {
                        return;
                }
                pcntl_signal_dispatch();
                if ($this->interrupted === true) {
                        throw new InterruptedException('Command interrupted by user');
                }
        }

So this should be fine, once we update to NC 15.

**Comment by icewind1991** [comment]
Can verify that 2846826 fixes the issue (without your own patch applied)

**Comment by rainerjung** [comment]
Yes, verified, it fixes it. Thanks!!
