### ISSUE TITLE
No sharing settings in v2

### ISSUE THREAD

**Issue by reins-ch** [nextcloud/groupfolders#255]
Since the upgrade to v2 there is no option to allow the sharing of individual files or folders inside a group folder.

Is this feature planned to be integrated again?

**Comment by cweickhmann** [comment]
Same problem here with v2.0.1

**Comment by cweickhmann** [comment]
Ha, found the culprit: Me.

The second image in the [https://github.com/nextcloud/groupfolders/blob/master/README.md] shows how to enable sharing and it is turned off by default (which is wise, I think).

Maybe I'm wrong, but did this work like this in v2.0.1?

**Comment by reins-ch** [comment]
How did I not see this earlier?
But why did the sharing settings change after the update?
And why was there no note in the release?

Questions after questions...

**Comment by cweickhmann** [comment]
It may have been the same in v2.0.1 - Don't know, I only found it just now.
