### ISSUE TITLE
Group Folders size displays (for example) "104,9 MB" when "100 MB" is set (quota)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/groupfolders#2553]
Group Folders size displays (for example) "104,9 MB" when "100 MB" is set (quota)

![2023-09-13_10-19](https://github.com/nextcloud/groupfolders/assets/33763786/977b6a80-e659-4c81-bf7c-9abb8ea4b0b1)

The problem occurs for any group folders ; another noticed example : "524,3 MB" instead of 500 MB

Tested on Nextcloud 27.0.2 with GF 15.2.0

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to GF management page and check size (create a new GF or change quota of an existing GF, if necessary)
2. See that displayed quota values don't fit what was seized by administrator

### Expected behaviour
100 MB should be displayed if 100 MB was seized (for example)

### Actual behaviour
104,9 MB is displayed instead of 100 MB

### Server configuration

**Operating system:** Ubuntu server 20.04 LTS

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 10.3.38

**PHP version:** 8.2.10

**Nextcloud version:** (see Nextcloud admin page)

**Group folders version:** 15.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** from older version

**Where did you install Nextcloud from:** Manually, regular web installer

**Are you using external storage, if yes which one:** local/s3/smb/sftp/... No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...

### Client configuration
**Browser:** Firefox 117

**Operating system:** Ubuntu desktop 22.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Can be provided if necessary
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Can be provided if necessary
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Can be provided if necessary
```
</details>

**Comment by XueSheng-GIT** [comment]
@Jerome-Herbinet just double checked with the regular user quota and it behaves in the same way. Selecting 1GB results in 1,1GB. It seems to be a general Nextcloud thing.

**Comment by Jerome-Herbinet** [comment]
@juliushaertl @icewind1991 any idea ? I'm not familiar with that file size unities notion, but is there any chance that what was seized in the quota field is (right after) counted/calculated (and so rendered) with another unity ?
