### ISSUE TITLE
 Add ability to control where a group-to-group share target resides

### ISSUE THREAD

**Issue by jvantslot** [nextcloud/groupfolders#2554]
### Synopsis

Currently when sharing files or folders between groups, there is no way to configure the placement of the shared folder.  It would be very useful to be able to locate the target share in a specific place in the folder structure.

For example:

Given that two departments have their own group folders:

1.  LAB
2.  SALES

And:

SALES has no access to the LAB group folders and visa versa (per security design).

#### Scenario 
The LAB creates and manages Technical Data Sheets (TDS) , in PDF form,  for company produced products.  However SALES needs access (Read-Only) to these documents in order to distribute them to customers etc., as well as other departments that may need access to these documents.

### Current Behavior

The issue with the current behavior for sharing files and folders from group to group works, is that if you are a member of SALES with no access to LAB, the shared target shows up in your base home folder in Nextcloud.  However if you are a member of SALES and also a member of LAB, you don't see the share in your home folder at all.  You can only see it in the LAB->Data Sheets->TDS->Published folder.  So the method of accessing the folder is inconsistent with the rest of the SALES group who do not have access to LAB.

**Note**: I realize that you can see the shared folder from the Shared With Me folder.  However you have to know that the data you want happens to be located in a shared folder.

The current behavior places shared files and folders between groups outside the group folder structure.  This is not obvious and confusing to users.

### Feature Request

It would be IDEAL if, when the LAB group shared the TDS folder from somewhere nested in LAB's folder hierarchy, they could specify where in the SALES group folder hierarchy that target share is located.

For example:

LAB shares the folder LAB->Data Sheets->TDS->Published
and in the SALES group folder there would be the shared folder as SALES->TDS

This behavior is something similar to the way soft-links work in Linux folder structures.

#### Alternatively

If specifying the target location is problematic, have the default behavior be to place the target share in the base of the target group, rather than in the base of the USER's home folder.  This would eliminate the need for LAB to have intimate knowledge of SALE's folder structure.

If the default behavior would be to place the target share in the base of the SALES Group Folder, and if SALES could then move that target folder to a suitable location within the SALES Group Folder structure, that might be the best method for dealing with specifying the target location.

#### Using the Link Editor App

You can share the folder from LAB with the group SALES and then copy the link to the share and create a new URL file in the correct location (SALES->TDS) pointing to that share.  However when someone from the SALES group clicks that link it prompts them to confirm opening an outside link, which is maybe OK when using the Nextcloud web interface, but it redirects to a browser, when using the Nextcloud mobile app.  When Using webDav, the .URL extension is not recognized at all.

#### Create a new group that both SALES and LAB can access

Our organization has numerous departments, all with their own Group Folder.  Creating additional group folders to handle all the possible combinations of access between departments would be complicated, cluttered and confusing, never mind opening the possibility of massive duplication of data.  Something we are trying to avoid by moving to Nextcloud from SAMBA.  Our SAMBA folder structure grew into a complete mess over the years because of this behavior.  I prefer that Department Groups live in their own group folder silos for convenience and ease of finding the files they use on a daily basis.

#### Using actual soft-links in the underlying OS directory structure 

Creating symlinks in the underlying Linux folder structure would negate the ability for "Ad-hoc" sharing between groups since it would require an admin to set these up.  I also assume that a cron job to run the appropriate occ files:scan operation would be needed to run at a frequency to make this all usable.  So not ideal.

**Comment by provokateurin** [comment]
You could probably also solve this by making a second groupfolder nested inside the LABS groupfolder and then give SALES also access to that. Then both groups will have the folder in question at the same place in the filesystem hierarchy.

As for the feature request I think this is rather something for server, so please open an issue there if this is still relevant and the workaround I just mentioned is not sufficient.
