### ISSUE TITLE
Feature Request: sub-folders quota

### ISSUE THREAD

**Issue by parsmmm** [nextcloud/groupfolders#2558]
Hello
Please add a new feature to create sub-folders and set quotas on sub-folders

**Comment by XueSheng-GIT** [comment]
You can create subfolders for Groupfolders already and set a quota. Did you try that already? Or doesn't this work for some reason?

**Comment by joshtrichards** [comment]
Hi @parsmmm - Does your 👍 on @XueSheng-GIT suggestion indicate you've found the functionality requested in the existing implementation? Let us know so we can close this out if so.

**Comment by parsmmm** [comment]
@joshtrichards Hi Yes, it was very simple, but it was not mentioned in the description of the app or I hadn't found it
In order to create a subfolder, we must write a new folder with the same name as the main folder plus / and the name of the subfolder in the group folder settings, for example:
Foldername/SubFoldername

**Comment by XueSheng-GIT** [comment]
> Yes, it was very simple, but it was not mentioned in the description of the app or I hadn't found it

@parsmmm Issue in regards to documentation to nested groupfolders exists already. https://github.com/nextcloud/groupfolders/issues/1372
Thus, this issue can be closed. Would you please take care? Thanks!
