### ISSUE TITLE
BUG: Make groupfolders independent from existing folders owned by admin or ppl lose data!

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/groupfolders#26]
There's a weird overlap with existing folders. Take this scenario:

* Go to the Files app and create a folder named `superawesometest`
* Put a few files in it.
* Go to the Group Folders admin and create a folder named `superawesometest`
* Add the Admin group to the access rights for `superawesometest`
* Go back to Files and observe the new Group Folder has overwritten the existing `superawesometest` and it is empty. Where are my files?!!?!
* Go to the Group Folders admin and remove Admin group access to the folder `superawesometest`
* Go back to Files and observe the new Group Folder has disappeared and the existing `superawesometest` is back with its original content!
* Note that this overwriting of existing folders with (empty) Group Folders also happens with users - if you create a group folder with the same name as a folder one of your users has, they will lose access to that folder and all its content.

I think Group Folders should act like shares - if somebody shares a folder with the same name as an existing one with you, it should show up besides the existing one, not overwrite it.

**Comment by jospoortvliet** [comment]
* This bug is also in master (1.10), just tested
* deleting the Group Folder does NOT delete the users' folder and its data (thankfully). It merely obscures it while the Group Folder exists.

**Comment by dan-nkl** [comment]
#18

**Comment by jospoortvliet** [comment]
Ah, now I understand what you reported ;-)

May I suggest to try and have a more extensive description - maybe @icewind1991 understood the problem but I didn't, at least... Now I'm sorry for creating a duplicate. Let me just make mine a comment on yours.
