### ISSUE TITLE
Groupfolders fails after NC Beta 28.0.0.1 install.

### ISSUE THREAD

**Issue by noci2012** [nextcloud/groupfolders#2606]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. install NC Beta 28.0.0.1
2. after install the site is inaccessible.
3.

### Expected behaviour
I expect the system to work

### Actual behaviour
In NGINX Log:
PHP message: PHP Fatal error:  Class OCA\GroupFolders\Helper\LazyFolder contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Files\Folder::searchBySystemTag) in /var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php on line 32" while reading response header from upstream, client: 192.168.x.x, server: ncbeta.xxxx.xxxxx, request: "GET /index.php/apps/files/preview-service-worker.js

### Server configuration

**Operating system:**
Linux, Proxmox LXD container

**Web server:**
NGINX 

**Database:**
MYSQL

**PHP version:**
PHP8.2-FPM

**Nextcloud version:** (see Nextcloud admin page)
Beta 28.0.0.1

**Group folders version:**
Current as of 6 Nov. 2023

**Updated from an older Nextcloud/ownCloud or fresh install:**
This once started as a an OC4 up to NC 15, then clone to host beta versions.

**Where did you install Nextcloud from:**
Original Beta stream (6/11/2023)

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
None

**Are you using encryption:** yes/no
No / Yes    - some accounts are as a test for future use.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
No

### Client configuration
**Browser:**
Chromium (119)

**Operating system:**
Linux, Gentoo current

### Logs
From NGINX Error log the stderr output from PHP-FPM.

#### Web server error log
<details>
```
PHP message: PHP Fatal error:  Class OCA\GroupFolders\Helper\LazyFolder contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Files\Folder::searchBySystemTag) in /var/www/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php on line 32" while reading response header from upstream, client: 192.168.x.x, server: ncbeta.xxx.xxx, request: "GET /index.php/apps/files/preview-service-worker.js
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nextcloud does NOT execute
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Browser shows ERROR 500
```
</details>

**Comment by nickvergessen** [comment]
Should work with the now compatible beta release

**Comment by noci2012** [comment]
correct.
