### ISSUE TITLE
[Bug]:  PHP deprecation warning  "deprecated, use {$var}" apps/groupfolders/lib/Command/Scan.php

### ISSUE THREAD

**Issue by tuxmaster5000** [nextcloud/groupfolders#2624]
This error will be logged:

Nov 23 09:00:05 Nextcloud[26425]: {"reqId":"E0pFTjqf5AYfqtLnPkD6","level":3,"time":"2023-11-23T09:00:05+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Using ${var} in strings is deprecated, use {$var} instead at /var/www/nextcloud/apps/groupfolders/lib/Command/Scan.php#86","userAgent":"--","version":"26.0.8.2","data":{"app":"PHP"}}

For the complete system environment see:
https://github.com/nextcloud/server/issues/41674

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/groupfolders/pull/2515
