### ISSUE TITLE
Uncaught TypeError: window.OCP.Files.Navigation is undefined

### ISSUE THREAD

**Issue by come-nc** [nextcloud/groupfolders#2625]
### Steps to reproduce
1. Open Files UI
2. Open share tab in the right sidebar

### Expected behaviour
See ACL options

### Actual behaviour
No ACL options and this error:
```
Uncaught TypeError: window.OCP.Files.Navigation is undefined
    <anonymous> main.ts:36
    <anonymous> groupfolders.ts:113
    <anonymous> groupfolders.ts:113
main.ts:36:19
```

### Server configuration

**Nextcloud version:** 28 (master)

**Group folders version:** 16.0.0

**Comment by artonge** [comment]
@susnux I think you fixed a similar issue. Isn't it related to the new "init" logic Barth introduced with F2V?

**Comment by susnux** [comment]
Yes and no, the problem for group folders is fixed, but this is still an issue on server core.
