### ISSUE TITLE
ACLs are not correctly applied on trashed subfolders.

### ISSUE THREAD

**Issue by come-nc** [nextcloud/groupfolders#2626]
### Steps to reproduce
1. Add a groupfolder
2. Create a subfolder
3. Add an ACL rule to hide subfolder from userA
4. Log in as userA and see that subfolder is not listed
5. Log in as admin and delete subfolder
6. Log in as userA and find subfolder in trash

### Expected behaviour
ACLs should still apply to trashed items

### Actual behaviour
Users can see files they should not be able to.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page) 27

**Group folders version:** 15.3.1

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/groupfolders/pull/2631
