### ISSUE TITLE
Activities and notifications for groupfolders

### ISSUE THREAD

**Issue by kokotko1337** [nextcloud/groupfolders#263]
Showing activity- who and when downloaded files from GF
Notofication - if there is something new , send mail to group - atm im doing this with script , but is not native and dirty

I really appreciate your work guys, but this 2 things missing and i think they are key features. Im not programmer, so i have no idea how to do this. But on other side i can drop small donation and i think there are more of us ...

**Comment by team-a2** [comment]
Hi kokotko1337,
can You share Your script for notifying if something is new inside a groupfolder here?

Thanks in advance!

**Comment by kokotko1337** [comment]
@team-a2 it is just dirty linux script using Find files younger as 24hours in defined folders , and when something is found it makes txt file and it send it via distribution group on exchange , where are defined emails, which are informed 

i have mail discusion with @bigcookie and he shared his script, his method is better like mine 

check here - scroll down
https://github.com/nextcloud/groupfolders/issues/101

**Comment by fschrempf** [comment]
This should be possible using the activity app. There is a config option to enable this for groupfolders. Please see: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/activity_configuration.html#activities-in-groupfolders.

I will close this as stale. If you think there is still something missing, please create a new issue. Thanks!
