### ISSUE TITLE
Files in a group folder suddenly disappeared, and sometimes the image in the screenshot appeared.

### ISSUE THREAD

**Issue by ebao-mis** [nextcloud/groupfolders#2633]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.The user logs into the group folder, and in less than a minute the contents of the group folder disappears.
2.
3.

### Expected behaviour
Tell us what should happen
The user logs into the group folder, and in less than a minute the contents of the group folder disappears.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**Ubuntu

**Web server:**apache

**Database:**mysql 8.0

**PHP version:**8.1.24

**Nextcloud version:** 25.0.12

**Group folders version:**13.1.6

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**docker hub

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
Use S3 for primary storage, configured inside config.php
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
ldap
### Client configuration
**Browser:**
![groupfile lost](https://github.com/nextcloud/groupfolders/assets/151919905/7fadd2da-99c9-48db-a717-ba54375a4b4b)

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>
[Uploading nextcloud.log…]()

**Comment by joshtrichards** [comment]
Can you provide the Nextcloud server logs from this one minute period?

**Comment by ebao-mis** [comment]
[nextcloud.log](https://github.com/nextcloud/groupfolders/files/13484209/nextcloud.log)



> 您能否提供这一分钟的Nextcloud服务器日志？

[nextcloud.log](https://github.com/nextcloud/groupfolders/files/13484215/nextcloud.log)

**Comment by Innky-Joe** [comment]
![Untitled](https://github.com/nextcloud/groupfolders/assets/156313232/d99298df-bb59-4be8-b16e-231e06bc19a8)


I am running Group folders by Robin Appelman AGPL-licensed 16.0.1 on NC V.28 and add advanced permission rule not showing, can anyone help me out?

Related resources
Anything shared with the same group of people will show up here

**Comment by joshtrichards** [comment]
@Innky-Joe Please don't post on unrelated issues. Your query sounds appropriate for the help forum - https://help.nextcloud.com

**Comment by provokateurin** [comment]
@ebao-mis unfortunately the logs you are from a 2 hour period which prevents narrowing down the problem.
Since nobody else seems to have this problem I will close this issue for now. Please re-open if this issue is still relevant to you.
