### ISSUE TITLE
ACL permissions are not shown in Files sidebar

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/groupfolders#2637]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Javascript code fails here with `client === undefined`:
https://github.com/nextcloud/groupfolders/blob/e601d498ad7d497424ae5ea0807db7f95aee72be/src/client.js#L190

### Steps to reproduce
1. Create a groupfolder
2. Enable advanced permissions
3. Open Sharing tab in Files sidebar

### Expected behaviour

Table for setting ACL should be visible to user (screenshot from NC v27, groupfolders 15.3.1, console errors unrelated)
![image](https://github.com/nextcloud/groupfolders/assets/93392545/f0105b73-278f-47ba-8780-b829f4086e7d)

client object is
```
{
    "_root": "/remote.php/dav/files/admin",
    "_host": "stable27.local",
    "_defaultHeaders": {
        "X-Requested-With": "XMLHttpRequest",
        "requesttoken": "token"
    },
    "_baseUrl": "https://stable27.local/remote.php/dav/files/admin",
    "_client": {..},
    "_fileInfoParsers": [..],
    "_propfindProperties": [..]
}
```

### Actual behaviour

Table is missing due to JS failed (screenshot from NC v28, groupfolders 16.0.0)
![image](https://github.com/nextcloud/groupfolders/assets/93392545/37b12c19-3f65-467a-8121-162716ebb3b7)

### Server configuration

**Nextcloud version:** 28+

**Group folders version:** 16.0.0

#### Browser log
<details>
<summary>Browser log</summary>
```
vue.runtime.esm.js:3049 TypeError: Cannot read properties of undefined (reading 'getFileInfo')
    at e.value (client.js:190:17)
    at o.loadAcls (SharingSidebarView.vue:247:1)
    at o.beforeMount (SharingSidebarView.vue:240:1)
    at bn (vue.runtime.esm.js:3017:61)
    at pa (vue.runtime.esm.js:4031:13)
    at e (vue.runtime.esm.js:3854:5)
    at ii.$mount (vue.runtime.esm.js:8772:12)
    at init (vue.runtime.esm.js:4411:19)
    at vue.runtime.esm.js:6571:17
    at h (vue.runtime.esm.js:6525:13)
```
</details>

**Comment by Antreesy** [comment]
This code doesn't called:
https://github.com/nextcloud/groupfolders/blob/e601d498ad7d497424ae5ea0807db7f95aee72be/src/client.js#L143

So I'm assuming, it's on Files app side (`OCA.Files.FileList` is not initialized, which happens on stable27)

**Comment by come-nc** [comment]
ping @susnux @artonge I have this behavior as well, but with other errors:
```
[ERROR] files: Header workspace already registered
Object { app: "files", uid: "admin", level: 0, header: {…} }
ConsoleLogger.js:74:18

15:05
TypeError: i is undefined
propFind client.js:190
loadAcls SharingSidebarView.vue:247
beforeMount SharingSidebarView.vue:240
VueJS 18
mount files_sharing_tab.js:74
mounted SidebarTab.vue:121
VueJS 19
open Sidebar.vue:481
exec sidebarAction.ts:49
openDetailsIfAvailable FileEntry.vue:250
VueJS 33
vue.runtime.esm.js:3049:16

15:05
A setting with the same name is already registered Settings.js:41:11
```

**Comment by limatus** [comment]
Is there any update on the NC 28 version? It has been updated and merged for the other branches, and I am looking forward to having this functionality again. 😉

**Comment by Antreesy** [comment]
> Is there any update on the NC 28 version?

Hi! I have merged only inherited permissions fix fir other branches, current issue is unrelated

**Comment by Innky-Joe** [comment]
![Untitled](https://github.com/nextcloud/groupfolders/assets/156313232/5f81be5a-f23f-4b51-a962-7a19f145ad58)


I am running Group folders by Robin Appelman AGPL-licensed 16.0.1 on NC V.28 and add advanced permission rule not showing, can anyone help me out?

Related resources
Anything shared with the same group of people will show up here
