### ISSUE TITLE
No sync since update to version 2.0.1 path needs to be relativ...

### ISSUE THREAD

**Issue by Kiter1988** [nextcloud/groupfolders#265]
Hi, 

i have updatet to 2.0.1, some fatal errors are there.
The Win10 client says "path needs to be relative to the system wide data folder and point to a user specific fil"
Nextcloud version is 14.0.4
Groupfolders version 2.0.2 now. 

Can anyone help me ? 
I dont have a ssh access

`Sabre\DAV\Exception: path needs to be relative to the system wide data folder and point to a user specific file

    /www/htdocs/XXXXXX/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 230:

    OCA\DAV\Connector\Sabre\File->convertToSabreException(BadMethodCallException {})

    /www/htdocs/XXXXXX/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:

    OCA\DAV\Connector\Sabre\File->put(null)

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:

    OCA\DAV\Connector\Sabre\Directory->createFile("Neues Textdokument.txt", null)

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529:

    Sabre\DAV\Server->createFile("files/Chris ... t", null, null)

    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

    call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:

    Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /www/htdocs/XXXXXX/nextcloud/apps/dav/lib/Server.php - line 293:

    Sabre\DAV\Server->exec()

    /www/htdocs/XXXXXX/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /www/htdocs/XXXXXX/nextcloud/remote.php - line 163:

    require_once("/www/htdocs ... p")

Eingefasst vonBadMethodCallException: path needs to be relative to the system wide data folder and point to a user specific file

    /www/htdocs/XXXXXX/nextcloud/lib/private/Encryption/Keys/Storage.php - line 347:

    OC\Encryption\Util->getUidAndFilename("/__groupfol ... t")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Encryption/Keys/Storage.php - line 274:

    OC\Encryption\Keys\Storage->getPathToKeys("/__groupfol ... t")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php - line 282:

    OC\Encryption\Keys\Storage->renameKeys("/__groupfol ... t", "/__groupfol ... t")

    /www/htdocs/XXXXXX/nextcloud/apps/files_trashbin/lib/Storage.php - line 163:

    OC\Files\Storage\Wrapper\Encryption->rename("/__groupfol ... t", "/__groupfol ... t")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Jail.php - line 281:

    OCA\Files_Trashbin\Storage->rename("/__groupfol ... t", "/__groupfol ... t")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 276:

    OC\Files\Storage\Wrapper\Jail->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php - line 88:

    OC\Files\Storage\Wrapper\Wrapper->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 276:

    OC\Files\Storage\Wrapper\PermissionsMask->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 276:

    OC\Files\Storage\Wrapper\Wrapper->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php - line 299:

    OC\Files\Storage\Wrapper\Wrapper->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php - line 269:

    OC\Files\Storage\Wrapper\Availability->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/apps/files_trashbin/lib/Storage.php - line 163:

    OC\Files\Storage\Wrapper\Encryption->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 570:

    OCA\Files_Trashbin\Storage->rename("Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 220:

    OC\Files\Storage\Wrapper\Wrapper->moveFromStorage(OCA\Files_Tr ... l}, "Neues Textd ... t", "Neues Textdokument.txt")

    /www/htdocs/XXXXXX/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:

    OCA\DAV\Connector\Sabre\File->put(null)

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:

    OCA\DAV\Connector\Sabre\Directory->createFile("Neues Textdokument.txt", null)

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529:

    Sabre\DAV\Server->createFile("files/Chris ... t", null, null)

    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

    call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:

    Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])

    /www/htdocs/XXXXXX/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

    /www/htdocs/XXXXXX/nextcloud/apps/dav/lib/Server.php - line 293:

    Sabre\DAV\Server->exec()

    /www/htdocs/XXXXXX/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /www/htdocs/XXXXXX/nextcloud/remote.php - line 163:

    require_once("/www/htdocs ... p")`

**Comment by Cardes** [comment]
Same issue here plus webupload gives internal server error.

What further information is needed?

Cheers

**Comment by Henk57** [comment]
This problem could be related to recent Nginx. I've switched to Apache and the problem of incorrect links was gone.
On multiple sites are instructions how to correct the redirect in the Nginx install. Nginx does not read .htaccess.

**Comment by sunchezz89** [comment]
Same issue here, whith Apache.

System specs
Ubuntu 16.04.5 LTS
PHP 7.0.32-0ubuntu0.16.04.1
NC 15.0.2
Apache/2.4.37
GF 2.0.2

**Comment by Cardes** [comment]
I could'nt find a way to get groufolders to work again so i changed the setup and ended up using external storage app with "local" folders. This may also be an option for others with filesystem access.

**Comment by sunchezz89** [comment]
i disabled encryption completly and now everything is working as expected

**Comment by pierreozoux** [comment]
encryptionis not yet supported.
