### ISSUE TITLE
Timestamp in filename issue

### ISSUE THREAD

**Issue by come-nc** [nextcloud/groupfolders#2657]
I am not completely sure how this affects features, but there is an inconsistency between file URL in UI and database.

The issue is that files_trashbin/Sabre/TrashFile uses getLastModified to build the filename, while in other places we use deleted_time.

I think for legacy backend mtime and deletedtime are the same thing because in `apps/files_trashbin/lib/Helper.php:88` the timestamp from filename is put in mtime.

We can either change groupfolders trashbin backend to fake mtime to deleted_time or change files_trashbin to consistently use getDeletedTime instead of getLastModified or getMTime.

**Comment by come-nc** [comment]
@icewind1991 I think we can close this one?

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/groupfolders/pull/2714#issuecomment-1877092784
Fixed in nextcloud/server#42558
