### ISSUE TITLE
Impossible to share group folders with circles you are not member of

### ISSUE THREAD

**Issue by dwaxweiler** [nextcloud/groupfolders#2665]
### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Make sure you are admin of a Nextcloud instance.
2. Create user U.
3. User U creates circle C.
4. You create a group folder.
5. You click the pencil button in the column "Group or circle".
6. You click in the "Add group or circle" field.

### Expected behaviour
Circle C should be shown in the drop-down list. As an administrator, it should not be necessary for me to be in the circles I want to share a group folder with.

### Actual behaviour
Circle C is not shown in the drop-down list.

### Server configuration

**Nextcloud version:** 27.1.4

**Group folders version:** 15.3.1

**Are you using an external user-backend, if yes which one:** no

**Comment by dwaxweiler** [comment]
Workaround:
1. Create a new group, such as "Group folder management", for user U.
2. Under "Administrative privileges", assign this group to "Group folders".
3. Let user U assign circle C to the group folder.

As an administrator, I will then see the IDs instead of the names of the circles on the group folders page. I can also change their permissions (write, share, delete, unsharing).

This is a risky workaround as I give more privileges to people than they need, and I need to explain how it works to them.

**Comment by chkpnt** [comment]
This issue severely limits the usefulness of using circles with group folders.

Another workaround is to add the NC admin temporarily to the circle by the circle owner, admin or moderator. After the NC admin has left the circle, only the IDs are shown on the group folders page, which is quite awkward:

![grafik](https://github.com/nextcloud/groupfolders/assets/1956979/53324083-72c2-495a-9bca-95a48e6126ce)

**Comment by joshtrichards** [comment]
This is a Circles (now Teams) matter, not Group Folders. It currently functions as expected based on implementation based on my understanding.

See nextcloud/circles#188

**Comment by fabieins** [comment]
> This is a Circles (now Teams) matter, not Group Folders. It currently functions as expected based on implementation based on my understanding.
> 
> See [nextcloud/circles#188](https://github.com/nextcloud/circles/issues/188)

This Addon is called "Team folders" now - so as an nextcloud Admin i expect to create a "Team Folder" for Teams even if i'm not a member of this Team.

Or even better - a Team Admin can create a "Team Folder" for his Team. This Folder should not be connected to this user - as this Folder should be usable for the Team even if this Admin leaves the Team.
