### ISSUE TITLE
Issue with sharing documents from group folders for "admin" group

### ISSUE THREAD

**Issue by ukrainizator** [nextcloud/groupfolders#2666]
I’m having trouble sharing files and folders from group folders via public link. Interesting fact: all users except one user in group "admin" and **admin** can share documents from group folders. I can create an external link from these two accounts, but I cannot edit it and if someone tries to use this link, they will receive the message: “The page was not found on the server or you may not have permission to view it.” When I add any user to the “admin” group, this user loses the ability to share files from group folders (i.e. a link is created, but when opening this link the above-mentioned message appears). Even if you later remove this user from the group “admin”, the ability to share does not return.
p.s. users log in to Nextcloud using ldap.

**Steps to reproduce:**
1. add user to group "admin";
2. let the user share any file or folder from groupfolder by creating a public link;
3. copy and send the link to any recipient;
4. try opening the public link on another computer -> you will receive the message: “The page was not found on the server or you may not have permission to view it.”

**Expected behaviour:**
Link opens the shared file or folder in the browser

**Actual behaviour:**
Link opens the error page “The page was not found on the server or you may not have permission to view it.”

Operating system: Debian GNU/Linux 11 (bullseye)
Web server: Apache/2.4.56
Database: 10.5.21-MariaDB-0+deb11u1
PHP version: PHP 8.2.11
Nextcloud version: 27.1.4
Group folders version: 15.3.1
Files sharing version: 1.19.0

Nextcloud updated from an older Nextcloud install.
Are you using external storage, if yes which one: local
Are you using an external user-backend, if yes which one: LDAP

**Client configuration**
Browser: Chrome or Firefox
Operating system: Windows 10 Enterprise

**Logs**

Web server error log (/var/log/apache2/error.log)
<details>
<summary>Web server error log</summary>
[Mon Dec 11 00:00:01.812523 2023] [http2:warn] [pid 723] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Mon Dec 11 00:00:01.838860 2023] [mpm_prefork:notice] [pid 723] AH00163: Apache/2.4.56 (Debian) OpenSSL/1.1.1w configured -- resuming normal operations
[Mon Dec 11 00:00:01.838875 2023] [core:notice] [pid 723] AH00094: Command line: '/usr/sbin/apache2'
</details>

Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"ttHs3o8nf9fUHpAqYrQR","level":3,"time":"December 11, 2023 07:55:03","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )","userAgent":"--","version":"27.1.4.1","exception":{"Exception":"OC\\User\\NoUserException","Message":"Backends provided no user object","Code":0,"Trace":[{"function":"getUserFolder","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/LazyFolder.php","line":74,"function":"call_user_func_array"},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php","line":40,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":73,"function":"getUserFolder","class":"OC\\Files\\Node\\LazyRoot","type":"->"},{"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":72,"function":"getVersionsForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":59,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/var/www/html/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":43,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/html/nextcloud/lib/private/Files/Node/Root.php","Line":364,"message":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )","exception":{},"CustomMessage":"Error while running background job (class: OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions, arguments: )"}}
</details>

Browser log
<details>
<summary>Browser log</summary>
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="pl" data-locale="pl" translate="no" >
	<head
 data-requesttoken="E4b42BH4KBPgYnYr+3AOx5OiZ7OHu34a+uFNcRnQk+Y=:VPGrinCvZCKoJzBzviN9/sTwTPrz80l5qrcDKXrg+JY=">
		<meta charset="utf-8">
		<title>
			Nextcloud		</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#0082c9">
		<link rel="icon" href="/core/img/favicon.ico">
		<link rel="apple-touch-icon" href="/core/img/favicon-touch.png">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
		<link rel="manifest" href="/apps/theming/manifest?v=17ba0791">
		<link rel="stylesheet" href="/core/css/server.css?v=b250ff31-11">
<link rel="stylesheet" href="/apps/theming/css/default.css?v=34e90de1-11">
<link rel="stylesheet" href="/core/css/guest.css?v=b250ff31-11">
		<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/dist/core-common.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/dist/core-main.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/core/l10n/pl.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/dist/core-files_fileinfo.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/dist/core-files_client.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/js/core/merged-template-prepend.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/apps/files_sharing/l10n/pl.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/dist/files_sharing-main.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/apps/theming/l10n/pl.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=" defer src="/apps/theming/js/theming.js?v=b250ff31-11"></script>
<script nonce="RTRiNDJCSDRLQlBnWW5ZciszQU94NU9pWjdPSHUzNGErdUZOY1JuUWsrWT06VlBHcmluQ3ZaQ0tvSnpCenZpTjkvc1R3VFByejgwbDVxcmNES1hyZytKWT0=">
var _oc_debug=false;
var _oc_isadmin=false;
var backendAllowsPasswordConfirmation=true;
var oc_dataURL=false;
var _oc_webroot="";
var _oc_appswebroots={"activity":"/apps/activity","admin_audit":"/apps/admin_audit","bruteforcesettings":"/apps/bruteforcesettings","cfg_share_links":"/apps/cfg_share_links","cloud_federation_api":"/apps/cloud_federation_api","comments":"/apps/comments","dav":"/apps/dav","deck":"/apps/deck","federatedfilesharing":"/apps/federatedfilesharing","federation":"/apps/federation","files":"/apps/files","files_accesscontrol":"/apps/files_accesscontrol","files_external":"/apps/files_external","files_pdfviewer":"/apps/files_pdfviewer","files_reminders":"/apps/files_reminders","files_sharing":"/apps/files_sharing","files_trashbin":"/apps/files_trashbin","files_versions":"/apps/files_versions","forms":"/apps/forms","groupfolders":"/apps/groupfolders","logreader":"/apps/logreader","lookup_server_connector":"/apps/lookup_server_connector","nextcloud_announcements":"/apps/nextcloud_announcements","notifications":"/apps/notifications","oauth2":"/apps/oauth2","onlyoffice":"/apps/onlyoffice","password_policy":"/apps/password_policy","photos":"/apps/photos","privacy":"/apps/privacy","provisioning_api":"/apps/provisioning_api","recommendations":"/apps/recommendations","related_resources":"/apps/related_resources","serverinfo":"/apps/serverinfo","settings":"/apps/settings","sharebymail":"/apps/sharebymail","sharelisting":"/apps/sharelisting","support":"/apps/support","suspicious_login":"/apps/suspicious_login","text":"/apps/text","theming":"/apps/theming","twofactor_backupcodes":"/apps/twofactor_backupcodes","updatenotification":"/apps/updatenotification","user_ldap":"/apps/user_ldap","user_status":"/apps/user_status","viewer":"/apps/viewer","workflowengine":"/apps/workflowengine"};
var datepickerFormatDate="dd.MM.y";
var nc_lastLogin=0;
var nc_pageLoad=1702283696;
var dayNames=["Niedziela","Poniedzia\u0142ek","Wtorek","\u015aroda","Czwartek","Pi\u0105tek","Sobota"];
var dayNamesShort=["Nd.","Pon.","Wt.","\u015ar.","Czw.","Pt.","Sob."];
var dayNamesMin=["Nd","Pn","Wt","\u015ar","Czw","Pt","Sob"];
var monthNames=["Stycze\u0144","Luty","Marzec","Kwiecie\u0144","Maj","Czerwiec","Lipiec","Sierpie\u0144","Wrzesie\u0144","Pa\u017adziernik","Listopad","Grudzie\u0144"];
var monthNamesShort=["Sty.","Lut.","Mar.","Kwi.","Maj","Cze.","Lip.","Sie.","Wrz.","Pa\u017a.","Lis.","Gru."];
var firstDay=1;
var _oc_config={"auto_logout":false,"blacklist_files_regex":"\\.(part|filepart)$","loglevel":3,"lost_password_link":null,"modRewriteWorking":true,"no_unsupported_browser_warning":false,"session_keepalive":true,"session_lifetime":1440,"sharing.maxAutocompleteResults":25,"sharing.minSearchStringLength":0,"version":"27.1.4.1","versionstring":"27.1.4"};
var oc_appconfig={"core":{"defaultExpireDateEnabled":false,"defaultExpireDate":null,"defaultExpireDateEnforced":null,"enforcePasswordForPublicLink":false,"enableLinkPasswordByDefault":false,"sharingDisabledForUser":false,"resharingAllowed":false,"remoteShareAllowed":true,"federatedCloudShareDoc":"https:\/\/docs.nextcloud.com\/server\/27\/go.php?to=user-sharing-federated","allowGroupSharing":true,"defaultInternalExpireDateEnabled":false,"defaultInternalExpireDate":null,"defaultInternalExpireDateEnforced":null,"defaultRemoteExpireDateEnabled":false,"defaultRemoteExpireDate":null,"defaultRemoteExpireDateEnforced":null},"files":{"max_chunk_size":10485760}};
var _theme={"entity":"Nextcloud","name":"Nextcloud","productName":"Nextcloud","title":"Nextcloud","baseUrl":"https:\/\/chmura.poznan.pl","syncClientUrl":"https:\/\/nextcloud.com\/install\/#install-clients","docBaseUrl":"https:\/\/docs.nextcloud.com","docPlaceholderUrl":"https:\/\/docs.nextcloud.com\/server\/27\/go.php?to=PLACEHOLDER","slogan":"bezpieczny dom dla wszystkich Twoich danych","logoClaim":"","folder":""};

</script>
		<link rel="stylesheet" media="" href="/apps/theming/theme/default.css?plain=1&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: light)" href="/apps/theming/theme/light.css?plain=1&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark)" href="/apps/theming/theme/dark.css?plain=1&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="(prefers-contrast: more)" href="/apps/theming/theme/light-highcontrast.css?plain=1&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="(prefers-color-scheme: dark) and (prefers-contrast: more)" href="/apps/theming/theme/dark-highcontrast.css?plain=1&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light.css?plain=0&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark.css?plain=0&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/light-highcontrast.css?plain=0&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/dark-highcontrast.css?plain=0&amp;v=17ba0791" class="theme"/><link rel="stylesheet" media="" href="/apps/theming/theme/opendyslexic.css?plain=0&amp;v=17ba0791" class="theme"/><meta name="robots" content="noindex, nofollow"/>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Aplikacja do poprawnego działania wymaga JavaScript. <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">włącz JavaScript</a> i wczytaj stronę ponownie.		</div>
	</div>
</noscript>
					<input type="hidden" id="initial-state-core-projects_enabled" value="ZmFsc2U=">
					<input type="hidden" id="initial-state-core-config" value="eyJhdXRvX2xvZ291dCI6ZmFsc2UsImJsYWNrbGlzdF9maWxlc19yZWdleCI6IlxcLihwYXJ0fGZpbGVwYXJ0KSQiLCJsb2dsZXZlbCI6MywibG9zdF9wYXNzd29yZF9saW5rIjpudWxsLCJtb2RSZXdyaXRlV29ya2luZyI6dHJ1ZSwibm9fdW5zdXBwb3J0ZWRfYnJvd3Nlcl93YXJuaW5nIjpmYWxzZSwic2Vzc2lvbl9rZWVwYWxpdmUiOnRydWUsInNlc3Npb25fbGlmZXRpbWUiOjE0NDAsInNoYXJpbmcubWF4QXV0b2NvbXBsZXRlUmVzdWx0cyI6MjUsInNoYXJpbmcubWluU2VhcmNoU3RyaW5nTGVuZ3RoIjowLCJ2ZXJzaW9uIjoiMjcuMS40LjEiLCJ2ZXJzaW9uc3RyaW5nIjoiMjcuMS40In0=">
					<input type="hidden" id="initial-state-core-capabilities" value="eyJjb3JlIjp7InBvbGxpbnRlcnZhbCI6NjAsIndlYmRhdi1yb290IjoicmVtb3RlLnBocFwvd2ViZGF2IiwicmVmZXJlbmNlLWFwaSI6dHJ1ZSwicmVmZXJlbmNlLXJlZ2V4IjoiKFxcc3xcXG58XikoaHR0cHM/OlxcXC9cXFwvKSgoPzpbLUEtWjAtOStfXStcXC4pK1stQS1aXSsoPzpcXFwvWy1BLVowLTkrJkAjJT89fl98ITosLjsoKV0qKSopKFxcc3xcXG58JCkifSwibWV0YWRhdGFBdmFpbGFibGUiOnsic2l6ZSI6WyJcL2ltYWdlXFxcLyhwbmd8anBlZ3xoZWlmfHdlYnB8dGlmZilcLyJdLCJncHMiOlsiXC9pbWFnZVxcXC8ocG5nfGpwZWd8aGVpZnx3ZWJwfHRpZmYpXC8iXX0sImZpbGVzIjp7ImJpZ2ZpbGVjaHVua2luZyI6dHJ1ZSwiYmxhY2tsaXN0ZWRfZmlsZXMiOlsiLmh0YWNjZXNzIl0sImNvbW1lbnRzIjp0cnVlLCJ1bmRlbGV0ZSI6dHJ1ZSwidmVyc2lvbmluZyI6dHJ1ZSwidmVyc2lvbl9sYWJlbGluZyI6dHJ1ZSwidmVyc2lvbl9kZWxldGlvbiI6dHJ1ZX0sImFjdGl2aXR5Ijp7ImFwaXYyIjpbImZpbHRlcnMiLCJmaWx0ZXJzLWFwaSIsInByZXZpZXdzIiwicmljaC1zdHJpbmdzIl19LCJvY20iOnsiZW5hYmxlZCI6dHJ1ZSwiYXBpVmVyc2lvbiI6IjEuMC1wcm9wb3NhbDEiLCJlbmRQb2ludCI6Imh0dHBzOlwvXC9uZXh0Y2xvdWQud29kci5wb3puYW4ucGw6ODQ0M1wvb2NtIiwicmVzb3VyY2VUeXBlcyI6W3sibmFtZSI6ImZpbGUiLCJzaGFyZVR5cGVzIjpbInVzZXIiLCJncm91cCJdLCJwcm90b2NvbHMiOnsid2ViZGF2IjoiXC9wdWJsaWMucGhwXC93ZWJkYXZcLyJ9fV19LCJkYXYiOnsiY2h1bmtpbmciOiIxLjAiLCJidWxrdXBsb2FkIjoiMS4wIn0sImRlY2siOnsidmVyc2lvbiI6IjEuMTEuMiIsImNhbkNyZWF0ZUJvYXJkcyI6dHJ1ZSwiYXBpVmVyc2lvbnMiOlsiMS4wIiwiMS4xIl19LCJmaWxlc19zaGFyaW5nIjp7ImFwaV9lbmFibGVkIjp0cnVlLCJwdWJsaWMiOnsiZW5hYmxlZCI6dHJ1ZSwicGFzc3dvcmQiOnsiZW5mb3JjZWQiOmZhbHNlLCJhc2tGb3JPcHRpb25hbFBhc3N3b3JkIjpmYWxzZX0sImV4cGlyZV9kYXRlIjp7ImVuYWJsZWQiOmZhbHNlfSwibXVsdGlwbGVfbGlua3MiOnRydWUsImV4cGlyZV9kYXRlX2ludGVybmFsIjp7ImVuYWJsZWQiOmZhbHNlfSwiZXhwaXJlX2RhdGVfcmVtb3RlIjp7ImVuYWJsZWQiOmZhbHNlfSwic2VuZF9tYWlsIjpmYWxzZSwidXBsb2FkIjp0cnVlLCJ1cGxvYWRfZmlsZXNfZHJvcCI6dHJ1ZX0sInJlc2hhcmluZyI6ZmFsc2UsInVzZXIiOnsic2VuZF9tYWlsIjpmYWxzZSwiZXhwaXJlX2RhdGUiOnsiZW5hYmxlZCI6dHJ1ZX19LCJncm91cF9zaGFyaW5nIjp0cnVlLCJncm91cCI6eyJlbmFibGVkIjp0cnVlLCJleHBpcmVfZGF0ZSI6eyJlbmFibGVkIjp0cnVlfX0sImRlZmF1bHRfcGVybWlzc2lvbnMiOjIzLCJmZWRlcmF0aW9uIjp7Im91dGdvaW5nIjp0cnVlLCJpbmNvbWluZyI6dHJ1ZSwiZXhwaXJlX2RhdGUiOnsiZW5hYmxlZCI6dHJ1ZX0sImV4cGlyZV9kYXRlX3N1cHBvcnRlZCI6eyJlbmFibGVkIjp0cnVlfX0sInNoYXJlZSI6eyJxdWVyeV9sb29rdXBfZGVmYXVsdCI6ZmFsc2UsImFsd2F5c19zaG93X3VuaXF1ZSI6dHJ1ZX0sInNoYXJlYnltYWlsIjp7ImVuYWJsZWQiOnRydWUsInNlbmRfcGFzc3dvcmRfYnlfbWFpbCI6dHJ1ZSwidXBsb2FkX2ZpbGVzX2Ryb3AiOnsiZW5hYmxlZCI6dHJ1ZX0sInBhc3N3b3JkIjp7ImVuYWJsZWQiOnRydWUsImVuZm9yY2VkIjpmYWxzZX0sImV4cGlyZV9kYXRlIjp7ImVuYWJsZWQiOnRydWUsImVuZm9yY2VkIjpmYWxzZX19fSwiZm9ybXMiOnsidmVyc2lvbiI6IjMuNC4yIiwiYXBpVmVyc2lvbnMiOlsidjIiLCJ2Mi4xIl19LCJub3RpZmljYXRpb25zIjp7Im9jcy1lbmRwb2ludHMiOlsibGlzdCIsImdldCIsImRlbGV0ZSIsImRlbGV0ZS1hbGwiLCJpY29ucyIsInJpY2gtc3RyaW5ncyIsImFjdGlvbi13ZWIiLCJ1c2VyLXN0YXR1cyIsImV4aXN0cyJdLCJwdXNoIjpbImRldmljZXMiLCJvYmplY3QtZGF0YSIsImRlbGV0ZSJdLCJhZG1pbi1ub3RpZmljYXRpb25zIjpbIm9jcyIsImNsaSJdfSwicGFzc3dvcmRfcG9saWN5Ijp7Im1pbkxlbmd0aCI6MTAsImVuZm9yY2VOb25Db21tb25QYXNzd29yZCI6dHJ1ZSwiZW5mb3JjZU51bWVyaWNDaGFyYWN0ZXJzIjp0cnVlLCJlbmZvcmNlU3BlY2lhbENoYXJhY3RlcnMiOnRydWUsImVuZm9yY2VVcHBlckxvd2VyQ2FzZSI6dHJ1ZSwiYXBpIjp7ImdlbmVyYXRlIjoiaHR0cHM6XC9cL25leHRjbG91ZC53b2RyLnBvem5hbi5wbDo4NDQzXC9vY3NcL3YyLnBocFwvYXBwc1wvcGFzc3dvcmRfcG9saWN5XC9hcGlcL3YxXC9nZW5lcmF0ZSIsInZhbGlkYXRlIjoiaHR0cHM6XC9cL25leHRjbG91ZC53b2RyLnBvem5hbi5wbDo4NDQzXC9vY3NcL3YyLnBocFwvYXBwc1wvcGFzc3dvcmRfcG9saWN5XC9hcGlcL3YxXC92YWxpZGF0ZSJ9fSwicHJvdmlzaW9uaW5nX2FwaSI6eyJ2ZXJzaW9uIjoiMS4xNy4wIiwiQWNjb3VudFByb3BlcnR5U2NvcGVzVmVyc2lvbiI6MiwiQWNjb3VudFByb3BlcnR5U2NvcGVzRmVkZXJhdGVkRW5hYmxlZCI6dHJ1ZSwiQWNjb3VudFByb3BlcnR5U2NvcGVzUHVibGlzaGVkRW5hYmxlZCI6dHJ1ZX0sInRoZW1pbmciOnsibmFtZSI6Ik5leHRjbG91ZCIsInVybCI6Imh0dHBzOlwvXC9uZXh0Y2xvdWQud29kci5wb3puYW4ucGwiLCJzbG9nYW4iOiJiZXpwaWVjem55IGRvbSBkbGEgd3N6eXN0a2ljaCBUd29pY2ggZGFueWNoIiwiY29sb3IiOiIjMDA4MmM5IiwiY29sb3ItdGV4dCI6IiNmZmZmZmYiLCJjb2xvci1lbGVtZW50IjoiIzAwODJjOSIsImNvbG9yLWVsZW1lbnQtYnJpZ2h0IjoiIzAwODJjOSIsImNvbG9yLWVsZW1lbnQtZGFyayI6IiMwMDgyYzkiLCJsb2dvIjoiaHR0cHM6XC9cL25leHRjbG91ZC53b2RyLnBvem5hbi5wbDo4NDQzXC9hcHBzXC90aGVtaW5nXC9pbWFnZVwvbG9nbz91c2VTdmc9MSZ2PTExIiwiYmFja2dyb3VuZCI6Imh0dHBzOlwvXC9uZXh0Y2xvdWQud29kci5wb3puYW4ucGw6ODQ0M1wvYXBwc1wvdGhlbWluZ1wvaW1nXC9iYWNrZ3JvdW5kXC9rYW1pbC1wb3JlbWJpbnNraS1jbG91ZHMuanBnIiwiYmFja2dyb3VuZC1wbGFpbiI6ZmFsc2UsImJhY2tncm91bmQtZGVmYXVsdCI6dHJ1ZSwibG9nb2hlYWRlciI6Imh0dHBzOlwvXC9uZXh0Y2xvdWQud29kci5wb3puYW4ucGw6ODQ0M1wvYXBwc1wvdGhlbWluZ1wvaW1hZ2VcL2xvZ28/dXNlU3ZnPTEmdj0xMSIsImZhdmljb24iOiJodHRwczpcL1wvbmV4dGNsb3VkLndvZHIucG96bmFuLnBsOjg0NDNcL2FwcHNcL3RoZW1pbmdcL2ltYWdlXC9sb2dvP3VzZVN2Zz0xJnY9MTEifSwidXNlcl9zdGF0dXMiOnsiZW5hYmxlZCI6dHJ1ZSwicmVzdG9yZSI6dHJ1ZSwic3VwcG9ydHNfZW1vamkiOnRydWV9fQ==">
					<input type="hidden" id="initial-state-core-versionHash" value="ImIyNTBmZjMxIg==">
					<input type="hidden" id="initial-state-theming-data" value="eyJuYW1lIjoiTmV4dGNsb3VkIiwidXJsIjoiaHR0cHM6XC9cL25leHRjbG91ZC53b2RyLnBvem5hbi5wbCIsInNsb2dhbiI6ImJlenBpZWN6bnkgZG9tIGRsYSB3c3p5c3RraWNoIFR3b2ljaCBkYW55Y2giLCJjb2xvciI6IiMwMDgyYzkiLCJkZWZhdWx0Q29sb3IiOiIjMDA4MmM5IiwiaW1wcmludFVybCI6IiIsInByaXZhY3lVcmwiOiJodHRwczpcL1wvd3d3LndvZHIucG96bmFuLnBsXC9rb250YWt0XC9yb2RvIiwiaW52ZXJ0ZWQiOmZhbHNlLCJjYWNoZUJ1c3RlciI6IjE3YmEwNzkxIiwiZW5hYmxlZFRoZW1lcyI6W119">
					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo"></div>
						</div>
					</header>
								<main>
					<h1 class="hidden-visually">
						Nextcloud					</h1>
						<div class="body-login-container update">
		<div class="icon-big icon-search"></div>
		<h2>Nie znaleziono strony</h2>
		<p class="infogroup">Strona nie została znaleziona na serwerze lub możesz nie mieć uprawnień do jej przeglądania.</p>
		<p><a class="button primary" href="/">
			Powrót do Nextcloud		</a></p>
	</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo" class="guest-box">
			<p class="info">
				<a href="https://chmura.poznan.pl" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – bezpieczny dom dla wszystkich Twoich danych<br/><a href="https://chmura.poznan.pl/kontakt/rodo" class="legal" target="_blank" rel="noreferrer noopener">Polityka prywatności</a>			</p>
		</footer>
	</body>
</html>

</details>

**Comment by provokateurin** [comment]
Could not reproduce. Please provide more information about the steps to reproduce and re-open if necessary.
