### ISSUE TITLE
TypeError: Argument 1 passed to OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionsFolder() must be of the type int, string given, called in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154

### ISSUE THREAD

**Issue by mtippmann** [nextcloud/groupfolders#267]
NC: 15 
Groupfolders: 2.0.2 

Seeing this in the Logfile from cron (that run's with php7.3 cli) - so it's maybe a PHP7.3 related error. 

```json
{
  "reqId": "bbg4JJ8VemzDijAzZ2uh",
  "level": 3,
  "time": "2018-12-18T21:15:05+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "cron",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "TypeError",
    "Message": "Argument 1 passed to OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionsFolder() must be of the type int, string given, called in /var/www/nextcloud/apps/
groupfolders/lib/Versions/VersionsBackend.php on line 154",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php",
        "line": 154,
        "function": "getVersionsFolder",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->",
        "args": [
          "1"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 53,
        "function": "getAllVersionedFiles",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->",
        "args": [
          {
            "id": "1",
            "mount_point": "StuRa",
            "groups": {
              "StuRa": "31"
            },
            "quota": "-3",
            "size": 0
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php",
        "line": 40,
        "function": "expireAll",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/nextcloud/lib/private/BackgroundJob/Job.php",
        "line": 61,
        "function": "run",
        "class": "OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions",
        "type": "->",
        "args": [
          null
        ]
      },

      {
        "file": "/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php",
        "line": 55,
        "function": "execute",
        "class": "OC\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/cron.php",
        "line": 123,
        "function": "execute",
        "class": "OC\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      }
    ],
    "File": "/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php",
    "Line": 189,
    "CustomMessage": "--"
  },
  "userAgent": "--",
  "version": "15.0.0.10"
}
```

**Comment by karottenbaum** [comment]
I'm encountering this error regularly also. I'm running the cronjob with PHP 7.0.33.
```json
{"reqId":"OSFpw8Yg9fet4fWFKaLv","level":3,"time":"2018-12-19T08:30:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /var/www/html/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154","Code":0,"Trace":[{"file":"/var/www/html/apps/groupfolders/lib/Versions/VersionsBackend.php","line":154,"function":"getVersionsFolder","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->","args":["1"]},{"file":"/var/www/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":53,"function":"getAllVersionedFiles","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->","args":[{"id":"1","mount_point":"Familie","groups":{"group":"31"},"quota":"-3","size":0}]},{"file":"/var/www/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":48,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->","args":[{"id":"1","mount_point":"Familie","groups":{"group":"31"},"quota":"-3","size":0}]},{"file":"/var/www/html/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":40,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->","args":[]},{"file":"/var/www/html/lib/private/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->","args":[null]},{"file":"/var/www/html/lib/private/BackgroundJob/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/apps/groupfolders/lib/Versions/VersionsBackend.php","Line":189,"CustomMessage":"--"},"userAgent":"--","version":"15.0.0.10","id":"5c1a520b6cdc6"}
```

**Comment by freeyourcat** [comment]
I'm encountering exactly the same problem with cronjob and PHP 7.2 after upgrading to Nextcloud 5.0 and Group folders 2.0.2.

**Comment by DrDeath** [comment]
I think, it is not PHP related

php 7.0.30
Nextcloud 15.0.0
Group Folders 2.0.2

[cron] Error: TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /volume1/web/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154 at <<closure>>

0. /volume1/web/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php line 154
   getVersionsFolder("1")
1. /volume1/web/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 53
   getAllVersionedFiles({id: "1",mount_p ... 0})
2. /volume1/web/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 48
   expireFolder({id: "1",mount_p ... 0})
3. /volume1/web/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   expireAll()
4. /volume1/web/nextcloud/lib/private/BackgroundJob/Job.php line 61
   run(null)
5. /volume1/web/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   execute(OC\BackgroundJob\JobList {}, OC\Log {})
6. /volume1/web/nextcloud/cron.php line 146
   execute(OC\BackgroundJob\JobList {}, OC\Log {})

GET /cron.php
from xxx.xxx.xxx.xxx at 2019-01-01T08:48:39+00:00

**Comment by freeyourcat** [comment]
i agree, it seems to be a type mismatch problem in the group folder app.. can we label this issue as a bug?

**Comment by maghog** [comment]
Same problem...

[cron] Error: TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /var/www/owncloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154 at <<closure>>

0. /var/www/owncloud/apps/groupfolders/lib/Versions/VersionsBackend.php line 154
   getVersionsFolder("1")
1. /var/www/owncloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 53
   getAllVersionedFiles({id: "1",mount_p ... 0})
2. /var/www/owncloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 48
   expireFolder({id: "1",mount_p ... 0})
3. /var/www/owncloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   expireAll()
4. /var/www/owncloud/lib/private/BackgroundJob/Job.php line 61
   run(null)
5. /var/www/owncloud/lib/private/BackgroundJob/TimedJob.php line 55
   execute(OC\BackgroundJob\JobList {}, OC\Log {})
6. /var/www/owncloud/cron.php line 123
   execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-01-16T01:15:06+01:00

**Comment by BornToBeRoot** [comment]
Same issue

```
TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /var/www/html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154
/var/www/html/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php - line 154:

OCA\GroupFolders\Versions\VersionsBackend->getVersionsFolder("1")

/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 53:

OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles({ id: "1",mo ... 0})

/var/www/html/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php - line 48:

OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder({ id: "1",mo ... 0})

/var/www/html/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php - line 40:

OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()

/var/www/html/nextcloud/lib/private/BackgroundJob/Job.php - line 61:

OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)

/var/www/html/nextcloud/lib/private/BackgroundJob/TimedJob.php - line 55:

OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

/var/www/html/nextcloud/cron.php - line 123:

OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

**Comment by derdershat** [comment]
here too same issue

**Comment by tomastd** [comment]
Same issue here

  | TypeError: Argument  1 passed to  OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be  of the type integer, string given, called in  /var/www/html/alastria/apps/groupfolders/lib/Versions/VersionsBackend.php  on line 154
-- | --

**Comment by virusuk** [comment]
The same here 
TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154

**Comment by najcardboyz** [comment]
same issue 

{"reqId":"o9GNaEAYuTbkJs2AS164","level":3,"time":"2019-02-06T20:15:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /var/najacloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154","Code":0,"Trace":[{"file":"/var/najacloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":154,"function":"getVersionsFolder","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->","args":["1"]},{"file":"/var/najacloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":53,"function":"getAllVersionedFiles","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->","args":[{"id":"1","mount_point":"Folder Group","groups":[],"quota":"1073741274","size":0}]},{"file":"/var/najacloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":48,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->","args":[{"id":"1","mount_point":"Folder Group","groups":[],"quota":"1073741274","size":0}]},{"file":"/var/najacloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":40,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->","args":[]},{"file":"/var/najacloud/lib/private/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->","args":[null]},{"file":"/var/najacloud/lib/private/BackgroundJob/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/najacloud/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/najacloud/apps/groupfolders/lib/Versions/VersionsBackend.php","Line":189,"CustomMessage":"--"},"userAgent":"--","version":"15.0.2.0","id":"5c5b97e7cb1b8"}

**Comment by MinIsMin** [comment]
Please stop writing "same issue" without contributing further.
The bug is known and every new "same here" only spams the people who subscribed to this issue.

**Comment by Sprinterfreak** [comment]
Just a thought...
I changed apps/groupfolders/lib/Versions/VersionsBackend.php:154 to
`$versionsFolder = $this->getVersionsFolder((int)$folder['id']);`
added a forced cast to int. Now watch it over night. Sadly I can't force it to happen by running cron.php manually.

**Comment by Sprinterfreak** [comment]
No. Wasn't that easy. But today I noticed a little fuckup in the database

> $ occ groupfolders:list
> +-----------+-----------+---------------------------------------+-----------+---------+
> | Folder Id | Name      | Groups                                | Quota     | Size    |
> +-----------+-----------+---------------------------------------+-----------+---------+
> | 1         | FoO       | FoO: read, write, share, delete       | Unlimited | 66.6 MB |
> | 2         | Testgroup | Testgroup: read, write, share, delete | Unlimited | 10 MB   |
> | 4         | Drölftest | FoO: read, write, share, delete       | Unlimited | 5.3 MB  |
> |           |           | Drölftest: read, write, share, delete |           |         |
> +-----------+-----------+---------------------------------------+-----------+---------+

In my oppinion looks a bit suspicious. The group permissions don't match the group names and there is a definition without name and index?

**Comment by fwolfst** [comment]
@Sprinterfreak Did that work out? We could form a PR towards that.

**Comment by PpaiSanchez** [comment]
Hello, the mistake still exists. Since 18.12.2018 the error is known, and still it is not processed! When can a solution be expected?
Thank you.

Same on PHP 7.2 and NC 15.0.4.0 + Group folders 2.0.2:
[cron] Error: TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /var/www/html/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154 at <<closure>>

**Comment by Sprinterfreak** [comment]
@fwolfst worked out partially but moved the issue to the next level. I didn't invetigated it further until now but I think the cast should happen at that point where the array of group folder configuration is collected.
Still strange because I normally expect php to cast stuff on its own.

**Comment by Sprinterfreak** [comment]
Still not. Now it's complaining
> Undefined index: permissions at /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php#155
Needs further investigating.

**Comment by Sprinterfreak** [comment]
My PR forces id to be type integer instead of string wich solves this issue for me.
After that fixed a new error appeared in the code never reached before by the compiler. Someone tried to access indices wich cannot be supplied the way it was coded. If `$folder['permissions']` is really needed by mountProvider->getMount(), my code has to be improved again because I just allow it to be missing (null) at this point. Doesn't seem to be an issue. Moar coffee to the devs. :)

**Comment by PpaiSanchez** [comment]
Now under Settings - Group Folder - under Groups only a 0 is displayed.

**Comment by Sprinterfreak** [comment]
Kind of expected. The whole groupfolders expire manager module looks like someone has forgotten to stage half of his work during development. There are variables used, never defined before.
Like I mentioned earlier. I bet $folder['permissions'], wich is null at the moment and isn't possibly defined anywhere during previous execution because of entirely missing code, leads to this.
It didn't seem to affect the whole thing before, because the expire manager simply crashed entirely before beeing able to do anything. Now it's time to reverse engineer this thing and try to add the missing bits. @PpaiSanchez feel free to also participate.

**Comment by PpaiSanchez** [comment]
Thanks icewind1991, the code looks good now.

**Comment by Henk57** [comment]
The errror seems back with NC 22.
Exception: Argument 1 passed to OC\Group\Manager::getUserIdGroupIds() must be of the type string, null given, called in /home/xxxx/domains/xxxx.nl/public_html/cloud/lib/private/Group/Manager.php on line 316
