### ISSUE TITLE
After installing Groupfolders app, menu item no longer appears in the left sidebar

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/groupfolders#2670]
There seems to be issues registering the Groupfolders App after installation. For the user, the result is that the menu item will be missing from the left sidebar. This is a regression from previous versions. 

### Steps to reproduce
1. Install Groupfolders App
2. Navigate to Files App
3. Groupfolders menu item is missing from Files left-sidebar.

### Expected behaviour
Groupfolders menu item should appear on the left sidebar
![Bildschirmfoto 2023-12-13 um 10 45 46](https://github.com/nextcloud/groupfolders/assets/62374139/ae573baf-b5d7-4204-8854-19826dcd6061)

### Actual behaviour
Menu item is missing:
![Bildschirmfoto 2023-12-13 um 10 47 34](https://github.com/nextcloud/groupfolders/assets/62374139/b5304a14-85e8-4a60-8f87-f502dabf1008)

### Server configuration

Tested with https://github.com/szaimen/nextcloud-easy-test

**Nextcloud version: 28

**Group folders version: 16.0.0 

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from: https://github.com/szaimen/nextcloud-easy-test

### Client configuration
**Browser:*Chrome*

**Operating system:*MacOS*

#### Browser log
<details>
<summary>Browser log</summary>

```
main.ts:37 Uncaught TypeError: Cannot read properties of undefined (reading 'register')
    at main.ts:37:12
    at groupfolders.ts:113:2
    at groupfolders.ts:113:2
```
</details>

**Comment by artonge** [comment]
Should have been fixed by https://github.com/nextcloud/groupfolders/pull/2645
Are you on the latest 28 versions?

**Comment by solracsf** [comment]
@artonge has that been released?

**Comment by Dennis1993** [comment]
I think it i fixed right?
The version 16.0.1 has the #2640 in the changelog listed.
If the problem still exists feel free to open this issue again :)
