### ISSUE TITLE
Add option to "mount" a shared group folder at an arbitrary point in personal home directory and to not mount it at all

### ISSUE THREAD

**Issue by nagmat84** [nextcloud/groupfolders#2699]
Currently, a shared group folder appears at two locations:

 1. on the top level of "All Files" aka the "home" directory
 2. inside the navigation panel on the left hand side below the category "Group folders"

Bullet point 2 is fine, nothing to argue here. However, IMHO bullet point 1 is problematic and I would like to see an option to "mount" a shared group folder at an arbitrary point in personal home directory and to not mount it at all. (I use the term "mount" here in imitation of the Linux style to manage file system in lack of a better, alternative term.)

In case, a user decides not to mount a shared folder at all, the shared folder would only but still be accessible for that user via the navigation panel on the left below the category "Group Folders", however the group folder would not appear inside the normal directory tree (as the user has decided to not mount it).

There are two aspects why I believe the current approach is problematic: a) the purpose/meaning of the folder "All Files", b) the way how the desktop full clients sync group folders:

 * _Purpose/Meaning of "All Files":_ I admit the purpose of "All Files" is somewhat ambiguous. On the one hand, on could say as it is called "All Files" group folders should appear here. However, on the other hand, "All Files" is also the link to the top-level directory of a user's personal directory, i.e. "home" directory. IMHO, a users should have the freedom to organize their home directory to their liking. Shared group folders should not be put there forcefully, if a user would like to have them in a different location. Alternatively, one should create a new category inside the left navigation panel and clearly distinguish between "All Files" and "Home Directory". If the latter would exist, then "All Files" could stay as it is right now.
 * We (i.e. my family and I) use Nextcloud to sync our personal home directory across our shared devices (i.e. laptops, desktop PCs). However, the group folders should only be synced once to avoid file duplication. This currently not possible, if group folders appear as real folders inside each personal home directory. It would be much appreciated, if the Nextcloud Desktop Client would treat each group folder as independent data store which could be synced to a different, independent local location.
   The intended setup look like
    * On Linux, users use the desktop client to sync
        * their personal Nextcloud home directory to `/home/<user>/Documents`
        * the Nextcloud group folder `<xyz>` to `/home/shared/<xyz>` (assuming that `shared` is not used as home directory of a user which happens to have an account called `shared`)
    * On Windows, users use the desktop client to sync
        * their personal Nextcloud home directory to `C:\Users\<user>\Documents`
        * the Nextcloud group folder `<xyz>` to `C:\Users\Public\\<xyz>`
   
   Yes, I am aware that this approach still requires some manual labor to correctly setup up directory permissions for the shared folders on each client such that users have correct local read/write permissions on each device for the group folders they have access to. However, this is a step I am willing to take as the group folders are rather static and only setup once.
    However, we are six persons who share four devices and the current approach means that the group folders are duplicated for each user inside their home directory. This are several tons of GB of unnecessary data.

**Comment by provokateurin** [comment]
This usecase is completely out of scope for Groupfolders.
