### ISSUE TITLE
Change root folder for Group folders

### ISSUE THREAD

**Issue by jlanza** [nextcloud/groupfolders#270]
Is there any way to change the root folder for GF? Currently is the root of the user, but I would like to set it to, for instance GroupFolders or similar.

This is to better avoid having similar names as the ones set by users.

**Comment by rarapost** [comment]
Also iw would be fine to locate group folders in the left side pane - among "Recent", "Favorites", "Shared" ... etc
It would be the best to locate group folders to the left pane with the name that admin  gave them, and allow users to create link to them elsewhere in user's filesystem with different name (given by the user)

**Comment by icewind1991** [comment]
You can achieve this by "nesting" groupfolders, create a "Groupfolders" folder, and then a "Groupfolders/Foo" folder

**Comment by rarapost** [comment]
That's fine, thank you. But it still does not allow to locate the folder to the left pane and also move these folders alsewhere, as it is possible for normally shared folders. So I create new request on it.
