### ISSUE TITLE
Sharing via api not possible

### ISSUE THREAD

**Issue by pebosi** [nextcloud/groupfolders#271]
Created a new group folder "Groupfolder" added a folder "Test" and tried to share via shares api:

curl --request POST   --url 'https://box/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json'   --header 'authorization: Basic YWRtaW46blhngtTW9CSHEtb0dUZ0gtSkplZ0gtRGlDMmI='   --header 'content-type: application/x-www-form-urlencoded'   --header 'ocs-apirequest: true'   --data 'shareType=3&path=%2FGroupfolder%2FTest'

Resulted in Error 403.
Sharing the folder via Web-interface works as expected.

Recently updated to Nextcloud 15 and newest version of groupfolders. With Nextcloud 14, 13 it worked.

**Comment by pebosi** [comment]
The base64 string above is for sure not real. Tried differnt users with permissions to the group folder.

**Comment by JanUrlaub** [comment]
Same here. is there some new infos?

**Comment by ricain** [comment]
Same issue here but with APIv1
#nextcloud/ios/issues/795

**Comment by jospoortvliet** [comment]
Also mentioned here: https://github.com/nextcloud/server/issues/14189 - with some more example.

**Comment by juliushaertl** [comment]
From a quick look it seems that https://github.com/nextcloud/server/blob/b557f52c2290379b99838f86c7ab90892b955b41/lib/private/Share20/Manager.php#L296 is causing the issues here. The original node doesn't have an owner for files in a group folder. I'm not sure yet, why it does work in the web ui then, but maybe the mounts are set up differently with an active user session.

**Comment by ricain** [comment]
so this is a [nextcloud/server](https://github.com/nextcloud/server) bug and not a [nextcloud/groupfolder](https://github.com/nextcloud/groupfolders) issue ?

**Comment by radoslavius** [comment]
I found the reason and solution.

Reason:
When attempting to create a share, the nextcloud does not detect a correctly logged user. As @juliushaertl wrote: same code `$share->getNode()->getOwner()->getUID()` in `lib/private/Share20/Manager.php` returns empty string instead of username.

Solution:
So if you use the guzzle library, just set the 'cookies' parameter to true and call `GET /shares` (for example) before calling `POST /shares`. This way the user logs in and the share is created correctly.

Tested on version 16.0.4

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/groupfolders/issues/271 should fix this

**Comment by fuco809** [comment]
same issue here with latest v17 and with curl.

share a folder works.
share a groupfolder fails.

# curl -vvv -k -u "USER:PASS" -H "OCS-APIRequest: true" -X POST "https://mynextcloudserver.tld/ocs/v1.php/apps/files_sharing/api/v1/shares" -d path="/Folder" -d shareType=3
# curl -vvv -k -u "USER:PASS" -H "OCS-APIRequest: true" -X POST "https://mynextcloudserver.tld/ocs/v1.php/apps/files_sharing/api/v1/shares" -d path="/Groupfolder" -d shareType=3
USER is member of the groupfolder group with all rights.

fail response (in german)
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Kann die Berechtigungen von /GemeindenAdmin/files/Groupfolder nicht erhöhen</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>

**Comment by juliushaertl** [comment]
There is no release yet with the fix for Nextcloud 17 since the pull request has been merged just some days ago with https://github.com/nextcloud/groupfolders/pull/721

This should be fixed with the next maintenance release.
