### ISSUE TITLE
No versioning for files in group Folders

### ISSUE THREAD

**Issue by masterdot** [nextcloud/groupfolders#2718]
### Steps to reproduce
1. Create a group folder
2. create and change files in it
3. no versioning is done
4. "normal" files are versioned, group folder files seem to miss the changes
### Expected behavior 
Versioning history of all files, editable in nextcloud aio and the office component
### Actual behavior 
Files are just as they are, but there seems to be kind of versioning, in the activities are states of files, but just some. Maybe its saved not very often

### Host OS 
debian 12

#### Nextcloud AIO version 
27.1.5
#### Current channel 
stable

**Comment by vidlb** [comment]
Can confirm this issue in NC 27.1.5 , groupfolders 16.0.1
It does not affect files created prior to latest app update.

**Comment by gwnmikedus** [comment]
Confirm this for NC 27.1.4, group folders 15.3.2

No file version history is available (as far as I can see), I do hope the actual versioning isn't lost and its merely missing in the front-end.

In any other location (shared folder) or another non-group folder all history is working.

**Comment by vidlb** [comment]
@gwnmikedus yes I checked for one of the my files, versions still exists on the disk.  
You can find a file id (in the URL) and check for existing versions using `ls -alh <nextcloud data dir>/__groupfolders/<folder ID>/<file ID>`

**Comment by vagner-dias** [comment]
+1 same issue here
V27.1.5

**Comment by Serial32** [comment]
+1 same issue here
V27.1.5

**Comment by Constey** [comment]
+1 in V27.1.5 can confirm still exists

im not sure but is it possible that in NC 18.0.1 and group folders 16.0.1 this is fixed?

**Comment by heisian** [comment]
Didn't test too much but it seems sometimes versioning works and sometimes it doesn't. Although I have ZFS snapshots, they are more difficult to access for various reasons so it would be preferred to rely on built-in NextCloud versioning.

For now I have disabled use of Group Folders but I hope this gets addressed at some point in the future!

**Comment by vagner-dias** [comment]
I have just updated all my apps in Nextcloud and this issue seems fixed

**Comment by solracsf** [comment]
@hanzei what about 16.0.3?

**Comment by vidlb** [comment]
Seems fixed for me in NC 27 + app 15.3.4

**Comment by 0x326** [comment]
Can confirm. For Nextcloud 27.1.5 and Group Folders 15.3.4, edits to a `.ods` file via Collabora Online made another version.
![image](https://github.com/nextcloud/groupfolders/assets/20781397/65892001-c683-4a1d-bbc8-c03e3fca6753)

**Comment by tatrapikao** [comment]
Im on [Nextcloud Hub 8] (29.0.6) and groupfolders Version 17.0.3 and still affected by this.

**Comment by joshtrichards** [comment]
@tatrapikao Please provide reproduction steps that generate this problem in your environment. All of my testing is in 29.0.6 w/ 17.0.3.
