### ISSUE TITLE
Security issue: sharing allways possible

### ISSUE THREAD

**Issue by Tai-Pan-RX** [nextcloud/groupfolders#273]
Nextcloud version: 15.0.0
Group folders version: 2.0.2

I have created a group folder "Test" for the group "admin" **without** sharing permissions
![bildschirmfoto 2019-01-05 um 11 16 08](https://user-images.githubusercontent.com/46396531/50723428-d17da500-10dd-11e9-8937-b84fe17e60f8.png)

The subfolder "Subtest" of "Test" can't be shared as expected
![bildschirmfoto 2019-01-05 um 11 17 26](https://user-images.githubusercontent.com/46396531/50723446-0c7fd880-10de-11e9-982d-277b0265df10.png)

But the whole "Test" folder **can be shared**
![bildschirmfoto 2019-01-05 um 11 16 55](https://user-images.githubusercontent.com/46396531/50723450-16094080-10de-11e9-9785-436a5a5074da.png)

**Comment by kliver50** [comment]
Same issue.

**Comment by hottwister** [comment]
same
