### ISSUE TITLE
Ionos Managed Nextcloud : In a group folder, "Preview generator" thumbs can't be seen by read-only users

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/groupfolders#2740]
I don't know if the problem is related: 
- Group Folders
- Preview generator
- Ionos configuration

When I create a group folder and grant a user read-only rights (no write, create, delete or share rights), he won't see the preview thumbnails for files (e.g. images). To see them, I've discovered a workaround that consists in granting him creation rights too. This bypass is annoying from a functional and, of course, a safety point of view.

 I've never come across this anywhere other than Ionos Managed Nextcloud. 

I'm afraid they'll bury the problem (as they usually do when I point out a problem).

Has anyone ever seen or heard of this? How could we identify and fix this ... or assume that it's a configuration problem on the Ionos side.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Server configuration

**Operating system:** Linux 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64

**Web server:** nginx/1.24.0 (fpm-fcgi)

**Database:** mysql 10.5.19

**PHP version:** 8.2.9

**Nextcloud version:** 26.0.4 Enterprise - 26.0.4.3

**Group folders version:** 14.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** From an older one

**Where did you install Nextcloud from:** N/A

**Are you using external storage, if yes which one:** S3 (I think, not sure, but I've seen ""class": "\\OC\\Files\\ObjectStore\\S3"," in the system report.) 

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 121

**Operating system:** Ubuntu Desktop LTS 22.04

### Logs

Can be provided if necessary

#### Web server error log
<details>
Can be provided if necessary
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
Can be provided if necessary
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Can be provided if necessary
</details>

**Comment by koelle25** [comment]
I have the same problem on a self-hosted instance with local storage. So I think it's neither a problem of Ionos Managed nor S3 storage but actually something ACL/permission related.

Combination of Preview-Generator + Groupfolder + read-only Link-Share = Previews cannot be loaded (404 errors).

Without the Preview-Generator app this problem does NOT occur.

@Jerome-Herbinet Can you re-open the issue?

**Comment by icewind1991** [comment]
This is fixed in my testing with https://github.com/nextcloud/server/pull/39367
