### ISSUE TITLE
Problem with webdav after update to Nextcloud 28.01 from 27.1.5 - appears to be related to Group Folder app.

### ISSUE THREAD

**Issue by BillThomasNZ** [nextcloud/groupfolders#2753]
Running Nextloud 27.1.5 with Group Folder app version 15.3.3 (recently released I think). OS is Rocky Linux 9.3 with apache 2.4.57. PHP version is 8.2.14. MariaDB version 15.1 Distrib 10.5.22-MariaDB

If I proceed with the offer to update  to Nextcloud 28.01. The admin overview reports that webdav appears to be broken

messages like this are repeating in the log:

QueryNotFoundException Could not resolve OCA\GroupFolders\Helper\LazyFolder! Class “OCA\GroupFolders\Helper\LazyFolder” does not exist

PS. Disabling the Group Folders App causes the error to go away but I do need Group Folders. 

I tried the Nextcloud update before and after the update of the Group Folder app to version 15.3.3 with the same result.

For the time being I have backed out the Nextcloud update by restoring the VM from a backup image. 

### Steps to reproduce
1. Allow the update to Nextcloud 28.01 to proceed 
2. After the update completes, the admin overview is reporting that webdav appears to be broken.

If further diagnostics are required, I will need to run the update again as the logs were destroyed when I restored the VM from backup.

**Comment by joshtrichards** [comment]
> `QueryNotFoundException Could not resolve OCA\GroupFolders\Helper\LazyFolder! Class “OCA\GroupFolders\Helper\LazyFolder” does not exist`

Based on the reference to this class (Helper\LazyFolder), your group folders app isn't up-to-date. Not sure how that happened, but the file hasn't existed since v15.3.3 which was for NC27.

The version of group folders for NC28 is >v16.0.0 which won't have this problem. Can you see if there is a newer version offered under *Apps* in your environment? Also double check you don't have two versions installed somehow (like if you have two `apps` folders configured or something).

I can't replicate this problem in any of my environments on NC28.

**Comment by BillThomasNZ** [comment]
On https://apps.nextcloud.com/apps/groupfolders I see the following:

Releases
Nextcloud version 	Stable channel 	Nightly channel 	All releases
28 	16.0.2 	- 	28
27 	15.3.3 	- 	27

So perhaps all I needed to do was update group folders after applying the Nextcloud update.

**Comment by BillThomasNZ** [comment]
So I just ran the update again and it looks like Group Folders was updated to 16.0.2 as part of that process but I still get the errors:
"Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken."

Multiple log entries like this:

Error	files_versions	
QueryNotFoundException Could not resolve OCA\GroupFolders\Helper\LazyFolder! Class "OCA\GroupFolders\Helper\LazyFolder" does not exist

**Comment by BillThomasNZ** [comment]
So I decided to stop the web server services and restart them and it seems to have fixed the problem. The error messages have stopped and it is no longer reporting the "webdav seems to be broken" status. Maybe php-fpm had something cached from the old version?  Anyway thanks for your attention. It threw me a bit as I hadn't seen anything like that on previous upgardes.

**Comment by BillThomasNZ** [comment]
Fixed problem by restarting web server services after upgrade.
