### ISSUE TITLE
No file versions visible in Group Folders

### ISSUE THREAD

**Issue by Serial32** [nextcloud/groupfolders#2755]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Nextcloud 27.1.5
2. Install the App "Versions" v1.20.0
3. Install the App "Group folders" v15.3.3
4. Create a group folder
5. Navigate to the new group folder and create a text file
6. Edit the file and save the changes
7. Repeat step 6 multiple times

### Expected behaviour
Several versions of the file should be listed under Details / Versions.

### Actual behaviour
The area under Details / Versions is empty. However, if you look at the file system with the shell, you will find several file versions. These are only not displayed in the web browser. This behavior only occurs in Group folders. Other folders are not affected.

### Server configuration

**Operating system:** Ubuntu Server 20.04.6

**Web server:** Nginx 1.25.3-1~focal

**Database:** MariaDB 10.11.6+maria~ubu2004

**PHP version:** 8.2

**Nextcloud version:** 27.1.5

**Group folders version:** 15.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Chrome

**Operating system:** Macos

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by vagner-dias** [comment]
https://github.com/nextcloud/groupfolders/issues/2718
