### ISSUE TITLE
Copy / move  from one subfolder to another subfolder does not work

### ISSUE THREAD

**Issue by survival8** [nextcloud/groupfolders#2771]
### Steps to reproduce
1. setup:
- Create a root folder named folder_r_a with read permission for the user John
- Create a subfolder in folder_r_a with the name sub_a with write permission for the user John
- Create a root folder named folder_r_b with read permission for the user John
- Create a subfolder in folder_r_b with the name sub_b with write permission for the user John

2. the user John creates a file in sub_a

3. the user John selects the file and presses "copy or move"

4. in the new window, the user clicks on the home button to go to the root

5. then the folders "folder_r_a" and "folder_r_b" in the root directory are not visible in the window
-> This means that the user John cannot copy or move a file from sub_a to sub_b.

Only if John has write permissions for the folder_r_b, the folder name is displayed in the "Copy/Move - Window" and then it would possible to copy or move. But the write premission for the root folders would not be an option.

Use case:
There are several root directories that no user is allowed to write to. There are subdirectories in these directories where different users have different rights.
Users should now copy or move files from a subdirectory of a root directory to the subdirectory of another root directory.
For example, copy from administration to general information:
-Department
   |_ Administration
   |_ Finance
-Public
   |_ General information
   |_  ...

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
28.0.1
**Group folders version:**
16.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
no
**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no
### Client configuration
**Browser:**
various
**Operating system:**
various

### Logs
No log because no error or others related to this issue in log

**Comment by heisenbol** [comment]
I believe that this problem exists regardless of the source location of the file/folder you want to move. The source can be anywhere. If the user does not have create permission on the root groufolder, but has permissions on a subfolder, he can not select the subfolder as the root folder is not visible (is not offered as destination for move)

**Comment by bwurst** [comment]
Stumbled upon this issue and reported it as a bug in nextcloud server: https://github.com/nextcloud/server/issues/44649
It is a design decision to filter out write protected folders in copy/move dialog so you can't step into folders you have no write permission. 
Nextcloud core has no feature to make intermediate folders write protected so the developers obviously did not concern about this.

Workarounds I found so far:
1. temporarily share subfolder directly to a user that wants to copy stuff into it
2. Use a desktop or mobile app

**Comment by fuco809** [comment]
maybe same - https://github.com/nextcloud/groupfolders/issues/2926
