### ISSUE TITLE
Define Maximum Space for group folders per Config

### ISSUE THREAD

**Issue by fr3ddy-sudo** [nextcloud/groupfolders#2788]
Hello,
is it possible to define a maximum space for Group folders per config?
So that it is impossible to make e.g. a group folder bigger than 5GB, in my case I want to define a Group folder admin per cloud, and this person only can create Group folders but not can define the space size. 
The Space size every time have 5GB. 

Thanks, Freddy

**Comment by provokateurin** [comment]
This is not possible. Either you are an admin that can create and edit groupfolders or you are not an admin and can do neither of them.
