### ISSUE TITLE
Group Folders not shown in the WebUI after the update to 28.0.2

### ISSUE THREAD

**Issue by MrXermon** [nextcloud/groupfolders#2811]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Updated Nextcloud from Version 28.0.1 to 28.0.2
2. "All files" page does not show the group-folders anymore.
3. "Groupfolders" pages does show the folders but they do not contain any content.
4. Sync via WebDAV seems to be working normal, though.

### Expected behaviour
The created groupfolders should be visible in the WebUI under the "All files" page and should contain content.
Interestingly, for the admin-user it works without any issue.

### Actual behaviour
"All files" page does not show the group-folders anymore.
"Groupfolders" pages does show the folders but they do not contain any content.
Sync via WebDAV seems to be working normal, though.

### Server configuration

**Operating system:** Ubuntu 22.04.3 LTS

**Web server:** nginx 1.18.0-6ubuntu14.4

**Database:** mariadb-server 1:10.6.12-0ubuntu0.22.04.1

**PHP version:** php8.1-fpm 8.1.2-1ubuntu2.14

**Nextcloud version:** 28.0.2

**Group folders version:** 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 28.0.1

**Where did you install Nextcloud from:** Website

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox/Edge

**Operating system:** macOS/Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No issues shown, here.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors shown, here.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No errors shown, here.
```
</details>

**Comment by koelle25** [comment]
@MrXermon Can you try again with the Groupfolders 16.0.4 update from today? And maybe also try disabling the app, then enabling it again.

**Comment by MrXermon** [comment]
> @MrXermon Can you try again with the Groupfolders 16.0.4 update from today? And maybe also try disabling the app, then enabling it again.

Will try the update once again during the weekend and will update the issue.

**Comment by MrXermon** [comment]
@koelle25 Seems to be good, now. I guess we can close the case for now.

**Comment by JoeMrCoffee** [comment]
I seem to have the same issue in Nextcloud 28.0.5 with Groupfolders 16.0.7. The group folders show in all files, but if you click on the Groupfolders tab in the left hand bar none show up. 
![image](https://github.com/nextcloud/groupfolders/assets/45982832/fd87f601-c7fe-479d-bc1f-9f6a2dee94b3)
