### ISSUE TITLE
Can't Delete Group Folders?

### ISSUE THREAD

**Issue by McCoyCOREUSA** [nextcloud/groupfolders#2846]
v16.0.4

Is there no way to delete a group folder? I can't delete from the main files list. Can't delete from the Group Folders list. And in the Group Folders, if you check any folders, there are no options to do anything with selected items.

I'm stuck. Can't get rid of them.

![2024-03-08_13-12-36](https://github.com/nextcloud/groupfolders/assets/104024793/765d57eb-248d-4751-affe-1ae4c02ec549)

**Comment by fschrempf** [comment]
You need to do it in the admin settings for the groupfolders app. Same place where you create them. You can't do it in the files app.

**Comment by McCoyCOREUSA** [comment]
Isn't that the App admin in my screenshot?

**Comment by fschrempf** [comment]
No, this is the files app in the screenshot, not the admin settings. See https://github.com/nextcloud/groupfolders?tab=readme-ov-file#configuring-group-folders.

**Comment by McCoyCOREUSA** [comment]
Ah! Got it. Thank you!

**Comment by McCoyCOREUSA** [comment]
closing issue
