### ISSUE TITLE
CHANGELOG.md contains obsolete information

### ISSUE THREAD

**Issue by SignFinder** [nextcloud/groupfolders#2885]
Hi team,
Let me highlight that CHANGELOG.MD inside groupfolders-v16.0.4.tar.gz or 17.0.0-beta1 contains obsolete infomation about version 13.0.0-beta1 and that is all.
Could you kindly actualize it at least from time to time.

**Comment by joshtrichards** [comment]
Let's consolidate this into #2966 because it's really part of the release process, since a changelog is already being maintained currently (attached to every tagged release).
