### ISSUE TITLE
Group folders is partially disappearing after updating NC 28.0.2 to 28.0.3

### ISSUE THREAD

**Issue by SignFinder** [nextcloud/groupfolders#2886]
Hi team,
I have found strange problem when I tried to update Nextcloud from 28.0.2 to 28.0.3
After I ran "sudo -u www-data php occ upgrade", it disabled groupfolders 16.0.4 plugin as incompatible and did not enabled after correct finish of updating process.
I started apache and found that all group folders and plugin disappeared from web interface - there were not Group Folders plugin in active\disabled apps in admin web interface.
I tried to enable it via "sudo -u www-data php occ app:enable groupfolders" and received the answer that plugin is enabled. 
But it (and all group folders) was not appeared to web interface again, after server rebooting too.
I was forced to revert NextCloud to 28.0.2.

**Comment by tintou** [comment]
I had the same issue because my username was only consisting of numbers, this has been fixed in 28.0.4

**Comment by SignFinder** [comment]
I have had another issue. Nexcloud 28.0.2, received updating GF from 16.0.4 to 16.0.5 Pressed and after updating all Group Folders disappeared. Disabling and enabling of GP App helped me tp fprce the arrearing of all group folders in NC.

**Comment by joshtrichards** [comment]
Hi @SignFinder - Somehow you managed to bypass the bug reporting template. At a minimum, we need your Nextcloud log entries from when you upgraded and also attempted to manually enable/disable the app.

**Comment by joshtrichards** [comment]
Closing since we can't do anything without logs and none have been provided so far. If this re-occurs, please check your `nextcloud.log` for details that may be helpful in isolating the underlying cause.
