### ISSUE TITLE
sort Groups by name and/or use combobox for group name

### ISSUE THREAD

**Issue by dirks** [nextcloud/groupfolders#289]
Use case:
- you have many groups (e.g. via ldap)
- you want to change the groups that have permissions to a folder

It can quite some time to find the correct group as the list is not sorted. While one can start to type in the field (blind) this is often not sufficient to find the desired group if you have groups that start with the same letters as only the first three(?) characters are used to jump to a matching entry. A combobox like https://jqueryui.com/autocomplete/#combobox would really help here.

**Comment by derHSE** [comment]
Yep, that is exact our use case. Having about 700 groups to manage in NC, all starting with the same 6 letters. This feature is highly appreciated.

**Comment by icewind1991** [comment]
Fixed with e0c6d3fcd920a2cff57afb369882f6dd7c634820

**Comment by icewind1991** [comment]
Fixed with e0c6d3fcd920a2cff57afb369882f6dd7c634820
