### ISSUE TITLE
GROUP folders deleted folders/files inconsistent and wrong

### ISSUE THREAD

**Issue by Henk57** [nextcloud/groupfolders#290]
As mentioned in #115 and #97 and #165 and through https://github.com/nextcloud/server/issues/13380 , also in NC 15 release (with groupfolders 2.0.2 and after updating and repairing all tables with occ, the groupfolders is unreliabale. Occ does not even look at the groupfolders during files:repair --all.

Non existing files and folders keep showing up in the browser and WebDAV environment.

Since this issue is already mentioned nearly a year ago, the only sollution I see is to disable this plugin. Instead I make a 'group admin' user that shall hold all groupfolders.
Most users are non-ICT and get confused with this behavior. They like Nextcloud, but this kind of problems should not come-up.

**Comment by gagaha** [comment]
I can confirm inconsistencies in NC 15 an groupfolders 2.0.2.
Using S3 as primary storage in NC15 and deleting files from a group folder causes the following problem:
The files will be copied to the trash bin in an endless loop, resulting in thousands of copies of the files being stored in the trash bin / S3 bucket.
This is a huge problem, cause it wastes your whole space and you can't delete the files from the trash bin.

**Comment by Henk57** [comment]
I've moved all content of each groupfolder to a new user account.

1. I renamed first the existing group to groupname_old and created a new goup with the usual name (groupname as it was) in the new user account. I shared those folders with admin and what it was. I checked with FTP if all content is moved.
2. I deleted all sharing for the old groupfolders
3. I deleted all old group folders (and they are removed as FTP shows)
4. I disabled the plugin
5. I removed the plugin (through the app console)
6. I ran all occ commands to claean up and repair things
7. And the deleted files and folders keep showing up.
8. Then I used phpmyadmin to discover that these folders and files still are in the cache folder. Named __groupfolders./... I deleted all of those. And I deleted first the groupsfolders tables. Just deleting those folders was not enough. Therefore the cache delete is needed.
9. Then run all occ commands again.
10. The files and folders that should not appear are definitively gone.

Perhaps this procedure is usefull to you.

**Comment by erkankyn1** [comment]
Hi, i delete all own groupfolder files in __groupfolders and i disabled groupfolders add on in gui apps page, this method is worked but few time. I have 600GB data on my groupfolders add on. How to fix this bug ? If you fixed this problem can you contact me on mail ?
erkan.yildirim[at]albil.com.tr

**Comment by Henk57** [comment]
You have to delete the cache manualy. This is not done with occ for the teamfolders. I believe there a 2 folders for teamfolders in the database cache. It is in the database!

If in your case the files itself are not removed, just use FTP to delete them manualy. Run then occ scan all files to repair if needed.

**Comment by erkankyn1** [comment]
Hi again,
I tested your advice. 
This occ commands doesn't work for me. I acces my nextcloud database and find my "groupfolders" database table and i delete it. Now i have new bug, if i create new groupfolder and select group, new folder can't seeing on selected groups my homepage and if i try delete this folder, this folder doesn't deleted on my "groupfolders" settings page. I wait your best advice. thanks lot.

**Comment by erkankyn1** [comment]
> Tekrar merhaba, 
> tavsiyenizi test ettim. 
> Bu occ komutları benim için çalışmıyor. Nextcloud veritabanıma erişiyorum ve "groupfolders" veritabanı tablomu buluyorum ve siliyorum. Şimdi yeni hatam var, yeni grup klasörü oluşturup grup seçersem, yeni grup seçilen gruplarda ana sayfamı göremiyor ve bu klasörü silmeye çalışırsam bu klasör "grup klasörleri" ayarları sayfamda silinmiyor. En iyi tavsiyeni bekliyorum. çok teşekkürler.

By the way, if i create new "groupfolders" folder, this folder doesn't creates in my server on "/var/nc_Data/__groupfolders/". I hope this information helps you for your advice.

**Comment by klada** [comment]
Hi,

I have experienced a similar issue. Through WebDAV I see a lot of these HTTP requests, answered with 404:

```
PROPFIND /remote.php/dav/files/useraccount/project-groupfolder/Top/Subfolder
```

There are records present for this path in oc_filecache:

```
$ SELECT path FROM oc_filecache WHERE PATH LIKE  '%/Top/Subfolder/%';

__groupfolders/42/Top/Subfolder/Sample.pdf 
```

But in the filesystem there is no matching subfolder below `/data/nextcloud/__groupfolders/42/`. The big issue here is that this situation cannot be fixed through occ files:scan, that's what I did:

```
occ files:scan -v --path /useraccount/files/project-groupfolder/
```

The verbose output properly lists all of the files under `__groupfolders/42/`, however the missing folder `Top` is not deleted by the scan operation. This means that the filecache is now inconsistent.

**Comment by erkankyn1** [comment]
Hi,

If we find groupfolders file cache table and delete all lost or deleted folders, probably fix the bug. I delete all __groupfolders file and delete groupfolders add-on and setup again groupfolders add-on, but if i create new groupfolder, "__groupfolders" folder is not create "1" folder. My last created folder's number is 28 and "__groupfolders" folder not create number 1 file. İt's create 29 number folder. I hope we fix this bug. 

Best Regards.

**Comment by Henk57** [comment]
I think it is not a problem. De numbering is just an internal reference. The real problem is that the groupfolders not work as one should excpect.

**Comment by samip5** [comment]
Can confirm that this is a problem with the Docker version of Nextcloud too. Just when I though, I had everything working like I want it to be.

Using encryption, yes.

**Comment by expert-geeks** [comment]
Function to clear group folders trash has recently been added by [rullzer & juliushaertl](https://github.com/nextcloud/groupfolders/commit/6119b1e245c750667a14ae24cede9b25b2bff29f) (thanks guys!) 

`sudo -u www-data php /var/www/nextcloud/occ groupfolders:trashbin:cleanup`

**Comment by JOduMonT** [comment]
Same here, I'm unable to rename any GroupFolder

- Nextcloud version 20
- Nextcloud Group Folder 8.2.0

I used FlowUpload to upload few GiB in 5 differents GroupFolders

When I try to rename the content inside these GroupFolders
- via WebDav I simply receive an `Error: Internal Server Error`
- via the WebUI the message is: `Could not rename "GroupFolderName"✖`
I don't have a SSH access on this instance.

**Comment by pierreozoux** [comment]
This issue is quiet old, there are various discussion, and it is not clear. The original authors seems to have moved away, and the last comment opened another issue. I'll close this one for now.

(If you feel like it should be reopened, please just create a new one, and with a currently supported Nc version.)
(sorry if you feel it is not fair, I'm trying to clean issues here :) )
