### ISSUE TITLE
Confirm Deletion by Password-Entry

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/groupfolders#2911]
Hi,

everywhere in Nextcloud you have to confirm critical changes by entering your password. Even uncritical changes (e.g. adding a user to a group).

I think it would be good to have a password confirmation too if you want to delete a group folder.

**Comment by joshtrichards** [comment]
This will be easier after #3140 since we can then just use the existing vue library: https://github.com/nextcloud-libraries/nextcloud-password-confirmation

**Comment by provokateurin** [comment]
Fixed in all recent releases.
