### ISSUE TITLE
MySQL : Impossible `WHERE` noticed after reading const tables

### ISSUE THREAD

**Issue by solracsf** [nextcloud/groupfolders#2917]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
While analysing Nextcloud performance, I noticed a lot _(**hundreds of thousands**)_ of queries like these:

```
MariaDB [nextcloud]> EXPLAIN SELECT `f`.`fileid`, `mapping_type`, `mapping_id`, `mask`, `a`.`permissions`, `path` FROM `oc_group_folders_acl` `a` INNER JOIN `oc_filecache` `f` ON `f`.`fileid` = `a`.`fileid` WHERE (`path_hash` IN ('a6260ab4e36f07cecbf907d64f121029')) AND (`storage` = 2) AND (((`mapping_type` = 'user') AND (`mapping_id` = 'ygerig')) OR ((`mapping_type` = 'group') AND (`mapping_id` = 'Utilisateurs_Docs')) OR ((`mapping_type` = 'group') AND (`mapping_id` = 'Utilisateurs Nextcloud Docs')));
+------+-------------+-------+------+---------------+------+---------+------+------+-----------------------------------------------------+
| id   | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra                                               |
+------+-------------+-------+------+---------------+------+---------+------+------+-----------------------------------------------------+
|    1 | SIMPLE      | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL | Impossible WHERE noticed after reading const tables |
+------+-------------+-------+------+---------------+------+---------+------+------+-----------------------------------------------------+
1 row in set (0.000 sec)
```

Reporting in case these need som kind of optimisation

### Server configuration

**Operating system:** Ubuntu 22.04

**Web server:** Apache 2.4

**Database:** MariaDB 10.6

**PHP version:** 8.2

**Nextcloud version:** (see Nextcloud admin page) 27.1.8

**Group folders version:** 15.3.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Manually

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

**Comment by provokateurin** [comment]
According to https://stackoverflow.com/a/39569478 this is not an issue. Please re-open if you think otherwise.
