### ISSUE TITLE
NCv28: Users unable to move/copy into some group folders (OK in v27)

### ISSUE THREAD

**Issue by fermion2020** [nextcloud/groupfolders#2926]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Summary
NextCloud has been updated from version 27 to 28. The configuration of group folders with restricted permissions at different levels causes inconsistencies in the user interface, particularly when attempting to copy files into specific subfolders.

### Steps to reproduce
1. Configure group folders with restricted permissions:
   * Top-level folder (`level_one`) prohibits users from writing.
   * Subfolder (`level_two`) within level_one allows users to write and read.
2. Access the user web interface and attempt to copy files into the `level_two` subfolder. Note that the `level_two` subfolder may not appear in the copy/move window, despite being visible in the interface.

### Expected behaviour
Users should be able to see all relevant subfolders, including the `level_two` subfolder, when attempting to copy files within the group folder structure. The copy/move window should display all subfolders with appropriate permissions, allowing users to select and copy files as needed. (We had this in the previous NC version)

### Actual behaviour
In the current setup, the `level_two` subfolder may not appear in the copy/move window, despite being visible in the user interface. This discrepancy limits users' ability to copy files into specific subfolders, leading to frustration and inefficiency in file management tasks.

### Server configuration

**Operating system:**
Docker environment based on Alpine

**Web server:**
Nginx

**Database:**
mariadb:10.11

**PHP version:**
php-fpm 8.2.16

**Nextcloud version:** (see Nextcloud admin page)
28.0.3

**Group folders version:**
16.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from version 27

**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
SAML

### Client configuration
**Browser:**
Chrome, Edge, Safary

**Operating system:**
Windows 10/11, MacOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by fuco809** [comment]
same there -> shared groupfolder disappears in the filepicker dialog when trying to copy or move one,multi files or a folder. if pressing home button - all groupfolders disappears in the picker.
tested with 28.0.4 and 28.0.5

**Comment by fuco809** [comment]
retested with newer versions

NC 28.0.6 + groupfolder 16.0.6 -> same problem
NC 29.0.1 + groupfolder 17.0.0(final) -> seems to work again - all groupfolders are shown in move/copy dialog
