### ISSUE TITLE
Wrong order of permission check in TrashBackend

### ISSUE THREAD

**Issue by x7airworker** [nextcloud/groupfolders#2932]
While debugging an issue I had with deleting files from the trash, I've noticed the following code:
https://github.com/nextcloud/groupfolders/blob/master/lib/Trash/TrashBackend.php#L199

Essentially this will delete the file in any case if its found, regardless if the user has permission to this file or not. An easy fix for this issue is to make the check for `userHasAccessToPath` before the unlink call.

In my tests, I get the `NotPermittedException` response through WebDAV, but the file gets deleted anyways. This is visible after a reload of the page.

**Comment by provokateurin** [comment]
Fixed in all recent releases
