### ISSUE TITLE
"GroupFolders" 16.0.6 and Nextcloud 29.0.0: "Error: This app cannot be enabled because it makes the server unstable"

### ISSUE THREAD

**Issue by RichardHausgartner** [nextcloud/groupfolders#2940]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update the **docker image** from **Nextcloud 28.0.5 to Nextcloud 29.0.0**

### Expected behaviour
App "GroupFolders" is active and working

### Actual behaviour
The app "GroupFolders" was automatically deactivated. When trying to enable it through Nextcloud admin panel, I receive a toast:
`Error: This app cannot be enabled because it makes the server unstable`.

For me, it helped to enable it through the occ command:
`php occ app:enable groupfolders`

But now I don't know if there **is an incompatibility** between **GroupFolders 16.0.6** and **Nextcloud 29.0.0** which is not visible to me yet.
Does someone have similar trouble when updating to NC 29?

**Comment by Nietzscheanman** [comment]
Suffering from the same issue here, major problem due to it being part of our company operation :/

**Comment by BigBen2003** [comment]
[English via Google Translate]
In order to avoid incompatibility problems, I have a second Nextcloud test environment in which all apps in the production environment run. Only when the most important apps in the current Nextcloud version 29 have been released and can be installed without any problems will the production environment be changed.

[German]
Um Inkompatibilitätsprobleme aus dem Wege gehen zu können, habe ich eine zweite Nextcloud-Testumgebung, in der alle Apps der Produktionsumgebung laufen.  Erst wenn die wichtigsten Apps in der aktuellen  Nextcloud Version 29 freigegeben sind und sich ohne Probleme installieren lassen, wird die Produktionsumgebung umgestellt.

**Comment by beankylla** [comment]
Hi,
I have the same issue.
The bummer is that you then no longer have access to the group folders.
Quite the issue, not sure i will keep using them now. Will probably create another user that shares the files instead of group folders. 
Would it make sense for group_folders to use the same logic to prevent everything breaking when app is not active?
That way the app could be used for config etc. but shares would still be available if it breaks

**Comment by Nietzscheanman** [comment]
The convoluted way in which I fixed it is by (i) navigating to the groupfolders location on the server drive itself and (ii) copying the files from there to a new regular folder on a pc and (iii) then back to a new nextcloud folder.

For some reason when copying them straight to nextcloud without the pc step in between they remained hidden, I guess something related to permissions that was removed when copying to pc first. Total IT-noob here so no idea what I am doing, just needed the files back.

Now solved it via sharing folders as well, will do it like that from now on - was quite a scare.

**Comment by jmechnich** [comment]
DISCLAIMER: you should probably only try this if you somewhat understand what is being done (and ideally backup your Nextcloud before doing anything).

While trying to fix another issue (#2935) I have built a tarball from the current master: [groupfolders-17.0.0-beta.1.tar.gz](https://github.com/nextcloud/groupfolders/files/15175976/groupfolders-17.0.0-beta.1.tar.gz)

You can also try building it yourself:
```
# building
git clone  https://github.com/nextcloud/groupfolders.git
cd groupfolders
make appstore
# for some reason the tar archive is versioned 8.0.0 but it does not matter in the end
# installation, similar if you downloaded the file from here
sudo cp build/groupfolders-8.0.0.tar.gz /var/www
cd /var/www/nextcloud/apps
sudo -u www-data /var/www/nextcloud/occ app:disable groupfolders
sudo mv groupfolders ~/groupfolders.backup
sudo -u www-data tar zxvf /var/www/groupfolders-8.0.0.tar.gz
sudo -u www-data /var/www/nextcloud/occ app:enable groupfolders
```

It seems to work in general but I am still getting a regular (but different than before) error from the cron job.

So, at least for me, it did not make things worse... 😅

**Comment by mos87** [comment]
Is there any information from the maintainers when an stable version 17 can be released? (@icewind1991, @juliushaertl, ...)
If it is about 3-4 days I will wait patiently, if it is about 2-3 weaks i would use a workaround ...
I would be happy if there are any informations.

**Comment by tj775** [comment]
A short statement about the further steps would be helpful. When will Group Folders be available for Nextcloud 29?

**Comment by Emanuel-S-1** [comment]
We also have Nextcloud currently with Group Folders feature unavailable. Very unfortunate. Going forward we will delay roll out off new versions until required apps are available. We'd prefer not to roll back to Nextcloud 28. If you could give an approximation by when Group Folders should be back, that would be very helpful.

**Comment by chberger** [comment]
I've enabled `Group folders` 16.0.6 manually, as we lost all our permissions after upgrading to `Nextcloud` 29. As this version of the app doesn't support NC 29 officially, I'm aware that there must be some incompatibilities. What I've figured out so far is that the NC client cannot sync files that have been renamed within a `Group folder` (at least on Windows). I did not face other issues related to that. Anyway, this is something I can accept. It's much better than having no data access at all. 😅 

Anyway, disabling the app during the NC update silently doesn't sound like a valid update strategy either. IMHO this procedure should also be reconsidered...

**Comment by zlElo** [comment]
How looks? I really need it...

**Comment by BigBen2003** [comment]
> How looks? I really need it...

Ich warte auch schon auf eine Aktualisierung. Solange es keine funktionierende Gruppenordner-Funktion gibt, kann kein Update der Nextcloud-Version durchgeführt werden.

**Comment by sthag** [comment]
I hope it is ok to ask this here...

I already did the upgrade to NC29 and group folder app is now missing.
The files are gone for all users but still present on the server.
Will an updated groupfolder app, compatible with NC29, restore the working situation before the NC upgrade as it was with NC28?

**Comment by BigBen2003** [comment]
> I hope it is ok to ask this here...
> 
> I already did the upgrade to NC29 and group folder app is now missing. The files are gone for all users but still present on the server. Will an updated groupfolder app, compatible with NC29, restore the working situation before the NC upgrade as it was with NC28?
Genau an diesem Punkt gehen die Meinungen auseinander. Manche meinen, dass die Gruppenordner nach einem Update wieder hergestellt werden. Manche meinen allerdings, dass es nicht der Fall ist. - Daher ist es besser, wenn man mit dem Nextcloud Update wartet, bis es ein Update vom Gruppenordner gibt. In Nextcloud 28 läuft das AddIn "GroupFolder" anstandslos. Es scheint wohl nicht so leicht zu sein, das AddIn an die neue Nextcloud 29 anzupassen.

**Comment by burner-** [comment]
Any estimation when groupfolder comes to nc29? nc28 have bug what cause constant logouts for users so there is great pressure to update instance. However groupfolders still wont support nc29 even it is featured app. So do we have any estimation when this situation get resolved?

**Comment by icewind1991** [comment]
17.0.0 is released for 29
