### ISSUE TITLE
Documentation: there is no home folder

### ISSUE THREAD

**Issue by fulldecent** [nextcloud/groupfolders#2961]
The documentation states that a group folder will show up in a home folder.

![Screenshot 2024-05-14 at 11 49 45](https://github.com/nextcloud/groupfolders/assets/382183/e39c359e-2766-4c59-a54a-7c376e8c1c8e)

---

However I just created a Nextcloud account for testing here https://try.nextcloud.com/ and there is no home folder:
![Screenshot 2024-05-14 at 11 50 53](https://github.com/nextcloud/groupfolders/assets/382183/9fea7dde-6be3-4efb-bf93-b8b75745542b)

**Comment by fulldecent** [comment]
Related context and expectations for shared drives: https://github.com/nextcloud/server/issues/45314

**Comment by solracsf** [comment]
What you see here is the Home folder (aka. the root - _Home_ - folder of all files).
So, if Group Folders app was installed, and configured, any Group Folder wold appear on that list for authorized users.

**Comment by fulldecent** [comment]
Will a pull request be considered if this wording can be improved?

**Comment by solracsf** [comment]
Feel free to submit it, it will certainly be reviewed :)
