### ISSUE TITLE
Error while running background job ExpireGroupVersions (with groupfolders 17.0.0). TypeError: VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\Files\File, OC\Files\FileInfo given

### ISSUE THREAD

**Issue by prolibre** [nextcloud/groupfolders#2964]
Nextcloud 29.0.0 and Nextcloud 29.0.1
The latest groupfolders update (17.0.0) introduces a new bug in the logs.

Reported by @jmechnich at https://github.com/nextcloud/groupfolders/issues/2935

```
{
  "reqId": "0okAL3KAiSQD23u5JJlv",
  "level": 3,
  "time": "2024-05-21T03:50:03+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 102515, arguments: null)",
  "userAgent": "--",
  "version": "29.0.0.19",
  "exception": {
    "Exception": "TypeError",
    "Message": "OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionFolderForFile(): ArgumeError while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersionsnt #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\FileInfo given, called in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 92",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php",
        "line": 92,
        "function": "getVersionFolderForFile",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 81,
        "function": "getVersionsForFile",
        "class": "OCA\\GroupFolders\\Versions\\VersionsBackend",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php",
        "line": 60,
        "function": "expireFolder",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php",
        "line": 43,
        "function": "expireAll",
        "class": "OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/Job.php",
        "line": 80,
        "function": "run",
        "class": "OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 102,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php",
        "line": 92,
        "function": "start",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/cron.php",
        "line": 176,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\TimedJob",
        "type": "->"
      }
    ],
    "File": "/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php",
    "Line": 78,
    "message": "Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 102515, arguments: null)",
    "exception": {},
    "CustomMessage": "Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 102515, arguments: null)"
  }
}
```

Have a nice day.

**Comment by HuguesDug** [comment]
Same error on my side

**Comment by baltaner** [comment]
Hi,
also same error on my nextcloud.
Nextcloud 29.0.1
groupfolders 17.0.0

**Comment by Dennis1993** [comment]
We have the same error after the update to 29 (29.0.1 at the moment).
Our log get spammed with the error in the first post.

**Comment by urmel1960** [comment]
same here nc 29.0.1 and Groupfolders 17.0

**Comment by contoporte** [comment]
exactly the same problem with nextcloud 29.0.1 and groupfolders 17.0

**Comment by ReimuHakurei** [comment]
Needs testing, but from what I can see in the NC code, `File` extends `Node` which extends `FileInfo`, so this could possibly be fixed by doing the following.

In groupfolders/lib/Versions/GroupVersion.php, replace:
`private File $versionFile,` with `private FileInfo $versionFile,`

In groupfolders/lib/Versions/VersionsBackend.php, replace:
`private function getFolderIdForFile(File $file): int {`
with
`private function getFolderIdForFile(FileInfo $file): int {`

`public function getVersionFolderForFile(File $file): Folder {`
with
`public function getVersionFolderForFile(FileInfo $file): Folder {`

Someone who is actually familiar with the codebase here should verify this isn't going to horribly break anything.

**Comment by PaddySwiss** [comment]
Not sure if based on same issue, but the error log on my system is a little bit different:
**TypeError** OCA\GroupFolders\Versions\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\Files\File, OC\Files\FileInfo given, called in /var/www/nextcloud.noser-solutions.ch/apps/groupfolders/lib/Versions/VersionsBackend.php on line 92
Error while running background job OCA\GroupFolders\BackgroundJob\ExpireGroupVersions (id: 116, arguments: null)

**Comment by baltaner** [comment]
@ReimuHakurei
your suggested changes are stopping the errors on my server - groupfolders is still working...

**Comment by prolibre** [comment]
> @ReimuHakurei your suggested changes are stopping the errors on my server - groupfolders is still working...

+1 @baltaner

**Comment by s0undy** [comment]
same issue here.

Applied changes proposed by @ReimuHakurei and it fixes the error.

Verified by manually running ```occ groupfolders:expire``` which completed without errors.

**Comment by alphasixtyfive** [comment]
Group folders is one of the most important apps on NC yet it is the one that attracts most issues.

**Comment by raffaelone** [comment]
> Needs testing, but from what I can see in the NC code, `File` extends `Node` which extends `FileInfo`, so this could possibly be fixed by doing the following.
> 
> In groupfolders/lib/Versions/GroupVersion.php, replace: `private File $versionFile,` with `private FileInfo $versionFile,`
> 
> In groupfolders/lib/Versions/VersionsBackend.php, replace: `private function getFolderIdForFile(File $file): int {` with `private function getFolderIdForFile(FileInfo $file): int {`
> 
> `public function getVersionFolderForFile(File $file): Folder {` with `public function getVersionFolderForFile(FileInfo $file): Folder {`
> 
> Someone who is actually familiar with the codebase here should verify this isn't going to horribly break anything.

Appling this fix I take another error from logs

```
TypeError
OCA\GroupFolders\Versions\GroupVersion::getVersionFile(): Return value must be of type OCP\Files\File, OC\Files\FileInfo returned
Error while running background job OCA\GroupFolders\BackgroundJob\ExpireGroupVersions (id: 31591, arguments: null)
```

**Comment by alphasixtyfive** [comment]
@solracsf would it be possible to get someone to make a hot-fix?

**Comment by helmo** [comment]
While preparing my own PR with the here suggested changes I found that @solracsf already has one in draft on #2976
That one has a few extra changes which were seemingly needed to please the linters and checks.

I can confirm that it solves the issue for me.

**Comment by solracsf** [comment]
Can you please check if https://github.com/nextcloud/groupfolders/pull/2976 fixes your issues as it stands?

Note that the extra https://github.com/nextcloud/groupfolders/issues/2964#issuecomment-2135098424 will fail on `fopen()` calls: https://github.com/nextcloud/groupfolders/actions/runs/9336320832/job/25696721210?pr=2976#step:6:18

**Comment by solracsf** [comment]
Hi @artonge as you've worked on this, can you take a look when possible? Thanks 👍

**Comment by artonge** [comment]
PR: https://github.com/nextcloud/groupfolders/pull/2989
Could someone report whether this is fixing the issue?
