### ISSUE TITLE
Sugestão: Adicionar recurso de ponto de montagem especifico para pastas de grupo.

### ISSUE THREAD

**Issue by SamuelAbrantes** [nextcloud/groupfolders#2982]
Uma sugestão:

Queria uma forma de conseguir indicar quais locais os arquivos ficar. Por exemplo, eu insiro um novo HDD SAS no meu servidor,
ai eu vou e monto ele em /mnt/extern1

Ai quando eu for la criar uma pasta de grupo eu poder indicar qual diretório eu quero que esses arquivos fiquem.
Isso junto ao recurso de definir limite de uso por diretório vai ajudar bastante na expansão de armazenamento de arquivos e na usabilidade do APP.

**Comment by SamuelAbrantes** [comment]
Eu tentei coisas tipo criar um link simbólico para /var/www/html/nextcloud/data/__groupfolders mas da erro... aparece erros de permissão, como se eu ou ninguém no NextCloud tivesse permissão para fazer upload dos arquivos.

**Comment by solracsf** [comment]
Please post in English. Thanks 👍

**Comment by SamuelAbrantes** [comment]
> Please post in English. Thanks 👍 
Ok.
