### ISSUE TITLE
Error after updating to nextcloud 29.0.2

### ISSUE THREAD

**Issue by gmt-it** [nextcloud/groupfolders#3003]
After updating to version 29.0.2, nextcloud, I encountered the following error:

{"reqId":"TSFwoLrJNYxGMEncGP1e","level":3,"time":"2024-06-07T16:35:04+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 1528, arguments: null)","userAgent":"--","version":"29.0.2.2","exception":{"Exception":"TypeError","Message":"OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\\Files\\File, OC\\Files\\FileInfo given, called in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 92","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","line":92,"function":"getVersionFolderForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":81,"function":"getVersionsForFile","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php","line":60,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php","line":43,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":176,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php","Line":78,"message":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 1528, arguments: null)","exception":[],"CustomMessage":"Error while running background job OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions (id: 1528, arguments: null)"},"id":"66633dcd7816c"}

**Comment by solracsf** [comment]
Please search for issues before posting, this has already been fixed. Thanks 👍
