### ISSUE TITLE
What is the state of the "known issues" for groupfolders?

### ISSUE THREAD

**Issue by Ra72xx** [nextcloud/groupfolders#3010]
When visiting the Github site for "groupfolders", the documentation prominently links to an extensive list of known bugs and limitations ([https://github.com/nextcloud/groupfolders/issues/1414](url)).

This issue, however, has last been updated in 2021 and has moreover been classified as "spam". At least some of the bug reports collected in this issue have already been closed or are also years old.

So, what is the current state of "groupfolders"? Is it still buggy and unusable (I currently use it - again after bad experiences years ago - and until now it seems quite usable), or should this intimidating link on the front page be removed / updated?

**Comment by Zeugma440** [comment]
Gotta +1 on that one. 

Groupfolders _looks like_ something we'd need, but I'm very intimidated by the know issues list, especially "Sharing of directories inside a group folder can lead to [all kinds of problems](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+sharing%22+label%3Abug+).", where there are stagnating issues opened since 2019.

Is that module on the verge of being replaced by something else from vanilla? Or have the main contributors been called in priority on other parts of the NC ecosystem?

**Comment by solracsf** [comment]
> Is that module on the verge of being replaced by something else from vanilla? Or have the main contributors been called in priority on other parts of the NC ecosystem?

I simply believe main priorities goes to actual Nextcloud Enterprise customers bug reports and features requests. Otherwise, module relies on community contributions (as the whole Nextcloud ecosystem).

**Comment by fschrempf** [comment]
> So, what is the current state of "groupfolders"? Is it still buggy and unusable (I currently use it - again after bad experiences years ago - and until now it seems quite usable), or should this intimidating link on the front page be removed / updated?

The "Known Issues" issue probably needs updating. Some things might have been resolved and new problems have occurred. As long as there is no serious effort from anyone to properly maintain this app it will remain in a state of "might work (or break) for your use-case but can cause you serious headaches at any time". Just my two cents.

**Comment by Ra72xx** [comment]
> > So, what is the current state of "groupfolders"? Is it still buggy and unusable (I currently use it - again after bad experiences years ago - and until now it seems quite usable), or should this intimidating link on the front page be removed / updated?
> 
> The "Known Issues" issue probably needs updating. Some things might have been resolved and new problems have occurred. As long as there is no serious effort from anyone to properly maintain this app it will remain in a state of "might work (or break) for your use-case but can cause you serious headaches at any time". Just my two cents.

You're probably right, but "groupfolders" is, on the surface, an officially supported Nextcloud app suggested by I think several "app packages" in the app store. There were AFAIK also some very optimistic press releases concerning group folders, the possibiity to use ACLs, and so on. 

This does not really fit in with the seemingly missing official maintainance state of the app. I'm completely aware that most of the development is done by volunteers and I appreciate that, however then the PR department is not really synchronized with the ground reality of the code base, I'm afraid ;-).

As of now, I'm using "groupfolders" and have not encountered any bugs (this was different some years ago), but I'm a bit unsure as the way this bug report is evolving suggests that this might only be per chance.

**Comment by fschrempf** [comment]
> This does not really fit in with the seemingly missing official maintainance state of the app. I'm completely aware that most of the development is done by volunteers and I appreciate that, however then the PR department is not really synchronized with the ground reality of the code base, I'm afraid ;-).

That's point on and something that's already been the topic of the other issue that is currently pinned here: https://github.com/nextcloud/groupfolders/issues/1215.

**Comment by provokateurin** [comment]
We are working on this, so please refer to https://github.com/nextcloud/groupfolders/issues/1414 and https://github.com/nextcloud/groupfolders/issues/1215
