### ISSUE TITLE
Groupfolder error in log file

### ISSUE THREAD

**Issue by jsfrederick** [nextcloud/groupfolders#302]
I am getting the following error in my Nextcloud Log since the upgrade to Groupfolders 2.02.  Looks like it's Groupfolder related.  Any thoughts?  Nextcloud 15.0.2

`[cron] Error: TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154 at <<closure>>

0. /var/www/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php line 154
   getVersionsFolder("1")
1. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 53
   getAllVersionedFiles({id: "1",mount_p ... 0})
2. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 48
   expireFolder({id: "1",mount_p ... 0})
3. /var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   expireAll()
4. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
   run(null)
5. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   execute(OC\BackgroundJob\JobList {}, OC\Log {})
6. /var/www/nextcloud/cron.php line 123
   execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-01-30T05:00:07+00:00`

**Comment by Bables55** [comment]
I have also occurred, occurring once a day.

Nextcloud 15.0.2, CentOS 7.3, PHP 7.3.1, Nginx 1.14.1

**Comment by bpcurse** [comment]
Same on Nextcloud 15.0.4, Group folders 2.0.2

**Comment by icewind1991** [comment]
can you retest with the just released 2.0.3

**Comment by bpcurse** [comment]
@icewind1991 Just installed 2.0.3 and will reply tomorrow, waiting for the issue to reappear. Or is there a way to trigger the cron error right now?

**Comment by jsfrederick** [comment]
Just installed 2.0.3.  Will see what the log file says in the morning.

**Comment by jsfrederick** [comment]
latest error message with 2.0.3:

[PHP] Error: Object of class OCA\GroupFolders\Versions\GroupVersion could not be converted to string at /var/www/nextcloud/apps/groupfolders/lib/Versions/ExpireManager.php#126
at 2019-02-22T03:45:09+00:00

**Comment by bpcurse** [comment]
It got better :) Now I only found the exact same error message in the log as @jsfrederick

**Comment by ClepToManix** [comment]
still same error in 2.0.3 with nc 15.0.4

**Comment by rollanders** [comment]
I get similar error - see below

Ubuntu 18.04
NC 15.05
Group Folder 2.0.3


[core] Error: OCP\Files\NotPermittedException:  at <<closure>>

0. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 62
   delete()
1. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 48
   expireFolder({id: 4,mount_poi ... 0})
2. /var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   expireAll()
3. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
   run(null)
4. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/nextcloud/cron.php line 123
   execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-03-03T19:45:02+01:00

[PHP] Error: Object of class OCA\GroupFolders\Versions\GroupVersion could not be converted to string at /var/www/nextcloud/apps/groupfolders/lib/Versions/ExpireManager.php#126

at 2019-03-03T19:45:02+01:00

**Comment by icewind1991** [comment]
Please check if db8450b fixes the issue for you

**Comment by jsfrederick** [comment]
Installed, watching the logs to see what happens.

**Comment by bpcurse** [comment]
Looks good on my instance, no more log entries, seems to be fixed.
Thank you @icewind1991  :+1:
