### ISSUE TITLE
In same folder group, two different admin group in a same group can't view same desactivated users

### ISSUE THREAD

**Issue by pascald0210** [nextcloud/groupfolders#3028]
Nextcloud v27.1.10.2

> Enabled:
>  - activity: 2.19.0
>  - admin_audit: 1.17.0
>  - announcementcenter: 6.8.1
>  - bruteforcesettings: 2.7.0
>  - calendar: 4.7.6
>  - cfg_share_links: 4.2.0
>  - circles: 27.0.1
>  - cloud_federation_api: 1.10.0
>  - collectives: 2.12.0
>  - comments: 1.17.0
>  - contacts: 5.5.3
>  - contactsinteraction: 1.8.0
>  - dashboard: 7.7.0
>  - dav: 1.27.0
>  - event_update_notification: 2.4.0
>  - external: 5.2.1
>  - federatedfilesharing: 1.17.0
>  - files: 1.22.0
>  - files_antivirus: 5.5.5
>  - files_mindmap: 0.0.30
>  - files_pdfviewer: 2.8.0
>  - files_reminders: 1.0.0
>  - files_rightclick: 1.6.0
>  - files_sharing: 1.19.0
>  - files_trashbin: 1.17.0
>  - files_versions: 1.20.0
>  - firstrunwizard: 2.16.0
>  - forms: 3.4.7
>  - geoblocker: 0.5.14
>  - groupfolders: 15.3.8
>  - guests: 2.5.2
>  - keeweb: 0.6.13
>  - logreader: 2.12.0
>  - lookup_server_connector: 1.15.0
>  - mail: 3.7.1
>  - nextcloud_announcements: 1.16.0
>  - notifications: 2.15.0
>  - oauth2: 1.15.2
>  - onlyoffice: 9.2.2
>  - password_policy: 1.17.0
>  - photos: 2.3.0
>  - polls: 7.1.1
>  - privacy: 1.11.0
>  - provisioning_api: 1.17.0
>  - quota_warning: 1.19.0
>  - recommendations: 1.6.0
>  - related_resources: 1.2.0
>  - serverinfo: 1.17.0
>  - settings: 1.9.0
>  - sharebymail: 1.17.0
>  - spreed: 17.1.9
>  - support: 1.10.1
>  - survey_client: 1.15.0
>  - suspicious_login: 5.0.0
>  - systemtags: 1.17.0
>  - text: 3.8.0
>  - theming: 2.2.0
>  - theming_customcss: 1.16.0
>  - translate: 1.2.0
>  - twofactor_backupcodes: 1.16.0
>  - twofactor_totp: 9.0.0
>  - updatenotification: 1.17.0
>  - user_status: 1.7.0
>  - viewer: 2.1.0
>  - workflowengine: 2.9.0
> Disabled:
>  - encryption
>  - federation: 1.17.0
>  - files_external
>  - user_ldap: 1.11.0
>  - weather_status: 1.0.0
In a groupfolders, user desactivated by an admin group is not showed by another admin group (same group) in users desactivated list.

**Comment by provokateurin** [comment]
Please provide steps to reproduce this issue. Disabling users in groups has nothing to do with groupfolders.
