### ISSUE TITLE
Group Folders quota information

### ISSUE THREAD

**Issue by rmsmgaspar** [nextcloud/groupfolders#3029]
Hi,
I'm using Group Folders for some stuff, therefore when I have the need for larger data movement, the quota applied is exceeded, but I don't have the visibility before, is there the possibility to implement a quota information in the group folder?
Thanks so much for your work.

**Comment by joshtrichards** [comment]
Duplicate of #1736 (admin) or #44 (user). Subscribe and/or upvote and/or comment on those issues if they're of interest.
