### ISSUE TITLE
Cannot modify group permissions

### ISSUE THREAD

**Issue by pointhi** [nextcloud/groupfolders#304]
When I want to modify the permissions of a group, the changes do not take effect.

Looking onto the network the post request to ```cloud.example.com/apps/groupfolders/folders/1/groups/``` returns **302**

**Comment by ZeikoFr** [comment]
Hi @pointhi Is this issue still present in an up-to-date NC instance ?

**Comment by pierreozoux** [comment]
No answers, Ill close but feel free to reopen if still present
