### ISSUE TITLE
Changes in the files app UI are not shown immediately, but need refreshing the page

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/groupfolders#3080]
After the recent update of NC to 28.0.8 I found that all operations with files (creating/renaming/deleting) are not rendered immediately in the file UI, and this is particular to group folders but not the ordinary local files or folders.

1. create a file text.txt in a folder A using files app
2. observe that it appears in the list of files in the files app
3. rename it to text2.txt
4. observe that the name is not changed
5. refresh the page and observe that the changes are shown

The same happens with folders.

Additionally, I see the _pending_ status of the file, which doesn't disappear.

**Comment by joshtrichards** [comment]
No longer the case with the latest maintenance releases (28.0.9, >=29.0.5).
