### ISSUE TITLE
files cannot be deleted from group folders

### ISSUE THREAD

**Issue by GuidoDr** [nextcloud/groupfolders#309]
files from group folders cannot be deleted, even files that were just uploaded a minute or several minutes ago.

{"reqId":"HYif79Oiy85OmWiTX1O9","level":3,"time":"2019-01-27T22:59:50+00:00","remoteAddr":"xx.5.5.63","user":"guido","app":"no app in context","method":"DELETE","url":"\/remote.php\/dav\/files\/guido\/LVV-Baden-W%C3%BCrttemberg\/test.txt","message":"**Could not find mount point, can't keep encryption keys**","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}

NC 15.0.2 with group folders 2.0.2
Server side encryption is not enabled. Server was in the last months first migrated vom NC13 to NC14 and then to NC15.

The error is also mentioned here: (therefore I do not know if the error should be mentioned here or just there)

https://github.com/nextcloud/server/issues/13380

**Comment by GuidoDr** [comment]
problem remains also after the migration from NC 15.0.2 to 15.0.4:

{"reqId":"tIgzv8CPvDvbUIKslrBp","level":3,"time":"2019-02-08T06:19:28+00:00","remoteAddr":"xx.5.5.192","user":"guido","app":"no app in context","method":"DELETE","url":"\/remote.php\/dav\/files\/guido\/LVV-Baden-W%C3%BCrttemberg\/test.txt","message":"**Could not find mount point, can't keep encryption keys**","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.4.0"}

**Comment by GuidoDr** [comment]
I got it **solved** by completely uninstalling the default encryption module of Nextcloud.
(I deleted the encryption directory and all its files and subdirectories in the nextcloud/apps directory even though we did not use the encryption)
Not really a preferred solution to delete a default app only to get another app working again. 👎

**Comment by GuidoDr** [comment]
it got fixed with version 2.0.4

**Comment by priethor** [comment]
Thanks, I just upgraded to 2.0.4 and it's working! Yay!
