### ISSUE TITLE
After upgrade to NC29 all ACL permissions are set to inherit

### ISSUE THREAD

**Issue by hokascha** [nextcloud/groupfolders#3097]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. update from NC28 to NC29
2. try to access group folders with advanced permissions
3.

### Expected behaviour
access based on ACL rules should work the same way as in NC28. 

### Actual behaviour
All permissions where set to "inherit" which previously was "allow". Rules that had "forbidden" are still there. All other's are set to "inherit" which breaks access to most of our group folders. I had to manually set all ACL rules again.
Also, the group folders names are displayed by their number when being opened in the top breadcrumb section.
### Server configuration

**Operating system:**
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
**Web server:**
Apache2
**Database:**
Mysql 8.0.39
**PHP version:**
PHP8.0
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Hub 8 (29.0.4)
**Group folders version:**
17.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
from NC28
**Where did you install Nextcloud from:**

**Are you using external storage, if yes which one:** local/s3/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/Saml/...
no
### Client configuration
**Browser:**
any
**Operating system:**
any
#### Web server error log
<details>
<summary>Web server error log</summary>
no warnings/error at webserver level

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
No idea what to post - the logs are huge. Please advice.

</details>

#### Browser log
<details>
<summary>Browser log</summary>
nothing of interest here

</details>

**Comment by solracsf** [comment]
> Also, the group folders names are displayed by their number when being opened in the top breadcrumb section.

Already fixed on 29.0.5.

**Comment by Xiller** [comment]
29.0.5 i have Still this, after update:

All permissions where set to "inherit" which previously was "allow". Rules that had "forbidden" are still there. All other's are set to "inherit" which breaks access to most of our group folders. I had to manually set all ACL rules again.

and it doestn work on one person, exempale: Folder1->Subfolder1->Subfolder2->subfolder3
before update, oneGroupe was set "forbidden sharing"
one user i set that he can in Subfolder2 - Allow Shareing.
AFTER UPDATE:
its inherit, but the user cannot share!
i have to go in Sufolder2 AND subfolder3 to allow that he can share subfolder3 . After i did it manual, the position of the user go to the top (over the groupe where he is in too, where sharing is forbidden) and it works.
