### ISSUE TITLE
Is a slash/backslash in groupfolder name officially supported?

### ISSUE THREAD

**Issue by avychodil** [nextcloud/groupfolders#310]
I want to have structure of shared folder in organisation so I have created groupfolers like:

company\folder name1
company\folder name2

that is work great and when user have folder company, the share will appear imediately. I just don't know whether it is supported function cause I didn't find it anywhere. To prevent future problems with it could anybody confirm it is an intention this behaviour and it will stay like this even in future versions.

Thank you,

Ales

**Comment by avychodil** [comment]
I want to have structure of shared folder in organisation so I have created groupfolers like:

company\folder name1
company\folder name2

that is work great and when user have folder company, the share will appear imediately. I just don't know whether it is supported function cause I didn't find it anywhere. To prevent future problems with it could anybody confirm it is an intention this behaviour and it will stay like this even in future versions.

Thank you,

Ales

**Comment by RogerWilco2015** [comment]
Hello avychodil,
I have tried the same thing.
It works both with slashes (/) and backslashed (\). If the user doesn't have a "company" folder (as per your example), you can add it as a GroupFolder.
Everything seems to work fine except the client app.
In fact in my experience changes that take place in that folder are not synchronized locally by the app.
Vice-versa works: a local change on the pc is propagated in the cloud.

If we could get this to work it would be great, the limitation of having all group folders attached to the root folder makes things very messy an cluttered when you have lots of them.

Can someone shed some light on this?
Thank you.

**Comment by avychodil** [comment]
It's strange cause I've done it and it works great both on server and on local client (Mac OSX). The only problem is, whether it will be like this in future versions.

**Comment by RogerWilco2015** [comment]
The problem arises only if I create the "company" folder as another Group Folder. If the "company" folder is created by the user then all works as expected in my case as well.

**Comment by fschrempf** [comment]
We have at least two other related issues in #977 and #618 and I'm wondering myself if this is/should be supported.

@icewind1991 @juliushaertl Do you now if slashes/backslashes in folder names is officially supported? If not we should add code to prevent creating them and document this. If yes we need to care about potential bugs related to this.

**Comment by icewind1991** [comment]
Note that there are 2 separate cases here, folder name with a `/` in to create subfolders such as in this issue, and the folder name being just a `/` causing the groupfolder to effectively replace the users home.

Both cases are considered supported but for the first case there is currently no support for ensuring the parent folder exist so admins should create both the parent folder and subfolder groupfolders separately.

https://github.com/nextcloud/groupfolders/pull/1380 adds this to the docs

**Comment by fschrempf** [comment]
@icewind1991 Thanks for clarifying this and for the proposed update to the docs. I think we probably need some further explanations about nested groupfolders in the docs, but this is a good first step and the rest can be discussed in #1372.
