### ISSUE TITLE
[Bug]: public share not shown on group folders for other users

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/groupfolders#3123]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

All users need to know if documents or folders are shared with public links to avoid storing internal and/or sensible information. 

runs on Hetzner Server - no access to shell hence not all questions answered

### Steps to reproduce

- create a group folder
- create folders in this group folder
- User A creates a public share link on a folder and the "paper clip" is shown 
- User B does not see the paper clip - apparently the paper clip is only shown to the user who created the share
- User B creates an internal document not knowing that the folder is shared - this is an **organisational security issue** as documents are exposed unintentionally in public links

### Expected behavior

show paper clip to all users.

### Installation method

None

### Nextcloud Server version

26

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Other

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
runs on Hetzner Server - no access to shell
```

**Comment by provokateurin** [comment]
Duplicate of https://github.com/nextcloud/groupfolders/issues/2408
