### ISSUE TITLE
Show Correct Path for deleted files

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/groupfolders#3124]
Hey,

when you delete a file and then go to "files > deleted files "you will see "all files\filename" or "all files\subfolder\filename".

It would be much more convenient if we could see the group folder name here. "groupfolder name\filename" or "groupfoldername\subfolder\filename"

**Comment by provokateurin** [comment]
I can not reproduce this exact issue, but the "Original location" column only shows the subfolder inside the groupfolder and not the path of the groupfolder too. I think this is a UX issue, so something we should fix.
