### ISSUE TITLE
disable group folders should issue a warning, that all synced client data will be deleted.

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/groupfolders#3129]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
This issue and the proposed solution led to deletion of all synced data on connected desktop and especially local availalbe data on mobile clients, 
https://github.com/nextcloud/fulltextsearch/issues/858#issuecomment-2294889748

Luckily the data on the server were not deleted (as war as I can see). Probably these get only removed I the app itself is removed. So I just had to re-sync some 150GB and those off-line have not been affected.

**Describe the solution you'd like**
The disable operation should at least issue a warning, that this will lead to loss of synced  client data.

**Describe alternatives you've considered**
This was proposed - but obviously only valid for this special case.
https://github.com/nextcloud/fulltextsearch/issues/858#issuecomment-2295835286
It was a NC-Service provider which took this action as the update of the group folder app made the NC server in accessible.

**Additional context**

**Comment by provokateurin** [comment]
You mean when the groupfolders app is disabled? I don't think there is a way to show a warning when this happens, but as with any app it should be obvious to the admin that disabling/removing them has side effects.
Maybe a general warning about this should be shown when any app is disabled/removed, but that is nothing for Groupfolders. Please open an issue in server to request such a warning to be shown.

**Comment by ferdiga** [comment]
sorry - it should be mentioned in the group folder admin page "do you want to disable and all synced groupfolders on clients will be deleted", the server does, what it should do
