### ISSUE TITLE
Moved a 200mb groupfolder and trash immediately grew to 19gb, consuming all disk space, lost all files in folder.

### ISSUE THREAD

**Issue by winstonford** [nextcloud/groupfolders#313]
version 15.0.2 snap on ubuntu 16.04

I moved a groupfolder with less than 200mb, moved it back, and got a 423 lock error.

I logged into my server to find that my group folder trash immediately grew to 19gb and left zero space on my / partition.

I began reporting this issue in the snap repo but after researching and learning about trash issues with groupfolders in nextcloud 15, decided to post here.

This is the snap issue: https://github.com/nextcloud/nextcloud-snap/issues/884

I did nextcloud.occ trashbin:cleanup and emptied trash for all users, but the groupfolder trash remained at 19gb.  When I restarted my snap, a machine began to sync, and trash instantly grew to 21gb, again leaving zero disk space on root partition.

The original folder that I moved now retains the folder structure, but all files are gone.

I am happy to provide any log files or anything that may help resolve this issue.

In the meantime I will no longer use groupfolders.

**Comment by icewind1991** [comment]
Should be fixed with 2.0.4
