### ISSUE TITLE
[Bug]: Groupfolder without permission appears again with red background color

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/groupfolders#3169]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [ ] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the update to version 28.0.8 a groupfolder that i was member of a time ago appeared again with red background color.
![screenshot](https://github.com/user-attachments/assets/598830e1-f983-408a-add8-24aeed4577e8)

### Steps to reproduce

1. Add member to group folder.
2. Remove member from group folder.
3. Update to version 28.0.8

### Expected behavior

The groupfolder shouldn't be visible as it was before.

Was there a change in the behaviour?

### Nextcloud Server version

28

**Comment by provokateurin** [comment]
Do you have some logs from the upgrade and when you open the Files app?
Otherwise I don't think there is a way to reproduce it.
