### ISSUE TITLE
Shared URL will change in several hours

### ISSUE THREAD

**Issue by Bables55** [nextcloud/groupfolders#319]
Issue a shared URL with data in a folder set up by Group Folders.app.  The shared URL changes to a different one after several hours. The target data is not touched by anyone. With data placed outside the Group Folders, there is no change in such a shared URL.

I heard it on the Nextcloud forum, but I heard that it is normal for the URL to be changed by releasing the share URL once. Is GroupFolder doing some unintended acts similar to that?

--
Nextcloud 15.0.2-15.0.4, PHP 7.3.2, CentOS 7.6, Group Folders.app 2.0.2

**Comment by Bables55** [comment]
>Ver.2.0.3: fix share permissions on group folder root
It seems that cron error has occurred once a day, but is it corrected including this issue in this update?

**Comment by pierreozoux** [comment]
@Bables55 is it still the case?
