### ISSUE TITLE
Someone without delete rights in the group can permanently delete the file from the recycle bin

### ISSUE THREAD

**Issue by tiptoptom** [nextcloud/groupfolders#3279]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Group folder A created
2. Group B created
3. User C added to group B
4. Group folder A made accessible for group B
5. Created a file as user C in group folder A and moved it to the recycle bin
6. Group B revoked the “delete” rights for group folder A
7. User C could see the file in the recycle bin and delete it permanently

### Expected behaviour
Someone without delete rights in the group shouldn't be able to permanently delete a file from the recycle bin

### Actual behaviour
someone without delete rights in the group can permanently delete the file from the recycle bin

### Server configuration

**Operating system:** Linux 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64

**Web server:** nginx/1.25.3 (fpm-fcgi)

**Database:** mysql 10.5.26

**PHP version:** 8.2.22

**Nextcloud version:** (see Nextcloud admin page) 29.0.5 - 29.0.5.1

**Group folders version:** 17.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** hetzner storage Share

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:129.0) Gecko/20100101 Firefox/129.0

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by provokateurin** [comment]
Fixed in all latest releases
