### ISSUE TITLE
no advanced permissions for groupfolder

### ISSUE THREAD

**Issue by Overpass4014** [nextcloud/groupfolders#3289]
### Actual behaviour
After the nextcloud update to version 30, I can no longer see any extended permissions for the group folders.

### Server configuration

**Operating system:**

**Web server:*apache*

**Database:*mysql*

**PHP version:*8.2*

**Nextcloud version:*30* (see Nextcloud admin page)

**Group folders version:*18.0.1*

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

**Operating system:*debian*

**Comment by provokateurin** [comment]
You mean in the sidebar in the Files app?

**Comment by provokateurin** [comment]
Please send the browser and server logs so I can check what is going wrong.
I wasn't able to reproduce the issue on my side.

**Comment by joshtrichards** [comment]
I can't reproduce this problem either. Perhaps the problem is somewhere else, such as settings lost for some reason.

Is the account you're logging in as is still listed under *Administration settings->Group folders* as being able to manage *Advanced Permissions*?

**Comment by Overpass4014** [comment]
The Problem is now solved.
After i update Groupfolders from to 18.0.3 the problem is not solved.
But now i update Nextcloud from 30.0.0 to 30.0.1 the Problem ist solved and i am happy.
Thanks for you help!
