### ISSUE TITLE
Groupfolders advanced permissions on Main Folders

### ISSUE THREAD

**Issue by lastsamurai26** [nextcloud/groupfolders#3329]
Is it possible that I share a group folder with all groups but that folders which are created in this group folder are automatically forbidden for all users and only the creator of the folder can see it? 

Example 
groupfolder - > Facility(All groups can see everything)
User A create folder Facility\Cleaning
-> The Cleaning folder should belong to User A and all others are not allowed to see it -> User A must explicitly assign rights

**Comment by provokateurin** [comment]
You can achieve that by nesting Groupfolders:
```
Groupfolder A -> access by group A and group B
Groupfolder A/B -> access by group B
```
That way only users in group B will be able to see and interact with the subfolder.
