### ISSUE TITLE
Click on “add group” dropdown causes WSOD

### ISSUE THREAD

**Issue by stefanriske** [nextcloud/groupfolders#3366]
**Context**
It's about the “add group” dropdown in the modal window that appears if you click on the pen icon in the “Groups” column on the groupfolders' overview page (/settings/admin/groupfolders).
I'm still fairly new to the Nextcloud. Maybe/hopefully, I have simply overlooked something trivial.

**Expected behaviour**
In the past (on Nextcloud 16, with groupfolders v4, I think), when I clicked on the pen icon to edit the permissions, I was able to click on the  “add group” dropdown to add a user group.

**Actual behaviour**
Now, after upgrading to Nextcloud 30 (groupfolders v18), a click on the “add group” dropdown causes a WSOD and the browser console shows the following errors – I redacted some private URL parts.

```
react-dom.production.min.js:216 Invariant Violation: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at /themes/*/apps/groupfolders/build/settings.js:22:421
at a (/themes/*/apps/groupfolders/build/settings.js:22:524)
at findDOMNode (/themes/*/apps/groupfolders/build/settings.js:22:103904)
at t.value (/themes/*/apps/groupfolders/build/settings.js:31:52598)
at gs (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:257767)
at Ll (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:274573)
at t.unstable_runWithPriority (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:300652)
at Wo (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:216713)
at Bl (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:271312)
at Al (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:267423)
cs @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
ha @ react-dom.production.min.js:131
gs @ react-dom.production.min.js:220
Ll @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Bl @ react-dom.production.min.js:252
Al @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Yo @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
Le @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73


react-dom.production.min.js:123 Uncaught Invariant Violation: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
at /themes/*/apps/groupfolders/build/settings.js:22:421
at a (/themes/*/apps/groupfolders/build/settings.js:22:524)
at findDOMNode (/themes/*/apps/groupfolders/build/settings.js:22:103904)
at t.value (/themes/*/apps/groupfolders/build/settings.js:31:52598)
at gs (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:257767)
at Ll (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:274573)
at t.unstable_runWithPriority (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:300652)
at Wo (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:216713)
at Bl (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:271312)
at Al (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:267423)
(anonymous) @ react-dom.production.min.js:13
a @ react-dom.production.min.js:14
findDOMNode @ react-dom.production.min.js:266
value @ react-select-a34e9d12.browser.esm.js:405
gs @ react-dom.production.min.js:219
Ll @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Bl @ react-dom.production.min.js:252
Al @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Yo @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
Le @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73


react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'scrollHeight')
at t.value (react-select-a34e9d12.browser.esm.js:809:1)
at t.value (react-select-a34e9d12.browser.esm.js:784:1)
at As (react-dom.production.min.js:224:493)
at _s (react-dom.production.min.js:230:294)
at Ll (react-dom.production.min.js:256:468)
at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
at Wo (react-dom.production.min.js:122:325)
at Bl (react-dom.production.min.js:252:279)
at Al (react-dom.production.min.js:243:371)
at react-dom.production.min.js:123:115
cs @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
ha @ react-dom.production.min.js:131
gs @ react-dom.production.min.js:220
Ll @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Bl @ react-dom.production.min.js:252
Al @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Yo @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
Ie @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Dr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Zt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Kt @ react-dom.production.min.js:73


react-dom.production.min.js:123 Uncaught TypeError: Cannot read properties of undefined (reading 'scrollHeight')
at t.value (react-select-a34e9d12.browser.esm.js:809:1)
at t.value (react-select-a34e9d12.browser.esm.js:784:1)
at As (react-dom.production.min.js:224:493)
at _s (react-dom.production.min.js:230:294)
at Ll (react-dom.production.min.js:256:468)
at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
at Wo (react-dom.production.min.js:122:325)
at Bl (react-dom.production.min.js:252:279)
at Al (react-dom.production.min.js:243:371)
at react-dom.production.min.js:123:115
value @ react-select-a34e9d12.browser.esm.js:809
value @ react-select-a34e9d12.browser.esm.js:784
As @ react-dom.production.min.js:224
_s @ react-dom.production.min.js:230
Ll @ react-dom.production.min.js:256
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Bl @ react-dom.production.min.js:252
Al @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wo @ react-dom.production.min.js:122
Yo @ react-dom.production.min.js:123
Xo @ react-dom.production.min.js:122
Le @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
```

**Steps to reproduce**
1. Go to the groupfolders' overview page (/settings/admin/groupfolders).
2. In the “Groups” column, click on the pen icon in an existing Group folder to open its permissions modal window.
3. Click on the  “add group” dropdown to add a user group.
4. Suddenly, the entire screen turns white, and the browser console throws multiple JavaScript errors.

**Server configuration**
- Operating system: Ubuntu 22.04.1
- Web server: Apache 2.0
- Database: MariaDB 10.6.18
- PHP: 8.2
- Nextcloud version: 30.0.0
- Group folders version: 18.0.3

Please let me know if I can provide further information or if there's something I missed.

**Comment by provokateurin** [comment]
Could you try a hard refresh with Ctrl+shift+R to ensure it's not a caching issue?

**Comment by stefanriske** [comment]
Thank you for the suggestion. Yes, I always use the hard reload after updates. Unfortunately, it didn't help this time.

**Comment by joshtrichards** [comment]
Unable to reproduce.

What browser? And can you also double-check in a different browser and/or in privacy mode and/or with extensions disabled?

Also, can you share a bit more about your environment? Are you using a WAF, CloudFlare, or anything like that?

Anything red/showing an error under the browser inspect *Network* tab when you load (reload) that page and attempt to do that action?

**Comment by stefanriske** [comment]
Hi Josh, thank you for looking into this. To answer your questions:

> What browser? And can you also double-check in a different browser and/or in privacy mode and/or with extensions disabled?

We tested it on different machines (iMac, MacBook, Windows 11 Notebook), in different browsers (latest Chrome, Safari, Firefox, Edge). I have disabled all browser extensions. We get the same WSOD after clicking on the dropdown field on all machines.
However, you inspired me to do the unthinkable and test it in Safari on an iPad Air 5 (iOS 18.0.1) and it works there perfectly.

The JavaScript error does mention the 'scrollHeight', which is probably not an issue on touch devices.

> react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'scrollHeight')

Is it possible that it's a JavaScript error, and has nothing to do with server-side services (WAF, CloudFlare, etc)?


> Also, can you share a bit more about your environment? Are you using a WAF, CloudFlare, or anything like that?

It's a managed server. Unfortunately, I have upgraded to Nextcloud 30 shortly before we moved from our previous shared hosting to a managed server (same hoster, though). It's difficult to say if this issue was present on our previous shared hosting or not – I haven't tested this particular function after the upgrade to Nextcloud 30, before we moved to the new server.
I can ask the support if they are using any of the mentioned technologies. However, the fact that it doesn't work on any desktop browser but it works flawlessly on a touch device, tells me that it's a client-side error.

> Anything red/showing an error under the browser inspect Network tab when you load (reload) that page and attempt to do that action?

Everything has the 200 status on page load. After I click on the dropdown field (when everything goes white), the network tab doesn't change – no new entries, and existing entries don't change.

Please let me know if I can provide further information to help resolve this issue.
Were there any changes involving the scrollHeight that would explain the issue?

**Comment by joshtrichards** [comment]
> Is it possible that it's a JavaScript error, and has nothing to do with server-side services (WAF, CloudFlare, etc)?

WAFs and Cloudflare can mess with the JavaScript payload. But, yes, anything is possible. However, you're seeing things break across a wide variety of browsers that work just fine for us. :)

Saw this:

```
at /themes/*/apps/groupfolders/build/settings.js:22:421
at a (/themes/*/apps/groupfolders/build/settings.js:22:524)
at findDOMNode (/themes/*/apps/groupfolders/build/settings.js:22:103904)
at t.value (/themes/*/apps/groupfolders/build/settings.js:31:52598)
at gs (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:257767)
```

Are you using the deprecated old-style custom theming?

**Comment by stefanriske** [comment]
Josh, you were right! ❤️

> at /themes/*/apps/groupfolders/build/settings.js:22:421
at a (/themes/*/apps/groupfolders/build/settings.js:22:524)
at findDOMNode (/themes/*/apps/groupfolders/build/settings.js:22:103904)
at t.value (/themes/*/apps/groupfolders/build/settings.js:31:52598)
at gs (/apps-external/groupfolders/js/groupfolders-settings.js?v=4784ba85-32:2:257767)

These files were in my themes folder and after all these years, I don't even remember putting them there, or did the groupfolders plugin do it automatically?

As a test, I deleted the entire /themes/*/apps/groupfolders folder and now it works again. Will I be missing something if I don't have these files anymore?

**Comment by provokateurin** [comment]
That is legacy theming, you probably don't need it anymore if you don't even remember adding the files 😅

**Comment by stefanriske** [comment]
Thank you very, very much for your help! 🙂
