### ISSUE TITLE
Do not store group folders inside user data directory

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/groupfolders#338]
Do not store group folders inside the Nextcloud user directory under user name [`__groupfolders `](https://github.com/nextcloud/groupfolders/blob/eab26b3d461a98a4b241232a430fc50dc0437b89/lib/AppInfo/Application.php#L54).
This makes it possible to delete all data associated with a group folder if a user `__groupfolders` decides to delete his account (for example using the [drop_account](https://apps.nextcloud.com/apps/drop_account) app).

**Comment by pierreozoux** [comment]
Maybe a good workaround would be to forbid `__groupfolders` username? This would be an easy fix without much impact..
