### ISSUE TITLE
Object of class OCA\GroupFolders\Versions\GroupVersion could not be converted to string at /var/www/html/apps/groupfolders/lib/Versions/ExpireManager.php#126

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/groupfolders#339]
Hello, we get sporadically the following errors in the logs:

{"reqId":"Jn8DYDXhaBye11e9HTE2","level":3,"time":"2019-03-06T12:15:03+01:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Object of class OCA\\GroupFolders\\Versions\\GroupVersion could not be converted to string at /var/www/html/apps/groupfolders/lib/Versions/ExpireManager.php#126","userAgent":"--","version":"15.0.5.3","id":"5c7fdb30bb670"}

NC: 15.0.5.3
Group folders: 2.0.3
PHP: 7.2.15

**Comment by icewind1991** [comment]
Please check if db8450b fixes the issue for you

**Comment by Schmuuu** [comment]
Hi @icewind1991 
Your code changes fixed the issue for me at least. Thank you!

**Comment by PpaiSanchez** [comment]
I was also helped. Thx.

**Comment by icewind1991** [comment]
Fixed with 2.0.4
