### ISSUE TITLE
groupfolders 18.0.5 broken after nextcloud upgrade to 30.0.2

### ISSUE THREAD

**Issue by jpchev** [nextcloud/groupfolders#3424]
### Steps to reproduce
1. install group folder 18.0.5
2. upgrade Nextcloud from 30.0.0 to 30.0.2

### Expected behaviour
no regression

### Actual behaviour
in the group folders UI, lines appear doubled and clicks result only in javascript errors

### Server configuration

**Operating system:** kubernetes

**Nextcloud version:** (see Nextcloud admin page) 30.0.2

**Group folders version:** 18.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** update from 30.0.0

</details>

**Comment by provokateurin** [comment]
I am unable to reproduce this problem, both on 18.0.5 and the latest master branch.
For a short time there was a bug in 18.0.4 (https://github.com/nextcloud/groupfolders/issues/3414) which could be a possible cause?

Please make sure you are really using 18.0.5 and send some clear steps to reproduce.
Please also include the server and browser logs (remove any sensitive details), so I can get a better idea of the problem.

**Comment by provokateurin** [comment]
Without further information it is not possible to confirm or fix the issue. If you re-open, please add the additional info I asked for in the previous comment.
