### ISSUE TITLE
iOS app cannot share link from group folder

### ISSUE THREAD

**Issue by Wotisrv** [nextcloud/groupfolders#346]
I'm using group folders app v.2.3.1 with NC 15.0.5 on Fedora Server 29 Linux. Everything is working fine with group folders except the sharing of files with iOS NC app does not work. It is working with Android  NC app.
It does not matter which user has copied files to group folders. Sharing is working fine with NC Android app but not with iOS NC app.
I have tried with different iOS versions both iPhone and IPad and the results was the same. Share link does not work.
I have also tried with other Nextcloud clients and with them, sharing files has worked.
Maybe I should have published this issue in Nextcloud / ios?

**Comment by shutupfry** [comment]
I'm having the same issue. I can't generate a functional share link from the iOS app version 2.23.5.1 but I can from the web interface on my laptop. My server is 16.0.0 on FreeNAS 11.2 U4.1 running group folders 4.0.0

**Comment by Bables55** [comment]
I faced the same problem. I can't publish URLs on NC apps, but on PCs. I'm strange that there are two patterns when trying to publish a URL in an NC app.
The first is immediately disabled when the switch is turned on.  The second is similar in behavior to the first, but displays an error. It's a 404 error with "Request Faild: not Found". And I can press "Send link" below and send the URL. At this time, I can't disable it. This does not change even if all permissions are enabled.
---
Nextcloud 16.0.4, PHP 7.3.8, Groupfolders 4.1.0, NC iOS app 2.23.8.30

**Comment by juliushaertl** [comment]
If it works though the web UI please open an issue in the iOS app repo.

**Comment by Bables55** [comment]
> If it works though the web UI please open an issue in the iOS app repo.
There is no problem with Web browsers. The behavior is exactly the same as the desktop version.

**Comment by ricain** [comment]
This has been created: https://github.com/nextcloud/ios/issues/795

@juliushaertl there is also an issue about API and Group Folder app #271 which make it (possibly) a Group Folder bug.

cc @marinofaggiana

**Comment by Wotisrv** [comment]
Just some info. Even with an updated system to Fedora 30, NC 16.0.4.1, php 7.3.8, Group Folders 4.1.0 the issue still appears.

**Comment by ricain** [comment]
@wotisrv root cause has been found and issue is now tracked in #271
