### ISSUE TITLE
Newly created group folder cannot be shared

### ISSUE THREAD

**Issue by schmidtedv** [nextcloud/groupfolders#3467]
I remember, this was possible, but I don't anymore, when this behavior has changed. However, I'm using GF 15.3.11 with NC 27.1.11 on Ubuntu 20. First time I create a new group folder (in Firefox) the folder is shown in the list, but if I share this folder with a couple of groups right after creation, this share is not saved (anymore). I would have to update the page first and then share the folder, so that these change gets saved. I remember, it worked before, creation and sharing in one step, so this looks like a bug to me.

The Errorlog is empty and the behavior can be reproduced everytime.

**Comment by schmidtedv** [comment]
Well, we can't upgrade right now, because NC is missing at least 1 app we still need.

 

Mit freundlichen Grüßen
 
Florian Schmidt

 

Von: Kate ***@***.***> 
Gesendet: Donnerstag, 5. Dezember 2024 12:28
An: nextcloud/groupfolders ***@***.***>
Cc: schmidtedv ***@***.***>; Author ***@***.***>
Betreff: Re: [nextcloud/groupfolders] Newly created group folder cannot be shared (Issue #3467)

 

Please update to Nextcloud 29 or higher first, then we can check if this problem still exists. 27 doesn't receive any bug and security fixes anymore so you should definitely upgrade anyway.

**Comment by provokateurin** [comment]
Which app?

If you can't upgrade, then I'd like to close this issue for now as we can't really help you right now.

**Comment by schmidtedv** [comment]
The App Extract

However, you can close this. If I find the issue in NC 30, I will open another case, ok?
