### ISSUE TITLE
Feature Request: API for Advanced Permissions Management

### ISSUE THREAD

**Issue by gommez1991** [nextcloud/groupfolders#3479]
Hello Nextcloud Team,

Thank you for your amazing work on the Groupfolders application! 🙌

#### Context
I am currently automating the management of group folders in my Nextcloud instance. While the existing API allows creating and sharing folders, there is currently no API endpoint to manage **advanced permissions** (e.g., restricting read/write/delete access for specific groups or users). These permissions are crucial for securely organizing and managing our collaborative workflows.

#### Feature Description
I would like to request an API endpoint that allows:
1. Setting advanced permissions for subfolders within a group folder.
2. Restricting access (read/write/delete) for specific groups or users.
3. Retrieving the current advanced permissions configuration for a folder.

#### Use Case Example
For example, we have a group folder named `Project X` with:
- A subfolder `Admin`, visible only to the `Admin` group.
- A subfolder `Development`, visible to the `Dev` group and `Team-Tech Leaders`.
- A quota of 1GB.

Currently, such configurations can only be done manually via the UI, which is time-consuming and not scalable for larger deployments.

#### Expected Outcome
An API that allows programmatically configuring advanced permissions, enabling more seamless automation and integration with third-party tools.

Thank you for considering this request. I am happy to provide further details or help test any implementation of this feature.

Best regards,  
Ahmed

**Comment by provokateurin** [comment]
Thanks for your interest in Groupfolders!
We already have an issue about this topic: https://github.com/nextcloud/groupfolders/issues/1256
So closing as a duplicate :)
