### ISSUE TITLE
allow group admin to create and edit group folders

### ISSUE THREAD

**Issue by sualko** [nextcloud/groupfolders#35]
cc @danscharon

**Comment by dan-nkl** [comment]
Wow 👍 That would be awesome! Love this idea :)

**Comment by sualko** [comment]
I would suggest to add an extra entry to the settings menu near to the "Users" and "Apps" links. This could be done by this little snippet:

```
$userObject = \OC::$server->getUserSession()->getUser();
$isSubAdmin = false;
if($userObject !== null) {
$isSubAdmin = \OC::$server->getGroupManager()->getSubAdmin()->isSubAdmin($userObject);
}

if ($isSubAdmin || IS_ADMIN){
\OC::$server->getNavigationManager()->add(function () {
    $urlGenerator = \OC::$server->getURLGenerator();
    return [
        'type' => 'settings',
        'id' => 'groupfolders',
        'order' => 10,
        'href' => $urlGenerator->linkToRoute('myapp.page.index'),
        'icon' => $urlGenerator->imagePath('myapp', 'app.svg'),
        'name' => \OC::$server->getL10N('myapp')->t('My App'),
    ];
});
}
```

**Comment by putt1ck** [comment]
@sualko so that group folders can be created by anyone (who is a group admin) rather than centrally controlled?

**Comment by sualko** [comment]
@putt1ck yes, that was my intention, but I had no time to dick into this.

**Comment by richard-dg** [comment]
> @sualko so that group folders can be created by anyone (who is a group admin) rather than centrally controlled?

Yes. That'd be great. The group admin should have full control over existing group folders and also be able to create new ones. Of course only for the groups he administers.

**Comment by nursoda** [comment]
This is related to https://github.com/nextcloud/groupfolders/issues/35

**Comment by ZeikoFr** [comment]
Hi @sualko If I understand your proposal correctly, this should be now possible with the ACL am I right ?

**Comment by fschrempf** [comment]
> Hi @sualko If I understand your proposal correctly, this should be now possible with the ACL am I right ?

I don't think this has anything to do with ACL. This is about allowing group admins to be able to create and manage groups folders for the groups they have admin privileges. Currently only a super admin is allowed to do this.

I think it would be very helpful to implement this feature.

**Comment by putt1ck** [comment]
Creation of group folders should be limited to those who can create groups; with ACLs only one folder is really needed per group (kinda by definition) and maybe not that many. So a group needs a group folder requests it, and permissions are applied as needed, with advanced permissions enabled and control granted as needed. Group admins and others can then create and secure subfolders as required.

I cannot see a logical reason a group would need multiple folders just for that group (which is all that could be enabled for a group-level admin) so opening the security model doesn't make sense.

**Comment by fschrempf** [comment]
@putt1ck That's a good point. The super admin could create a groupfolder by default for each group that is created and leave the rest to be managed by ACL in the sub directories. I think I will try this approach for now.

**Comment by fschrempf** [comment]
As pointed out by @putt1ck above, with the ACL feature available, there is not really a need for someone other than the admin to create groupfolders. If no one has any objections I would suggest to advertise using ACL to any user that requests this and close this as "won't fix" for now?

**Comment by putt1ck** [comment]
Agreed
