### ISSUE TITLE
Improve UX for nested folder creation

### ISSUE THREAD

**Issue by small1** [nextcloud/groupfolders#355]
In the settings where you add the group folders it would be good too have a small tip on how to make nested folders.

As it is right now there are many that just writes a folder name and afterwards cant figure out how to add a second one within that.

Best choice would be if one could reorder folders in some way to show that some are subfolders.  But it can also be acceptable to just show a small message.

**Comment by ZeikoFr** [comment]
Hi, I know this is a pretty old issu but does the ACL that are now available fix your request ? If so I think you can close the issue.

(I might have misunderstood your request as my english level is not perfect)

**Comment by pierreozoux** [comment]
It is currently possible to create nested subfolders, but indeed, it is not obvious.

**Comment by fschrempf** [comment]
I'm closing this in favor of the more generic issue #1372.
