### ISSUE TITLE
No synchronization of group folder contents via desktop client after initial configuration

### ISSUE THREAD

**Issue by patrick-stickler-csc-fi** [nextcloud/groupfolders#36]
After adding a particular user account which belongs to a group having a group folder shared to it, all of the group folder contents get sync'd to the desktop as expected, but updates to the group folder by other users never get sync'd.

If the user account is mounted via WebDav, changes show up whenever the mounted directory space is refreshed, but even quitting and restarting the Nextcloud desktop sync app does not force a resync of the group folders. 

Modifying/deleting files locally in the sync'd space does, though, update the group folder space in Nextcloud, so the sync issue seems to be uni-directional. Changes on the server never show up locally.

FWIW, this is with Nextcloud v12, OS-X Sierra.

**Comment by MatthlK** [comment]
Hi,

file changes / new files on server don't sync with client (mac 2.2.4.1) anymore with version 1.1.0. Changes on client get synced. Is it save to downgrade?

Thanks.
Nextcloud 12 here - osx sierra.

**Comment by thfree** [comment]
Similar problem after upgrading to 1.1.0

**Comment by FMiot** [comment]
I have the Same problem after upgrade.

**Comment by icewind1991** [comment]
Fix is here: https://github.com/nextcloud/server/pull/5685
