### ISSUE TITLE
directory tree of group folders

### ISSUE THREAD

**Issue by marianoju** [nextcloud/groupfolders#364]
I have setup a Nextcloud with groupfolders and organized read/write permission by groups. 

**Problem description** 
Feedback from users concludes that there is a lack of transparency: 
1. user can not see which folders exist that user can not access (this is a valid setting, but should can also be helpful the other way in an organizational use case and should be optional); 
2. user can not see which permissions user has for each folder (there is only a very discreet notification “You don’t have permission to upload or create files here” visible within the respective group folder when no write permission is given); 
3. user can not see which other groups exist (that user do not belong to) and which group folders they can access with which rights (this is a valid setting, but should can also be helpful the other way in an organizational use case and should be optional). 

**Feature request**
I request a feature to be introduced, that allows to (dynamically) create a directory tree of the group folders that visualizes groups and rights, taking into account optional settings as outlined above. 

**Workaround** 
1. Create an user that has read permission for all group folders. 
2. Synchronize directories via the desktop client to my machine. 
3. Plot a graphical tree of my local directories (similar to [this](https://www.commandlinefu.com/commands/view/710/)). 
4. Create a table (based on the aforementioned plot) that illustrates groups and permission. 
5. Repeat process when directory structure or permissions change(s). 

**Remark** 
I understand, that the current situation may be preferable in certain settings (e.g. where security is valued higher than openness). The workaround is time-consuming, error-prone and relies on an administrator to create a snapshot of the structure.

**Comment by fschrempf** [comment]
@marianoju Have you looked at the "Advanced Permissions" (ACL) feature? It sounds like this would serve your needs.

**Comment by pierreozoux** [comment]
the 3 is https://github.com/nextcloud/groupfolders/issues/975

For the 2nd, I just tested:
![image](https://user-images.githubusercontent.com/1863453/113429031-23eebe80-93d8-11eb-928d-011663c56748.png)

it is quiet clear.

As for the 1rst 🤷‍♂️  I understand it can be needed.. But then you can fiddle with rights so people could see the top folders but not the content.

I'll close as a wontfix, sorry :)
