### ISSUE TITLE
Allow group admins to create group folders

### ISSUE THREAD

**Issue by kungknut** [nextcloud/groupfolders#366]
We would appreciate the ability of users with group administration privileges to be able to create group folders and assign privileges to the groups administrated by that user.

The group administrator should only be able to manage group folders created by the group administrator itself.

**Comment by chrsch** [comment]
I would like to second this. Is it possible to get an outline from the devs what is needed to implement this feature? So I could see if we can contribute. Thanks!

**Comment by gtchm** [comment]
Please we need this so very much!!

**Comment by gtchm** [comment]
Could you guys please confirm that the only option currently available to edit the permissions (and ACL) from the WEB UI is to be admin for the whole UI?

**Comment by wiswedel** [comment]
let's discuss this in #400

**Comment by fschrempf** [comment]
> let's discuss this in #400

#400 is about who is allowed to edit advanced permissions (ACL). I think this feature request is about who is allowed to create and configure a group folder in the first place which is limited to the super admin at the moment. There is also #35 as a duplicate.

In my case I want to allow group admins assigned by the super admin to be able to create group folders for the groups they are allowed to manage, which is completely independent of ACL and #400.

I think we can keep this closed, but not as solved by #400, but as duplicate of #35.
