### ISSUE TITLE
if groupfolders in list of files and folders then search function is buggy on changing view or changing list order

### ISSUE THREAD

**Issue by stekaa** [nextcloud/groupfolders#373]
### Steps to reproduce

    1. Create some files and folders.

    2. In view "All files" use search function to list only some of the files and folder.

    3a. Change the view (e.g. click "Recent", "Favorites") and switch back to "All files"

    3b. Change the order of the list by clicking "Name"

### Expected behaviour
The List should contain all files and folders or only the files and folders matching search. Search pattern should pe visible in search field.

### Actual behaviour
There are no files/folders in list. Or they are filtered but incomplete. Below list the text "x folders and y files match 'test'" is written. I can't reset search pattern. No matter what I search it always lists files matching the first pattern.

I have to switch to "Activity", "Galery" or "Settings" and back or reload the whole page to get all my files listed again.

The bug only happens if there is a groupfolder in the list!

### Server configuration

**Operating system**: SUSE SLES12

**Web server:** Apache 2.4.23

**Database:** MariaDB 10.0.35

**PHP version:** 7.0.7

**Nextcloud version:** 14.0.8
### Client configuration

**Browser:** Firefox 65.0.1, IE 11

**Operating system:** Windows10, Windows 7

**Comment by fschrempf** [comment]
@stekaa I don't think this is still a problem with the latest release. Please open a new issue if you think there's still something wrong.
