### ISSUE TITLE
Groupfolder with external upload not working

### ISSUE THREAD

**Issue by dkellenb** [nextcloud/groupfolders#38]
Given:
- Nextcloud 12.0.0
- Group folders 1.1.0
- Create group folder `group_folder` with group `group_folder_share`
- Create a folder named `upload` in `group_folder`
- Share `upload` folder by share with link and upload only
- Upload files to this folder from external

=> Folder cannot be opened anymore and user is redirected to it's home directory

The only log i can see is:
```
Warning | no app in context | Missing expected parameters in change user hook | 2017-07-11T11:57:26+0200
-- | -- | -- | --
Warning | no app in context | Missing expected parameters in change user hook | 2017-07-11T11:57:25+0200
```

**Comment by anatomism** [comment]
I'd agree - there seems to be something fairly majorly wrong with the latest release.  All my desktop apps have stopped syncing group folders.  They say they're in sync but they really are not.

The previous version of Group Folders worked fine.  It also forced my clients to re-sync every bit of data from the Nextcloud server as per my topic...

**Comment by icewind1991** [comment]
I can access the upload folder correctly, although the uploaded files all have invalid permissions.

https://github.com/nextcloud/server/pull/5708 Fixes that problem, @dkellenb please check if that also fixes the problem for you

**Comment by dkellenb** [comment]
Yes, patch nextcloud/server#5708 fixes the problem.

**Comment by MorrisJobke** [comment]
Fixed by https://github.com/nextcloud/server/pull/5708
