### ISSUE TITLE
3.0.0 upgrade breaks occ

### ISSUE THREAD

**Issue by fasterit** [nextcloud/groupfolders#395]
````
# occ
An unhandled exception has been thrown:
ParseError: syntax error, unexpected '=' in /var/www/cluster4711/apps/groupfolders/lib/Command/ACL.php:150
Stack trace:
#0 /var/www/cluster4711/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/cluster...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#2 [internal function]: spl_autoload_call('OCA\\GroupFolder...')
#3 /var/www/cluster4711/lib/private/AppFramework/Utility/SimpleContainer.php(96): ReflectionClass->__construct('OCA\\GroupFolder...')
#4 /var/www/cluster4711/lib/private/AppFramework/Utility/SimpleContainer.php(119): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\GroupFolder...')
#5 /var/www/cluster4711/lib/private/AppFramework/DependencyInjection/DIContainer.php(426): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#6 /var/www/cluster4711/lib/private/ServerContainer.php(116): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#7 /var/www/cluster4711/lib/private/Console/Application.php(219): OC\ServerContainer->query('OCA\\GroupFolder...')
#8 /var/www/cluster4711/lib/private/Console/Application.php(134): OC\Console\Application->loadCommandsFromInfoXml(Array)
#9 /var/www/cluster4711/console.php(95): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/cluster4711/occ(11): require_once('/var/www/cluster...')
```

Disabling the groupfolders app in settings makes `occ` work again.
This is on Nextcloud 15.0.7.0 (current stable).

**Comment by Nils160988** [comment]
I can confirm this bug for groupfolders 3.0.0 with NC 15.0.7 and php 7.0 on Ubuntu 16.04.

Otherwise, no further problems seem to occur with groupfolders on a first check.

**Comment by IntelligentesTierMaulApollo13** [comment]
Same for me. Need to run a files:scan, but I am unable to do so - due to the exact same error.

NC 15.0.7, PHP 7.2, Ubuntu 18.04, Groupfolders 3.0.0

**Comment by kr4z33** [comment]
Same on attempting maintenance mode via occ command, setup similar to Nils160988

I noticed the following line in the logs on upgrading to 3.0.0 & disabling:
```
[PHP] Error: Array to string conversion at [Nextcloud install location]/lib/private/App/DependencyAnalyzer.php#356
```

**Comment by TP75** [comment]
I can confirm this bug for groupfolders 3.0.0 with NC 15.0.7.0 and PHP 7.0.33 on a Debian 9 server.

_occ_ seems to get broken completely by this app version i.e. including the _maintenance_ command.

**Comment by Nils160988** [comment]
Since this seems to be a severe error because it breaks nextcloud itself, it might be a possibility to stop the delivery of version 3.0.0 for Nextcloud 15 until there is a fix.
@juliushaertl ?

**Comment by juliushaertl** [comment]
Thanks for reporting. We have removed the 14/15 compatibility for the 3.0.0 release of the app store. If you have already upgraded you should follow the instructions in https://help.nextcloud.com/t/groupfolder-3-0-0-breaks-occ/52212 to restore the old version.

**Comment by fasterit** [comment]
Manual fixing isn't a good solution as you have thousands of broken systems out there already.
Why not release a 3.0.1 that works with your current stable release and fix systems the way they got broken? Because these people all run updates but don't necessarily use occ until they need to fix a serious issue to then find it broken, too. I.e. Nextcloud fails for them in a moment of truth.

**Comment by fabiomt** [comment]
nextcloud/apps/groupfolders/lib/Command/ACL.php
On line 150 changed from this:
[$mask, $permissions] = $this->parsePermissions($permissionStrings);
To this:
[$mask, $permissions] == $this->parsePermissions($permissionStrings);

That fixed for me.

**Comment by fasterit** [comment]
@juliushaertl make this ^ into a 3.0.1 and fix this issue properly?

**Comment by nuvitong** [comment]
Hi,

I think `==`, i.e. a comparison, doesn't make sense, but the assignment is what the author had in mind.
It seems to me, that the shorthand syntax for [symmetric array destructering][1], which is new since php 7.1, is not correctly recognized. 

I changed the line to the alternative `list()` syntax, which seems to solve the issue (in my case updating the news feeds with occ).

```php
list($mask, $permissions) = $this->parsePermissions($permissionStrings);
```

Kind regards,

Tobias

[1]: https://php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring

**Comment by TP75** [comment]
@nuvitong 
> I think `==`, i.e. a comparison, doesn't make sense, but the assignment is what the author had in mind.
> It seems to me, that the shorthand syntax for [symmetric array destructering](https://php.net/manual/en/migration71.new-features.php#migration71.new-features.symmetric-array-destructuring), which is new since php 7.1, is not correctly recognized.

Thanks and the contribution looks very reasonable to me.  
I will reply after testing this with NC 15.0.7.0 and PHP 7.0 in our environment.

**Comment by joergmschulz** [comment]
indeed. In my php7.0 environment the fix of nuvitong helps.

**Comment by zansystem** [comment]
Hi, also in Centos 7 with NC 15.0.7 same problem. 
Removing groupfolder, resolve.

**Comment by TP75** [comment]
Tanks again and the a.m. hotfix by @nuvitong seems to avoid the main hassle.  

However, **be warned there may be other issues** in the groupfolders 3.0.0 code and a return to the 2.0.4 version should be a safe solution.

You may have a look into the [Comparing changes of groupfolders 3.0.0 against master view in GitHub](https://github.com/nextcloud/groupfolders/compare/v3.0.0...master) for further consideration.

**Comment by icewind1991** [comment]
3.0.1 has been released for NC14/15 to fix this issue
