### ISSUE TITLE
3.0.0 groupfolders colour does not respect theming

### ISSUE THREAD

**Issue by eFreshman** [nextcloud/groupfolders#397]
By color adjustments using the theming APP, my folders are usually gray. After the update the group folders in the standard blue, whilst the other folders are still gray.

This is on Nextcloud 15.0.7.0 (current stable).

**Comment by rspierenburg** [comment]
Same here

**Comment by HealthCIO** [comment]
I can confirm this is an issue on my system as well.  PHP 7.2, Ubuntu 18.04, NextCloud Stable 15.0.7.

**Comment by bpcurse** [comment]
Same problem with Nextcloud 16.0.0 (groupfolders 3.0.0).
