### ISSUE TITLE
Nextcloud 15

### ISSUE THREAD

**Issue by CHazz** [nextcloud/groupfolders#406]
i have Nextcloud 15 but still have announcement for update to 3.0.0 (NC 16)

**Comment by Nils160988** [comment]
This is because https://github.com/nextcloud/groupfolders/pull/402 has not been merged yet. As soon as this is done, you should get the announcement for 3.0.1 (which is the same as 2.0.4).

**Comment by icewind1991** [comment]
3.0.1 has been released for NC14/15
