### ISSUE TITLE
Allow (proper) renaming of group folders

### ISSUE THREAD

**Issue by 9662** [nextcloud/groupfolders#41]
This is a wee feature request:

> As an administrator with the ability to create group folders, I would like to be able to rename those folders from the administration interface (`cloud.example.com/settings/admin/groupfolders`)

I expect this is orthogonal to the problems reported in #33 and #7.

**Comment by icewind1991** [comment]
Fixed with 6c78ef13d551433118307fc730f4dfe90a7e566e
