### ISSUE TITLE
3.0.0 / NC 16: edit of text files in group folders not possible. After opening, they are empty

### ISSUE THREAD

**Issue by puzich** [nextcloud/groupfolders#412]
If I open a text file in a group folder, which was previously filled before, it is only a "1" in it. All changes I have made, are gone.

This issue is only present, if advanced permissions are active

**Comment by maghog** [comment]
Same problem...

**Comment by htyangya** [comment]
Same problem... and wei can update it with the full content，only by read online it is empty
