### ISSUE TITLE
NC 14/15/16: Opening or adding an OnlyOffice Document within a group folder doesn't work.

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/groupfolders#413]
Nextcloud 14, 15, 16:
Opening or adding an OnlyOffice Document within a group folder doesn't work.

![Screenshot 1](https://user-images.githubusercontent.com/31374152/57079401-8d4b8b80-6cf0-11e9-9eca-7df1cd3cd0b1.gif)

![Screenshot 2](https://user-images.githubusercontent.com/31374152/57079400-8d4b8b80-6cf0-11e9-8af7-59a9de80a4d9.gif)

**Comment by puzich** [comment]
#411

**Comment by icewind1991** [comment]
Closing as duplicate of #411
