### ISSUE TITLE
Can't open with Collabora if used advanced permission

### ISSUE THREAD

**Issue by htyangya** [nextcloud/groupfolders#420]
If advanced permissions are opened and any set of advancedl permission rules are added to the folder, all files in the folder can no longer be opened with collabora. Tip: Connection to online collaboration failed, please try again later or contact the administrator.

**Comment by htyangya** [comment]
I upgraded to version 4.0 and tried again. The problem was not solved. As long as any group opens a high-level permission rule, the group account cannot open a file.

**Comment by icewind1991** [comment]
Can you check if 833749c2df8328735cbe96cdc2dee7c9aded44f2 fixes the problem for you

**Comment by wiswedel** [comment]
@htyangya Does the issue still remain or can we close this ticket?

**Comment by fschrempf** [comment]
I'm assuming this is fixed, so I'm closing now. If not, please comment or open a new issue. Thanks!
