### ISSUE TITLE
ACL not visible in Safari browser (since groupfolders 4.0.0)

### ISSUE THREAD

**Issue by DrDeath** [nextcloud/groupfolders#421]
To reproduce:

Use browser Safari on a Mac.

Click on the three dots on a groupfolder,
select "Details"
select "Share".

The additional "ACL" Options are not shown.

Same on a firefox browser will show the ACL options.

**Comment by DrDeath** [comment]
Closing issue.
Seems to be fine now in Nextcloud 16.0.1

**Comment by HewittJC** [comment]
This is an issue now in Google Chrome. I will open a new issue
