### ISSUE TITLE
Unavailable after updating to Ver. 4.0

### ISSUE THREAD

**Issue by Bables55** [nextcloud/groupfolders#422]
I can't use GroupFolder.app on Nextcloud 16. When I updated NC16, GF 3.0.2 could use on NC16. A few days later 4.0 was released and I updated.
When I look at the group folder item on the admin settings, I can see the title of the setting but everything else is white. Then I went back to 3.0.2, but I can not use 3.0.2.

--- 
Nextcloud 16.0.0
CentOS 7.6
Nnginx 1.14.2
PHP 7.3.4

**Comment by fschrempf** [comment]
@Bables55 If you still see issues like this, please test against a recent release and open a new issue. Thanks!
