### ISSUE TITLE
Existing shared links and private links changed after update from 2.0.4 to 3.0.2

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/groupfolders#423]
Hi there,

i did an update from the groupfolder app and also moved the Nextcloud Data directory to a different location on my server. Second should not have an influence on created shared links right ?

After the update of the groupfolder app links created via the "Create private link and copy to clipboard" in the Desktop-App are different suddenly. That means also all links previously created are not working anymore at the moment. 
I recognized that also the URL changed a little when accesing files in groupfolders.

2.0.4: http:///nextcloud.docker.xxx.local/index.php/apps/onlyoffice
3.0.2: http://nextcloud.docker.xxx.local/apps/onlyoffice

The file path then is identical but the **index.php** is new. 

i am happy about any help on this

**Comment by icewind1991** [comment]
the groupfolder app has no influence on these links, please open a issue in the server app
