### ISSUE TITLE
Can't delete advanced permission rule

### ISSUE THREAD

**Issue by steffen-kdab** [nextcloud/groupfolders#431]
* Create a subfolder of a group folder, add some advanced permission rules
* Try to delete a rule again, nothing happens. Chrome console shows:
![image](https://user-images.githubusercontent.com/2077697/57676954-fd79db80-7625-11e9-878b-aadb478f9929.png)

Nextcloud 16.0.0.9 (same with 16.0.1-RC1)
Groupfolders 4.0.0

**Comment by DecaTec** [comment]
How is it posible to delete an advanced permission rule?
There's the "add..." button, but I cannot figure out how to remove an advanced permission rule.

**Comment by jpbraun** [comment]
Same problem. Can't remove access rule.

![2019-05-19_171605](https://user-images.githubusercontent.com/31374152/57984264-69ab7380-7a5a-11e9-97eb-0e30acfeeb6d.gif)

**Comment by DecaTec** [comment]
@jpbraun Oh there the option is to delete access rules.
I tested it with a lower desktop resolution (1366x768) and there I cannot see the delete button:
![2019-05-20_07-13](https://user-images.githubusercontent.com/9428899/57997850-23442c00-7acf-11e9-906e-345835bf4ef3.png)

On a higher desktop resolution, the button is visible.

**Comment by steffen-kdab** [comment]
I can confirm that this is indeed fixed since 4.0.1, thanks! :+1:
