### ISSUE TITLE
Show filesystem path to Group Folder

### ISSUE THREAD

**Issue by osscombat** [nextcloud/groupfolders#432]
Hi! Is it possible to show the actual Group Folder location on the filesystem (like this is done for user profiles) in the NC web-interface? This will be helpful to identify the folders with non-Latin unicode names.

**Comment by fschrempf** [comment]
Why would you need that information in the web UI and where is this visible for user profiles? Why would you need to identify the filesystem locations for groupfolders? Can you explain?

**Comment by osscombat** [comment]
this is useful to identify the corresponding paths in the filesystem,
especially for non-latin names.

чт, 18 мар. 2021 г., 20:29 Frieder Schrempf ***@***.***>:

**Comment by CarlSchwan** [comment]
If you are an admin, you can get the id with `sudo -u www-data ./occ groupfolders:list` and then go to `__groupfolder/{id}`. Ihmo exposing the path to normal users is a terrible ux idea.
