### ISSUE TITLE
Unable to remove advanced permission rule

### ISSUE THREAD

**Issue by jonasgarstick** [nextcloud/groupfolders#433]
Try to remove an advanced permission rule in a group folder if more than one access rule is set. If you click on the X nothing happens:

![delete-permission](https://user-images.githubusercontent.com/17829368/57859769-e1c43000-77f3-11e9-9cb1-a6dfcdd173b5.png)

If there is only one access rule defined, I am able to remove the rule as intended.

Nextcloud version 16.0.1
Group folders version 4.0

**Comment by jpbraun** [comment]
I have the same problem.

**Comment by pierreozoux** [comment]
@jonasgarstick  do you still have the issue?
Does your user have special char in it?
What if you do it on a folder without special char? Is it the same?
Do you have any browser log? or server log?
Can you try to deactivate all your browser plugins and try to reproduce?

Thanks!

**Comment by jonasgarstick** [comment]
> @jonasgarstick do you still have the issue?
> Does your user have special char in it?
> What if you do it on a folder without special char? Is it the same?
> Do you have any browser log? or server log?
> Can you try to deactivate all your browser plugins and try to reproduce?
> 
> Thanks!

This issue seems to be fixed, I just verified with Nextcloud 20.0.9 and Group folders 8.2.0. Thanks for tidying up here @pierreozoux
