### ISSUE TITLE
Setting item is not displayed

### ISSUE THREAD

**Issue by Bables55** [nextcloud/groupfolders#439]
When I select a group folder from the administrator's settings, only the header "Group folders" is displayed and nothing else is displayed.

I was disabling folders when Group Folders was working without problems. The app itself is enabled. Only settings are disabled. So the user did not see the group folder. I faced this problem as I tried to enable it after a long time.

I tried removing and reinstalling the app. What else should I do?

--- 
Nextcloud 16.0.1
Group folders 4.0.1

**Comment by VanDerLars** [comment]
I've got the same problems.

Without this feature, Nextcloud unfortunately not useable for us :/

**Comment by Bables55** [comment]
It did not improve by 4.0.2.

**Comment by Bables55** [comment]
I want to reset the Group folder settings because I may give up the settings. Just by uninstalling the application, MariaDB has group folder remnants.

Which table is the Group folder?
When I manually deleted the four tables with "group_folders" included in the table name, NC broke. *NC returned when I returned the table.

**Comment by MorrisJobke** [comment]
Is there anything in the network tab that is not a default response (40x or 50x HTTP responses are highlighted in red and may indicate problems).

**Comment by VanDerLars** [comment]
Here is a screenshot of our js console while opening the settings-page:
![Bildschirmfoto 2019-06-07 um 16 00 18](https://user-images.githubusercontent.com/9517567/59109739-e20ca280-893d-11e9-8f63-dd8b225cb902.png)

**Comment by VanDerLars** [comment]
The following assets can not be loaded (shotted from the network section of the dev tools):

![Bildschirmfoto 2019-06-07 um 16 05 44](https://user-images.githubusercontent.com/9517567/59109866-25671100-893e-11e9-91d3-1b5ad9e29c17.png)

**Comment by VanDerLars** [comment]
Is there any information how to fix that problem or if it'l be fixed in the nearer future?

We've set up Nextcloud on three different devices, all of them shows this issue.

**Comment by MorrisJobke** [comment]
@juliushaertl @skjnldsv Any idea why this css file isn't loaded, but everything else?

**Comment by skjnldsv** [comment]
99% of the time it's a webserver config.
@Bables55 @VanDerLars  Are you using apache? Nginx?

**Comment by Bables55** [comment]
>  Are you using apache? Nginx?
I use Nginx.

**Comment by skjnldsv** [comment]
@Bables55 please post your config :)

**Comment by Bables55** [comment]
This problem was solved by ver.4.0.4.
Thank you.

**Comment by Bables55** [comment]
I thought that I solved it, but this problem revived. Apparently, it can only be displayed correctly just after updating to 4.0.4. I set up the group folder at that time, but it is alive and functioning properly.
It seems that only the setting screen can not be displayed.

**Comment by Bables55** [comment]
When I use Firefox, Brave, Sleipnir Edge web browser, Groupfolder setting items are displayed. We don't know Chrome, so we can probably use it. Vivaldi(same Chromium system)  is not displayed. Vivaldi seems to have no impact on extensions. We use Vivaldi.

**Comment by Bables55** [comment]
I extend the question. I set the detailed permissions.
I can not find at least the setting item of "Create" on the browser. It is only "Write, Share, Delete".
I tried with the occ command but I do not know the Path. Nothing is displayed in occ groupfolders: permissions <Folder ID>.

**Comment by pierreozoux** [comment]
@Bables55 you say that you have the problem with only Vivaldi browser?

**Comment by Bables55** [comment]
I hadn't used GroupFolder in a while. I just tried it and was able to view the settings for it.
