### ISSUE TITLE
The requested uri() cannot be processed by the script '/var/www/html/cron.php'

### ISSUE THREAD

**Issue by tikoflano** [nextcloud/groupfolders#441]
Every time my background cron job is called I get a bunch of errors in my logs (one entry for each user that is in a group folder):

`Exception: The requested uri() cannot be processed by the script '/var/www/html/cron.php')`

It seems that it started when I upgraded from 4.0.0 to 4.0.1 (I would like to downgrade to 4.0.0 to be sure, but I don't know and haven't found any way to do it)
**Update:** I downgraded to 4.0.0 and the errors are gone.

I can access de URL https://MYHOST/cron.php and it shows `"{"data":{"message":"Backgroundjobs are using system cron!"},"status":"error"}"`

The full log (sometimes it shows "no app in context" and sometimes "files") :

> [no app in context] Error: Exception: The requested uri() cannot be processed by the script '/var/www/html/cron.php') at <<closure>>
> 
>  0. /var/www/html/custom_apps/groupfolders/lib/Mount/MountProvider.php line 104
>     OC\AppFramework\Http\Request->getRawPathInfo()
>  1. /var/www/html/custom_apps/groupfolders/lib/Mount/MountProvider.php line 126
>     OCA\GroupFolders\Mount\MountProvider->getCurrentUID()
>  2. /var/www/html/custom_apps/groupfolders/lib/Mount/MountProvider.php line 90
>     OCA\GroupFolders\Mount\MountProvider->getMount(1, "/alvaro/files/Operaciones", 31, -3, OC\Files\Cache\CacheEntry {}, OC\Files\Storage\StorageFactory {}, true, OC\User\User {})
>  3. <<closure>>
>     OCA\GroupFolders\Mount\MountProvider->OCA\GroupFolders\Mount\{closure}("*** sensitive parameters replaced ***")
>  4. /var/www/html/custom_apps/groupfolders/lib/Mount/MountProvider.php line 88
>     undefinedundefinedarray_map(Closure {}, ["*** sensitive parameter replaced ***"])
>  5. /var/www/html/lib/private/Files/Config/MountProviderCollection.php line 103
>     OCA\GroupFolders\Mount\MountProvider->getMountsForUser(OC\User\User {}, OC\Files\Storage\StorageFactory {})
>  6. /var/www/html/lib/private/Files/Filesystem.php line 447
>     OC\Files\Config\MountProviderCollection->addMountForUser(OC\User\User {}, OC\Files\Mount\Manager {})
>  7. /var/www/html/apps/files_sharing/lib/SharedStorage.php line 127
>     OC\Files\Filesystem::initMountPoints("alvaro")
>  8. /var/www/html/apps/files_sharing/lib/SharedStorage.php line 482
>     OCA\Files_Sharing\SharedStorage->init()
>  9. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 495
>     OCA\Files_Sharing\SharedStorage->getWrapperStorage()
> 10. /var/www/html/apps/files_sharing/lib/SharedStorage.php line 166
>     OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage("OC\\Files\\Storage\\FailedStorage")
> 11. /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php line 495
>     OCA\Files_Sharing\SharedStorage->instanceOfStorage("OC\\Files\\Storage\\FailedStorage")
> 12. /var/www/html/lib/private/Files/Utils/Scanner.php line 150
>     OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage("OC\\Files\\Storage\\FailedStorage")
> 13. /var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php line 88
>     OC\Files\Utils\Scanner->backgroundScan("")
> 14. /var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php line 112
>     OCA\Files\BackgroundJob\ScanFiles->runScanner(OC\User\User {})
> 15. /var/www/html/lib/private/BackgroundJob/Job.php line 61
>     OCA\Files\BackgroundJob\ScanFiles->run(null)
> 16. /var/www/html/lib/private/BackgroundJob/TimedJob.php line 55
>     OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
> 17. /var/www/html/cron.php line 123
>     OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
> 
> at 2019-05-22T15:00:04+00:00

**Comment by rollanders** [comment]
I got the same error on 2 installations.

**Comment by rollanders** [comment]
I can confirm - the error disappeared after removing the groupfolder that was changed into a groupfolder after being created as an ordinary folder. I created a new folder the correct way and no errors since then.

**Comment by simonspa** [comment]
I get the same error on NC 16.0.1, Groupfolder 4.0.1 but there was no name overlap with existing folders.

**Comment by simonspa** [comment]
```
[files] Error: Exception: The requested uri() cannot be processed by the script '/var/www/nextcloud/cron.php') at <<closure>>

 0. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 104
    OC\AppFramework\Http\Request->getRawPathInfo()
 1. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 126
    OCA\GroupFolders\Mount\MountProvider->getCurrentUID()
 2. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 97
    OCA\GroupFolders\Mount\MountProvider->getMount(2, "/smn/files/GroupfolderTest", 31, -3, OC\Files\Cache\CacheEntry {}, OC\Files\Storage\StorageFactory {}, true, OC\User\User {})
 3. <<closure>>
    OCA\GroupFolders\Mount\MountProvider->OCA\GroupFolders\Mount\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 99
    undefinedundefinedarray_map(Closure {}, ["*** sensitive parameter replaced ***"])
 5. /var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php line 103
    OCA\GroupFolders\Mount\MountProvider->getMountsForUser(OC\User\User {}, OC\Files\Storage\StorageFactory {})
 6. /var/www/nextcloud/lib/private/Files/Filesystem.php line 447
    OC\Files\Config\MountProviderCollection->addMountForUser(OC\User\User {}, OC\Files\Mount\Manager {})
 7. /var/www/nextcloud/lib/private/Files/Filesystem.php line 376
    OC\Files\Filesystem::initMountPoints("smn")
 8. /var/www/nextcloud/lib/private/legacy/util.php line 308
    OC\Files\Filesystem::init("smn", "/smn/files")
 9. /var/www/nextcloud/lib/private/Files/Utils/Scanner.php line 106
    OC_Util::setupFS("smn")
10. /var/www/nextcloud/lib/private/Files/Utils/Scanner.php line 142
    OC\Files\Utils\Scanner->getMounts("")
11. /var/www/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 88
    OC\Files\Utils\Scanner->backgroundScan("")
12. /var/www/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 112
    OCA\Files\BackgroundJob\ScanFiles->runScanner(OC\User\User {})
13. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
    OCA\Files\BackgroundJob\ScanFiles->run(null)
14. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
15. /var/www/nextcloud/cron.php line 123
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-05-24T10:00:10+02:00
```

**Comment by rkaraba** [comment]
I get the same error on NC 16.0.1, Groupfolder 4.0.1 but there was no name overlap with existing folders.
I also have tested it on demo.nextcloud.com and if i create any group folder i get this error

[files] Error: Exception: The requested uri() cannot be processed by the script '/var/www/html/cron.php') at <<closure>>

 0. /var/www/html/apps/groupfolders/lib/Mount/MountProvider.php line 104
    OC\AppFramework\Http\Request->getRawPathInfo()
 1. /var/www/html/apps/groupfolders/lib/Mount/MountProvider.php line 126
    OCA\GroupFolders\Mount\MountProvider->getCurrentUID()
 2. /var/www/html/apps/groupfolders/lib/Mount/MountProvider.php line 97
    OCA\GroupFolders\Mount\MountProvider->getMount(1, "/admin/files/kvalita", 31, -3, OC\Files\Cache\CacheEntry {}, OC\Files\Storage\StorageFactory {}, true, OC\User\User {})
 3. <<closure>>
    OCA\GroupFolders\Mount\MountProvider->OCA\GroupFolders\Mount\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/apps/groupfolders/lib/Mount/MountProvider.php line 99
    undefinedundefinedarray_map(Closure {}, ["*** sensitive  ... }])
 5. /var/www/html/lib/private/Files/Config/MountProviderCollection.php line 103
    OCA\GroupFolders\Mount\MountProvider->getMountsForUser(OC\User\User {}, OC\Files\Storage\StorageFactory {})
 6. /var/www/html/lib/private/Files/Filesystem.php line 447
    OC\Files\Config\MountProviderCollection->addMountForUser(OC\User\User {}, OC\Files\Mount\Manager {})
 7. /var/www/html/lib/private/Files/Filesystem.php line 376
    OC\Files\Filesystem::initMountPoints("admin")
 8. /var/www/html/lib/private/legacy/util.php line 308
    OC\Files\Filesystem::init("admin", "/admin/files")
 9. /var/www/html/lib/private/Files/Utils/Scanner.php line 106
    OC_Util::setupFS("admin")
10. /var/www/html/lib/private/Files/Utils/Scanner.php line 142
    OC\Files\Utils\Scanner->getMounts("")
11. /var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php line 88
    OC\Files\Utils\Scanner->backgroundScan("")
12. /var/www/html/apps/files/lib/BackgroundJob/ScanFiles.php line 112
    OCA\Files\BackgroundJob\ScanFiles->runScanner(OC\User\User {})
13. /var/www/html/lib/private/BackgroundJob/Job.php line 61
    OCA\Files\BackgroundJob\ScanFiles->run(null)
14. /var/www/html/lib/private/BackgroundJob/TimedJob.php line 55
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
15. /var/www/html/cron.php line 123
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-05-24T23:04:16+02:00

**Comment by n15c** [comment]
Still having the same problem with NC 18.0.4 and Groupfolders 6.0.6.
Tried three installations, always the same problem.
[Pastebin of Exception trace](https://pastebin.com/06UPHz8t)

Having the same problem when using `occ groupfolders:scan` and when starting the cronjob.

**Comment by fschrempf** [comment]
Can anyone please check if this issue still exists in recent stable releases of NC and groupfolders app? Thanks!

**Comment by fschrempf** [comment]
I'm closing this as stale. There is missing feedback and I can't reproduce this on my side.
