### ISSUE TITLE
Solved (GF 4.0.2): GF 4.0.1: Can't open documents within groupfolder with onlyoffice (since update 4.0.0->4.0.1)

### ISSUE THREAD

**Issue by jpbraun** [nextcloud/groupfolders#443]
NC 16: I can't open OnlyOffice documents in groupfolders. I had no problems with GF 4.0.0

**Comment by tikoflano** [comment]
I'm having the same problem with uploaded documents. I can open the ones created directly from NC though.

The error log shows:

> Error: Call to a member function getUID() on null

**Comment by jpbraun** [comment]
This is a serious problem for us. When will it be fixed?

**Comment by jpbraun** [comment]
Thank you for fixing the problem.

**Comment by thecube13** [comment]
Can't open documents within groupfolder with Read Only wrights. GF 4.0.2 ((
In out.log:
Error: Error response: statusCode:404 ;body:
{"message":"Files not found"}

**Comment by psyk3d** [comment]
is it wierd that I am experiencing the same issue on 5.0.4?

**Comment by pierreozoux** [comment]
can't reproduce so I'll close it.

feel free to reopen
