### ISSUE TITLE
v16.0.1  internal server error when downloading a share files from a link

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/groupfolders#444]
Hello.

Since update 16.0.1, i get an internal server error when downloading a share files from a link.

full story at https://help.nextcloud.com/t/v16-0-1-share-link-downloads-internal-serveur-error/53790

fixed when groupfolder is disabled

**Comment by stratege1401** [comment]
i start over, using both GUI and OCC ....

Every times the groupfolders (4.0.1) is enable i get error when trying to download any type of files from a share link.

see https://help.nextcloud.com/uploads/default/optimized/2X/e/e119c3c73c3105f42176f94e954c8fed730c8de7_2_1035x549.png

**Comment by cobiam** [comment]
We are the university of quindio, colombia and we used strongly nextcloud for 1 year, there are currently many group folders constantly used in the production environment and there are also many public links that are required to work, but as long as this incompatibility continues we are having serious problems and in some way it begins to compromise the stability of the service. I urge you to solve this problem as soon as possible or provide us with a temporary but effective solution, because as administrator I can not disable groupfolders, but it is also required to work well as before, public links. Thank you very much for your collaboration and support.

**Comment by 4001982248998** [comment]
Also happens here, just after upgrading from 16.0.0 to 16.0.1.

Log entry:

```
{
  "reqId":"VQWx2tbrx79r3zMW3R0N",
  "level":3,
  "time":"2019-05-24T09:44:42+00:00",
  "remoteAddr":"217.76.110.53",
  "user":"--",
  "app":"index",
  "method":"GET",
  "url":"\/index.php\/s\/gaEmkFaBimSjadj\/download",
  "message":{
    "Exception":"Error",
    "Message":"Call to a member function getUID() on null",
    "Code":0,
    "Trace":[
      {
        "file":"\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php",
        "line":126,
        "function":"getCurrentUID",
        "class":"OCA\\GroupFolders\\Mount\\MountProvider",
        "type":"->",
        "args":[

        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php",
        "line":90,
        "function":"getMount",
        "class":"OCA\\GroupFolders\\Mount\\MountProvider",
        "type":"->",
        "args":[
          3,
          "\/37B60CC4-911B-42E7-A331-1AE2D9F61E84\/files\/Group Share 02",
          31,
          -3,
          {
            "__class__":"OC\\Files\\Cache\\CacheEntry"
          },
          {
            "__class__":"OC\\Files\\Storage\\StorageFactory"
          },
          true,
          {
            "__class__":"OC\\User\\User"
          }
        ]
      },
      {
        "function":"OCA\\GroupFolders\\Mount\\{closure}",
        "class":"OCA\\GroupFolders\\Mount\\MountProvider",
        "type":"->",
        "args":[
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php",
        "line":88,
        "function":"array_map",
        "args":[
          {
            "__class__":"Closure"
          },
          [
            "*** sensitive parameter replaced ***",
            {
              "folder_id":2,
              "mount_point":"Group Share 01",
              "permissions":31,
              "quota":-3,
              "acl":true,
              "rootCacheEntry":{
                "__class__":"OC\\Files\\Cache\\CacheEntry"
              }
            }
          ]
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Config\/MountProviderCollection.php",
        "line":103,
        "function":"getMountsForUser",
        "class":"OCA\\GroupFolders\\Mount\\MountProvider",
        "type":"->",
        "args":[
          {
            "__class__":"OC\\User\\User"
          },
          {
            "__class__":"OC\\Files\\Storage\\StorageFactory"
          }
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php",
        "line":447,
        "function":"addMountForUser",
        "class":"OC\\Files\\Config\\MountProviderCollection",
        "type":"->",
        "args":[
          {
            "__class__":"OC\\User\\User"
          },
          {
            "__class__":"OC\\Files\\Mount\\Manager"
          }
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php",
        "line":376,
        "function":"initMountPoints",
        "class":"OC\\Files\\Filesystem",
        "type":"::",
        "args":[
          "37B60CC4-911B-42E7-A331-1AE2D9F61E84"
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/util.php",
        "line":308,
        "function":"init",
        "class":"OC\\Files\\Filesystem",
        "type":"::",
        "args":[
          "37B60CC4-911B-42E7-A331-1AE2D9F61E84",
          "\/37B60CC4-911B-42E7-A331-1AE2D9F61E84\/files"
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/apps\/files_sharing\/lib\/Controller\/ShareController.php",
        "line":570,
        "function":"setupFS",
        "class":"OC_Util",
        "type":"::",
        "args":[
          "37B60CC4-911B-42E7-A331-1AE2D9F61E84"
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
        "line":166,
        "function":"downloadShare",
        "class":"OCA\\Files_Sharing\\Controller\\ShareController",
        "type":"->",
        "args":[
          "gaEmkFaBimSjadj",
          null,
          "",
          ""
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php",
        "line":99,
        "function":"executeController",
        "class":"OC\\AppFramework\\Http\\Dispatcher",
        "type":"->",
        "args":[
          {
            "__class__":"OCA\\Files_Sharing\\Controller\\ShareController"
          },
          "downloadShare"
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php",
        "line":126,
        "function":"dispatch",
        "class":"OC\\AppFramework\\Http\\Dispatcher",
        "type":"->",
        "args":[
          {
            "__class__":"OCA\\Files_Sharing\\Controller\\ShareController"
          },
          "downloadShare"
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php",
        "line":47,
        "function":"main",
        "class":"OC\\AppFramework\\App",
        "type":"::",
        "args":[
          "OCA\\Files_Sharing\\Controller\\ShareController",
          "downloadShare",
          {
            "__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "token":"gaEmkFaBimSjadj",
            "_route":"files_sharing.sharecontroller.downloadShare"
          }
        ]
      },
      {
        "function":"__invoke",
        "class":"OC\\AppFramework\\Routing\\RouteActionHandler",
        "type":"->",
        "args":[
          {
            "token":"gaEmkFaBimSjadj",
            "_route":"files_sharing.sharecontroller.downloadShare"
          }
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php",
        "line":297,
        "function":"call_user_func",
        "args":[
          {
            "__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"
          },
          {
            "token":"gaEmkFaBimSjadj",
            "_route":"files_sharing.sharecontroller.downloadShare"
          }
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/lib\/base.php",
        "line":975,
        "function":"match",
        "class":"OC\\Route\\Router",
        "type":"->",
        "args":[
          "\/s\/gaEmkFaBimSjadj\/download"
        ]
      },
      {
        "file":"\/var\/www\/nextcloud\/index.php",
        "line":42,
        "function":"handleRequest",
        "class":"OC",
        "type":"::",
        "args":[

        ]
      }
    ],
    "File":"\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php",
    "Line":113,
    "CustomMessage":"--"
  },
  "userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0",
  "version":"16.0.1.1"
}
```

**Comment by stratege1401** [comment]
not sure, but seem to impact circles too ... 

groupfolders is an absolute must have !!!

I wish i could help but i am no dev ( my skill are mostly for hardware components and welding ...

**Comment by xf-** [comment]
@cobiam  & @sagorika1996 maybe help to solve this instead of complaining about the issue. This is not helpful. You need 3 lines to fix this issue.....

**Comment by cobiam** [comment]
Good morning, you are absolutely right @xf- , I must be proactive, but I have been reviewing these solutions and they have not worked.
https://github.com/nextcloud/server/issues/14962
https://github.com/nextcloud/server/issues/14986

If you can help us with the 3 lines that you tell us, we could get out of so much trouble in our jobs. I have fully trusted the Nextcloud community and its product, and now it is the official information repository of this university and it is 24k users.
I also ask you to understand me a little, having users complaining about this problem every day.
Thank you very much for the collaboration and understanding. I hope with all your heart you can share the 3 lines and their location to put them as soon as possible.

**Comment by xf-** [comment]
@cobiam i was a little bit annoyed because in recent month more and more people complain about good working open source projects making one mistake. This is a small addon and has nothing to do with 24k users. The developer trys to cover a lot of stuff in tests, but maybe the test didn't match the case and also his setup is different.
If you look at the [contributions only 1-2 develops and 2 bots](https://github.com/nextcloud/groupfolders/graphs/contributors) active in past year and rolling out a small add-on without a staging environment isn't a good idea. Wait a few days or even 1-2 weeks for a small addon to update and check the issue tracker before (maybe check the changelog on first date for keywords like security release).
Also this is an issue and should contain helpful information's for the developer (maybe unable to recreate the issue without background).  Relevant information are PHP Version, Database, Webserver... (Take a look at the [server issue tempalte](https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md)) and ofcourse logs IN the issue. @4001982248998 was first user providing a backtrace (can be found in Admin log area)

Take a look at the error. It is a a really simple error:
* A function is called on null. That often means the function before returned null and no object and a check is missing.
* Check where the function is called -> Line 126
```php
                if ($acl && $user) {
                        $inShare = $this->getCurrentUID() === null || $this->getCurrentUID() !== $user->getUID();
```
* **It can be `null`** or looks like a $user can be set and is compared with some user userID/userID
* Looks like in the [Code](https://github.com/nextcloud/groupfolders/blob/master/lib/Mount/MountProvider.php#L102-L114) returns no `null` and `getUser` returns it and calls `getUid` afterwards. Fix it with a simple condition.

(No warranty about that conclusion and  way to fix it)

**Comment by cobiam** [comment]
Good evening, first i want thanks to all people that help us every day.
Specially to @xf- for your help and patience.
I modify this from ../nextcloud/apps/groupfolders/lib/Mount/MountProvider.php
 $inShare = $this->getCurrentUID() === null || $this->getCurrentUID() !== $user->getUID();
I change simply from this getCurrentUID() === null  to this getCurrentUID() !== null 
And the public links its works again.
Good Night.

**Comment by stratege1401** [comment]
I still have troubles; sorry.


EDIT: i did modify getCurrentUID() === null to this getCurrentUID() !== null 
my step: 
- modify file ../nextcloud/apps/groupfolders/lib/Mount/MountProvider.php

- occ app:enable groupefolders

- even did an apache2 restart

Still getting error code when trying to download

Feel free to test the link https://nextcloud.rkn.ovh/index.php/s/test_dwnld

**Comment by xf-** [comment]
I also crated a pull request with the fix and the Maintainer committed a fix.

**Comment by stratege1401** [comment]
> 
> 
> I also crated a pull request with the fix and the Maintainer committed a fix.

did you check my link ?

**Comment by cobiam** [comment]
Good morning, again thanks you @xf- for your help. @stratege1401 he was publish the complete fix about public links. You must update the groupfolders app. Hurry XD.
In my university they are very happy.

**Comment by stratege1401** [comment]
THANKS TO ALL INVOLVED, updated to 4.0.2 and bug is fixed. 
https://nextcloud.rkn.ovh/index.php/s/test_dwnld updated for thnaks and testing purposes.

I close 444
