### ISSUE TITLE
Cannot configure quota on group folder

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/groupfolders#45]
Aside of the defaults in dropdown I'd like to configure 25GB as limit. Whenever I enter a value via other and leave the focus of the input field it get simply lost.

Aside of this configuration issue I have uploaded around 9GB and it shows me 1.1GB used. Something is really wrong here and can fill my disk and may cause a serious outage.

**Comment by icewind1991** [comment]
> Whenever I enter a value via other and leave the focus of the input field it get simply lost.

You need to press enter to confirm a custom quota value, leaving the input reverts the change
