### ISSUE TITLE
very high cpu Nextcloud 16.0.1

### ISSUE THREAD

**Issue by finalls** [nextcloud/groupfolders#456]
Server:
Nextcloud: 16.0.1
Database: postgresl 10
PHP: 7.2
groupfolders: 4.0.2

If you turn on the application. And several times in a row to update the main page.

Result.
High CPU load.
top process potgresql SELECT.

SELECT "f".* FROM "oc_filecache" "f" WHERE ("f"."storage" IN ($1, $2, $3, $4, $5, $6, $7, $8, $9)) AND (("f"."mimetype" <> $10) OR ("f"."size" = 0)) AND ("f"."path" NOT LIKE $11) AND ("f"."path" NOT LIKE $12) ORDER BY "f"."mtime" DESC LIMIT 500 OFFSET 1163000)

If you turn off groupfolders.
Result: OK

**Comment by pierreozoux** [comment]
is it still the case?

**Comment by fschrempf** [comment]
I'm closing this as stale. Please open a new issue if this problem persists. Thanks!
