### ISSUE TITLE
How sync with clients when save files directly to a groupfolder

### ISSUE THREAD

**Issue by gmartinr** [nextcloud/groupfolders#46]
I've write a script for download some info from a FTP to a groupfolder path. But can't find a way to synchronize with clients.

"sudo -u www-data php occ files:scan --all" is a solition but takes long time and according to manual "sudo -u www-data php occ files:scan --path=my_groupfolder_path" is not valid.

**Comment by icewind1991** [comment]
> occ files:scan --path=my_groupfolder_path

Should be `occ files:scan --path=/user/files/my_groupfolder_path`

Any user that has access to the folder should be fine, with changes being applied to all users.

Other than the `files:scan` workaround, this use case is not supported as it's a limitation of Nextcloud itself.
