### ISSUE TITLE
Add groupfolders:scan --all option

### ISSUE THREAD

**Issue by Madic-** [nextcloud/groupfolders#465]
Please add the option to rescan all group folders, like with files:scan --all.
At the moment when modifing the content in multiple folders we need to scan each folder separately.

**Comment by CptDayDreamer** [comment]
Any updates on this? I can't believe that it is so hard to add this option... correct me if I'm wrong.

**Comment by pierreozoux** [comment]
> I can't believe that it is so hard to add this option...

you are welcome to PR ;) (I'm not a dev, so I can't comment if it is hard or not ;) I guess it is not that hard, hence it is a good first issue!)

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/groupfolders/pull/2214
