### ISSUE TITLE
ACL not visible in Chrome browser (since groupfolders 4.0.2)

### ISSUE THREAD

**Issue by HewittJC** [nextcloud/groupfolders#466]
After updating to NC 16.0.1 and GroupFolders 4.0.2 I am no longer able to see the advanced permission rule button in the Google Chrome browser. However when I open the same page in Safari I am able to see it again.

---

In Chrome:

![image](https://user-images.githubusercontent.com/28607855/58726736-82981b00-83b0-11e9-9058-db29f24917c7.png)

---

In Safari:

![image](https://user-images.githubusercontent.com/28607855/58726788-9fcce980-83b0-11e9-9009-8a2b516ed0c5.png)

**Comment by gtchm** [comment]
I can confirm that I have the same exact issue.

**Comment by juliushaertl** [comment]
Repoened #894 and closing this one as a duplicate
