### ISSUE TITLE
HOWTO: Migrate a production shared folder to groupfolder

### ISSUE THREAD

**Issue by jlord87** [nextcloud/groupfolders#468]
Hello everybody,

I've been using nextcloud (and owncloud before the fork) since many years. Before this awesome app (groupfolder) I was used to create a "corporate account" that shared folders to groups and users.

> 
> my setup:
> Ubuntu 18.,04 server, latest stable nextcloud (15.0.8) waiting for the 16.0.2 to upgrade
> my clients are using owncloud/nextcloud client and are mainly on windows 10/7.

Now I would like to migrate this "standard shares" to group folders without moving files and forcing users to syncronize again gigabytes of datas.

What is the best way to do this? Do you have any suggestion?
BTW, I'm in production environment, I cannot loose anything, and I would like to reduce any kind of complication to the endusers.

Thank you for any hint

**Comment by mklemme1** [comment]
Hallo

I would appreciate a solution for this problem as well.

**Comment by fschrempf** [comment]
There is a duplicate request in #612 including a possible workaround. I will close this in favor of #612.
