### ISSUE TITLE
Problems with files automated tagging and group folders (with subfolders)

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/groupfolders#469]
There where a few issues that no automated tagging is possible inside group folders. All of these where closed with a hint that this should work by now.

**This works:**
1. Create a group folder, e.g. "Documents".
2. Add an automated tagging option:  Assign tag "document" when file system tag is "folder documents".
3. Add the tag "folder documents" to the group folder "Documents".
4. Create a file in the group folder "Documents"

Result: The tag "document" is assigned to the new file.

**With subfolders, it doesn't work**
1. Create a group folder, e.g. "Documents".
2. Create a **subfolder** in group folder "Documents", e.g. "Invoices".
3. Add an automated tagging option to the subfolder **Invoices**:  Assign tag "invoice" when file system tag is "folder invoices".
4. Add the tag "folder invoices" to the subfolder "Invoices".
5. Create a file in the subfolder "Invoices"

Result: The tag "invoice" is **not** assigned to the new file.

**Server config**
- NC 16
- MariaDB
- nginx

**Logs**
There are no logs generated.

**Comment by maghog** [comment]
Same issue

**Comment by FelixLutze** [comment]
Same issue

**Comment by wiswedel** [comment]
can't reproduce the issue with

- Server 16.0.5 / Group Folders 4.1.3
- Server 17.0.0 / Group Folders 5.0.3

Can you please re-check with one of the above versions?

**Comment by DecaTec** [comment]
Yes, I'm on NC 16.0.5 and Group Folders 4.1.3 and the problem seems to be solved.
@FelixLutze What versions are you using?

**Comment by emilianocapasso** [comment]
Same Issue here, 16.0.1 Group Folders: 4.1.4

**Comment by FelixLutze** [comment]
I am using the latest stable version of Nextcloud and all installed apps.
It works for me if I exclude all folders specifically.

I've done that by adding the following rule to File access control:
MIME type is not httpd/unix-directory

**Comment by n15c** [comment]
With the new type of automated tagging (using a workflow) you don't have the possibility to use a file system tag anymore.

I solved it using a regex of the request URL. If the regex ist matching, it will tag all the files inside, even in the subfolders. Be aware that the request URL is not the same as the view URL.

For example this is the URL: `https://<HOSTNAME>/remote.php/webdav/Technik/vminst.log`
And this the used REGEX: `/(?:.*)\/webdav\/Technik\/(?:.*)/ `

But be aware with this kind of tagging. If another user who is not in the groupfolder group creates a folder with the same name, it will tag it too.

**Comment by pierreozoux** [comment]
looks like it is fixed, feel free to reopen.
