### ISSUE TITLE
Allow to move a groupfolder away from root directory

### ISSUE THREAD

**Issue by hanzei** [nextcloud/groupfolders#47]
It doesn't seem possible to move a groupfolder out of the root directory. It would help users if this would be possible.

**Comment by putt1ck** [comment]
To clarify:

you want users to move group folders to appear other than in their "home" folder? So that the user controls where the group folder appears?

**Comment by Hanzei** [comment]
@putt1ck Yes, exactly that

**Comment by putt1ck** [comment]
Would that not make it hard to tell people how to find the content of a group folder i.e. if each user has the group folder in a different location?

Presumably this is to allow the end user to not be see group folders in the "wrong" place within their own (carefully constructed!) set of folders - at which point maybe a solution that fits both needs would be for the group folders to have a universal parent folder in the left menu?

**Comment by Hanzei** [comment]
> Would that not make it hard to tell people how to find the content of a group folder i.e. if each user has the group folder in a different location?

I don't think this would be a problem because a group folder is placed by default in the root directory. So moving it away from the default location requires user action.

> at which point maybe a solution that fits both needs would be for the group folders to have a universal parent folder in the left menu?
This would be a great feature but for me it doesn't solve the problem because it does not work on not-web based devices like the mobile app or the deskttop app.

**Comment by Floflobel** [comment]
This is an important feature request, because in nextcloud, a shared folder can be moved.
I have a large number of shared folders and this allows our users to sort them in their own way.

**Comment by appoli13** [comment]
Also interested in this feature. 
I’m setting up an environment for a small business that and would like to nest the group folders (put some within others) so they can match the org structure. 

The intended purpose is for the structure to be replicated for all users who can edit and/or see what’s contained in them. The way the org is structured they only have 1 area that isn’t visible to everyone. All the other areas/folders can be seen by everyone, but only edited by those with the permission to do so (to enhance productivity/collaboration - allows others to see what’s going on/progress that has been made. This would be all under a folder that would contain all other folders/documents & unless it’s a group folder can be edited by anyone. In addition there would also be a group folder inside that can only be seen by execs/admins). 

There might be a better way to do structure this using groups, sharing (and the permissioning that goes with sharing) & using circles, but the documentation on circles is essential nonexistent so until we learn more about it, this is how think it would be structured.

**Comment by Pit-Storm** [comment]
Is there a possability to have a overview what needs to be done for having this feature? It would be rly nice for usability.
Could the easiest way be to place a symlink inside the user directory which he/she can move around like he/she wants. So it will point every time to the write place in absolute path.

Where to start with implementing this?

**Comment by langfingaz** [comment]
For those interested: In #87 I explained a solution how an admin (who creates the groupfolders) can change their path to some subfolder (so they're not all in the hom dirs of the users). Even if this still doesn't mean that the users can move shared groupfolders individually, it is a step towards better organization ;)

**Comment by fschrempf** [comment]
So there are three different, but related topics here:

1. The possibility to set custom storage locations for groupfolders: see #87 
2. The possibility to have groupfolders within an other groupfolder to create a hierarchy for all users: e. g. see https://github.com/nextcloud/groupfolders/issues/87#issuecomment-535452689 and #1372
3. The possibility to let the user decide where the groupfolder appears in his own folder hierarchy.

This issue seems to be mainly about point 3, but I'm not sure if this is really something we want or how this would even look like. Can you please check if the possibilities of putting groupfolders within other groupfolders (point 2) can be used to solve/improve your use case?

**Comment by putt1ck** [comment]
It's about the visual clutter that results for people in an organisation with access to a lot of group folders. The neatest/simplest solution would be to have group folders under "group folders" in the left side bar; otherwise the root view of the file system for some users is too noisy but is outside their control to tidy. By moving group folders under a group folder root you both make that view tidier while keeping the location consistent and therefore relatable across users; "oh, that form, you'll find it in the "Health and Safety" group folder" is both meaningful (it's a common and easily found location) and removes noise.

Group folders as sub folders of other group folders does create a common hierarchy for all users that can see those group folders, but makes for inconsistent security models; I haven't thought of a scenario using it that's not better solved with advanced permissions.

**Comment by fschrempf** [comment]
> It's about the visual clutter that results for people in an organisation with access to a lot of group folders. The neatest/simplest solution would be to have group folders under "group folders" in the left side bar; otherwise the root view of the file system for some users is too noisy but is outside their control to tidy. By moving group folders under a group folder root you both make that view tidier while keeping the location consistent and therefore relatable across users; "oh, that form, you'll find it in the "Health and Safety" group folder" is both meaningful (it's a common and easily found location) and removes noise.

Ok, so this is purely about web UI improvements.

But I think we couldn't show the groupfolders *only* in a separate space in the sidebar and remove them from the default root view, as there are other users that expect this to stay as it is and to find all groupfolders in their root view.

Maybe it would be possible to create a new "groupfolders" view in the sidebar and add an option for users to hide groupfolders from the root view if desired.

> Group folders as sub folders of other group folders does create a common hierarchy for all users that can see those group folders, but makes for inconsistent security models; I haven't thought of a scenario using it that's not better solved with advanced permissions.

I guess you are right. Whenever one needs to have a hierarchy it is probably better to use ACL and don't put groupfolders within others.

**Comment by p-sims** [comment]
> So there are three different, but related topics here:
> 
> The possibility to set custom storage locations for groupfolders: see #87 <https://github.com/nextcloud/groupfolders/issues/87>
> The possibility to have groupfolders within an other groupfolder to create a hierarchy for all users: e. g. see #87 (comment) <https://github.com/nextcloud/groupfolders/issues/87#issuecomment-535452689> and #1372 <https://github.com/nextcloud/groupfolders/issues/1372>
> The possibility to let the user decide where the groupfolder appears in his own folder hierarchy.

In response to the list of possible issues (quoted above), I would say that the 3rd is the most significant, certainly the my helpful in terms of my use case. Whilst there might be advantages of a filter view that just shows groupfolders in the web UI, this is not a complete solution as it doesn’t change anything for those who solely or primarily use nextcloud via clients.

Whilst I agree that being able to nest groupfolders would complicate access permissions, being able to move groupfolders into ordinary folders (i.e. folders not shared with anyone) within each users file tree would not create this problem. It would also allow a way of users resolving the clutter of their root directory that would apply across all platforms, clients and the web UI. 

There are many case when group folders are being used for project work when you might want to ‘achieve' a groupfolder within you folder structure (i.e. move a groupfolder into a normal folder call ‘achieve’), or put groupfolders in folders for each year. Sometimes for organisation related folders (particularly in the case of contractors) you might want to put the project or organisation shared folder in a folder with files relating to that project, that you don’t want to share with others (e.g. contracts, timesheets, your personal notes on the project).

Coming back to point 2 in the list — I haven’t encountered much need to nest group folders, but I can see why it would be useful to be be able to share certain files or folders within a groupfolder with specific extra individuals which aren’t part of the group, or via a link with anyone.

I think the most important thing with groupfolders is to ensure documentation is clear what you can and can’t do with groupfolders (e.g. you can move them into folders, but not into share folders), and that any error message are clear and explanatory. If someone tries to move a group folder using web UI or on their computer, the client or web interface needs to provide a helpful error message. I believe currently if you try and move a groupfolder out of the root on a computer synced to nextcloud, the folder moves and then nextcloud just doesn’t sync properly without telling you why (or at least this was the case with v2.6 of mac client). Just getting the client to stop syncing entirely with error “you can’t move groupfolder “XXXXX” out of the nextcloud root directory” would be so helpful. In all case nextcloud should either seamlessly do what ever you ask, or it should clearly tell you it’s not possible to do X or Y. 

Peter

**Comment by fschrempf** [comment]
> I think the most important thing with groupfolders is to ensure documentation is clear what you can and can’t do with groupfolders (e.g. you can move them into folders, but not into share folders), and that any error message are clear and explanatory. If someone tries to move a group folder using web UI or on their computer, the client or web interface needs to provide a helpful error message. I believe currently if you try and move a groupfolder out of the root on a computer synced to nextcloud, the folder moves and then nextcloud just doesn’t sync properly without telling you why (or at least this was the case with v2.6 of mac client). Just getting the client to stop syncing entirely with error “you can’t move groupfolder “XXXXX” out of the nextcloud root directory” would be so helpful. In all case nextcloud should either seamlessly do what ever you ask, or it should clearly tell you it’s not possible to do X or Y.

I agree with this part and I just tried to move a groupfolder into a normal directory and with the desktop client for Linux (v3.1.3) I got a message from the client that the folder can't be moved and it reverted the move and instead kept a copy of the groupfolder in the new destination. So it seems like the client handles this properly.

**Comment by fschrempf** [comment]
> Maybe it would be possible to create a new "groupfolders" view in the sidebar and add an option for users to hide groupfolders from the root view if desired.

I just found that this request already exists in #139. If nobody has any objections I would suggest to handle this specific feature over there and close this request
