### ISSUE TITLE
Group folder contents cannot be accessed - encrypted?

### ISSUE THREAD

**Issue by myllymik** [nextcloud/groupfolders#49]
Hi,

Somehow I have ended up in situation where any data in group folders cannot be accessed no more. Trying to open file with the web-ui ends up in internal server error. Logs have messages such as:

Error | PHP | fclose() expects parameter 1 to be resource, string given at /opt/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#750 | 2017-08-03T10:54:42+0300
-- | -- | -- | --
Error | PHP | fclose() expects parameter 1 to be resource, string given at /opt/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#749 | 2017-08-03T10:54:42+0300
Error | PHP | stream_wrapper_register(): Protocol ocencryption:// is already defined. at /opt/nextcloud/lib/private/Files/Stream/Encryption.php#196 | 2017-08-03T10:54:42+0300
Error | PHP | fclose() expects parameter 1 to be resource, string given at /opt/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php#750 | 2017-08-03T10:54:42+0300

While trying to access the files within I can see the contents (listing works in web-ui as well): 

# ls __groupfolders/1/
IT-tiimin jaettu kansio.txt  Tunnuksia.ods

but:

# cat __groupfolders/1/IT-tiimin\ jaettu\ kansio.txt
HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:HEND---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------.....

..which would suggest that somehow it's encrypted while I think group folders should not be?

I have tried to run occ encryption:decrypt-all and it runs without errors but there's no effect on these files.
Is there a way to restore the files?

Br,
-Mika

**Comment by myllymik** [comment]
Some additional info:

Restoring earlier backup doesn't seem to help. The files are already encrypted. However occ encryption:status shows that encryption is disabled. I did enable it previously. Also, after restoring a backup there's a forced upgrade. 

I suppose I could use local synced copies (at least those seem still readable) of the files to re-create everything but would be nice to know what caused this and/or what I did wrong.

**Comment by myllymik** [comment]
My "workaround" was to re-install from scratch and restore group folder contents from local copies. For now I have left encryption disabled, at least until it's somehow confirmed that it is safe and this will not happen again. It's not much of a workaround but after a while of banging by head into the wall I could not find any other solution or the reason that caused the problem originally.

**Comment by icewind1991** [comment]
Using groupfolders with encryption is not supported.

The upcoming groupfolders release that will come with NC15 will properly disable encryption for group folders.
