### ISSUE TITLE
Problems displaying folder icons in shared group folders

### ISSUE THREAD

**Issue by thecube13** [nextcloud/groupfolders#490]
In the subfolders of the shared groups folder, the URL shows the icons of unknown files instead of the folder icons.

NC  version: 16.0.1.1
Group Folders app version: 4.0.3
Ubuntu 18.04
Expected:
![icon-groupfolders-folder-group](https://user-images.githubusercontent.com/47567205/60269069-6f686480-98f6-11e9-86ae-8cdc859a723c.png)
Shown:
![icon-core-filetypes_file](https://user-images.githubusercontent.com/47567205/60269186-a50d4d80-98f6-11e9-8f73-99474ef1ab91.png)

**Comment by icewind1991** [comment]
is there anything in the browser's console log that might be relevant?

**Comment by thecube13** [comment]
in the browser's console is nothing unusual.

HTML code: 

background image in nextcloud's main window:
`<div class="thumbnail" style="background-image:url(/apps/theming/img/groupfolders/folder-group.svg?v=87);">`

After opening from a shared link:
`<div class="thumbnail" style="background-image:url(/apps/theming/img/core/filetypes/file.svg?v=87);">`

**Comment by jtagcat** [comment]
Happens only with link shares of only group folders

**Comment by parafin** [comment]
#801 and #809 seem to be a duplicates.

This is quite old and annoying oversight. Are there any plans on fixing it?..

**Comment by pierreozoux** [comment]
Looks like resolved by #1235 

Feel free to reopen if not the case
