### ISSUE TITLE
Fresh install has incorrect OCS endpoints

### ISSUE THREAD

**Issue by whittacre** [nextcloud/groupfolders#499]
I've just recently update my server to NextCloud 16.0.1 along with installing GroupFolders to try and test some integration.
when I try and make a test call
`curl -u $USER:$PASS -X GET -H "OCS-APIRequest: true" \
"$SERVER/nextcloud/ocs/v1.php/apps/groupfolders/folders" `
it responds saying that it doesn't recognize the query
`<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>998</statuscode>
  <message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.
</message>
 </meta>
 <data/>
</ocs>`

I did a bit of digging into which routes are being registered and it seems that a prefix is being incorrectly applied to the requested route.
requested routes: "/ocs/apps/groupfolders/folders", "/ocsapp/apps/groupfolders/folders"
known route: "/apps/groupfolders/folders"

As a workaround, I found that changing line 2 of apps/groupfolders/appinfo/routes.php to `return ['ocs' => [` will get it working.

**Comment by icewind1991** [comment]
`https://example.com/apps/groupfolders/folders` is the correct url for the groupfolders api
