### ISSUE TITLE
Versioning support

### ISSUE THREAD

**Issue by kosli** [nextcloud/groupfolders#50]
Versioning, Trash and Activity Support in GroupFolders would be great.

**Comment by putt1ck** [comment]
+1

**Comment by tr-ageev** [comment]
After update from 12.0.0 to 12.0.2 versioning seems start working. But from what i see it's not a problem of GroupFolders app themselfs, but global problem to detect real path to shared files or files in group folders.

**Comment by hieronymousch** [comment]
+1

**Comment by C0rn3j** [comment]
Not having any activity makes this app pointless for our usage, what if someone goes rogue and starts deleting files? We won't have any easy way to track who.

Currently worked around this by creating a folder under an admin acc, gave the acc unlimited quota and shared it with an LDAP group.  

That way I get exactly what I wanted to achieve with this app.

**Comment by putt1ck** [comment]
Activity does seem to be supported (NC12.03, Group Folders 1.1) in the same way as a normal folder.

**Comment by C0rn3j** [comment]
Am on NC12.03 with GF1.1 - I may be completely misunderstanding how activity works, but this is how I see a file created by a user in the GF under an admin account.

https://i.imgur.com/No4D9Bg.png

VS regular shared folder with a group 

https://i.imgur.com/Cw2Xoiz.png - this is how I imagine the GF activity log should look like, but it doesn't

**Comment by putt1ck** [comment]
Ok, see your point. That looks like a permissions-related error - the activity is being recorded (you can see it as the file creator) but not being displayed. But should be posted as a new bug, as versioning as such is working whereas before it didn't work at all.

**Comment by putt1ck** [comment]
Activity visibility to other users now opened as an issue at https://github.com/nextcloud/groupfolders/issues/70 (thanks @C0rn3j )

**Comment by fiforms** [comment]
Is there any progress on this? I'm running 12.0.5. Versioning works, but I really would like to see Trash support in group folders.

**Comment by putt1ck** [comment]
Check carefully, you might find versioning only works for the user who created the version. I think we're waiting for https://github.com/nextcloud/activity/pull/190 for it to work for any user with access to the group folder.

**Comment by DJCrashdummy** [comment]
additional all versions seem to be vanished if the admin renames the groupfolder!

they are still on the server located at the users `files_versions` within the old name of the groupfolder... and after also renaming this folder manually or reverting the groupfolders name to the old one, the versions appear again in NC.

**Comment by guyinpv** [comment]
I have to stop using group folders due to lack of trash support. There is no way to recover deleted files then once the deletion syncs to everybody. This is no good.

Since nobody "owns" the group folder, it would be wise to show the deleted files under all/any admin users. Or under the user who deleted it. Or under some kind of master admin set within the group folder creation screen itself.

Somehow or another, we need to be able to recover files from group folders, otherwise it's not usable for me.

**Comment by DJCrashdummy** [comment]
@guyinpv this issue is mainly about versioning... there is a other issue (#99 ) about trashbin support.

**Comment by ThePatzen** [comment]
+1

**Comment by IwishIcanFLighT** [comment]
Any update on that issue ? Real bummer that this is missing.

**Comment by fwolfst** [comment]
@icewind1991 Can you give an estimate whether current maintainers/devs (thanks, the app is awesome if one knows what one gets) would be able to implement versioning (and/or trash) within -say- half a year? Like an honest "trying my best, will tackle next month" or an "sorry, too much other bugs, could happen, but dont count on it"...?

I cannot actively contribute or throw resources at this unfortunately, but need to make a decision whether I can use groupfolders confident that it will fit my requirements in the middle future; or whether I need to work around it (as in old times), with system-accounts owning folders. Later approach has the risk that "hidden" (unshared) stuff is carried around, but it might be wiser and more cheap to stick with some unneeded files than to loose an important file, or version thereof.

**Comment by putt1ck** [comment]
@fwolfst we have an interest in solving the trash/versions issue, but I'm not clear whether it's an app issue or actually an upstream cause that's waiting for a patch. @MorrisJobke or @icewind1991 might have a view on that.

**Comment by fwolfst** [comment]
As far as I understood, bigger work on core is needed and scheduled for NC 15 (which would mean a fix would be available earliest 2018-12-06, see #99). I wish I had resources to speed this up.

**Comment by putt1ck** [comment]
But on the otherhand

"Nextcloud 14 introduces access to the versioning and trash features through our API" (from https://nextcloud.com/blog/nextcloud-14-rc1-announced-with-video-verification-and-signaltelegram-2fa-support-improved-collaboration-and-gdpr-compliance/ )

Could groupfolders not just use the API or does that only work for completely external applications?

**Comment by icewind1991** [comment]
That api is for accessing trashbin and versions from the client, not for apps to provide trashbin/versions

As stated above, the required core changes to make this work should land in 15

**Comment by bruno-nk** [comment]
Am I the only one who believes this is a big deal? I really couldn't believe the basic (and great) functions from Nextcloud don't work on group folders and there is no warning about it.

There's no trash, versioning nor activity. This App should not be considered stable. On it's page (https://apps.nextcloud.com/apps/groupfolders) there's a note about not supporting encryption, please consider specifying it also doesn't support the previous functions.

Fortunately we didn't lose any files but I am now moving all the group folders into normal shared folders on an admin's account (same as C0rn3j).

**Comment by Nils160988** [comment]
Versioning now works in current master with NC15 RC1, try it out!

**Comment by MorrisJobke** [comment]
> Versioning now works in current master with NC15 RC1, try it out!

@icewind1991 Is this correct? Then this ticket could be closed.

**Comment by icewind1991** [comment]
versioning and trashbin work now

**Comment by Nils160988** [comment]
Activity still seems to be not supported which is also part of this issue so I think this issue should be kept open

**Comment by DJCrashdummy** [comment]
good point @Nils160988!

are versions after renaming (described at https://github.com/nextcloud/groupfolders/issues/50#issuecomment-381033304) now supported? - if not, i even call versioning still as unsolved!

**Comment by truonart** [comment]
Hey, I am on NC 16 and the file version app(v1.9.0) works as expected when used in normal folders but when nested within group folders(v4.1.3), we start to see some issues. For example, when reverting back to a previous version for a file within a group folder, the file will duplicate in the list of available versions. This creates this a huge list of the same file. In addition, after reverting, the preview shows that the file as changed, but when opening the file it is still the same version.

**Comment by biva** [comment]
@icewind1991 do you confirm that there are still some issues regardging versioning and activity app? Thanks!
