### ISSUE TITLE
No permission to delete files in new or existing groupfolders after upgrading to Nextcloud 16.0.2

### ISSUE THREAD

**Issue by Kunibert-007** [nextcloud/groupfolders#503]
I upgraded to Nextcloud-Version 16.0.2. After this, the Groupfolder-Plugin was deactivated. After activating I see all the files but I have no permissions to create or change files:

![image](https://user-images.githubusercontent.com/35669927/60766996-5bb8bd00-a0b1-11e9-85cc-8bc44bece58b.png)

In the options all settings to modify files are correct:
![image](https://user-images.githubusercontent.com/35669927/60767002-725f1400-a0b1-11e9-81e7-aefa57e8942f.png)
Setting the checkbox for 'Extended permissions' doesn't help.

If I try to create a new Groupfolder without existing files it is the same error-result.

Fix-Permissions (via FTP on 775 or via SSH with Nextcloudpi) doesn't help.

No idea what I could do anymore.

But I still need write exchange, it's very important.

I use Groupfolder-Version 4.03.

**Comment by Kunibert-007** [comment]
UPDATE:
Creating new files and editing existing files is possible but DELETING not.

**Comment by Zakspeed** [comment]
Hi.  to me the app "groupfolder" deactivated, I activated it.  

I have un-synchronized the group folders and Next resynchronized them. 

 it seems that everything is correct now

**Comment by Kunibert-007** [comment]
> Hi. to me the app "groupfolder" deactivated, I activated it.
> 
> Raspi 3b+ (nextcloudpi)
> Preview versión: 15.0.8
> 
> "Windows - Client"
> I have un-synchronized the group folders and Next resynchronized them.
> It seems that everything is correct now.
> 
> In Web-Nextcloud seem everything is OK.

Doesn't work for me. Tested with a new sync and the error is also there. When I try to delete a file I get the message "Error 500" in sync-client.
Deleting via Webinterface is also not possible.

**Comment by fschrempf** [comment]
Is anyone still seeing this kind of problem? If not I will close this as stale issue soon.
