### ISSUE TITLE
Cannot access NC 'files' app (page) if no FS acess to folder

### ISSUE THREAD

**Issue by ratermir** [nextcloud/groupfolders#504]
I accidentaly changed rights to group folder on nextcloud filesystem (e.g. folder with number corresponding to the GroupFolder ID)  the way that "www-data" account (which the  NextCoud server runs on) didn't have access to the folder, and it resulted to situation the web application NextCloud end user (who should have had access to this folder) saw an error page, when he tried to access index page. He had completely disallowed acces to the "files" web application.

The situation were corrected when
 * I disable access to this group
 * I corrected the folder permissions to allow NC to access it

I know it should not happen in "standard" using of the NC, on the other hand the behavior in such case shoule be more safe - for example to display error message and ignore this folder. It never should to disable accss to files.

NextCloud 16.0.1 on Debian 9, BD = Mysql, GroupFolder 4.0.3

**Comment by ratermir** [comment]
I accidentaly changed right to group folder on nextcloud filesystem (e.g. folder with number corresponding to the GroupFolder ID), the way the "www-data" account (which the  NextCoud server runs on) and it resulted to situation, the user  who should have had access to this folder saw an error page, when he tried to access index page. 

he situation were corrected when
 * I disable access to this group
 * I corrected the folder permissions to allow NC to access it

I know it should not happen in "standard" using of the NC, on the other hand the behavior in such case shoule be more safe - for example to display error message and ignore this folder. It never should to disable accss to files.

NextCloud 16.0.1 on Debian 9, BD = Mysql, GroupFolder 4.0.3

**Comment by wiswedel** [comment]
Sorry, but messing with the file system strictly contrary to the documented requirements is nothing the application can be held responsible for.
I'm also sure the NC logs were quire chatty about what's wrong.

**Comment by ratermir** [comment]
hmm I know that this is my mistake, but also (as a Java developer) I know that application should (and could) be as independent on environment as possible. I suppose this treating would be quite simple. But, if this is desired behavior, then everything is OK.
