### ISSUE TITLE
Advanced permission broken by client can lead to unauthorized data deletion

### ISSUE THREAD

**Issue by jlord87** [nextcloud/groupfolders#505]
Hello,

I'm on the latest 16.0.2 in my Ubuntu 18.04 server, php 7.2 and apache2.

I can override and accidentally loose data stored in a Group Folder with advanced permissions set using the latest client (Version 2.5.2git (build 20190319) on Windows 7).

How to reproduce:
1) create a group folder named TEST and share with "admin group" and "test group", marking the advanced permission flag
2) create two folders inside the main share: visible and invisible
3) inside "invisible" folder create a test file (let's say something like "test.txt")
3) set the advanced folder permission to deny everything to "test group" for the "invisible" folder (deny read, deny write, deny share, deny create, deny delete...)
4) log in with test user (member of test group). The invisible folder is not shown, you can only see the visible one. That's great.
5) if you try to create a folder named "invisible" you get an error (that's good too)
6) sync the new external share to your pc (in my case win7 with 2.5.2 client). Only the "visible" folder is synced.
7) create a folder named invisible and create inside this new folder a new file (lets say "test2.txt").
8) the sync client will give some error but will in the end sync the folder online, deleting the original invisible folder, resetting its advanced permission, removing the "test.txt" file and replacing its content with "test2.txt".

**This is really critical.**
I'm in a production environment and I do believe that **an unauthorized user can cause massive data deletion.**

I'll be glad to test and give any further information

Cheers
Francesco

**Comment by jlord87** [comment]
Bump...

really guys, anybody reading here?
This bug is something that really, really need to be fixed ASAP, people may be loosing data...

**Comment by JulianTosh** [comment]
Closed? With no comment?

**Comment by jlord87** [comment]
Should be fixed in next maintenance releases by this https://github.com/nextcloud/groupfolders/pull/519
