### ISSUE TITLE
Permissions I set into the groups folder are not apply on page change

### ISSUE THREAD

**Issue by maxlehot1234** [nextcloud/groupfolders#506]
Hi,

I setup a group folder, but I am not able to have change save for folder permissions.

I want to allow player to view only, but when I uncheck Write/Share/Delete, it was not save...

Is that normal?

Thanks again

Nextcloud 16.0.2

**Comment by maxlehot1234** [comment]
Anything ?

**Comment by maxlehot1234** [comment]
Anyone? This prevent me to correctly apply permissiosn for shared folders :(

**Comment by gary-kim** [comment]
I don't seem to be able to replicate this. Could you give some more information please?
Thank you

**Comment by maxlehot1234** [comment]
@gary-kim Each time I reload the page, settings are not saved.

If I click anywhere in the page and change page, settings not save related to permissions.
I need to enable the advanced permissions system temporaly cause of this.

![wt6do8te3t](https://user-images.githubusercontent.com/5159244/61174596-7044fb80-a570-11e9-9e3c-0b301d3dd8cd.gif)

That's a gif ^^ and you will see that each time I reload the page, permissions are reset to everything :P

Occured on Nextcloud 16.0.2 and 16.0.3. Never test previous versions


Thanks again

**Comment by wiswedel** [comment]
@maxlehot1234 I cannot reproduce this on 16.0.3 with Groupfolders 4.0.4 installed. What version of Groupfolders do you have?

**Comment by maxlehot1234** [comment]
I just update to 4.0.4 and I have the same problem.

Permissions are reset to default, write, share, delete allow after page reload, page change.

I also disable my 3 ad-blocks and same issue.

Another computer, same issue

**Comment by wiswedel** [comment]
Can you please export your system report via the Support page in the admin settings?

**Comment by maxlehot1234** [comment]
Yeah, here it is:

Inside the zip ;)
[2019-07-18.zip](https://github.com/nextcloud/groupfolders/files/3408389/2019-07-18.zip)

**Comment by wiswedel** [comment]
> Yeah, here it is:
> 
> Inside the zip ;)
> [2019-07-18.zip](https://github.com/nextcloud/groupfolders/files/3408389/2019-07-18.zip)

Hmm. Looks ok so far.
Maybe it's the slash in the group name?

**Comment by maxlehot1234** [comment]
There is no slash in the group name,
The exact group name was this: "Notes Tornades"


The long group name was a FTP external share

**Comment by wiswedel** [comment]
> There is no slash in the group name,

The GIF shows _Amis/Famille_ as group name!?

**Comment by maxlehot1234** [comment]
Ah this, yeah :P oops.

I will change this to see

**Comment by maxlehot1234** [comment]
I confirm thats the issue :P

Thanks again. but maybe try to prevent a group with a slash to being added into GroupFolders and put a hint?

**Comment by wiswedel** [comment]
I could imagine that's generally a bad idea that could go 💥 on several occasions.
Happy it's resolved so far.

**Comment by maxlehot1234** [comment]
I forgot that linux use it as a path too, so :P

Thanks anyway
