### ISSUE TITLE
Unzip file inside group folder

### ISSUE THREAD

**Issue by Glujaz** [nextcloud/groupfolders#508]
It's as the title says. I am unable to extract zip files inside a created group folder, although I have all the rights.

It simply says "unable to open"...

![A900ABF9-A940-494C-A49D-D5315FA0FEFE](https://user-images.githubusercontent.com/44747485/60925368-c03b6e00-a2a3-11e9-9561-a2def2fcd1db.jpeg)

Any idea ?

Thanks in advance ! :)

**Comment by juliushaertl** [comment]
This is most likely an issue of the extraction app, not handling any different storage backends like groupfolders. Please open an issue at https://github.com/PaulLereverend/NextcloudExtract/

**Comment by Glujaz** [comment]
Ok. Saw someone asking for the same thing on the extractor github.

Thanks and good day.
