### ISSUE TITLE
Desktop client treats group folders as external folders

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/groupfolders#509]
I yesterday created my first group folder and found that the client only downloads it when I manually approve it because it is being recognized by the client as an external folder, which it of course is not. 

I am afraid that this way, many of my users will miss out, because they won't understand what to do. 

I don't know if this is deliberate or a limitation of Nextcloud, and if so, whether the limitation can be overcome.

**Comment by wiswedel** [comment]
Group folders can become quite large in productive environments. You might only want to sync a subset of that folder.
Therefore this (local storage) security measurement is in operation (but can of course also be activated).

![image](https://user-images.githubusercontent.com/1804221/61199730-41996300-a6df-11e9-9572-0bab1498a65a.png)


Feel free to propose a more precise string: https://github.com/nextcloud/desktop/blob/master/src/gui/accountsettings.cpp

**Comment by vasyugan** [comment]
The problem is: Group folders are not external storage. So when the user
gets a notification about an external storage having been added when really
it is a group folder, they will not know what it is about and chances are
that many if not most will decline.

Sascha Wiswedel <notifications@github.com> schrieb am Mo., 15. Juli 2019,
09:02:

**Comment by christiaan2b** [comment]
Hi, addingh to vasyugan's comment, as a new user/admin of Nextcloud I found this quite confusing after coming from Dropbox. From a user's point of view these folders are not external storage but the very core of our storage as an organisation. If users want to use selective sync to reduce storage use that's fine but we need Group folders to be synced by default, as happens with Dropbox.

**Comment by vasyugan** [comment]
> From a user's point of view these folders are not external storage but the very core of our storage as an organisation. If users want to use selective sync to reduce storage use that's fine but we need Group folders to be synced by default, as happens with Dropbox.

Indeed! And add to that that when you add a group folder and users get a notification about an "external folder"  having been added, they have no idea what is going on, they simply don't know that they have to launch the Nextcloud settings (often they don't even know where to find them), find the folders list and manually select the group folders. I have colleages who are in another country who are not great at tech, so they are almost guaranteed to miss out on the group folders, unless I give them detailed instructions on what to do. 
If you want to save storage, one solution to look at would be to look at how the owncloud client handles VFS mode, where files all appear in the directory listing but  are only synced on demand, a bit like an SMB or NTS network drive, but with more caching. What is key is that all users by default _see_ all the files.

**Comment by vasyugan** [comment]
> Group folders can become quite large in productive environments. You might only want to sync a subset of that folder.
> Therefore this (local storage) security measurement is in operation (but can of course also be activated).
> 
> ![image](https://user-images.githubusercontent.com/1804221/61199730-41996300-a6df-11e9-9572-0bab1498a65a.png)
> 
> Feel free to propose a more precise string: https://github.com/nextcloud/desktop/blob/master/src/gui/accountsettings.cpp

It is not just about wording but about making it at least dramatically easier, because knowing my users, three quarters them simply _will not_ open the Nextcloud settings. navigate to the list of folders, expand it, click the folders to by synced and then click "apply". They are too easily intimidated by anything techy than they are not going to do it, unless I take them by the hand and do it with them. Sorry, but that's how it is. Therefore what the client should do is do is to present you with a prompt saying "A group folder XXX has been added. Do you want to synchronize it to your computer?" and the prompt should allow you to click yes/no/remind me later it order to ensure a minimal chance that non-techy users will be able of handling this.

**Comment by Daksol** [comment]
Put simply, folders shared by "traditional shares" are seen by the Windows Synch client.
But folders made available by Group Folders (which is all  our folders!) are invisible.

(and Group Folders are not External Folders)

**Comment by fschrempf** [comment]
@vasyugan Would it be ok for you to close this issue and handle this request in https://github.com/nextcloud/desktop/issues/1966?

**Comment by vasyugan** [comment]
> @vasyugan Would it be ok for you to close this issue and handle this request in [nextcloud/desktop#1966](https://github.com/nextcloud/desktop/issues/1966)?

The other request seems to have zero attention from any dev, it will just linger there until it eventually gets marked as stale and closed, I fear. But, well, technically it is an issue with the client, yes.
