### ISSUE TITLE
Rename folder does not work properly

### ISSUE THREAD

**Issue by kyhuynhduc** [nextcloud/groupfolders#518]
FYI 
Step1: create group folder with name: "abcd abcd"
step2: go in side /abcd abcd
step3: create folder with name " new folder"
step4: rename " new folder " to " new folder.test"

result: folder "new folder.test" corrupted.
---
#16140
https://github.com/nextcloud/server/issues/16140
#16393
https://github.com/nextcloud/server/issues/16393

**Comment by Mululu** [comment]
The error occurs only in group folders. So the error must be in this app.

I hope for a quick fix

**Comment by Mululu** [comment]
#https://github.com/nextcloud/server/issues/16468 #

**Comment by juliushaertl** [comment]
Possible fix in https://github.com/nextcloud/groupfolders/pull/542
