### ISSUE TITLE
NotPermittedExecption Error

### ISSUE THREAD

**Issue by Bables55** [nextcloud/groupfolders#536]
I started using Group folders actively with 4.0.4.
Then an error is regularly output to the log. This is probably Cron's timing.

I can only set the three permissions "Write, Delete, Share".  I think that I had the authority of "Create" before. Is this abolished?
I can not get the path when I execute Groupfolders:permission with OCC command.
Are these errors related to this error?

### Error log
```
[core] Error: OCP\Files\NotPermittedException:  at <<closure>>

0. /MY-NEXTCLOUD/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 71
   OC\Files\Node\File->delete()
1. /MY-NEXTCLOUD/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 57
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder({id: 6,mount_poi ... e})
2. /MY-NEXTCLOUD/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
3. /MY-NEXTCLOUD/lib/private/BackgroundJob/Job.php line 61
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
4. /MY-NEXTCLOUD/lib/private/BackgroundJob/TimedJob.php line 55
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /MY-NEXTCLOUD/cron.php line 123
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

#### Server
- OS:
Linux 3.10.0-514.2.2.el7.centos.plus.x86_64 #1 SMP Wed Dec 7 19:10:15 UTC 2016 x86_64
- Webserver:
nginx/1.14.2 (fpm-fcgi)
- Database:
mysql 10.2.25
- PHP:
7.3.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, apcu, bcmath, curl, dba, dom, enchant, fileinfo, gd, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Comment by Bables55** [comment]
This is still happening and there will definitely be an error every hour.

```
[core] Error: OCP\Files\NotPermittedException:  at <<closure>>

0. /MY-NEXTCLOUD/nc/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 71
   OC\Files\Node\File->delete()
1. /MY-NEXTCLOUD/nc/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 57
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder({id: 6,mount_poi ... e})
2. /MY-NEXTCLOUD/nc/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
3. /MY-NEXTCLOUD/nc/lib/private/BackgroundJob/Job.php line 61
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
4. /MY-NEXTCLOUD/nc/lib/private/BackgroundJob/TimedJob.php line 55
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /MY-NEXTCLOUD/nc/cron.php line 124
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-10-30T09:43:04+09:00
```

---
CentOS 7.7, Nginx 1.16.1, PHP7.3.11, Groupfolder 5.0.4, Nextcloud 17.0.0

**Comment by Bables55** [comment]
This problem has not been solved in GF. Ver.5.0.5 and NC17.

**Comment by Bables55** [comment]
This problem has not been solved in GF. Ver.6.0.0 and NC18.

**Comment by SuperSandro2000** [comment]
Seeing this since recently too.
````
required for the db ready check
[core] Error: OCP\Files\NotPermittedException:  at <<closure>>

0. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 71
   OC\Files\Node\File->delete()
1. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 57
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder({id: 1,mount_poi ... e})
2. /var/www/html/custom_apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
3. /var/www/html/lib/private/BackgroundJob/Job.php line 61
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
4. /var/www/html/lib/private/BackgroundJob/TimedJob.php line 55
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/html/cron.php line 125
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-02-07T22:45:02+00:00
````

**Comment by thomasgg23** [comment]
Seeing this too with NC 19.0.1 and GroupFolders 6.0.6

[core] Error: OCP\Files\NotPermittedException:  at <<closure>>

0. /var/www/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 71
   OC\Files\Node\File->delete()
1. /var/www/html/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 57
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder({id: 16,mount_po ... e})
2. /var/www/html/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
3. /var/www/html/lib/private/BackgroundJob/Job.php line 62
   OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
4. /var/www/html/lib/private/BackgroundJob/TimedJob.php line 57
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/html/cron.php line 126
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

**Comment by thomasgg23** [comment]
#936 seems to be a duplicate

**Comment by thomasgg23** [comment]
Same here https://help.nextcloud.com/t/notpermittedexception-from-groupfolders-in-log-every-hour/62599/2

**Comment by thomasgg23** [comment]
And here https://help.nextcloud.com/t/groupfolders-app-notpermittedexception-error-doesnt-stop/63426/9

**Comment by thomasgg23** [comment]
When running the command there is the following error
```
sudo -u www-data php occ groupfolders:expire
...
...
Expiring version 1589547562 for 'XXXX'
In File.php line 138:
  [OCP\Files\NotPermittedException]
```

When changing the parameter 
`'versions_retention_obligation' => 'auto',`
to 
`'versions_retention_obligation' => 'disabled',`
in the nextcloud config.php
the error is gone, but also versioning.

https://docs.nextcloud.com/server/19/admin_manual/configuration_files/file_versioning.html?highlight=versions
