### ISSUE TITLE
Subgroupfolder upload error

### ISSUE THREAD

**Issue by yesbkz** [nextcloud/groupfolders#54]
Hi all,

I Have a issue, with following scenario:

Admin create GroupFolder A for Group A - with Write/Share permissons
User A member Group A
User B not member of Group A

User A create a Sub folder SubFolderB in GroupFolder A and Share with full permissions to User B.

User B uploads files to SubFolder B with error: Internal Server Error.

Files doesn't showing in Web Interface, but showing on file system level.

Logs files have following:

"Error\",\"Message\":\"Call to a member function getPath() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/ShareHelper.php(51):

**Comment by stjosh** [comment]
I have a very similar issue - same scenario as @yesbkz described with users A, B, groupfolder and subfolder. I can't upload files from the Windows desktop client. However, the error messages I see in the logs are smiliar, but not identical to what @yesbkz is observing (debug log enabled):

`{"reqId":"WZYA5dkaOjsAAJzpI5oAAAGl","level":3,"time":"2017-08-17T20:47:37+00:00","remoteAddr":"X","user":"czt-streaming","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/uploads\/czt-streaming\/2382954596\/.file","message":"filesize() [<a href='http:\/\/php.net\/manual\/en\/function.filesize.php'>function.filesize.php<\/a>]: stat failed for \/home\/XXX\/nextcloud-data\/__groupfolders\/8\/__groupfolders\/8\/StT\/stream.170705.0.mp3 at \/home\/XXX\/www\/YYY\/lib\/private\/Files\/Storage\/Local.php#161","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
{"reqId":"WZYA5dkaOjsAAJzpI5oAAAGl","level":3,"time":"2017-08-17T20:47:37+00:00","remoteAddr":"X","user":"czt-streaming","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/uploads\/czt-streaming\/2382954596\/.file","message":"copy(\/\/home\/XXX\/nextcloud-data\/__groupfolders\/8\/__groupfolders\/8\/StT\/stream.170705.0.mp3) [<a href='http:\/\/php.net\/manual\/en\/function.copy.php'>function.copy.php<\/a>]: failed to open stream: No such file or directory at \/home\/XXX\/www\/YYY\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
{"reqId":"WZYA5dkaOjsAAJzpI5oAAAGl","level":0,"time":"2017-08-17T20:47:37+00:00","remoteAddr":"X","user":"czt-streaming","app":"OC\\Files\\Cache\\Scanner","method":"MOVE","url":"\/remote.php\/dav\/uploads\/czt-streaming\/2382954596\/.file","message":"!!! Path 'files_versions\/Stream Dumps\/__groupfolders\/8\/StT\/stream.170705.0.mp3.v' is not accessible or present !!!","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
{"reqId":"WZYA5dkaOjsAAJzpI5oAAAGl","level":3,"time":"2017-08-17T20:47:37+00:00","remoteAddr":"X","user":"czt-streaming","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/uploads\/czt-streaming\/2382954596\/.file","message":"Undefined offset: 0 at \/home\/XXX\/www\/YYY\/lib\/private\/Share20\/Manager.php#1242","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
{"reqId":"WZYA5dkaOjsAAJzpI5oAAAGl","level":3,"time":"2017-08-17T20:47:37+00:00","remoteAddr":"84.226.172.151","user":"czt-streaming","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/uploads\/czt-streaming\/2382954596\/.file","message":"Call to a member function getPath() on null at \/home\/XXX\/www\/YYY\/lib\/private\/Share20\/Manager.php#1252","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
`

What I wonder: Why is the part `/groupfolders/8/` contained twice in some logs above?

Nextcloud Server Version: 12.0.2
Group Folders Version: 1.1.0
Windows Client Version: 2.3.2

I'll be glad to provide more info if required!

**Comment by putt1ck** [comment]
@stjosh does upload work as expected from the web UI?

**Comment by stjosh** [comment]
@putt1ck Thanks for the follow-up. Uploading over the Web-UI also does not work. Here's the two log lines this experiment yields:

```
{"reqId":"Wdu7ldkaOjsAATSzYO8AAAAB","level":3,"time":"2017-10-09T18:10:43+00:00","remoteAddr":"X","user":"test","app":"PHP","method":"PUT","url":"\/remote.php\/webdav\/Test\/Abend-GD.pages","message":"Undefined offset: 0 at \/home\/XXX\/www\/YYY\/lib\/private\/Share20\/Manager.php#1370","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"Wdu7ldkaOjsAATSzYO8AAAAB","level":3,"time":"2017-10-09T18:10:43+00:00","remoteAddr":"X","user":"test","app":"PHP","method":"PUT","url":"\/remote.php\/webdav\/Test\/Abend-GD.pages","message":"Call to a member function getPath() on null at \/home\/XXX\/www\/YYY\/lib\/private\/Share20\/Manager.php#1380","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
```

I.e., it seems that only the last two lines of my previous log are triggered "again" in this case.

**Comment by putt1ck** [comment]
I think is related to https://github.com/nextcloud/groupfolders/issues/55

**Comment by icewind1991** [comment]
This should be fixed with https://github.com/nextcloud/server/pull/7137
