### ISSUE TITLE
How I can set permissions for subfolders via API?

### ISSUE THREAD

**Issue by radoslavius** [nextcloud/groupfolders#541]
Hi,
I can set permission for subfolders in web browser, but I don't know how do this via API. `pacedata` is group folder.
Thanks for any tips
Radek

![image](https://user-images.githubusercontent.com/3509024/62044288-ce294280-b202-11e9-9116-bb7bc234716f.png)

**Comment by wiswedel** [comment]
@juliushaertl This ain't possible yet, is it?

**Comment by juliushaertl** [comment]
Permissions can be set though webdav, here is a very quick overview (at some point we should of course document this in detail)

## List acls

The list of applied acl rules for a folder can obtained by issuing a PROPFIND request to the folder or files WebDAV URL:

Request example:
```
<?xml version="1.0"?>
<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns" xmlns:ocs="http://open-collaboration-services.org/ns">
  <d:prop>
    <nc:acl-list />
    <nc:inherited-acl-list />
    <nc:group-folder-id />
    <nc:acl-enabled />
    <nc:acl-can-manage />
  </d:prop>
</d:propfind>
```

Response:
```
![image](https://user-images.githubusercontent.com/3404133/64160852-f5e07b80-ce3c-11e9-9dd0-56d85cf16b41.png)
```

## Updating acls

Updates can be performed with PROPPATCH

Request example:
```
<?xml version="1.0" encoding="UTF-8"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:nc="http://nextcloud.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:ocs="http://open-collaboration-services.org/ns">
   <d:set>
      <d:prop>
         <nc:acl-list>
            <nc:acl>
               <nc:acl-mapping-type>group</nc:acl-mapping-type>
               <nc:acl-mapping-id>admin</nc:acl-mapping-id>
               <nc:acl-mask>12</nc:acl-mask>
               <nc:acl-permissions>19</nc:acl-permissions>
            </nc:acl>
            <nc:acl>
               <nc:acl-mapping-type>user</nc:acl-mapping-type>
               <nc:acl-mapping-id>admin</nc:acl-mapping-id>
               <nc:acl-mask>4</nc:acl-mask>
               <nc:acl-permissions>27</nc:acl-permissions>
            </nc:acl>
         </nc:acl-list>
      </d:prop>
   </d:set>
</d:propertyupdate>
```

Some general details based on the notes from @icewind1991 
- The mask controls what of the permission is inherited (all 0 bits are inherited)
- you can get the inherited acl's by requesting the nc:inherited-acl-list property, note that these results are not "real" acls, but the combined permissions of all acls for parent folders.
- When listing acls as an admin you get all configured acls back, as non admin users you only see the acls that affect you, settings acls can only be done by admins

**Comment by mhincapie** [comment]
@juliushaertl Thanks for this information. Looking forward to the pending documentation @wiswedel.

**Comment by radoslavius** [comment]
Hi
@juliushaertl I will try your request example, but I have different response, what I'am doing wrong?

![image](https://user-images.githubusercontent.com/3509024/66918126-f31d9c80-f01e-11e9-9381-0ad2cb8eefeb.png)

Thanks

**Comment by radoslavius** [comment]
@juliushaertl can you advise me what to do with it? https://github.com/nextcloud/groupfolders/issues/541#issuecomment-542673951
