### ISSUE TITLE
Group Folder deletes data if you put a . (dot) in a sub-folder name

### ISSUE THREAD

**Issue by HealthCIO** [nextcloud/groupfolders#551]

**Comment by wiswedel** [comment]
@icewind1991 @juliushaertl 
Just reproduced this.
Applies to dot anywhere in a subfolder name.
Happens only on renaming a folder when already inside a group folder. Moving a folder with a dot in name from user storage into a group folder keeps the folder alive.

**Comment by juliushaertl** [comment]
I cannot reproduce this with 4.0.5 anymore, as it should actually be fixed by https://github.com/nextcloud/groupfolders/pull/542
