### ISSUE TITLE
Wrong Polish translation of "Group folders" phrase

### ISSUE THREAD

**Issue by mjd80** [nextcloud/groupfolders#56]
Hello,

Current translation of "Group folders" phrase, to Polish language, is wrong. 
Direct translation has to be "Foldery grupowe" instead of currently used "Grupa folderów".
Google Translator confirms.

"Grupa folderów", after translate it back to English, means: "Group of folders".

**Comment by tflidd** [comment]
@rakekniven Can you help here?

**Comment by rakekniven** [comment]
See https://www.transifex.com/nextcloud/nextcloud/translate/#pl/$/111930819 Adressed issue to polish team

**Comment by KB7777** [comment]
Heh, my fault. Did change to "Foldery groupowe" right now ;)
Close pls.
