### ISSUE TITLE
Admin of a group should be able to setup group folder structure

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/groupfolders#561]
Been playing with NC 16.0.0 official release and the nice new Group Folder ACLs. It works nice, but seems something is amiss. 

### What happens
As NC admin I create a couple of users, belonging to group *TestGroup1*, **User A** and **User B**. I configure **User A** as the *admin* of **TestGroup1**.

Then, as NC admin I create a Group Folder called Folder1. This folder is the group folder for TestGroup1 and has full access, RWD. I also allow Advanced Permissions.

In another browser I log in as User A and create a folder inside Folder1. At this point I am not able to set Advanced Permissions for the folder I just created. However, when I add the NC admin user as part of TestGroup1, and log in as admin, I am able to set advanced permissions for the already created folders and subfolders. 

### What I would like to happen

Group folders for us is a feature we see working as a type of  shared folder that can be setup inside a business unit in a large organization. So centrally managing each and every groupfolders' hierarchy is not viable. What I propose is that the rights to assign Advanced Properties be granted to the admin of a Group, so that NC admins can create the group folder, but whatever happens inside it, is totally up to a designated user inside that group (the admin of the group). Adding a group admin as part of the NC admin group is **NOT** an option for obvious reasons.

**Comment by waazdakka** [comment]
Same issue here : I have a lot of groups and I need to have 1 admin by group, who could manage advanced authorizations to the folder they have access to.
I can't give full NC admin access to these users, but they are admin of their groups and they should have the possibility to manage access to their folder and subfolder...

**Comment by juliushaertl** [comment]
Implemented with 4.1.0

**Comment by waazdakka** [comment]
Hello @juliushaertl , maybe I missed something but... Users can't add permissions with this version ? (This user is part of the "Communication" group and admin of this same group)

<img width="1103" alt="nextcloud-users" src="https://user-images.githubusercontent.com/9380081/63652497-13d51e80-c761-11e9-987f-8ae8661ba689.png">

<img width="1061" alt="Capture d’écran 2019-08-25 à 15 21 41" src="https://user-images.githubusercontent.com/9380081/63650571-2f81fa00-c74c-11e9-8a14-d26d99f20726.png">
Thanks!

**Comment by waazdakka** [comment]
Hello @juliushaertl Thanks for the integration ! 
However, it still impossible to add someone from another group : I can only manage permissions for the users inside the group I configured in the first place, instead of have the rights to add any user or group 
(And I can't obviously add all groups to all group folders and then manage rights folder by folder 😅)

**Comment by wiswedel** [comment]
> it still impossible to add someone from another group

Sure, the admin interface must be the top authority. You can't just override the admin's decision about group memberships and associations to group folders.

**Comment by hanserasmus** [comment]
> > it still impossible to add someone from another group
> 
> Sure, the admin interface must be the top authority. You can't just override the admin's decision about group memberships and associations to group folders.

Not sure if I understand this correctly. The idea initially was to have NC admin be able to assign full Group folder admin rights to any user in the group (or even better, have it inherited from a third party provisioning system :-) ) so that the newly elected group admin can then administrate that group folder on his or her own. This Group folder admin can then set up the rights on this folder for all the users in that group.

**Comment by wiswedel** [comment]
> The idea initially was to have NC admin be able to assign full Group folder admin rights to any user in the group (or even better, have it inherited from a third party provisioning system :-) ) so that the newly elected group admin can then administrate that group folder on his or her own. This Group folder admin can then set up the rights on this folder for all the users in that group.

And that's exactly how it works.
- The admin sets up a group folder and assigns initial rights to several groups.
- The admin promotes single members or whole groups from within the associated groups to manage ACL permissions for that group folder.
- All subfolders/-files inherit the rights from their parent folder, so if nobody does anything about the ACLs, the admin-set rules apply.
- Once an entitled group-folder-admin changes the permissions for someone from "inherit" to e.g. "allow", all sub-objects inherit that new right.

**Comment by hanserasmus** [comment]
Thank you so much. Will give this a go during the week sometime. Thanks to you and @juliushaertl for the hard work!

**Comment by hanserasmus** [comment]
Hey guys. I am working on figuring out how exactly to set up the permissions, and at one point screwed something up. Trying to revert it back so that the admin of the group has full rights to a specific folder. But getting the below error.
![image](https://user-images.githubusercontent.com/24249616/63770136-c37ecd80-c8d4-11e9-919c-27eabeaa4fc3.png)
I followed these instructions:

![image](https://user-images.githubusercontent.com/24249616/63770165-d4c7da00-c8d4-11e9-8b16-ee382ff7a807.png)
Am I doing something wrong? This occ commands will help a lot in the future with users maybe setting things up wrong, and we have to fix it on their behalf.

**Comment by juliushaertl** [comment]
@hanserasmus The command would be 
`occ groupfolders:permissions 4 --user martin KPA/hans -- +read`

However we should properly handle falsey command options, so could you open a separate issue for that?

**Comment by hanserasmus** [comment]
Will do, because the command you gave is also not working.  Same error it seems.
