### ISSUE TITLE
Other users with access to a groupfolders cant see shares created by other users

### ISSUE THREAD

**Issue by AlessandroP28** [nextcloud/groupfolders#57]
Hi, on Nextcloud 12 I create a Group Folder with write/share access permission to USER1 and USER2.
USER1 upload files or folders inside it. If it share file/folder with public link, why USER2 not see that share?
User2 sees the file as if it was not shared.
The user who creates a share on groupfolders, should have the option to share in Personal or Group permissions. Or directly with Group permission, but not only Personal, else others Users of that group not see share link.

**Comment by icewind1991** [comment]
This is the case with any system within Nextcloud where mutliple users have access to the same files, shares are always bound to the user that initiated the share, not whoever has accesss to the file that was shared.

**Comment by AlessandroP28** [comment]
The user who creates a share on groupfolders, should have the option to share in Personal or Group permissions. Or directly with Group permission, but not only Personal, else others Users of that group not see share link.
Otherwise it is useless :-//

**Comment by mbrgm** [comment]
@icewind1991 Could you be a bit more specific on where this would have to be changed in your opinion? I'm on one page with @AlessandroP28 ... shared folders within a team only make sense if everybody shares the same 'view'.
