### ISSUE TITLE
Why should i update 4.0.5 to 4.1.0? - OLD release notes!

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/groupfolders#573]
Could you please update release notes before you offer the update.
Otherwise i can't judge if i need or should update.

Thanks!

**Comment by oneilonline** [comment]
Well, the 4.1.0 didn't even include the fix for: [fa87c71](https://github.com/nextcloud/groupfolders/commit/fa87c7164d01fa4732fcbbc4b498cb4b2926b42e) = https://github.com/nextcloud/groupfolders/issues/565
I completed the upgrade, but then had to re-implement the changes. Defeated the purpose.
Perhaps there was no release notes because nothing changed...?

**Comment by DBJRdev** [comment]
I'm not involved in the programming, but from our own testing we can confirm the 4.1. has the following improvements:
- allows to assign users/groups to manage extended rights of a group folder;
- does not crash NC17betas anymore;
- updates of some libraries;

**Comment by oneilonline** [comment]
@DBJRdev "does not crash NC17beta2 anymore" is not true. As I stated, the fix fa87c71 = #565 was not included, which rendered NC17beta2 inaccessible.

**Comment by wiswedel** [comment]
Just updated the release notes for 4.1.0 (important feature enhancement).
The mentioned fix will go into the next maintenance release.

**Comment by pm-pm** [comment]
Where did you do that?
Here: [https://github.com/nextcloud/groupfolders](https://github.com/nextcloud/groupfolders) are still the old information.

**Comment by wiswedel** [comment]
> Where did you do that?
> Here: https://github.com/nextcloud/groupfolders are still the old information.

Release notes are on the release page: https://github.com/nextcloud/groupfolders/releases

Readme will be updated soon.

**Comment by wiswedel** [comment]
> Readme will be updated soon.

@pm-pm done, see https://github.com/nextcloud/groupfolders
