### ISSUE TITLE
Groupfolder permissions error not handled correctly

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/groupfolders#579]
When trying to edit the permissions for a specific group folder, a stack trace appears and the user cannot clearly see what is wrong.
![image](https://user-images.githubusercontent.com/24249616/63775054-da2a2200-c8de-11e9-9272-cd5a86e87fb5.png)
And running the command @juliushaertl suggested in the last reply in issue #561 also still an error:
![image](https://user-images.githubusercontent.com/24249616/63775164-13fb2880-c8df-11e9-9821-b12736272655.png)

**Comment by juliushaertl** [comment]
Might be an issue with the file id not casted to an integer.

**Comment by guystreeter** [comment]
Does this problem still exist? I was unable to reproduce it on Nextcloud 22.

**Comment by fschrempf** [comment]
Closing as duplicate of #470.
