### ISSUE TITLE
Add Advanced permissions rule - missing

### ISSUE THREAD

**Issue by ScotOz** [nextcloud/groupfolders#584]
I have Group Folders installed, all working without issue then all of a sudden for no reason some of the group folders lot their ability for me to view/add/change "Advanced permissions".

In Groupfolder set to enabled and advanced enabled etc.:
![CapturFiles-30-38-2019_08 38 37](https://user-images.githubusercontent.com/53585010/64014847-8df11300-cb66-11e9-9e8e-01f9b1f3120f.jpg)

The folder is missing the ability to view etc. (permissions previously see are still enforce though, however I am unable to edit/add):

![CapturFiles-30-37-2019_08 37 36](https://user-images.githubusercontent.com/53585010/64014956-cb55a080-cb66-11e9-969a-a0ba449a5a0f.jpg)

**Comment by wiswedel** [comment]
@juliushaertl There was this occ command during dev-time to update something in the db. Is this still necessary after updating to 4.1.0 to keep advanced permissions for existing folders?

**Comment by juliushaertl** [comment]
> @juliushaertl There was this occ command during dev-time to update something in the db. Is this still necessary after updating to 4.1.0 to keep advanced permissions for existing folders?

The command was just to run the migration during development since you checked out two versions of the development branch.

@ScotOz I guess you are using an admin user when trying to set the advanced permissions?

Could you check the browser network log? When opening the sharing sidebar there should be a PROPFIND request to the webdav location of your group folder. What is the response of this one for you?

It should state that the current user is able to manage permissions:
![image](https://user-images.githubusercontent.com/3404133/64160410-2d025d00-ce3c-11e9-8515-8653ff419b02.png)

Please also check the browser console for errors.

**Comment by ScotOz** [comment]
@juliushaertl sorry I didn't hear back sooner so I had to create a new folder, copy the contents and reapply the group permissions etc.

To answer your questions, I am using the user admin, I am able to add/remove etc. permissions without issue and only "some" folders had the permissions disappear.

However, I think I "may" know what causes the issue....I deleted a user, when I looked in the folders the previous user had been part of, as per the above original post, the Group Folder permissions disappears.

I will create some new permissions and a test user and attempt to recreate however I am guessing this is what may cause the issue....I will:

1. Add a new temp user
2. Create a new Group Folder
3. Apply Group Folder permissions etc.
4. Put in some content
5. Delete the new temp user and see if I get Group Folder permissions missing

I'll report back once done.

**Comment by ScotOz** [comment]
Okay, confirmed my.....if a user is part of a Group Folder is the user is removed without being first removed from any Group Folders they are part of then the ability to access Group Folder in the folders they're removed from occurs.

User and group folder added:
![CapturFiles-03-17-2019_09 17 18](https://user-images.githubusercontent.com/53585010/64169206-914f0c00-ce90-11e9-8f3e-a8528f824c87.jpg)

User deleted and then access the folder again:
![CapturFiles-03-17-2019_09 17 52](https://user-images.githubusercontent.com/53585010/64169239-a75ccc80-ce90-11e9-8c1f-b656e58dc181.jpg)

**Comment by ScotOz** [comment]
Sorry, you can see that the Temp Folder still remains as a Group Folder however permissions as in the previous post/image has disappeared:

![CapturFiles-03-24-2019_09 24 18](https://user-images.githubusercontent.com/53585010/64169521-54cfe000-ce91-11e9-9500-d477a5691c1e.jpg)

**Comment by juliushaertl** [comment]
Can you check the Nextcloud log and browser console for errors?

**Comment by ScotOz** [comment]
@juliushaertl sorry, I am a bit of a newbie in terms of NextCloud.....would you like to connect to my computer say via TeamViewer and I'll show you my config and how I get the error to occur?

**Comment by juliushaertl** [comment]
Here are some details for the browser console

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by fschrempf** [comment]
I guess this is the same issue as in #894 and many others.

**Comment by juliushaertl** [comment]
Repoened https://github.com/nextcloud/groupfolders/issues/894 and closing this one as a dupliate
