### ISSUE TITLE
View activities of all users in a group folder

### ISSUE THREAD

**Issue by Int32Overflow** [nextcloud/groupfolders#589]
Currently, activities can only be seen by the author of the file or folder in the group folder.
However, it would be very helpful if these activities could be seen by any user who has access to this folder.

**For example:**
- All users of the folder should be able to see when a public link was created. 
- All users of the folder should be able to see when the file was downloaded from a public link.

**Comment by RuudschMaHinda** [comment]
I think you are referencing this issue:
https://github.com/nextcloud/activity/issues/264

Unfortunately it's still pending due to "out of ideas" https://github.com/nextcloud/activity/issues/264#issuecomment-522596299

**Comment by nickvergessen** [comment]
I'm closing this so we have all discussion in one place only.
And since external storages are affected as a hole, it should not be in the groupfolders app ;)
