### ISSUE TITLE
Scan Directory for changes

### ISSUE THREAD

**Issue by Jab2870** [nextcloud/groupfolders#59]
For "normal" folders in nextcloud you can rescan the directory with 

    occ files:scan --path="path/to/dorectory"

Is there an equivalent to this for groupfolders?

I have a lot of digital films that I would like to be in a group folder. I don't want to have to manually upload all of them. I have added them to the directory `.../data/__groupfolders/1/`, but they are not showing.

**Comment by dan-nkl** [comment]
I think there is no option for that...
And don't even expect that someone cares about issues in this app..

**Comment by icewind1991** [comment]
Just specify the path as it is for the user that has the folder.

Which user is used for scanning doesn't matter, changes will be correctly detected for any user with access to that folder
