### ISSUE TITLE
NC 16.0.4 and GF 4.1 not working together

### ISSUE THREAD

**Issue by Sick-Andrew** [nextcloud/groupfolders#590]
I updated NC 16.0.2 -> 16.0.4 and GF was updated in the same process (web interface).
After Update was finished GF did not work correctly. Existing folders did not sync properly and NC showed an internal server error in the web interface.
Here are some details that might help. I solved the issue by deleting /nextcloud/apps/groupfolders completely and uploading a fresh groupfolders 4.0.5 folder from the NC store.

Oh and we use shared hosting so I used web interface and FTP access to the NC files.

If you need more info from the log let me know

> Type: OCP\Files\NotPermittedException
Code: 0
Message: Could not move /XXXX/files/MYFOLDER to /XXXX/files/MYFOLDER (1)
File: /home/dir/dir2/dir3/nextcloud/lib/private/Files/Node/Node.php
Line: 431

> [no app in context] Error: OCP\Files\NotPermittedException: Could not move /my_own_user_account/files/MYFOLDER to /my_own_user_account/files/ MYFOLDER (1) at <<closure>>

0. /nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 101
    OC\Files\Node\Node->move("/XXXX ... )")
1. <<closure>>
    OCA\GroupFolders\Mount\MountProvider->OCA\GroupFolders\Mount\{closure}("*** sensitive parameters replaced ***")
2. /nextcloud/apps/groupfolders/lib/Mount/MountProvider.php line 115
    undefinedundefinedarray_map(Closure {}, ["*** sensitive  ... }])
3. /nextcloud/lib/private/Files/Config/MountProviderCollection.php line 103
    OCA\GroupFolders\Mount\MountProvider->getMountsForUser(OC\User\User {}, OC\Files\Storage\StorageFactory {})
4. /nextcloud/lib/private/Files/Filesystem.php line 447
    OC\Files\Config\MountProviderCollection->addMountForUser(OC\User\User {}, OC\Files\Mount\Manager {})
5. /nextcloud/lib/private/Files/Filesystem.php line 376
    OC\Files\Filesystem::initMountPoints("my_own_user_account")
6. /nextcloud/lib/private/legacy/util.php line 309
    OC\Files\Filesystem::init("my_own_user_account", "/my_own_user_account/files")
7. /nextcloud/lib/private/Files/Mount/Manager.php line 89
    OC_Util::setupFS()
8. /nextcloud/lib/private/Files/View.php line 1374
    OC\Files\Mount\Manager->find("/__groupfolders")
9. /nextcloud/lib/private/Files/Node/Root.php line 198
    OC\Files\View->getFileInfo("/__groupfolders")
10. <<closure>>
    OC\Files\Node\Root->get("/__groupfolders")
11. /nextcloud/lib/private/Files/Node/LazyRoot.php line 64
    undefinedundefinedcall_user_func_array([OC\Files\Node\Root {},"get"], ["__groupfolders"])
12. /nextcloud/lib/private/Files/Node/LazyRoot.php line 141
    OC\Files\Node\LazyRoot->__call("get", ["__groupfolders"])
13. /nextcloud/apps/groupfolders/lib/AppInfo/Application.php line 55
    OC\Files\Node\LazyRoot->get("__groupfolders")
14. /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensitive parameters replaced ***")
15. /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 117
    Pimple\Container->offsetGet("GroupAppFolder")
16. /nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 404
    OC\AppFramework\Utility\SimpleContainer->query("GroupAppFolder")
17. /nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 382
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("GroupAppFolder")
18. /nextcloud/apps/groupfolders/lib/AppInfo/Application.php line 88
    OC\AppFramework\DependencyInjection\DIContainer->query("GroupAppFolder")
19. /nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}("*** sensitive parameters replaced ***")
20. /nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 117
    Pimple\Container->offsetGet("OCA\\GroupFolde ... d")
21. /nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 404
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\GroupFolde ... d")
22. /nextcloud/lib/private/ServerContainer.php line 134
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\GroupFolde ... d")
23. /nextcloud/apps/files_versions/lib/AppInfo/Application.php line 80
    OC\ServerContainer->query("OCA\\GroupFolde ... d")
24. /nextcloud/apps/files_versions/lib/AppInfo/Application.php line 63
    OCA\Files_Versions\AppInfo\Application->registerVersionBackends()
25. /nextcloud/apps/files_versions/appinfo/routes.php line 29
    OCA\Files_Versions\AppInfo\Application->__construct()
26. /nextcloud/lib/private/Route/Router.php line 351
    undefinedundefinedinclude_once("/home/maijomoy/ ... p")
27. /nextcloud/lib/private/Route/Router.php line 151
    OC\Route\Router->requireRouteFile("/home/maijomoy/ ... p", "files_versions")
28. /nextcloud/lib/private/Route/Router.php line 331
    OC\Route\Router->loadRoutes()
29. /nextcloud/lib/private/Route/CachingRouter.php line 60
    OC\Route\Router->generate("theming.Theming.getStylesheet", {v: "14"}, false)
30. /nextcloud/lib/private/URLGenerator.php line 79
    OC\Route\CachingRouter->generate("theming.Theming.getStylesheet", {v: "14"})
31. /nextcloud/apps/theming/appinfo/app.php line 34
    OC\URLGenerator->linkToRoute("theming.Theming.getStylesheet", {v: "14"})
32. /nextcloud/lib/private/legacy/app.php line 262
    undefinedundefinedrequire_once("/home/maijomoy/ ... p")
33. /nextcloud/lib/private/legacy/app.php line 155
    OC_App::requireAppFile(OCP\AppFramework\App {})
34. /nextcloud/lib/private/legacy/app.php line 128
    OC_App::loadApp("theming")
35. /nextcloud/lib/base.php line 960
    OC_App::loadApps()
36. /nextcloud/index.php line 42
    OC::handleRequest()

GET /nextcloud/index.php/apps/logreader/poll?lastReqId=1ogcYYzbFLDODAl6oOHK
from 5.63.49.226 by my_own_user_account at 2019-09-03T11:57:53+00:00

> Trace
#0 nextcloud/apps/groupfolders/lib/Mount/MountProvider.php(101): OC\Files\Node\Node->move('/XXXX-...')
#1 [internal function]: OCA\GroupFolders\Mount\MountProvider->OCA\GroupFolders\Mount\{closure}(Array)
#2 nextcloud/apps/groupfolders/lib/Mount/MountProvider.php(115): array_map(Object(Closure), Array)
#3 nextcloud/lib/private/Files/Config/MountProviderCollection.php(103): OCA\GroupFolders\Mount\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
#4 nextcloud/lib/private/Files/Filesystem.php(447): OC\Files\Config\MountProviderCollection->addMountForUser(Object(OC\User\User), Object(OC\Files\Mount\Manager))
#5 nextcloud/lib/private/Files/Filesystem.php(376): OC\Files\Filesystem::initMountPoints('XXXX...')
#6 nextcloud/lib/private/legacy/util.php(309): OC\Files\Filesystem::init('XXXX...', '/XXXX...')
#7 nextcloud/lib/base.php(974): OC_Util::setupFS()
#8 nextcloud/index.php(42): OC::handleRequest()
#9 {main}

**Comment by hriekehof** [comment]
I don't have the error message but i can confirm that error. I updated to 16.04 and GF 4.1 last friday and everything seemed to work. 
Today i recognized that the sync of group folders via the desktop client is not working properly. Files created in the browser never get synced to a client. 
Only when you manually start a sync in the desktop app newly added files gets synced.

**Comment by Sick-Andrew** [comment]
> Only when you manually start a sync in the desktop app newly added files gets synced.

That actually didn't work for me. I use 3 groups with different folders and permissions.

To be honest I did not focus on the sync at first. I had another tab with me as admin logged in open and wanted to share a groupfolders folder by creating a link. That's when I  realized neither the generated link, nor the log-in via web interface not the (forced) sync on the client worked.

**Comment by hriekehof** [comment]
OK i can confirm with GroupFolders 4.0.5 everything works fine with the sync again. I also had to downgrade from the store.
By the way a nice feature for Nextcloud would be to select the version of the App you want to install :)

**Comment by juliushaertl** [comment]
> [no app in context] Error: OCP\Files\NotPermittedException: Could not move /my_own_user_account/files/MYFOLDER to /my_own_user_account/files/ MYFOLDER (1) at <>

This seems to be an issue with the collision handling in case that MYFOLDER is already a regular folder in your users directory. Is that the case for you? Is there any reason this one could not be renamed to MYFOLDER (1) ?

**Comment by Sick-Andrew** [comment]
> > [no app in context] Error: OCP\Files\NotPermittedException: Could not move /my_own_user_account/files/MYFOLDER to /my_own_user_account/files/ MYFOLDER (1) at <>
> 
> This seems to be an issue with the collision handling in case that MYFOLDER is already a regular folder in your users directory. Is that the case for you? Is there any reason this one could not be renamed to MYFOLDER (1) ?

**Comment by Sick-Andrew** [comment]
Well I haven't tried renaming it but as the sync did not work anyway it wouldn't do any good.

I recollect that when I set up NC about a year ago MYFOLDER was created and had some files in it. 
Some time later I discovered GF and actually created this folder in GF assuming GF would just set some new permissions to it. But the initial folder was then deleted and overwritten by a GF folder with the same name. Thus, I had to upload the files again into the new GF folder.

Do you think that might have caused this issue due to some datebase collisions?

Besides that this folder has been around and with working sync every since. Neither the name nor the location have be changed.

**Comment by juliushaertl** [comment]
> Do you think that might have caused this issue due to some datebase collisions?

Yes, the groupfolders before 4.1.0 was just mounting the group folder over existing folders, so the original folder was still there but never visible. With 4.1.0 we automatically rename existing folders if a naming collision with a group folder happens, similar to how it is done for sharing.

**Comment by hriekehof** [comment]
what about the sync error ? Shall i open a new ticket for that ?

**Comment by Sick-Andrew** [comment]
> Yes, the groupfolders before 4.1.0 was just mounting the group folder over existing folders, so the original folder was still there but never visible. With 4.1.0 we automatically rename existing folders if a naming collision with a group folder happens, similar to how it is done for sharing.

OK but obviously something went terribly wrong and I'm just thinking this could affect thousands of people who don't even know that an old folder with this name existed somewhen.
I also checked nextcloud/data/ and all the users in there. MYFOLDER does not exist there apart from GF. So is it more of an database issue?
What can one do to prevent something like that from happening? Is it possible to switch the prevention off and handle it the way GF <4.1.0 did?

**Comment by en3r0** [comment]
Just ran into this issue, renaming the group folder resolve the issue.

**Comment by Sick-Andrew** [comment]
> Just ran into this issue, renaming the group folder resolved the issue.

Where did you do that? Via FTP?

**Comment by en3r0** [comment]
> Where did you do that? Via FTP?

I did that under the admin account via Settings > Group folders > and then clicking the pencil icon to edit. I did not have the admin account as part of the group to start with.
