### ISSUE TITLE
Admin login crash (Internal Server Error) after update to 4.1.0 (NC 16.0.3)

### ISSUE THREAD

**Issue by HAL9OO** [nextcloud/groupfolders#592]
Hi!

I was updating Group Folders via web interface and suddenly an error occurred. It seems to be similar to #241 - NC works, Group Folders as well but I can't login to my Admin panel.

NC Version 16.0.3
GF v 4.1.0
Apache 2.4.25
PHP 7.0.33
Debian 9.8
10.1.38-MariaDB-0+deb9u1

Sadly I can't find any log information (~/var/www/nextcloud/data/nextcloud.log is empty). This is strange as well because for sure there was a log when I've checked in a Admin Settings. W heavily rely on Group folders so I don't want to disable/uninstall the app.

PS. What is more interesting - only my admin account is locked, the other can easly login.

**Comment by juliushaertl** [comment]
Is /var/www/nextcloud/data/nextcloud.log writable by your webserver? There should be an error if the login fails

**Comment by HAL9OO** [comment]
OK, So I've found the correct log file and the error. Moreover other admins can't see the users list. The count and groups on the left are correct but there are no user entries and a message occures: An error occured during the request. Unable to proceed.

`{"reqId":"rBrs1ftEL0JN7DAKNzyA","level":3,"time":"2019-09-06T08:34:03+00:00","remoteAddr":"---","user":"admin","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/7ed13726643256347adf665df5887fd9\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":779,"function":"changeLock","class":"OC\\Lock\\DBLockingProvider","type":"->","args":["files\/7ed13726643256347adf665df5887fd9",2]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files\/PROJEKTY",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/PROJEKTY",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":615,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/PROJEKTY",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/View.php","line":1981,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/PROJEKTY",2,{"__class__":"OC\\Lock\\DBLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/View.php","line":790,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/admin\/files\/PROJEKTY",2,true]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Node.php","line":430,"function":"rename","class":"OC\\Files\\View","type":"->","args":["\/admin\/files\/PROJEKTY","\/admin\/files\/PROJEKTY\/ (1)"]},{"file":"\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php","line":101,"function":"move","class":"OC\\Files\\Node\\Node","type":"->","args":["\/admin\/files\/PROJEKTY\/ (1)"]},{"function":"OCA\\GroupFolders\\Mount\\{closure}","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php","line":91,"function":"array_map","args":[{"__class__":"Closure"},[{"folder_id":5,"mount_point":"DOKUMENTACJA\/_ADMINISTRACJA","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":9,"mount_point":"DOKUMENTACJA\/DELEGACJE","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":8,"mount_point":"DOKUMENTACJA\/MAJATEK_TRWALY","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":11,"mount_point":"DOKUMENTACJA\/OGOLNE","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":10,"mount_point":"DOKUMENTACJA\/PROMOCJA","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":12,"mount_point":"DOKUMENTACJA\/SPRZET_POMIAROWY","permissions":15,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":7,"mount_point":"DOKUMENTACJA\/SYSTEM_JAKOSCI","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":6,"mount_point":"DOKUMENTACJA\/SZABLONY","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":30,"mount_point":"DOKUMENTACJA\/BHP","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":14,"mount_point":"_DO_REALIZACJI","permissions":1,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":16,"mount_point":"DOKUMENTACJA","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":18,"mount_point":"_DO_REALIZACJI\/_CTKK","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":19,"mount_point":"_DO_REALIZACJI\/DRUK-3D","permissions":15,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":20,"mount_point":"_DO_REALIZACJI\/WYKONAWSTWO","permissions":15,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":21,"mount_point":"_DO_REALIZACJI\/_PUBLICZNE","permissions":31,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},"*** sensitive parameter replaced ***",{"folder_id":36,"mount_point":"PROJEKTY\/ESA\/FLPP\/Restricted","permissions":1,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}},{"folder_id":39,"mount_point":"PROJEKTY\/STATUTOWE\/BURSZTYN\/Archiwum\/","permissions":1,"quota":-3,"acl":false,"rootCacheEntry":{"__class__":"OC\\Files\\Cache\\CacheEntry"}}]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Config\/MountProviderCollection.php","line":103,"function":"getMountsForUser","class":"OCA\\GroupFolders\\Mount\\MountProvider","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Storage\\StorageFactory"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php","line":447,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},{"__class__":"OC\\Files\\Mount\\Manager"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php","line":376,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["admin"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/util.php","line":309,"function":"init","class":"OC\\Files\\Filesystem","type":"::","args":["admin","\/admin\/files"]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":974,"function":"setupFS","class":"OC_Util","type":"::","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/Lock\/DBLockingProvider.php","Line":256,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.132 Safari\/537.36","version":"16.0.3.0"}`

**Comment by HAL9OO** [comment]
OK, So I've found the correct log file and the error. Moreover other admins can't see the users list. The count and groups on the left are correct but there are no user entries and a message occures: An error occured during the request. Unable to proceed.

```
{
    "reqId": "rBrs1ftEL0JN7DAKNzyA",
    "level": 3,
    "time": "2019-09-06T08:34:03+00:00",
    "remoteAddr": "***proprietary_information***",
    "user": "admin",
    "app": "no app in context",
    "method": "GET",
    "url": "\/nextcloud\/index.php\/apps\/files\/",
    "message": {
        "Exception": "OCP\\Lock\\LockedException",
        "Message": "\"files\/7ed13726643256347adf665df5887fd9\" is locked",
        "Code": 0,
        "Trace": [{
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php",
            "line": 779,
            "function": "changeLock",
            "class": "OC\\Lock\\DBLockingProvider",
            "type": "->",
            "args": ["files\/7ed13726643256347adf665df5887fd9", 2]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php",
            "line": 615,
            "function": "changeLock",
            "class": "OC\\Files\\Storage\\Common",
            "type": "->",
            "args": ["files\/***proprietary_information***", 2, {
                "__class__": "OC\\Lock\\DBLockingProvider"
            }]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php",
            "line": 615,
            "function": "changeLock",
            "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type": "->",
            "args": ["files\/***proprietary_information***", 2, {
                "__class__": "OC\\Lock\\DBLockingProvider"
            }]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php",
            "line": 615,
            "function": "changeLock",
            "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type": "->",
            "args": ["files\/***proprietary_information***", 2, {
                "__class__": "OC\\Lock\\DBLockingProvider"
            }]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/View.php",
            "line": 1981,
            "function": "changeLock",
            "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
            "type": "->",
            "args": ["files\/***proprietary_information***", 2, {
                "__class__": "OC\\Lock\\DBLockingProvider"
            }]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/View.php",
            "line": 790,
            "function": "changeLock",
            "class": "OC\\Files\\View",
            "type": "->",
            "args": ["\/admin\/files\/***proprietary_information***", 2, true]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Node.php",
            "line": 430,
            "function": "rename",
            "class": "OC\\Files\\View",
            "type": "->",
            "args": ["\/admin\/files\/***proprietary_information***", "\/admin\/files\/***proprietary_information***\/ (1)"]
        }, {
            "file": "\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php",
            "line": 101,
            "function": "move",
            "class": "OC\\Files\\Node\\Node",
            "type": "->",
            "args": ["\/admin\/files\/***proprietary_information***\/ (1)"]
        }, {
            "function": "OCA\\GroupFolders\\Mount\\{closure}",
            "class": "OCA\\GroupFolders\\Mount\\MountProvider",
            "type": "->",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "\/var\/www\/nextcloud\/apps\/groupfolders\/lib\/Mount\/MountProvider.php",
            "line": 91,
            "function": "array_map",
            "args": [{
                    "__class__": "Closure"
                },
                [{
                    "folder_id": 5,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 9,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 8,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 11,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 10,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 12,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 15,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 7,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 6,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 30,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 14,
                    "mount_point": "***proprietary_information***",
                    "permissions": 1,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 16,
                    "mount_point": "***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 18,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 19,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 15,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 20,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 15,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 21,
                    "mount_point": "***proprietary_information***\/***proprietary_information***",
                    "permissions": 31,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, "*** sensitive parameter replaced ***", {
                    "folder_id": 36,
                    "mount_point": "***proprietary_information***\/***proprietary_information***\/***proprietary_information***\/***proprietary_information***",
                    "permissions": 1,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }, {
                    "folder_id": 39,
                    "mount_point": "***proprietary_information***\/***proprietary_information***\/***proprietary_information***\/***proprietary_information***\/",
                    "permissions": 1,
                    "quota": -3,
                    "acl": false,
                    "rootCacheEntry": {
                        "__class__": "OC\\Files\\Cache\\CacheEntry"
                    }
                }]
            ]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Config\/MountProviderCollection.php",
            "line": 103,
            "function": "getMountsForUser",
            "class": "OCA\\GroupFolders\\Mount\\MountProvider",
            "type": "->",
            "args": [{
                "__class__": "OC\\User\\User"
            }, {
                "__class__": "OC\\Files\\Storage\\StorageFactory"
            }]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php",
            "line": 447,
            "function": "addMountForUser",
            "class": "OC\\Files\\Config\\MountProviderCollection",
            "type": "->",
            "args": [{
                "__class__": "OC\\User\\User"
            }, {
                "__class__": "OC\\Files\\Mount\\Manager"
            }]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php",
            "line": 376,
            "function": "initMountPoints",
            "class": "OC\\Files\\Filesystem",
            "type": "::",
            "args": ["admin"]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/private\/legacy\/util.php",
            "line": 309,
            "function": "init",
            "class": "OC\\Files\\Filesystem",
            "type": "::",
            "args": ["admin", "\/admin\/files"]
        }, {
            "file": "\/var\/www\/nextcloud\/lib\/base.php",
            "line": 974,
            "function": "setupFS",
            "class": "OC_Util",
            "type": "::",
            "args": []
        }, {
            "file": "\/var\/www\/nextcloud\/index.php",
            "line": 42,
            "function": "handleRequest",
            "class": "OC",
            "type": "::",
            "args": []
        }],
        "File": "\/var\/www\/nextcloud\/lib\/private\/Lock\/DBLockingProvider.php",
        "Line": 256,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.132 Safari\/537.36",
    "version": "16.0.3.0"
}
```

**Comment by juliushaertl** [comment]
Can you maybe replace the ***proprietary_information*** entries with placeholders that are similar to the folder structure you use?

```
{
            "file": "\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Node.php",
            "line": 430,
            "function": "rename",
            "class": "OC\\Files\\View",
            "type": "->",
            "args": ["\/admin\/files\/***proprietary_information***", "\/admin\/files\/***proprietary_information***\/ (1)"]
}
```

Could you check if there is an existing folder with the same name as the groupfolder if you disable the groupfolders app? Is there still a folder present with the same name in the users data folder?

**Comment by juliushaertl** [comment]
Could you check if the following patch fixes the issue? It should also log an error when browsing the page:

```diff
diff --git a/lib/Mount/MountProvider.php b/lib/Mount/MountProvider.php
index da1292a..71aee22 100644
--- a/lib/Mount/MountProvider.php
+++ b/lib/Mount/MountProvider.php
@@ -97,9 +97,12 @@ class MountProvider implements IMountProvider {
                        }
                        if ($folderName !== $folder['mount_point']) {
                                $node = $userHome->get($folder['mount_point']);
-                               if ($node->getStorage()->instanceOfStorage('\OCP\Files\IHomeStorage')) {
+                               if ($node->getStorage()->instanceOfStorage(GroupFolderStorage::class)) {
+                                       \OC::$server->getLogger()->error('Tried to move groupfolder mount itself');
+                               } else if ($node->getStorage()->instanceOfStorage('\OCP\Files\IHomeStorage')) {
                                        $node->move($userHome->getPath() . '/' . $folderName);
                                }
+
                        }
```

**Comment by Tazzios** [comment]
From which version did you upgrade?
I also got the error, i`m not sure but i think my version was older then 4.0.5

How to fix (atleast in my case):
- Delete the groupfolders from apps.
- manual upload version 4.0.5 (nextcloud works)
- Update 4.0.5 to 4.1.0 from by the interface as normal

**Comment by HAL9OO** [comment]
I am not sure but I think it was older then 4.0.5 as well. Just to be sure - by deleting the app I won't corrupt overall setup of the folder structure?

**Comment by Tazzios** [comment]
oeps sorry i thought i didn`t send my comment. I was to quick 4.10 doenst work, is was disabled after enabling the same error

I didnt dare to delete the app with the webinterface for the risks you mention. so I renamed the existing folder by ftp and then uploaded the unzipped 4.0.5 .
  
So i`m now working with the old 4.0.5 till this issue is solved.

**Comment by Tazzios** [comment]
I did an upgrade from NC16.0.4 to 16.0.6 with groupfolder 4.0.5 installed. groupfolder was also automatically updated and i now have a working situation with NC 16.0.6 and  groupfolder  4.1.4

**Comment by pierreozoux** [comment]
Looks like both of you found a workaround and Nc 16 is no longer supported. Feel free to reopenan issue if needed.
