### ISSUE TITLE
Desktop client not syncing changes

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/groupfolders#597]
I updated Nextcloud and Groupfolders recently to 16.0.4 and 4.1.0. With GF 4.1.0 the sync of files by the desktop client is only working in some cases. These are the cases i observe.

1. When i create a file locally it gets synced by the desktop client to the server. But not to other clients automatically.
2. When i create a file in a groupfolder on the server its not getting synced automatically by any desktop client
3. Files get synced when i start a manual sync in the desktop client.
 
I downgrated GF to 4.0.5 and the sync problem is gone. Everything is synced quickly after it is changed in the browser or locally by the desktop app.

There was also a short discussion in #590 but it was bascially another problem.

**Comment by patricksebastien** [comment]
I also have this major issue. First I was under the impression that it was the desktop client because I do not have this bug using the Mac client. But it might be related to something else. 

Here's the full log and discussion about it:
https://github.com/nextcloud/desktop/issues/1430

I am sending a notification to all my users to use the force sync for now.

**Comment by patricksebastien** [comment]
Would it be possible to have a label on this. Surely we are not alone using group folder + desktop client.  Downgrading to 4.0.5 is not ideal (I fear this move, I am using group folder with advanced permission).

**Comment by wiswedel** [comment]
CC @icewind1991

**Comment by hriekehof** [comment]
I also can add that my observation was only with the windows desktop client. I didn't do any test with the mac client.

**Comment by gvansanden** [comment]
Sound like my issue indeed but it did work with 4.1.0.
I tested Mac, Windows and Linux clients, versions 2.5.2, 2.5.3 and 2.6.0, I also tested with the OwnCloud client, the issue was present in all versions across platforms

**Comment by gvansanden** [comment]
@hriekehof How did you do the downgrade?  I think I'll also have to do that

**Comment by hriekehof** [comment]
@gvansanden basically the following

1. Maintenance mode or something which makes your Nextcoud inaccessible by users
2. Deactivate the current Groupfolder App in Adminarea
3. Download the Version you want from the Store
4. Unpack it in the custom_apps folder and overwrite the current version
5. Active the Groupfolder App in Nextcloud
6. Go out of Maintenance mode

**Comment by gvansanden** [comment]
@hriekehof I did the same steps earlier, but the app still shows as 4.1.3 in the list, do you also have that?

**Comment by gvansanden** [comment]
@hriekehof Downgrade worked.  But I went to 4.1.0 which was working before.  The issue stays...

**Comment by gvansanden** [comment]
Downgraded to 4.0.5 and everything started working again... Not fun

**Comment by gvansanden** [comment]
I'm going to move away from groupfolders in favor of folders shared by a non-active user.  Too many sync issues with them and activities are broken.  Nice concept but not worth it.

**Comment by derdershat** [comment]
have same problem here... with downgrade to 4.0.5 it is back working.
I use old Windows Client 2.3.3 (because of missing notification in newer versions).

this is a big issue. could this be taken on a higher priority?

**Comment by wiswedel** [comment]
CC @nextcloud/desktop

**Comment by gvansanden** [comment]
@hriekehof No, it is server side

**Comment by patricksebastien** [comment]
@gvansanden Meaning nextcloud 16.0.4 or the groupfolder plugin? Since it's working for 4.0.5, I think it is safe to say that the bug is in the groupfolder plugin.

@icewind1991 Did you had the time to look at it. Do you have an idea.

**Comment by gvansanden** [comment]
@patricksebastien It's a bug in the groupfolder plugin for sure.  Not the client or Nextcloud core.  Groupfolders and sync are a headache that's not worth it

**Comment by TP75** [comment]
NC-Server 16.0.4.1, groupfolders 4.1.3, Debian 10.1, PHP 7.3.9
NC-client version 2.6.0stable (build 20190927), MacOS X / macOS Sierra 10.12.6 & Mojave 10.14.6

> I updated Nextcloud and Groupfolders recently to 16.0.4 and 4.1.0. With GF 4.1.0 the sync of files by the desktop client is only working in some cases. These are the cases i observe.

same here

> 1. When i create a file locally it gets synced by the desktop client to the server. But not to other clients automatically.

almost same. However, any unknown server content syncs to client if local file gets synced.

> 2. When i create a file in a groupfolder on the server its not getting synced automatically by any desktop client

same here

> 3. Files get synced when i start a manual sync in the desktop client.

same here

4. A fresh established client account gets a one-time sync if another client syncs.  Apparently falls back to (1.) afterwards.

HJope this helps.

**Comment by patricksebastien** [comment]
The bug is somewhere between 4.0.5 and 4.1.0:
https://github.com/nextcloud/groupfolders/compare/v4.0.5...v4.1.0
_116 files changed - I am looking to help as much as I can._

Groupfolder is an important app for nextcloud (without it I cannot use nextcloud (advanced permission)). But the desktop client is also very important to my users. I am sure I'm not alone using both.

**Comment by gvansanden** [comment]
@patricksebastien I agree, but it causes so many issues. Activities are broken on GF, putting items in trash locks up clients often as they still have a reference to a file they can no longer access. I'm sharing folders from a meta user for now.

**Comment by Thoro** [comment]
Also affected, is there a work around instead of downgrading the app - which seems to break my instance somehow ..

Has anyone figured out what is happening?

**Comment by wiswedel** [comment]
Could you please try reproducing once again with
- Server 16.0.5
- Group Folder 4.1.3
- Desktop client 2.6.0

**Comment by gvansanden** [comment]
@wiswedel I had the issue on that combination (now rolled back)

**Comment by wiswedel** [comment]
Alright. Reproduced it now also on
- Server 16.0.5
- Group Folders 4.1.3
- Desktop client 2.6.0 (and 2.6.1 RC1)

and also on 

- Server 17.0.0
- Group Folders 5.0.3
- Desktop client 2.6.0 (and 2.6.1 RC1)


Extra info: once _any_ change is made to a normal folder on the server (or another connected client), the group folder sync gets triggered also - but not if changes on the server have been made within a group folder only.

**Comment by rullzer** [comment]
Sounds like somehow somewhere an etag is not propagated.

**Comment by Thoro** [comment]
I have setup a testing instance now, but I have the same issue with 16.0.5 and 4.0.5. Possibly the issue is different from the other guys.

For me the local sync NEVER happens, even if I Force Sync. Only when I uncheck and recheck in the client it will sync.

It's a multiple times nested groupfolder, I assume this might be the issue.

It's 5x nested.

**Comment by TP75** [comment]
Have a look at:

[NC 2.6.0 client shows an unstable GUI window on Mac OS X after first config
#1501 ](https://github.com/nextcloud/desktop/issues/1501#issuecomment-544021694)

> Hey,
> 
> we've just released 2.6.1 RC1 which is built with Qt 5.12.5 on all platforms (also has OpenSSL 1.1.1d, so it features TLS 1.3).
> 
> You may give it a try:
> https://github.com/nextcloud/desktop/releases/tag/v2.6.1-rc1

Maybe the task of improving the RC1+ relates to the above?

**Comment by TP75** [comment]
> It's a multiple times nested groupfolder, I assume this might be the issue.

Please clarify the technical nature of "a multiple times nested groupfolder" if possible.

**Comment by Thoro** [comment]
@TP75 The group folder mountpoints are nested i.e.

each line represents one group folder:

/Level1
/Level1/Level2
/Level1/Level2/Level3
/Level1/Level2/Level3/Level4
/Level1/Level2/Level3/Level4/Level5

**Comment by patricksebastien** [comment]
@Thoro Are you using advanced permission?

**Comment by Thoro** [comment]
@patricksebastien not yet, plain old group folders

**Comment by rullzer** [comment]
So, I think we found it. #647 fixes this. (it causes https://github.com/nextcloud/groupfolders/issues/648 again but we have to find another way to fix it then).

We'll release a new patch release soon.

**Comment by juliushaertl** [comment]
Fix release with 4.1.4 and 5.0.4

**Comment by TP75** [comment]
> on my system i have sync issues with groupfolders , too...

@Patrock - Presumably you should file a new bug report i.e. **new issue** for this if you a.m. problem persists.
