### ISSUE TITLE
Group names are truncated - cannot see full name

### ISSUE THREAD

**Issue by miketranagfa** [nextcloud/groupfolders#599]
The permission toggle icons block the group names and there is no way to see the full name.  Is there any way around this? I can't shorten the group names because they are active directory groups with predetermined nomenclature

![image](https://user-images.githubusercontent.com/55154785/64634495-5e929f80-d3cb-11e9-96f5-c937160a9643.png)

**Comment by miketranagfa** [comment]
is there any possible workarounds?

**Comment by ischiros** [comment]
I confirm it's a problem, and even more with my 13'' screen.
Cf attached file : I see only the 5 first letters of each group with permissions. As I have several groups beginning with the same word, it make it impossible to know who has which permissions.

There is a convenient buble-style information on each option (read, write,...). Perhaps we could have the same on the group/user ?
![Capture d’écran 2019-12-29 à 15 00 21](https://user-images.githubusercontent.com/1273505/71557847-2c757e00-2a4c-11ea-8865-376dd2504347.png)

**Comment by pierreozoux** [comment]
I tried to reproduce but the ui has changed since.

And the mouse hover should work.

Feel free to reopen.

**Comment by ischiros** [comment]
Hello,

There is no change for me. The problem is still here.
The mouse hover doesn't give any information either.
Tested with a screen 1440 px wide.
I use Nextcloud v20.0.8

**Comment by ischiros** [comment]
And I don't know how to re-open the ticket.
I don't see ant option for that.

**Comment by pierreozoux** [comment]
Ill keep this one closed as it is a duplicate of

https://github.com/nextcloud/groupfolders/issues/938

**Comment by ischiros** [comment]
Ok, makes sense.
