### ISSUE TITLE
Desktop Client synchronization is not working

### ISSUE THREAD

**Issue by jkoopmann** [nextcloud/groupfolders#60]
Hi,

when I put a new file in a locally synched folder I get synchronization errors:

server replied: Internal Server Error (path needs to be relative to the system wide data folder and point to a user specific file)

Regards,
   JP

**Comment by julienlusson** [comment]
Same for me, but the files are in fact correctly sync with the server, but the client (Mac) keeps uploading the files again and again.

**Comment by joergmschulz** [comment]
upgrading to the new client helped in my case.

**Comment by putt1ck** [comment]
@jkoopmann can you confirm if your group folders are contained in an encrypted file system?

**Comment by jkoopmann** [comment]
Hi,

encryption is enabled but only for „external storage“. So all files on the server itself should be in an unencrypted file system.


Regards,
   JP

On 09.10.17 | KW41, 08:52  "Chris Puttick" <notifications@github.com<mailto:notifications@github.com>> wrote:


@jkoopmann<https://github.com/jkoopmann> can you confirm if your group folders are contained in an encrypted file system?

**Comment by Luto73** [comment]
Same issue here. Server side encryption is enabled. Although I can see that the file is uploaded to the server it does not show up in the web interface.

**Comment by jpantall** [comment]
Experiencing same issue here with Nextcloud Server version 12.0. Server-side encryption has been turned off. I was wondering if a fix has been published for this that I'm not aware of.

Thanks!

**Comment by icewind1991** [comment]
Using groupfolders with encryption is not supported.

The upcoming groupfolders release that will come with NC15 will properly disable encryption for group folders.

If you're experiencing this issue without using server side encryption then please open a new ticket for that.
