### ISSUE TITLE
NC 16.0.5: Error: Exception: Could not extract app groupfolders

### ISSUE THREAD

**Issue by IoanMihaila** [nextcloud/groupfolders#617]
Hello,

Just updated to NC 16.0.5 and on update of GroupFolders from 4.1.0 to 4.1.1 error is encountered.

`[core] Error: Exception: Could not extract app groupfolders at <<closure>>

0. /home2/r59250smar/cloud/lib/private/Installer.php line 178
   OC\Installer->downloadApp("*** sensitive parameter replaced ***")
1. /home2/r59250smar/cloud/settings/Controller/AppSettingsController.php line 532
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /home2/r59250smar/cloud/lib/private/AppFramework/Http/Dispatcher.php line 166
   OC\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
3. /home2/r59250smar/cloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Cont ... {}, "updateApp")
4. /home2/r59250smar/cloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "updateApp")
5. /home2/r59250smar/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Settings\\C ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({appId: "*** sen ... "})
7. /home2/r59250smar/cloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {appId: "*** sen ... "})
8. /home2/r59250smar/cloud/lib/base.php line 975
   OC\Route\Router->match("/settings/apps/update/groupfolders")
9. /home2/r59250smar/cloud/index.php line 42
   OC::handleRequest()

GET /index.php/settings/apps/update/groupfolders
from <<PUBLIC_IP>> by <<USERNAME>> at 2019-09-27T11:11:38+00:00`

**Comment by fschrempf** [comment]
@IoanMihaila If you still see this issue with the latest release, please open a new issue, as I will close this one as stale.
