### ISSUE TITLE
Group folder with name "/" (Slash) causing error

### ISSUE THREAD

**Issue by tobiasquinteiro** [nextcloud/groupfolders#618]
Dear,

After update version to 4.1.x when Group Folder with name "/" (Slash) is causing general error on system navigation. Until version 4.0.x was working perfectly, being a great option to organize root folder.

![Screenshot at 2019-09-30 12-28-26](https://user-images.githubusercontent.com/740513/65893381-3f5db100-e37e-11e9-848b-cb20364d3c37.png)
![Screenshot at 2019-09-30 12-28-17](https://user-images.githubusercontent.com/740513/65893391-42f13800-e37e-11e9-9bab-4bf93e990f6d.png)

**Comment by pierreozoux** [comment]
I think the fix would be to disable such a name.

**Comment by icewind1991** [comment]
Can't reproduce this issue with the latest version.

**Comment by fschrempf** [comment]
> Can't reproduce this issue with the latest version.

I also can't reproduce any error when having a groupfolder with the name "/", but it seems like it causes the groupfolder to be mounted as the users root and any normal directories and files of the user will not be visible anymore. There might be also other issues with this. Would it make sense to prevent this?

**Comment by fschrempf** [comment]
With https://github.com/nextcloud/groupfolders/issues/310#issuecomment-802933219 it is clear that this should work in general and as the described issue is not visible in the current version I will close this as stale. Please open an new issue if the problem persists.
