### ISSUE TITLE
Group folder name not shown for deleted files in trash

### ISSUE THREAD

**Issue by strzinek** [nextcloud/groupfolders#619]
Any file or folder in trash, which was deleted from group folder, does not show its original group folder name in tooltip. User is unable to distinguish between files with same names when each one came from different group folder.

Expected behavior: show tooltip with group name and full path for deleted files originated from group folders.

Tested versions:
groupfolders 4.1.1, 4.1.2
nextcloud 16.0.4, 16.0.5

**Comment by pierreozoux** [comment]
In Nc 17, I could see the path when I hover.

Ill close this.
