### ISSUE TITLE
Feature Request: Group Folder location

### ISSUE THREAD

**Issue by bodangren** [nextcloud/groupfolders#62]
I'd really like to set the group folder location to some external storage. Right now, it seems set in the data folder.

**Comment by dan-nkl** [comment]
#47

**Comment by Hanzei** [comment]
Its not a duplicate. #47 requests to move the folder inside nextcloud. This feature requests to move the data location.

**Comment by icewind1991** [comment]
If you're working with external storages already than it's probably easier to just configure the external storage to be available to the groups

**Comment by putt1ck** [comment]
In Linux/Unix this is easily done by mounting the group folder root (./data/__groupfolders/) from external storage. Unless you mean you want group folders to be located outside NC as such, i.e. on existing smb/cifs storage? I think that'd make a bit of mess of permissions though.

Be interested to know the use case for either of these approaches to group folders.

**Comment by buildingawesomethings** [comment]
Some other approach might be to just move the data folder to the external storage

**Comment by bodangren** [comment]
@putt1ck @buildingawesomethings  Nextcloud doesn't really allow migration of data manually AFAICT. I tried a method similar to what putt1ck recommended for my company's NC data (copying the data directory to network storage, then mounting in  the same place), and Nextcloud errored and reset metadata for all files to nothing. I had to undo and restore the DB from backup.

**Comment by putt1ck** [comment]
That has to be a permissions issue - we use this method all the time, either with iscsi to the VM or with the VM mounting the storage as a second volume from the host. We do this either with the default data directory location or by modifying the config to use another location.

NB to change location of just the group folders root would need some hacking, so as per the original issue, this would need to be a mount.

**Comment by tr-ageev** [comment]
My "/var/www/nextcloud/data" folder and of course "__groupfolders" inside her is mounted nfs share from FreeNas server and it's works fine.
