### ISSUE TITLE
Groupfolders 4.1.3 breaks shared folder sync

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/groupfolders#627]
I initially reported the bug on Nextcloud server, but it started after I update groupfolders from 4.1.0 to 4.1.3.

Any folder shared with you is not synced any more unless you force the sync in the client or wait for the 2 hour forced sync window.  This doesn't only affect groupfolders but any folder shared by another user with you.  It does not affect your own folders.

There are no errors in the logs, not on the server and not in debug mode on the client.

**Comment by hriekehof** [comment]
Sounds related to #597

**Comment by wiswedel** [comment]
closing as duplicate
