### ISSUE TITLE
Work around desktop client issue #597

### ISSUE THREAD

**Issue by biva** [nextcloud/groupfolders#643]
I'm creating a new issue to avoid polluting #597 

@gvansanden wrote in https://github.com/nextcloud/groupfolders/issues/597#issuecomment-541097782
> 
> 
> @patricksebastien I agree, but it causes so many issues. Activities are broken on GF, putting items in trash locks up clients often as they still have a reference to a file they can no longer access. I'm sharing folders from a meta user for now.

Hello @gvansanden What do you mean sharing files from a meta user? How do you manage the permissions in subfolders? For example, how do you manage to share a parent folder with read access for everybody, and some subfolders in write access for some users?

**Comment by pierreozoux** [comment]
original issue isfixed, I'll close this one.
