### ISSUE TITLE
Groupfolders not synced automatically

### ISSUE THREAD

**Issue by MaasRob** [nextcloud/groupfolders#653]
In Win 10 nextcloud client, group folders are recognized as external storage and not synced automatically. User needs to choose and sync manually. Is it possible to bind group folders at least on the same nextcloud server not as external storage? Thanks

**Comment by wiswedel** [comment]
You can disable the confirmation necessity in the client. Specifically disablig it for group folders only (or even only for specific group folders) is not possible.
