### ISSUE TITLE
Difference in permissions between normal shares and group folder shares is undocumented

### ISSUE THREAD

**Issue by dirks** [nextcloud/groupfolders#654]
When a user shares a normal folder she can set the following permissions:
- Can edit
- Can create
- Can change
- Can delete

If a user shares a group folder with other users the available permission are:
- Can edit
- Can create

While "Can edit" seems to be some kind of umbrella permission, the effective permissions between the two scenarios are different. If one of "the other users" tries to modify a file she is not able to do so. She can create a new file, but again not modify it.

I do not think the behavior is necessarily a bug, but it should at least be documented.

This was observed with
- Nextcloud 16.0.5
- Group folders 4.1.4
- Ubuntu 18.04
- PHP 7.2

**Comment by fschrempf** [comment]
With latest master I don't see the reduced sharing options fro groupfolders. It seems like this has been fixed. Please open a new issue if the issue still persists. Thanks!
