### ISSUE TITLE
Need help with file owning 

### ISSUE THREAD

**Issue by dEROZA** [nextcloud/groupfolders#656]
I use “Group folders app” and all users can delete the files in shared directory. I need to break access for the files deleting operation for non owner users. thx.

**Comment by wiswedel** [comment]
@dEROZA 
Just put the no-delete-users into a special group and disallow deletion via ACLs from the highest necessary hierarchy level: https://github.com/nextcloud/groupfolders#advanced-permissions

**Comment by dEROZA** [comment]
> @dEROZA
> Just put the no-delete-users into a special group and disallow deletion via ACLs from the highest necessary hierarchy level: https://github.com/nextcloud/groupfolders#advanced-permissions

I wanna allow to delete only own files for users, your method allow delete all files.

GroupA: can write and delete
But user1 from GroupA can delete only own files..

**Comment by wiswedel** [comment]
There are no "own" files in group folders - they all get their permissions from the group folders logic.

**Comment by dEROZA** [comment]
> There are no "own" files in group folders - they all get their permissions from the group folders logic.

can you help me with logic modify? tell which file responds when user tried to delete the file from group folder?

**Comment by wiswedel** [comment]
I'm afraid I don't get the question!?
Can you please rephrase what you mean by _which file responds when user tried to delete the file_?

**Comment by dEROZA** [comment]
which class defines delete operation? in core, or in groupfolders app..

**Comment by wiswedel** [comment]
sorry, don't know that

**Comment by dEROZA** [comment]
ok, thx a lot.
