### ISSUE TITLE
Groupfolders with subfolders get non-visible after setting Advanced Permission

### ISSUE THREAD

**Issue by rollanders** [nextcloud/groupfolders#664]
Some groupfolder become invisible in the files-app after ticking adavnced permissions. It seems that this apply to folders that already have subfolders. 

1. Create a Groupfolder
2. Create subfolders in this folder
3. Tick advanced permissions for the Groupfolder
4. The group folder is not visible in the files app. 
5. It becomes visible again if advanced permissions are unticked.

**Comment by wiswedel** [comment]
@rollanders do you have any file access control rules configured?

**Comment by fschrempf** [comment]
@rollanders Can you still reproduce this issue with a recent version of NC and groupfolders app? If yes please provide more details, otherwise I will close this as stale soon. Thanks!

**Comment by fschrempf** [comment]
Closing as stale. Please reopen, comment or create a new issue if necessary. Thanks!
