### ISSUE TITLE
Preview in shared group folder not working

### ISSUE THREAD

**Issue by santhrax** [nextcloud/groupfolders#67]
when group folder is shared via link user can access it and download the files but it is not possible to run the preview for photos

Error! Could not generate a preview of this file.

preview in "normal" shared folder working fine

**Comment by icewind1991** [comment]
I can't reproduce this issue, previews show as expected when link-sharing a group folder

**Comment by svenb1234** [comment]
Can this issue be be closed?

**Comment by ZeikoFr** [comment]
@juliushaertl We can close this one imo
