### ISSUE TITLE
Can’t favorite file on mobile client (iOS)

### ISSUE THREAD

**Issue by gerardjm** [nextcloud/groupfolders#674]
Hi, I get error 500 on IOS app when add file to favorites, disabling “Group Folders” make Favorites on iOS-Client work.

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/groupfolders/pull/665

**Comment by fschrempf** [comment]
This looks like it was fixes. I will close this as stale. Pleas open a new issue if you are still seeing this with the latest releases.
