### ISSUE TITLE
Can't find all Users in advances permissions

### ISSUE THREAD

**Issue by p-klassen** [nextcloud/groupfolders#675]
Nextcloud Version: 17.0.1 (Update-Chanel: stable)
Groupfolder Version: 5.0.4

Issue:
Cant find all Users when choosing Users/Groups with advance permission on group foldert in the admin menu. Same issue when setting advanced permission rules on group folders.

Example:
Let's say I have a Group called "GroupA", with 20 Users or something.
This Group is assigned to the Groupfolder "GroupA_Folder".
All User can see and use the new Groupfolder, but now comes the problem I face:
When I want to set advances permission on a groupfolder itself (like I want give permission to another group too, or deny permission to specific users), I can only choose one Group (GroupA) and only like 10 Users of this Group. I can't choose any other Group or any other Users (no matter if they are member of GroupA or not). When trying to type the Name of a not shown User, I get this Error Message:

No elements found. Consider Changing the Search Query.

It seems like I can only search for the "username" (which is the EntryUUID of our LDAP) but not for the display name (which is the user cn in our LDAP).

How to fix this?

**Comment by Bea-94** [comment]
I have the same issue, anyone can help? Thanks

**Comment by gasparakos** [comment]
We have same problem as @p-klassen . Our groups and users come from LDAP, system is: NC 19.0.4. Group Folders: 7.1.1
We have one group as 'Groups' for Folder. In 'Advanced Permissions' input field only the group name and first 10 user is listed in drop down. Only the group name can filtered.

**Comment by pierreozoux** [comment]
Do your ldap user have special chars in their name?

**Comment by patricksebastien** [comment]
I also have this issue (at least from NC 18). Now using NC 20 with GF 8.0.2. Some users are found when searching (I am not using LDAP, just basic user in NC), but most of them are not displaying (No elements found. Consider changing the search query.).

**Comment by fschrempf** [comment]
Probably related issue: #1446.

Can someone still reproduce this with a supported version (>=21)? Otherwise I will close this as stale soon. Thanks!

**Comment by fschrempf** [comment]
Closing this as stale. Please comment, reopen or create a new issue if you think this problem still exists. Thanks!
