### ISSUE TITLE
Unable to copy shared URL with iOS app

### ISSUE THREAD

**Issue by Bables55** [nextcloud/groupfolders#682]
When we try to issue a shared URL for a file or folder in Groupforlder, we cannot issue it with a 404 error by Nextcloud app on iOS devices. We don't have any problems outside of Groupfolder or normal web browsers(iOS).

---
Nextcloud 17.0.1, GroupFolder 5.0.4, CentOS 7.7, nginx 1.14.1

**Comment by fschrempf** [comment]
@Bables55 Do you still see this issue with the latest release?

**Comment by fschrempf** [comment]
I'm closing this as stale due to lack of information. Please create a new issue if this problem persists. Thanks!
