### ISSUE TITLE
Black icon for groupfolder in firefox

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/groupfolders#684]
Expected: group folder icon has same color as other folders

Actual result: group folder has black color.

Nextcloud: 17.0.1
Groupfolders: 5.0.4
Firefox 70.0.1 9 (windows and linux)

Other browsers have expected color:
Chromium 78.0.3904.108 on linux
Edge 78.0.3904.108 on windows

**Comment by rian-mcmillan** [comment]
Same problem here.
Groupfolders don't respect theming settings on firefox since last update of nextcloud / groupfolders.

Checked on Chromium on linux after reading this issue, where they indeed have the correct color.

**Comment by rian-mcmillan** [comment]
Workaround: Set the color in theme settings again, then the icons have the themed color.

**Comment by fschrempf** [comment]
I don't think this is still a problem, right? In my case the icons in Firefox have the correct color. Does anybody still see this issue with the latest release?

**Comment by fschrempf** [comment]
I'm closing this as stale. Please open a new issue if this problem persists. Thanks!

**Comment by mjanssens** [comment]
@fschrempf, indeed no need to keep the issue open, haven't seen this issue anymore, thanks for closing it.
