### ISSUE TITLE
Desktop client sync breaks when moving shares to group folder 

### ISSUE THREAD

**Issue by fcmildef** [nextcloud/groupfolders#693]
We are experiencing a problem and suspect is has to do with group folders. 
I am trying to be as specific as possible but I am not entireley sure what my users are doing ;)

User A has a bunch of folders that are shared with user B
A group folder is introduced as a replacement for all these shares, both user A and B are a member of it. 
User A starts re organizing stuff and moving the old shares to the group folder, sometimes renaming the folders, sometimes removing a folder and moving its contents to another folder in the group folder.
All of a sudden the desktop sync client of user B doesnt synchronise anymore and starts throwing errors like:
[OCC::DiscoverySingleDirectoryJob::directoryListingIteratedSlot 	Missing properties: "testfolder" 2 0 1542103459 "DNVS" "" "-0000001ocrvl2k5jw23"
where  testfolder is one of the original shares that now dont exist anymore but are in the group folder.
some of the original folders that have been moved into the group folder still exist in user A`s trash, that seems to be a problem for the group folder, once they are permantly removed, they dont show up as errors for the client.  < that seems like a bug to me
some of the folders are nowhere to be found, except in the database of nextcloud. So far the only sollution I have found for them is manually removing them from the database. 

Please let me know if I can provide any more information to try to resolve this

related issues reports: https://github.com/nextcloud/desktop/issues/819

**Comment by beedaddy** [comment]
@fcmildef Can you tell if the problem still exists? We have now also group folders introduced and I would like to know whether it is "save" to move shared foldes into an group folder.

**Comment by sveken** [comment]
This is still broken
When i add users to a group that has a folder shared too it, all the sync clients break with 500 internal server error PROPFIND
As soon as i deleted the group the sync client went green

**Comment by jospoortvliet** [comment]
The client side issue was closed as fixed - I assume this is then also fixed? @sveken can you still reproduce this?

**Comment by sveken** [comment]
> The client side issue was closed as fixed - I assume this is then also fixed? [@sveken](https://github.com/sveken) can you still reproduce this?

Sorry i do not use this feature anymore, and its been so long i have no idea what it was.
