### ISSUE TITLE
File Versions do not work properly in groupfolders

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/groupfolders#694]
Hi there,

at the moment i cannot get file versions to work properly for files in groupfolders. In normal none shared personal folders it seems to work.

I use an excel sheet for testing.
1. Put an excel sheet into a groupfolder
2. Sync it via desktop client.
3. Save a second version and sync it via desktop client
4. Restore the previous version in Nextclouds web interface
5. Open excel sheet on desktop synced via desktop app. Its not changed to the previous version

Current Installation:
- Nextcloud 16.0.6 as docker container apache
- Groupfolder App 4.1.4
- Used Browser: Latest Chrome
- Desktop Client: 2.6.1
- Windows 10 Pro latest updates

I really would like if versions would start to work in groupfolders since we use them alot in our installation. 

What is also strange that whenever i hit the versions button a new version seems to be created in the list of versions
![image](https://user-images.githubusercontent.com/9348635/70708201-42f4a900-1cda-11ea-8871-532a1121fc71.png)

I would expect when restoring a previous versions that the list just gets reordered.

**Comment by wiswedel** [comment]
@hriekehof what desktop app version are you using?

**Comment by wiswedel** [comment]
confirmed on NC 17.0.1 with client 2.6.1 (Linux)

**Comment by hriekehof** [comment]
hi i updated the comment i saw i had a mistake there :) I use Nextcloud on Win 10 Pro and i have the desktop client 2.6.1

**Comment by wiswedel** [comment]
CC @nextcloud/server-triage

**Comment by nickvergessen** [comment]
cc @icewind1991 

Although I think I remember versions being a topic for 18 only?

**Comment by alexanderdd** [comment]
Does anybody know if versions work properly with group folders?

I need to migrate all of our folders to group folders, but if versions don't work, I won't migrate.

**Comment by acsfer** [comment]
@alexanderdd it seems it does'nt as per https://github.com/nextcloud/groupfolders/issues/694

**Comment by CarlSchwan** [comment]
#1660 should have fixed some issues with rolling back versions. This has been backported to 20, 21 and 22. I'm gonna close this issue but feel free to reopen if the problem persists.
