### ISSUE TITLE
"Can't create file"

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/groupfolders#697]
In two different instances of Nextcloud on different servers I can't create files in group folders. 

I create a group folder for a certain group. I can create folders in it. But when I try to create or upload a file, it fails. I figured out, that when I try to create the same file again, I can't do that, because it already exists. When I reload the folder, it even shows up and I can edit it. 

Wenn I only create it once and reload, the file doesn't show up.

**Comment by AstroGD** [comment]
Same issue here. Uploading once doesn't work but uploading twice (or sometimes even three times) shows the "file does already exist"-dialog and after that the file becomes visible

**Comment by eriteric** [comment]
Same here. 

- Nextcloud 18.0.2
- Group Folder 6.0.3
- MySQL 10.4.12
- PHP 7.3.15
- Versions 1.11.0 enabled
- Default Encryption Module 2.6.0 enabled

In the web interface within a group folder will either get:
A) "Can't create file"
or
B) after creating a file and trying to rename it then get "can't rename" and/or "file already exists". Then when i refresh there are two files with the same contents, one with the old name and one with the new one. Then i have to manually delete the old one.

When trying to delete a file I get a similar error "can't delete", then if i try again it usually works.

The desktop sync app also has similar issues with these group folders (will fail to sync at first, then keep retrying and eventually sync, resulting in a lot of error output)

**Comment by pierreozoux** [comment]
encryption is indeed not supported.

This issue reminds me another one with s3 that also got fixed.

I'll close it. But if it is still unsolved, don't hesitate to comment or reopen.
