### ISSUE TITLE
Can't open OnlyOffice file in read-only mode: file not found

### ISSUE THREAD

**Issue by t-markmann** [nextcloud/groupfolders#698]
I am referencing this report in the community board: https://help.nextcloud.com/t/onlyoffice-and-groupe-folder-permissions-error-files-not-found-41676/62328

If you set an ACL to read-only mode for a group/user, this users account can not open the shared document in OnlyOffice (expected: read-only mode). 
As soon as I give write permission to this user/group, OnlyOffice can open it.

**Comment by joshtrichards** [comment]
Are you still experiencing this?

**Comment by provokateurin** [comment]
Closing for now. If this is still relevant please open an issue at https://github.com/nextcloud/officeonline instead as this is an issue with OnlyOffice and not Groupfolders.
