### ISSUE TITLE
Activity Feed for Groupfolders not working

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/groupfolders#699]
Hi there,

i'm using Nextcloud 16.0.6 with latest groupfolder App. I the activity feed for the groupfolders is not working. So i don't see who uploaded deleted or changes which files.
I only see the changes i made myself. 

Is there a way to activate this ? Or is it just not working ?

**Comment by wiswedel** [comment]
duplicate of https://github.com/nextcloud/activity/issues/264

**Comment by hriekehof** [comment]
sorry i don't understand how nextcloud/activity#264 really solves this issue ? Do i have to do this manual sql trick in the last comment ?

**Comment by wiswedel** [comment]
@hriekehof That issue is not a fix, but describes the same problem. Fix is still to be done.

**Comment by hriekehof** [comment]
ah sorry sometimes i'm still a github noob :) I thought the 264 is closed already but the its the link to this ticket which is closed.
