### ISSUE TITLE
Can't see activity of other users

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/groupfolders#70]
Am on NC12.03 with GF1.1 - 

this is how I see a file created by a user in a GF under an admin account.

https://i.imgur.com/No4D9Bg.png

VS regular shared folder with a group

https://i.imgur.com/Cw2Xoiz.png - this is how I imagine the GF activity log should look like, but it doesn't

**Comment by putt1ck** [comment]
Can see how you might not want to have the activity visible to all, but should be an option, maybe in permissions per group folder/group.

**Comment by icewind1991** [comment]
This is a problem with the activities app, there is an open PR for it here: https://github.com/nextcloud/activity/pull/190

**Comment by putt1ck** [comment]
FYI the files locks inside group folders issue has been fixed in a forked/patched, soon to be available W2G2 app (with other fixes/enhancements).

**Comment by putt1ck** [comment]
App now in store:

https://apps.nextcloud.com/apps/w2g2
