### ISSUE TITLE
occ groupfolder:group - how to format permissions 

### ISSUE THREAD

**Issue by deusoz** [nextcloud/groupfolders#706]
How to give full permissions to a group while adding to a groupfolder with occ?

HELP DOCS say
"Usage:
  groupfolders:group [options] [--]  <folder_id> <group> [  <permissions>...  ]

Arguments:
  folder_id              Id of the folder to configure
  group                  The group to configure
  permissions            The permissions to set for the group, leave empty for read only"

BUT, what to put in the "permissions" slot ? see below, I want ALL permissions turned on as i add the group to the groupfolder but cannot figure out how to format parsable permissions here. 

[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 "['+write']"
Unable to parse permissions input: ['+write']
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 "[+write]"
Unable to parse permissions input: [+write]
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 "+write"
Unable to parse permissions input: +write
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 [31]
Unable to parse permissions input: [31]
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 ALL
Unable to parse permissions input: ALL
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 all
Unable to parse permissions input: all
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 ['all']
Unable to parse permissions input: [all]
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 ['share']
Unable to parse permissions input: [share]
[root@aho ~]# sudo -u apache php /var/www/html/occ groupfolders:group 52 t1 PERMISSION_CREATE
Unable to parse permissions input: PERMISSION_CREATE

and tried many other obvious choices (+delete, +share, +create, etc. that are listed in docs) before asking for help.

**Comment by deusoz** [comment]
then I notice otherwise, I went in and enabled "Advanced permissions" via admin in Nextcloud.  But no matter who I give permissions to this way they do not propagate as that user or member of group given ability to write, edit, etc. files

**Comment by deusoz** [comment]
![image](https://user-images.githubusercontent.com/3331362/71222374-a0878780-22d0-11ea-8a09-7fb8855aa87e.png)

**Comment by deusoz** [comment]
Now to be clear, I created these users and the group folder via occ but eveything looks fine as far as I can tell that should prevent them from gaining permissions.

**Comment by Dubidubiduu** [comment]
For me it's just ./occ groupfolders:group 25 Aktiv_80 write

**Comment by Ninjiner** [comment]
Yeah @Dubidubiduu is correct.
Write the permissions as words and use spaces in between.
Example:
`occ groupfolders:group 1 my-awesome-group write delete`
