### ISSUE TITLE
Error msg when uploading

### ISSUE THREAD

**Issue by codde81123** [nextcloud/groupfolders#71]
Hi,

I've created a group folder and wanted to upload some files.
For each file I get the note "internal server error"
In the log I can see: "path needs to be relative to the system wide data folder and point to a user specific file"
The file is not visible but when I try to upload the same file I get the prompt "file already exists".

Any idea?

**Comment by Luto73** [comment]
I had the same issue with encryption enabled. After I disabled the NC encryption module everything works again. There is already an issue about this problem, I am using my mobile that‘s why I can‘t search for it right now.

**Comment by putt1ck** [comment]
@codde81123 can you confirm you are uploading with encryption enabled?

**Comment by MadDud** [comment]
The same issue.

> Fatal | webdav | Sabre\DAV\Exception: path needs to be relative to the system wide data folder and point to a user specific file | 2017-11-14T23:06:07+0100

Nextcloud - 12.0.3
Default encryption module - 1.6.0
Group folders -1.1.0

Server-side encryption - enabled
encrypt home storage - enabled

**Comment by putt1ck** [comment]
Group Folders doesn't support encryption. See #10

**Comment by icewind1991** [comment]
The upcoming groupfolders release that will come with NC15 will properly disable encryption for group folders.

**Comment by AndrewwHummer** [comment]
Is there a chance that there are still issues with server side encryption and group folders?

**Comment by scharel** [comment]
> 
> 
> Is there a chance that there are still issues with server side encryption and group folders?

I'm experiancing synchronization issues too, using NC 15.0.5:
`server replied:  (path needs to be relative to the system wide data folder and point to a user specific file)`

**Comment by wildcard418** [comment]
Same issue here. NC15.0.5, encryption enabled. Getting massive sync errors with shared group folders.

**Comment by 1aTa** [comment]
Same here with v15 and the newly released v16.

If I attempt to upload the same file(s) again, opt to keep the existing file(s) and refresh the page, the file(s) appear and are fully usable.

Nextcloud - v16.0.0
Default encryption module - v2.4.0
Group folders - v.3.0.0

Server-side encryption - Enabled
Encrypt home storage - Enabled

**Comment by reavessm** [comment]
I'm having same resolution as @1aTa , uploading the file once fails, uploading the second time fails.  Should this be reopened until the file uploads in one go?

**Comment by ukrainer8** [comment]
The same problem. Reported here https://github.com/nextcloud/server/issues/14988

**Comment by phonon112358** [comment]
same issue on NC18

**Comment by Boki4d** [comment]
I have the same issue with NC18 after the latest Groupfolders-Update...
"path needs to be relative to the system wide data folder and point to a user specific file"

Any Idea how this can be resolved?

**Comment by michaeldegroot** [comment]
issue from 2017 and still currently present, what is going on

**Comment by Boki4d** [comment]
> issue from 2017 and still currently present, what is going on
Disabling the encryption of the home folders solved the problem for me. There still seems to be an issue with group folders in combination with encryption. This is not a high priority issue, but I can only speak for myself.
