### ISSUE TITLE
finish occ documentation

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/groupfolders#719]
Most of the available occ commands for group folders are yet to be documented:

![image](https://user-images.githubusercontent.com/1804221/71347475-c4fe9080-256a-11ea-9e1f-79a9adc4d96b.png)

**Comment by wiswedel** [comment]
related: https://github.com/nextcloud/groupfolders/issues/706

**Comment by deusoz** [comment]
bravo!, and please tell me how to send in group permissions as in related #706 whenever someone has the time, thanks, happy holidays!
