### ISSUE TITLE
Folder based sync settings

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/groupfolders#727]
A folder based sync setting for desktop client would be a big win. This means a setting in groupfolders, example:
- regular
- optional (folder sync isn't activated by default, but user can activate it)
- no (folder isn't synced and user has no option to change that)

My use case:
I've got big and also sensitive folder which shouldn't be synced by default. The folder size setting in the client app isn't a solution for me and creating a 2nd nextcloud instance and pair them (https://help.nextcloud.com/t/setting-certain-folders-or-shared-folders-to-not-sync/34490/3) isn't a solution neither.

**Comment by wiswedel** [comment]
@Dubidubiduu Have you tried File Access Control yet? All you have to do is put some tag on the non-syncable folder and create a File Access Control rule that forbids accessing objects with that tag from the user agent "Desktop Client".

**Comment by Dubidubiduu** [comment]
Completely missed that. Haven't got the optional switch with that, and also have to switch functionality by group membership but in the end that will work for me, thank you!

(While activating missed to calibrate to the specific folder, so my desktop client lost everything... 🌊 )
