### ISSUE TITLE
 Error Uploading to Group Folders system wide data folder and point to a user specific file

### ISSUE THREAD

**Issue by axheli** [nextcloud/groupfolders#728]
Getting below error when uploading to groupfolder.
NC 17.0.2
MYSQL DB 
PHP 7.2
Apache2
Sabre\DAV\Exception: path needs to be relative to the system wide data folder and point to a user specific file
![image](https://user-images.githubusercontent.com/59488153/71835565-7e835880-3077-11ea-8a00-e420b2cafa7c.png)

**Comment by TheBigWave** [comment]
do you have encryption enabled? 
I've got the same Problem and its probably caused by the encryption module?

**Comment by axheli** [comment]
yes i do have it enabled

**Comment by axheli** [comment]
#1031

**Comment by axheli** [comment]
[https://github.com/nextcloud/groupfolders/issues/1031](url)
