### ISSUE TITLE
Update failed 4.1.4 to 4.1.5: `Doctrine\DBAL\Exception\DriverException`

### ISSUE THREAD

**Issue by aPollO2k** [nextcloud/groupfolders#729]
I'm on Nextcloud 16.0.7 and Groupfolders 4.1.4. I tried to update to 4.1.5 with following message:

`www-data@nextcloud:~/nextcloud$ php7.2 occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are                                                                                                                                                                                                      available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <groupfolders> ...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER                                                                                                                                                                                                      TABLE oc_group_folders_trash ADD file_id BIGINT DEFAULT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; m                                                                                                                                                                                                     ax key length is 767 bytes
Update failed
Maintenance mode is kept active
Reset log level
`

Can i convert this to largeprefix?

**Comment by ghaberek** [comment]
I had the same problem. Per [this answer](https://stackoverflow.com/a/31474509/2300395) I altered the `name` column on `oc_group_folders_trash` from `VARCHAR(250)` to `VARCHAR(191)`.

**Comment by dugite-code** [comment]
This is the command I ran in mysql to fix this:

`ALTER TABLE oc_group_folders_trash CHANGE name name VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

**Comment by aPollO2k** [comment]
Thank you. This fixed it for me. Don't know what triggered this issue.

**Comment by patricksebastien** [comment]
Should I do the alter table before updating (what's the correct order)? Or maybe it's fixed? Will bump from 16.0.4 to 16.0.8 and groupfolder 4.1.4 to 4.1.5.

**Comment by aPollO2k** [comment]
I was needed to execute this before the update process.

**Comment by icewind1991** [comment]
What version of mysql/mariadb are you using?

What is the output of

```sql
SELECT TABLE_NAME, ENGINE FROM information_schema.TABLES where TABLE_NAME='oc_group_folders_trash';
```

The filecache contains a `name` field of the same with an index, so it's weird that that seems to work but the one in groupfolders doesn't

**Comment by joshtrichards** [comment]
Did any of you on this thread have a response to the prior comment? 

I'm gonna close this out as stale since it's been 3+ years without any further installation/environment details needed to isolate the root cause. 

Glad a workaround was found. We can reopen if new information arises.
