### ISSUE TITLE
folder icon in shared links not shown correctly

### ISSUE THREAD

**Issue by jones1008** [nextcloud/groupfolders#73]
**Steps to recreate:**
- create a group folder
- create some folders in it
- create a share link of a folder with some subfolders within that group folder

**problem:**
The folder icons are just grey document icons and not the folder icon as usual:
![image](https://user-images.githubusercontent.com/25104859/32689366-7578cd38-c6e3-11e7-8e7c-c5e996eabc47.png)

**Comment by patricksebastien** [comment]
I have this issue with groupfolder 7.1.0 and nextcloud 19.0.4
