### ISSUE TITLE
Interaction with NC18, Collabora, files_fulltextsearch and Group Folders

### ISSUE THREAD

**Issue by intellirat** [nextcloud/groupfolders#737]
Environment:
NC Docker image installed on QNAP NAS, with Collabora Docker image, all behind NGINX reverse proxy. All apps/packages/images at current version.
Collabora installed and active on NC17
Group folders installed and active on NC17

Steps to reproduce:
NC18 upgrade (from 17)
Collabora doesn't work after NC18 upgrade (no click on documents - they download instead)
Debug via logs / known issues (open & closed), and direct queries to collabora URL
Disable 'Group folders' (not remove), and all works again
Repeatable with toggling 'Group folders'

Thanks!

**Comment by intellirat** [comment]
Relevant links:
https://help.nextcloud.com/t/nextcloud-18-collabora-not-working-anymore/68655
https://github.com/nextcloud/richdocuments/issues/793

**Comment by intellirat** [comment]
But it could be a wider issue, as files_fulltextsearch is also having issues - disabling that, and having group folders active works.

**Comment by juliushaertl** [comment]
Doesn't seem groupfolder related. Please report this issue at the files_fulltextsearch app.
