### ISSUE TITLE
Access rights for users belonging to two groups

### ISSUE THREAD

**Issue by HarryK58** [nextcloud/groupfolders#74]
I have a user X who belongs to group A and group B.
I create a group folder and give group A write permission, and group B only read permissions.
User X can then access the folder only with the rights of group B (read only rights).
Why he does not get the access rights of group A (write permissions)?
(Nextcloud 12.0.3  Group folders 1.1.0)

**Comment by icewind1991** [comment]
Duplicate of https://github.com/nextcloud/groupfolders/issues/69
