### ISSUE TITLE
Additional permissions not applied

### ISSUE THREAD

**Issue by kort3x** [nextcloud/groupfolders#745]
Nextcloud: 18.0.0
Groupfolders: 6.0.1

When a user is granted addtional rights on a subfolder it does not get applied.
When a user is refused inhereted rights on a subfolder it does get applied.

What am I missing?

**Comment by kort3x** [comment]
related issues:
https://github.com/nextcloud/groupfolders/issues/746
https://github.com/nextcloud/groupfolders/issues/749

**Comment by ChrissW-R1** [comment]
Look exactly like our problem: #598

**Comment by putt1ck** [comment]
See my comment https://github.com/nextcloud/groupfolders/issues/746 (the fix probably quite easy, it's in the UI)

**Comment by Pytal** [comment]
Closing in favour of #655
