### ISSUE TITLE
can't set advanced permission on fresh install

### ISSUE THREAD

**Issue by etibamecus** [nextcloud/groupfolders#749]
Nextcloud Version : 18.0.0 freshly installed
Groupfolders Version : 6.0.1 freshly installed
OS : Centos 7
Web Server : Nginx
Database : postgresql 12
Php : 7.3.14

Steps to reproduce :

1 - install nextcloud 18, groupfolders, enable it, 
2 - create groupfolder, add groups, and give "admin" (user or group) advanced permissions rights
3 - open share tab of created folder
4 - no permissions can be set (advanced permissions is not visible)

expected behabvior :

Admin can see normal window to set advanced permissions to users or groups

additional information :

on a different nextcloud instance on same host with same specs, which was updated to nextcloud 18 from 17 and groupfolder 6.0.1 i don't have the problem.

I tried clearing cache of browser with no success.

**Comment by etibamecus** [comment]
Ok, 

this morning after the nightly cron jobs, (back up, restart php / nginx / postgresql, flush redis and some updates) it seems to be working...

very weird though...

**Comment by lars-becker** [comment]
I had the same problem and it wasn't Nextcloud, but uBlock Origin. Could it be your AdBlocker?

**Comment by lars-becker** [comment]
Dammit. At another folder the problem persists. Forgot the aforementioned comment.

**Comment by biva** [comment]
Thanks for the Firefox hint! I solved it by restarting Firefox with addons disabled (Menu, Help, ...). And then restarted Firefox with addons enabled. It works now. I can't say which addon was causing troubles :(

Also related:
https://github.com/nextcloud/groupfolders/issues/774#issuecomment-597696866

**Comment by cenix102** [comment]
Hi everyone, did someone find a solution. I still cant use group folders

**Comment by caguiar** [comment]
I have the same problem.
I am configured as the user who has permissions to manage the advanced permissions on a group folder.
If I logout of Nextcloud and login again, and go straight to the folder, advanced permissions is visible. After being logged on for a while (don't know how long, but a few minutes) if I go back and the advanced permissions is no longer there.
Logout -> login, and its back.

**Comment by fschrempf** [comment]
Also see #894

**Comment by juliushaertl** [comment]
Repoened https://github.com/nextcloud/groupfolders/issues/894 and closing this one as a dupliate
