### ISSUE TITLE
"The given object name is invalid" when trying to set password for an "email" user of a folder inside a group shared folder.

### ISSUE THREAD

**Issue by rennu** [nextcloud/groupfolders#75]
We have a company wide shared folder that is shared to a group A (company users). When a member of group A creates a folder inside the company wide folder, shares it to user@example.com and tries to set password for the user, the system gives out error: "The given object name is invalid". Is this intended behaviour or is it a bug? (The vagueness of the message leads me to believe it's a bug).

Event with the error, the system sends an email about the password, though.

Nextcloud version: 12.03.
OS: Ubuntu 16.04

Steps to reproduce:

Users:
USER1 member of GROUP1
USER2 member of GROUP1

1. Create a FOLDER1 using USER1 and share it to group GROUP1
2. Use USER2 to create a folder FOLDER2 inside FOLDER1
3. Use USER2 to share FOLDER2 to user@example.com
4. Use USER2 to set password for FOLDER2 to email user@example.com
5. "The given object name is invalid"

**Comment by icewind1991** [comment]
I'm fairly sure this is a core server issue and should be opened there
