### ISSUE TITLE
Cannot add Group Folders because of error "Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes" using utf8mb4 

### ISSUE THREAD

**Issue by dante1119** [nextcloud/groupfolders#751]
I've tryed  to add the "Group Folders" app , but it fails with error :
_An exception occurred while executing 'CREATE TABLE oc_group_folders_trash (trash_id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(250) NOT NULL, original_location VARCHAR(4000) NOT NULL, deleted_time BIGINT NOT NULL, folder_id BIGINT NOT NULL, INDEX groups_folder_trash_folder (folder_id), INDEX groups_folder_name (folder_id, name), UNIQUE INDEX groups_folder_trash_unique (folder_id, name, deleted_time), PRIMARY KEY(trash_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes_
I did try also a **sudo -u www-data php occ maintenance:repair** but it did'nt work.
Nextcloud 17.0.2
Ubuntu 18.04
MariaDB 10.1.43 
nginx/1.14.0
The PHP 7.2 FastCGI Process Manager

Any help ? 
thanku

**Comment by NATC-7051** [comment]
I have the same error, 

Nextcloud 18.0.0
Ubuntu 18.04
MariaDB 10.1.43

any help will be appreciated.

**Comment by NATC-7051** [comment]
Solved:
Group folders should be installed and enabled before enabling MySQL 4-byte support:

https://docs.nextcloud.com/server/12.0/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by conrad-mobilitas** [comment]
@kesselb Installing the addon before enabling 4byte support seems like a workaround, not a fix. The problem is still present on NC 19. Please re-open the issue.
