### ISSUE TITLE
Allow stop inheritance of permissions

### ISSUE THREAD

**Issue by janpekar** [nextcloud/groupfolders#752]
When I want to create subfolder inside GroupFolder I can only extend permissions. I don't see inherited permissions like mentioned in https://github.com/nextcloud/groupfolders/issues/724 and I cannot cancel this inheritance.
I can substitute this feature by creating GroupFolder inside existing GroupFolder. But it has disadvantages
- desktop sync is not working on subgroup folders - see https://github.com/nextcloud/desktop/issues/1773 and https://github.com/nextcloud/groupfolders/issues/652
- creating subGroupFolder sounds like workaround, GUI is not ready for that
- size of folder is not updated on parent folders, so quota is not applicable
- I need to administer it through NC settings and not easily through create folder and modify properties

My recommendation is to implement something what is known in NTFS world, where you can
- assign permission(s) only for current folder and don't inherit it to subfolders
- stop inheriting permissions from parent on particular folder and create permissions from the scratch on that folder (it is important to keep the way to assign permissions when no permissions are inherited)

Both of above options can solve many problems, only one can be implemented.

**Comment by fschrempf** [comment]
I think what you want is possible without disabling inheritance. It's maybe not as straight-forward as it should be, but what about the workflow described here: https://github.com/nextcloud/groupfolders/issues/655#issuecomment-960823463. Does that solve your problem?

**Comment by provokateurin** [comment]
All of the problems/drawbacks of having nested Groupfolders have been fixed, so I think we have a solution for this.
