### ISSUE TITLE
Root of group folders

### ISSUE THREAD

**Issue by sodiumchl** [nextcloud/groupfolders#757]
Is it possible to to have the group folders created in this app appear in users' /Group_Folder/ instead of / ?

**Comment by sodiumchl** [comment]
It seems the following change works:
MountProvider.php:91:  '/' . $user->getUID() . '/files/Group Folders/' . $folder['mount_point'],
But /Group Folders have to be created for all users first.

**Comment by fschrempf** [comment]
It seems like you want to have the groupfolders content not in the users root file view, but in a separate subdir/view. So it seems like this is a duplicate of #139. If I got this wrong, please let me know and I will reopen.
