### ISSUE TITLE
Feature Request: Don't show sharing user's name to public

### ISSUE THREAD

**Issue by spackmat** [nextcloud/groupfolders#758]
We use the groupfolders to share files of our team to the public. But the public frontend shows the name of the user that cerated the share:

![screenshot-share-from-group-folder](https://user-images.githubusercontent.com/185854/74222791-8b6a1c00-4cb5-11ea-8d9b-3a995ee7f35b.png)

In our usecase, we don't want to expose that information to the public as it a) unnecessarily exposes the internal team structure and b) is confusing for the external receiver of that files as they don't know who that sharing person might be. Instead we need to have the group name as sender of a shared file (or no sender information at all). In fact, that is our primary reason to share files from a group folder instead of sharing them from a personal folder.

It would be perfect, if one could choose what information about the sender is shown to the receiver when a share is created. It also would be okay to show the groupfolder name as the sender or none at all. From my point of view the standard case for a groupfolder share is that it is not a personal share of one member.

This issue is inderectly connected to #117 to which I also agree: For our team internally the information about who shared files from our groupfolder is very interesting.

**Comment by fschrempf** [comment]
As far as I understand it, a public share via link is never related to any feature of the groupfolders app and always tied to the user who created the share. The groupfolders app is intended to share folders with groups and not with the public.

What you are requesting is something like an "anonymous sharing" feature and this was already discussed here: https://github.com/nextcloud/server/issues/9789.
