### ISSUE TITLE
Hide all subfolders expect one is explicitly shared

### ISSUE THREAD

**Issue by dipiana** [nextcloud/groupfolders#759]
I am looking for a way to hide (deny access ) to all subfolders of the folder **projects**.
Only people who are granted access to some of these subfolders should be able to access them.

Therefore I tried to set advanced permission for the folder "projects" to deny and the permission of project_01 (which is inside "projects") to allow.

Unfortunately, the user does not have access to project_01.

Is there a way to only share specific projects within a folder?

**Comment by Daksol** [comment]
See response to this item. It has arrangement of many subfolders at a level, but most users only see the one for their project (and would see two if part of two projects).

https://github.com/nextcloud/groupfolders/issues/1060
