### ISSUE TITLE
groupfolders sharing doesn't work

### ISSUE THREAD

**Issue by mc9625** [nextcloud/groupfolders#76]
When I share a folder created with groupfolders with a user outside the group, when this user upload a file, I cannot see it in the folder, only in "recent", and as soon as it leaves the folder and re enters, the file is disappeared.

**Comment by icewind1991** [comment]
I can not reproduce this behaviour

**Comment by ZeikoFr** [comment]
Hi @mc9625 I can not reproduce this behaviour in NC20 can you confirm that it's not present anymore ?

**Comment by fschrempf** [comment]
It seems like this issue is not present anymore. I will mark this as stale and close it.
@mc9625 Please reply or open a new issue if you still experience this problem.
