### ISSUE TITLE
Symbolic links in current release breaks update

### ISSUE THREAD

**Issue by Tie-fighter** [nextcloud/groupfolders#769]
Hello, dear maintainers!

I tried updating to 6.0.1 (in NC 18.0.1) but it fails with "Exception: Could not extract app..."

There seems to be two symlinks that cannot be created during extraction, failing the update process.

![image](https://user-images.githubusercontent.com/170315/74605105-f60bc500-50c4-11ea-84a7-6ae312d4ebbc.png)

They were not present in the last version of groupfolders, so maybe they should not have been shipped? /cc @icewind1991 

Best Wishes,
Thomas

PS: There is also an empty css folder there... Maybe the current package was generated from a dev branch by accident?

**Comment by Tie-fighter** [comment]
PS: There is also an empty css folder there... Maybe the current package was generated from a dev branch by accident?

**Comment by pierreozoux** [comment]
Thanks for the report, but looks like it has been fixed in the meant ime.

I'll close it, but feel free to reopen if you feel somebody should take a closer look.
