### ISSUE TITLE
Incorrect permission check when creating directory

### ISSUE THREAD

**Issue by nenadalm** [nextcloud/groupfolders#772]
When user tries to create new directory, plugin tests if user has CREATE permission on the new directory. Shouldn't it test if it has CREATE permission on parent directory?: https://github.com/nextcloud/groupfolders/blob/1e57ee260e6d35b59bba9d90b43a205197d66049/lib/ACL/ACLStorageWrapper.php#L132?

**Comment by fschrempf** [comment]
@nenadalm It looks like the code walks through all of the parent directories and checks the permissions on them. So this looks ok to me. Do you have any doubts left?

https://github.com/nextcloud/groupfolders/blob/1e57ee260e6d35b59bba9d90b43a205197d66049/lib/ACL/ACLStorageWrapper.php#L52-L54

https://github.com/nextcloud/groupfolders/blob/e44159a979bd6d5218a661bdae24c2246fe6e60e/lib/ACL/ACLManager.php#L91-L102

https://github.com/nextcloud/groupfolders/blob/e44159a979bd6d5218a661bdae24c2246fe6e60e/lib/ACL/ACLManager.php#L112-L120
