### ISSUE TITLE
ACL: Access Control List missing in Nextcloud 18

### ISSUE THREAD

**Issue by rmeissn** [nextcloud/groupfolders#774]
I run a Nextcloud instance and updated to v18 a few days ago. Since then I am missing the ACL view one the group folder. I checked that advanced permissions is ticked in settings for this folder and I remember granting such permissions on NC v16 or v17.

As you'll see in the screenshot there are no permissions set and no options to grant such - or am I missing something? There should be advanced permissions for this folder or at least the option to create such.

![Bildschirmfoto von 2020-02-20 13-21-15](https://user-images.githubusercontent.com/855967/74933388-206ec280-53e4-11ea-8fe5-43eac0aa89d3.png)

**Comment by biva** [comment]
I have the same issue: any update?

**Comment by biva** [comment]
For me, the problem was Firefox and not Nextcloud. I solved it by restarting Firefox with addons disabled (Menu, Help, ...). And then restarted Firefox with addons enabled. It works now. I can't say which addon was causing troubles :(

**Comment by rmeissn** [comment]
@biva You're right! I tried your solution and the ACL menu is shown now.

**Comment by tortuetorche** [comment]
Hi folks,

This workaround doesn't work for me with Firefox 74.0, with the last versions of Chromium and Chrome the menu is visible but only if the uBlock Origin extension is disabled for my Nextcloud website...

Have a good day,
Tortue Torche

**Comment by rmeissn** [comment]
@tortuetorche @biva The day later the menu is gone again. At least for my instance uBlock (installed in Firefox and Chromium) isn't blocking anything. It works as expected using Chromium, but not using Firefox. Updating to Firefox 74 isn't improving anything.

**Comment by langfingaz** [comment]
For me it helped to open a private Firefox browser window (with no previous cookies and no cached webcontent), then the advanced permissions were visible again.

**Comment by caguiar** [comment]
I have the same problem.
I am configured as the user who has permissions to manage the advanced permissions on a group folder.
If I logout of Nextcloud and login again, and go straight to the folder, advanced permissions is visible. After being logged on for a while (don't know how long, but a few minutes) if I go back and the advanced permissions is no longer there.
So "workaround": Logout -> login.
Nextcloud: 18.0.4
Group Folders App: 6.0.6
Browser: Firefox 785 (on Ubuntu Linux)

**Comment by mpfaff** [comment]
I've been able to temporarily fix this multiple times by removing the `__Host-nc_sameSiteCookielax` and `__Host-nc_sameSiteCookiestrict` cookies. In case it matters, `nc` is the subdomain Nextcloud is on.

**Comment by laarisyko** [comment]
We have the same issue with NC18 and NC19. It makes the group folder partly useless, if one can not set these permissions. But in total we love the group folders functionality!

**Comment by fschrempf** [comment]
Also see #894

**Comment by juliushaertl** [comment]
Repoened https://github.com/nextcloud/groupfolders/issues/894 and closing this one as a dupliate
