### ISSUE TITLE
New files in shared group folder not visible

### ISSUE THREAD

**Issue by dkellenb** [nextcloud/groupfolders#79]
### Steps to reproduce
1. Create `BugSharedFolderEdit` - Group
2. Create `BugSharedFolderRead` - Group
3. Create Group Folder `BugShared` and give to group `BugSharedFolderEdit` privileges for `write` and `share`
4. Now as a user `user-edit` part of group `BugSharedFolderEdit` create directory `BugShared/Ausschüsse/Order mit Space/Protokolle`
5. As next add a text file (webclient) into folder `BugShared/Ausschüse/Ordner mit Space/Protokolle/` with name `file-visible.txt`
6. Now give read-only privileges to folder `BugShared/Ausschüsse/Ordner mit Space/` to group `BugSharedFolderRead`
7. Add as user `user-edit` a second file into `BugShared/Ausschüsse/Ordner mit Space/Protokolle/` with file name `file-not-visible-its-a-bug.txt`
8. Now log in as user `user-read` (part of group `BugSharedFolderRead`) => You can see in folder `Ordner mit Space/Protokoll` only the file `file-visible.txt`, but not the file `file-not-visible-its-a-bug.txt`

### Server configuration
**Operating system**: CentOS 6.8 (Final)‬, centos-release-6-8.el6.centos.12.3.x86_64
**Web server:** Apache 
**Database:** MySQL 5.0.12
**PHP version:** 7.0.26
**Nextcloud version:** 12.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:** older install
**Where did you install Nextcloud from:** nextcloud.com zip archive
**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - tasks
  - user_external
  - user_ldap
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "oc9i4xlxxw2s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.***DOMAIN***.ch"
        ],
        "datadirectory": "\/home\/httpd\/vhosts\/cloud.DOMAIN.ch\/data",
        "overwrite.cli.url": "https:\/\/cloud.***DOMAIN***.ch",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud_prod",
        "dbhost": "localhost:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "theme": ""
    }
}
```

**Comment by dkellenb** [comment]
Additional note: I could reproduce it also without special characters and space. File needs to be in a subfolder of the shared folder.

**Comment by billyonthemountain** [comment]
I encountered a similar issue in 12.0.4. Did not reappear when I upgraded to 13 RC1.

**Comment by ZeikoFr** [comment]
Hi @dkellenb is this issue still revelant ?

If so I will try replication on an up to date instance.

If not be free to close the issue.

**Comment by dkellenb** [comment]
I tried to reproduce it, it's working with release 19.0.4.
