### ISSUE TITLE
Strange strings in translations

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/groupfolders#8]
```
    "big" : "iso",
    "b" : "b",
    "font" : "fontti",
    "i" : "i",
    "small" : "pieni",
    "strike" : "yliviivaus",
    "sub" : "alaindeksi",
    "sup" : "yläindeksi",
```

Are they really intended to be a translation of this app?

**Comment by comradekingu** [comment]
These are BB-codes, the question being whether to translate them or not.

**Comment by icewind1991** [comment]
I think that our translation scripts don't handle the minified js correctly

**Comment by icewind1991** [comment]
Fixed with https://github.com/nextcloud/docker-ci/commit/8d37cda1f0be3a67767f9089998d4ccbb9f2bbe6
