### ISSUE TITLE
Groupfolders do not show folder icon when share a folder with subfolders

### ISSUE THREAD

**Issue by jofrepla** [nextcloud/groupfolders#801]
Hi, when I share a link folder with subfolders inside in the groupfolders structure, the folder icon do not appear correctly.

![imagen](https://user-images.githubusercontent.com/62256712/76781077-6c781180-67ae-11ea-8f61-92f1cb9a7f1b.png)

![imagen](https://user-images.githubusercontent.com/62256712/76781338-dd1f2e00-67ae-11ea-8045-d95481a1b845.png)

I tried to solve it creating the path /app/theming/img/core/filetypes and copying the icon from data folder.

1 - sudo -u www-data mkdir /var/www/nextcloud/apps/theming/img/core/filetypes

2 - sudo -u www-data cp /path/to/data/appdata_ocg5dv4z64ej/theming/66/icon-core-filetypes_folder.svg   /var/www/nextcloud/apps/theming/img/core/filetypes/file.svg

it doesn't work, the nextcloud instance starts to work bad.

some idea?

thanks.

**Comment by CptDayDreamer** [comment]
The same problem since many versions for me.
