### ISSUE TITLE
Version 6.0.3 not shipped to the app store

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/groupfolders#806]
The apps page in my installations only shows the update to 6.0.2 (instead of 6.0.3) as available. If 6.0.2 is installed, it says all apps are up to date.
Is this intended @juliushaertl?

**Comment by juliushaertl** [comment]
Ah indeed it seems that the upload to the app store didn't work and also fails right now, I'm on it. Thanks for reporting.
