### ISSUE TITLE
GroupFolders API Create Folder request not Working

### ISSUE THREAD

**Issue by Benjamin-Forg** [nextcloud/groupfolders#808]
Hi there,

I'm having a problem getting the API to work, I want to create a folder using this command from terminal:

`curl -X POST "https://username:password@domain-name/cloud/apps/groupfolders/folders" -d "mounpoint:testfolder" -H "OCS-APIRequest:true"`

But it just gives me an XML response listing all the folders. 

Also the DELETE requests give me a "405 Method Not Allowed" error, the only things I got to work were GET requests.

Am I doing something wrong?

Thanks for you help

**Comment by RenWal** [comment]
It looks like nextcloud doesn't like the overloaded URLs (in the sense that there are multiple routes defined with different methods for the same URL). If you rename the API endpoint for addFolder in appinfo/routes.php from `/folders` to `/folders/add` then it works:

```
        [
                'name' => 'Folder#addFolder',
                'url' => '/folders/add',
                'verb' => 'POST'
        ],
```

**Comment by RenWal** [comment]
For me the issue went away when specifying the path with `index.php`. In your example:
```
curl -X POST "https://username:password@domain-name/cloud/index.php/apps/groupfolders/folders" -d "mounpoint:testfolder" -H "OCS-APIRequest:true"
```

**Comment by Benjamin-Forg** [comment]
Thanks for your help @RenWal, 

That fixed one problem but it still didn't work until I replaced the ``:`` with a ``=`` in ``"mountpoint:testfolder"`` so it works with:
<pre>curl -X POST "https://username:password@domain-name/cloud/index.php/apps/groupfolders/folders" -d "mountpoint=testfolder" -H "OCS-APIRequest:true"</pre>
