### ISSUE TITLE
When GroupFolders as public links, the folder icon is showing as file.svg not folder.svg

### ISSUE THREAD

**Issue by robertemm34** [nextcloud/groupfolders#809]
This issue is only effecting folders that are GroupFolders, other folders work as expected. 

**you can see a screenshoot here: https://www.screencast.com/t/7k7UBt2UZ**

The inspection of the pages is using the incorrect svg

url(/apps/theming/img/core/filetypes/**file.svg**?v=13) not url(/apps/theming/img/core/filetypes/**folder.svg**?v=13)

how can I correct this?

**Comment by robertemm34** [comment]
Is this conifg, or a code issue?

**Comment by patricksebastien** [comment]
![image](https://user-images.githubusercontent.com/441764/102533668-ba8ab000-4073-11eb-9dc4-2c6241464452.png)

I have the same issue

**Comment by pierreozoux** [comment]
Can you confirm it is fixes with 

https://github.com/nextcloud/groupfolders/pull/1318 ?

**Comment by JohnWalkerx** [comment]
> Can you confirm it is fixes with 
> 
> https://github.com/nextcloud/groupfolders/pull/1318 ?
@pierreozoux 
For me this issue still exists in app version 8.2.1 with Nextcloud 20.0.10

Is this fix already in that version included?

**Comment by stereo9** [comment]
@pierreozoux
issue still exists for me as well (after accessing the folder through shared link)

Nextcloud 21.0.2.
Group Folders 9.0.1

**Comment by fschrempf** [comment]
I can't reproduce this issue with NC 22.2.0 and Groupfolders 10.0.0.

**Comment by fschrempf** [comment]
I'm closing this as stale and because the original issue seems to be solved.

@stereo9 As you were able to reproduce a similar issue on NC21, can you please open a new issue and provide the exact steps to reproduce the problem? Thanks!
