### ISSUE TITLE
Folder Quota changed to 2GB, almost always

### ISSUE THREAD

**Issue by wstemb** [nextcloud/groupfolders#81]
I created a new Group folder, assigned to a Group and defined a  quota. Whatever I put something bigger than 2GB, from drop-down list or "Other", except "Unlimited", it is changed to 2GB when I exit and  return to "Group folders". 

Nextcloud Version: 12.0.4
Group Folder App Version: 1.1.0
OS: Ubuntu 16.04.3 LTS, 4.4.0-104-generic
Data Filesystem: ext4, 16% used

**Comment by fwmarcel** [comment]
Same problem.

**Comment by icewind1991** [comment]
Are you using a 32bit php version?

**Comment by wstemb** [comment]
Yes, it is a 32 bit. 
I suggest to to put some kind of warning messages in such cases in next releases.  
I will migrate my Nextcloud instance to a new 64bit system and recheck ASAP.

**Comment by nuttygraphics** [comment]
So, is this a limitation? Wouldn't it make sense to use an unsigned integer or is this not possible in php? I would expect 4GB limit otherwise. 
Wouldn't be so simple on my 32bit hardware.

**Comment by icewind1991** [comment]
All integers are signed in php

You can try applying https://github.com/nextcloud/groupfolders/commit/a320c7f170404600e65a342dce98ce39f0543072 and see if that helps, I don't have a 32bit php system setup to test

**Comment by wstemb** [comment]
Installed from scratch a new server, fully 64 bit and  migrated the Nextcloud instance to the new server. 
All is working as expected and described. 

My suggestion is to check the system and put a warning when somebody on a 32bit system tries to pass the system limits. 

From my point of view, the issue can be closed, if other contributor have nothing against.
