### ISSUE TITLE
file upload failed

### ISSUE THREAD

**Issue by yxwmok** [nextcloud/groupfolders#810]
webdav Api Err：
"message":{"Exception":"Sabre\\DAV\\Exception","Message":"path needs to be relative to the system wide data folder and point to a user specific file"

**Comment by yxwmok** [comment]
nextcloud version: 18.0.2
Group folders version: 6.0.3

**Comment by mesiah1970-haydar** [comment]
same here on 18.0.2 but not on 18.0.1

**Comment by mesiah1970-haydar** [comment]
Hello all

I can confirm now, that GF with Version 6.0.4 is working now:

Upload to public share is without an error
deletion of an file in the public share is without an error
File drop is on my installation of Nextcloud (no docker, just VM) is without an error
Rgds

Haydar

**Comment by jbunner** [comment]
Same error issue with NC 18.0.4, running GF 6.06, running on Docker.
Receive the WebDAV error when dragging-dropping new file in browser, but file actually transfers and is stored in data directory under __GroupFolders. It appears to actually upload, but not be indexed in the database.
However, if you choose the + button and upload file, it will upload the file and appear.

To reproduce - upload file into group folder (drag/drop). If you use the + Upload file to upload the same file again, it will show a duplicate file/overwrite option.

**Comment by pierreozoux** [comment]
Can you reproduce with Nc 20?

**Comment by fschrempf** [comment]
Closing as stale. Please open a new issue if you still see this problem. Thanks!
