### ISSUE TITLE
Add the ability to autocreate a folder for each group

### ISSUE THREAD

**Issue by yodatak** [nextcloud/groupfolders#815]
I could be cool to automaticly via button or occ create a folder for each group

**Comment by pierreozoux** [comment]
closing as a duplicate of https://github.com/nextcloud/groupfolders/issues/815

**Comment by fschrempf** [comment]
> closing as a duplicate of #815

This is #815 :smile:

**Comment by pierreozoux** [comment]
Arf :) there was another one, cant find it on the phone :/

**Comment by pierreozoux** [comment]
Here it is https://github.com/nextcloud/groupfolders/issues/312
