### ISSUE TITLE
Advanced permission rule can not be removed on small screen sizes

### ISSUE THREAD

**Issue by flow10** [nextcloud/groupfolders#826]
If the screen size drops below approximately 1415 pixels, the "X" icon to delete a rule disappears. Therefore on smaller laptop screens it is not possible to remove a rule.
If the screensize decreases more, even more options disappear and there is no scrollbar or other method to bring them back to the view.

**Comment by fschrempf** [comment]
@flow10 With NC 21, I have a horizontal scrollbar that prevents this issue. Can you please confirm that it is fixed for you?

**Comment by fschrempf** [comment]
I'm closing this due to lack of response and as I can't reproduce the issue. Please feel free to reopen or create a new issue if necessary. Thanks!

**Comment by flow10** [comment]
Hey, sorry for not answering. Yes, I can confirm this is not more a problem in newer Nextcloud Versions. Thank you!
