### ISSUE TITLE
show owner group(s) of group folders & subfolders/files

### ISSUE THREAD

**Issue by zecrazytux** [nextcloud/groupfolders#829]
The details/sharing tab only shows additionnal ACLs.
It would be very useful to know which groups can access group folders.

For example: user Bob has access to groups A and B.
user Alice has access to group B only,  thus, ignores the existence of group A (not shown on the interface or through webdav sync).

But Bob does not know who can access group A. How can he be assured Alice would not see a file it creates in A ?
Providing at least the group name(s) that have default permission would be nice.

**Comment by pierreozoux** [comment]
closing as a duplicated of https://github.com/nextcloud/groupfolders/issues/975
