### ISSUE TITLE
Can't create a Group-Folder

### ISSUE THREAD

**Issue by iGodPhil** [nextcloud/groupfolders#839]
Hey,

I'am the admin of my Nextcloud but everytime i want to creat a new folder into the admin panel it doesn't creat a folder? I type in the name of the new folder and push the creat button but nothing happen. What could I do wrong?

I'am running version 18.0.4

**Comment by pingou2712** [comment]
you have to associate a group with you inside.

**Comment by mesiah1970-haydar** [comment]
??? Nextcloud 18.04, did I miss something? On the NC Website only 18.0.3 is available.

**Comment by iGodPhil** [comment]
i had a group with me inside but meanwhile i can create groupfolders. I don't know what was wrong because i changed nothing.

**Comment by iGodPhil** [comment]
> ??? Nextcloud 18.04, did I miss something? On the NC Website only 18.0.3 is available.

Sorry that was a misstake.
