### ISSUE TITLE
Group folder permissions error (bug?)

### ISSUE THREAD

**Issue by xdp6688** [nextcloud/groupfolders#84]
I have create one group folder,  three group(one role is admin can write group folder, the others only read),  but result is users int this three group can't write .
You don’t have permission to upload or create files here

**Comment by putt1ck** [comment]
Presuming you mean the same bug as described here:

https://github.com/nextcloud/groupfolders/issues/69

Then there's patch in the repo. If it's not the same, please provide more information.
