### ISSUE TITLE
Cannot delete files from Trashbin

### ISSUE THREAD

**Issue by lenaulrich** [nextcloud/groupfolders#861]
When using groupfolders and deleting files they are stuck in the trash bin. When trying to delete a file from the trash bin permanently the message "Error while removing file from trashbin" is shown.

Error in the nextcloud.log:
{"Exception":"OCP\\Files\\NotPermittedException","Message":"","Code":0,"Trace":[{"file":"\/home\/user\/shared\/customer\/apps\/groupfolders\/lib\/Versions\/GroupVersionsExpireManager.php","l

Why this issue is caused:

- The file is marked as deleted and is listed in the database in the table: group_folders_trash with a link to the seemingly correct trash folder
- The file is not in the stated trash folder on the file system
- Therefore the file cannot be deleted

How to resolve this issue:

- Create the file in the correct trash bin folder
- Delete the file in the webinterface

Concerns Nextcloud version 17.0.3 (groupfolders version <= 5.05) and seems to be fixed in Nextcloud Version 17.0.5 (groupfolders version 5.0.5). After upgrading to Nextcloud version 17.0.5 the deleted files from Version 17.0.3 are still in the trashbin and cannot be deleted.

PHP Version 7.2

The issue cannot be solved by the occ command "files:scan" and "groupfolders:scan". Can you offer a solution for this issue?

**Comment by horvan** [comment]
Can confirm the same issue for 18.3 php7.2 It seems to be either a mass deletion issue., Cant just delete one file at once. Had not reproduced it yet. Sorry.
