### ISSUE TITLE
Mentions in comments do not work

### ISSUE THREAD

**Issue by sprnza** [nextcloud/groupfolders#863]
Hi!
It seems like I'm unable to mention users in comments on files of the group folder. Is it supposed to work or just my local issue?
Thanks!
GroupFolder v.6.0.5
Nextcloud 18.0.3
Usernames provided by LDAP backend (it include cyrillyc names and spaces)

**Comment by pierreozoux** [comment]
is it still the case with a more recent version?

**Comment by sprnza** [comment]
Yes, 
Nextcloud 20.08
GroupFolder 8.2.0
LdapContacts 2.0.3
I can choose contacts in sharing tab but nothing happens if I start typing @Имя (cyrillic) in comment field.

**Comment by pierreozoux** [comment]
Actually, I discovered the hard way that you shouldn't use utf8 chars on username.. so.. I guess it will be a wontfix, or go dicuss this on the server. Well not be able to fix anything here.
