### ISSUE TITLE
Allow custom storage location per group folder

### ISSUE THREAD

**Issue by klada** [nextcloud/groupfolders#87]
Hi,

at the moment all group folders are created flat under `$CONFIG["datadirectory"]/__groupfolders` . For larger-scale Nextcloud instances it is common to split files across multiple network shares (such as NFS shares). For the groupfolders app it would be sufficient if at least one hierarchy level could exist between the actual group folder (represented by the folder's id in the filesystem) and the `__groupfolders` root.

Let me give an example. This is the current state for two different group folders:

```
__groupfolders/
├── 2
│   └── dfsfsdfsd.txt
└── 3
    └── empty.txt
```

And I think that this state would be very desirable for bigger instances:

```
__groupfolders/
├── nfs-share-01
│   └── 2
│       └── dfsfsdfsd.txt
└── nfs-share-02
    └── 3
        └── empty.txt
```

This has multiple benefits:

- Additional space can be provided by simply adding another share from potentially another storage system
- Spreading IOPS across multiple storage systems (this is a big thing when dealing with many group folders)

This has some implications though:

- The location of each group folder would need to be configured (additional field in `oc_group_folders` table). This would mean that the Admin GUI and the API need to be extended.
- People might want a `move` command later to move a group folder from one filesystem location to another

I have already played a bit with the PHP code and from what I see there are only three things that would need to be changed:

- The `database.xml` (obviously, as we need another field)
- `MountProvider::getFolders($id)` would need to look up the actual storage path in the database
- The SQL query in `FolderManager::getAllFolders` would need to be changed for correct size calculations

What do you think of this improvement?

**Comment by flyinghuman** [comment]
i like this. +1

**Comment by langfingaz** [comment]
I found a way to achieve what you requested:
* In the groupfolder settings you can create a groupfolder `/groupfolders` that is shared with a list of groups but can not be managed by them.
* You can then add other groupfolders as children of the above groupfolder, e.g. `/groupfolders/folder1`, and let the users manage its content / work inside them.

Here's a screenshot on how the groupfolder settings page can look like:
* A folder located in the users root/home directory (`05_Finanzausschuss`)
* An other folder located at root (`06_Weitere_Arbeitsformen`) aswell as
* a subfolder/children of it (`01_AG_Digitale_Arbeitsumgebung`)

![https://cloud.privacy1st.de/s/CBy2zBsyHLsbZsD/preview](https://cloud.privacy1st.de/s/CBy2zBsyHLsbZsD/preview)

**Comment by langfingaz** [comment]
So I think this issue can probably be closed. Am I right?

**Comment by klada** [comment]
> So I think this issue can probably be closed. Am I right?

@langfingaz  Definitely not. What makes you think so? The issue has not been solved and nobody found out how to solve it yet. I have looked into this a while ago, but I failed due to the lack of time and knowledge of the general Nextcloud architecture.

We still need a native way to split group folder across multiple storages (possibly even different storage backends), while maintaining the possibility to automatically provision new group folders through the OCS API.

**Comment by langfingaz** [comment]
>  We still need a native way to split group folder across multiple storages

Oh, I'm really sorry. I somehow mixed two different things up and thought this was just about changing the path of a groupfolder - which was not possible some time ago as I remember.

**Comment by provokateurin** [comment]
Managing the physical storage is not something Nextcloud is supposed to do, so we will not implement this.
You can still do this my mounting your storages to the specific groupfolder IDs if you really need it.
