### ISSUE TITLE
Size of subfolder not counted in root groupfolder

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/groupfolders#875]
I'm facing an odd behaviour with groupfolders: When I'm logged in with my admin account, all folder sizes are computed correctly. But when I'm logged in with my normal user, that at least as read access to all subfolders in that groupfolder, the size of one subfolder isn't counted to the total file size. However, in the details view the size is show correctly.

![Screenshot_20200415_104917](https://user-images.githubusercontent.com/16020496/79320100-8457c800-7f09-11ea-95de-3cbd1e2f444d.png)
![Screenshot_20200415_105339](https://user-images.githubusercontent.com/16020496/79320104-8588f500-7f09-11ea-8c13-6d77f29a3f56.png)

Has anyone faced a similar issue and found a solution to it? Scanning the files with occ didn't help.

Best regards,

Chris

**Comment by Chartman123** [comment]
I don't know what just happened, but now it shows the correct size...

**Comment by fschrempf** [comment]
@Chartman123 Can you check #1069 and try if this does still happen with a recent version of NC and the groupfolders app?

**Comment by Chartman123** [comment]
@fschrempf I just had a quick view at some of our groupfolders and couldn't find an obvious difference in the size of the main folder vs. the sizes of the subfolders.

**Comment by fschrempf** [comment]
@Chartman123 Thanks for the fast response. I will close this for now. Please create a new issue if you still see this problem or reply to #1069 if you think this fits there. Thanks!
