### ISSUE TITLE
Errors when building release 4.1.6

### ISSUE THREAD

**Issue by Nienzu** [nextcloud/groupfolders#877]
I try to build the tag-4.1.6 for nextcloud-16
OS: CentOS-7 
Node: 10.20.1
NPM: 5.6.0

I encounter two error when I try to deploy 4.1.6 for nextcloud-16

1. No npm module : vue-click-outside
```
ERROR in ./src/SharingSidebarApp.js
Module not found: Error: Can't resolve 'vue-click-outside' in '/home/tommy/work/server/apps/groupfolders/src'
resolve 'vue-click-outside' in '/home/tommy/work/server/apps/groupfolders/src'
```
2. appinfo/info.xml
```
<dependencies>                                                                                                                                                                       
    <nextcloud min-version="18" max-version="18" />
</dependencies> 
```

I fix 1 for `npm install vue-click-outside` and 2 for `<nextcloud min-version="16" max-version="18" />`

Should I make a PR for fixing there two error?

**Comment by juliushaertl** [comment]
Actually there was a wrongly tagged "4.1.6", sorry about that. Please see https://github.com/nextcloud/groupfolders/releases/tag/v4.1.6 for the correct tag.
