### ISSUE TITLE
Error message when deleting from group folders (files ARE deleted, folder view not updated)

### ISSUE THREAD

**Issue by Tercus** [nextcloud/groupfolders#878]
I am using nextcloud 18.0.3 and whenever I delete a file from a group-folder I get an error message that deleting the file failed ([Screenshot](https://i.imgur.com/0PRJfI2.png)). The exact error message is `Error deleting file "Readme.md".`. The file view also isn't updated. When I reload the folder however, the file is gone.

**Comment by davimury** [comment]
I am having the same issue, are you using S3 Storage?

**Comment by pierreozoux** [comment]
I have the same error, and I'm using s3.

**Comment by pierreozoux** [comment]
Using last 18 version, the problem is not there anymore.

I think we can close, feel free to reopen if needed.

Thanks for fixing :)
