### ISSUE TITLE
files:scan to allow group folder selection

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/groupfolders#88]
When running occ files:scan you cannot choose to scan a group folder or group folders, leaving the only option of running --all. In addition it doesn't handle group folders well #8148

Ideally group folders should be a scan option, both all group folders and individual. This facility would be particularly useful when migrating content in from other systems - administrators could pull the content directly into the file system with its existing structures and then run the group folder scan to populate it into NC.

(originally submitted for occ https://github.com/nextcloud/server/issues/8149)

**Comment by icewind1991** [comment]
Scanning the folder that the group folder is mounted in should work.

```
occ files:scan --path /username/files/path/to/group/folder
```

**Comment by RafDeCoster** [comment]
doesn't seem to work with me. Always get "Unknown user 1 media"
any idea's

**Comment by FreeMinded** [comment]
We have the same issue. Somehow the occ files:scan does not seem to work for group folders at all.

`
/ # occ files:scan --path=/data/__groupfolders
Unknown user 1 data

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
`

**Comment by FreeMinded** [comment]
It works if you scan with a nextcloud user with access to this group folder. So the path @icewind1991 posted is correct but I misinterpreted it at first. The following might be easier to understand.
`occ files:scan --path=nextcloud_username/files/groupfolder_name`

Still the files:scan doesn't seem to fix issues for group folders. But that's a different strory.

**Comment by icewind1991** [comment]
The next release (should be released with nc15) will have a dedicated command to make it easier to scan a groupfolder

```
occ groupfolders:scan <folder_id>
```

You will be able to find your folder id using

```
occ groupfolders:list
```

**Comment by OlivierDoucet** [comment]
Dear all,
I use 
`occ groupfolders:scan 1`
but I have the error
In DBLockingProvider.php line 211:
  "files/2cb883f8591f4d4cac2f1a4365d35a67"("local::/data/::__groupfolders/1/s  
  canner::") is locked     

Do you know what occurd

**Comment by fultonm** [comment]
```There are no commands defined in the "groupfolders" namespace.```

**Comment by malventano** [comment]
> The next release (should be released with nc15) will have a dedicated command to make it easier to scan a groupfolder
> 
> ```
> occ groupfolders:scan <folder_id>
> ```
> 
> You will be able to find your folder id using
> 
> ```
> occ groupfolders:list
> ```

Did this change ever happen?

**Comment by Maximus48p** [comment]
php /var/www/html/occ groupfolders:list
php /var/www/html/occ groupfolders:scan <id>
