### ISSUE TITLE
Folder icon is missing

### ISSUE THREAD

**Issue by hermann-san** [nextcloud/groupfolders#882]
fresh NC installation 18.0.2 via Yunohost on Debian 9.12 64bit (Linux 4.9.0-12-amd64).  

creating a new folder in the admin panel works, but results in a missing icon. It looks like this

![grafik](https://user-images.githubusercontent.com/7679654/79701277-0c3c2a00-829c-11ea-8125-376bfa546d52.png)

but should look like this (customer details).
![grafik](https://user-images.githubusercontent.com/7679654/79701217-7d2f1200-829b-11ea-8b51-fe1e60b82656.png)

![grafik](https://user-images.githubusercontent.com/7679654/79701323-6dfc9400-829c-11ea-996e-444b0995b52f.png)

anyone is having an idea why this is and how to fix it?
Thanks.

**Comment by charentonvolley** [comment]
Same problem dans I notice an error : Nextcloud 18.0.4 / Group folders 6.0.6
Refused to execute .../apps/groupfolders/build/filess.js?v=7c747943-36 as script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.

**Comment by hermann-san** [comment]
@charentonvolley   I've noticed that groupfolders don't really has any additional value to the standard NC permissions. If I remember correctly , I could do all I want with without groupfolders.

**Comment by pierreozoux** [comment]
@hermann-san looks like related to yunohost, I couldn't reproduce, can you open your issue there please?
