### ISSUE TITLE
apps/groupfolders/folders/$folderId should provide ACL details

### ISSUE THREAD

**Issue by ArnY** [nextcloud/groupfolders#885]
Hello,

We are planning to rollout groupfolders in production (NC 17.0.2; groupfolders  5.0.7;16k users, several hundred groupfolders eventually). But for now, we're trying to use the groupfolders' API to generate the groups and set ACLs.

We are surprised that the _apps/groupfolders/folders/$folderId_ endpoint does not return the groupfolder's ACL but only a boolean while the _apps/groupfolders/folders_ endpoint does return  the acl details for all the folders. This does not appear to be logical. 

We couldn't find any other way to get all the ACLs for a groupfolder other than using the _apps/groupfolders/folders_ endpoint but once we'll have hundreds of groupfolders this will become very counterproductive.

Did I miss something?

Thanks

**Comment by fschrempf** [comment]
Let's make this specific request a part of #1256 and track the progress there.
