### ISSUE TITLE
Create/Assign automatically a folder based on group

### ISSUE THREAD

**Issue by TranslationsCloud** [nextcloud/groupfolders#89]
Hello,

I tried to use the API, but without success. So the request is the following:
how to automatically create/assign a shared folder, based on the group_id specified in the settings?

Is that, or will it be, possible?

**Comment by ZeikoFr** [comment]
Hi @TranslationsCloud is this issue still revelant ?

If so I will try replication on an up to date instance.

If not be free to close the issue.

**Comment by fschrempf** [comment]
It is not clear what the author wants to achieve and given there was no more reaction from him, I will close this issue.

@TranslationsCloud If you feel like there still is an issue, please open a new one and be precise about what you want to achieve. Thanks!
