### ISSUE TITLE
Enhancement proposal for GroupFolder

### ISSUE THREAD

**Issue by depasquale** [nextcloud/groupfolders#893]
Dear all,
I would really thank you for the great work with GroupFolder in Nextcloud 18. I have been able to create a very complex organization structure that is fitting our organizational needs, but because I have invested time and matured a good practice with the ACLs and how to organize sub-folders permissions, I would like to share some ideas that can be evaluated by you for future enhancements:

**1) permissions inheritance**. In order to fine set the permissions in our organization focused on Dept shares, responsabilities, and privileges, I have faced the difficulty to manage a rule for making a root folder visible to everyone and than hide specific subfolders to specific groups. In order to solve this, I have been forced to create a group "all_users" that in our user creation process shall be assigned to all our employees and users accessing NC. By default all_users have all the privileges set in the admin config (otherwise it is not possible to raise an "allow" privilege in a subfolder - known issue), and by default I am using this group to give all the folders a "not read" permission. This way you can add specific groups for a certain folder, and "all_users" with read denied will prevent others to get access to the protected resourse apart the listed groups (it is acting as a kind of ELSE statement in permissions evaluation).

CURRENT LIMITATION: when a folder is created via webdav (or by a person without the chance to grant advanced permissions) that folder is not inheriting the default desired behaviour, and the admin shall put manually the "all_users deny read permission".

SUGGESTIONS:
1. create a "catch all" group (e.g. Everyone) and give the chance to use such a group for "default permissions". Giving a global setting for defining "global default rules" to apply to all files and/or folders in specific Group Folders (similar the checks you use now, but plus "read" permission). 
2. In order to not have issues in overriding at subfolder level, It can be ok to "copy" the global defult rule automatically for each resource managed by Group Folder. In my honest opinion for single files it should be too much (for example I do not need such a function in my scenario)... but for folders I think this is very useful to prevent errors and accidental data sharing with people. Moreover, we can design paths in the folder tree to give specific people the access to a given sub-folder, without having access to all the sibling folders at each level!
3. A similar feature can prevent the need to create each element in the folder tree as a groupfolder via admin GUI, and give to ICT or DPO users the chance to look at newly created folders and decide with granularity how to get access to a certain resourse.
4. With global rules, when a folder is created (also via webdav), my suggestion is to give the default rule, and to the author the set "read/write/delete". This way, if I am wrong in creating a folder in the wrong part, as author I can still delete/rename and the other users use the default rules (e.g. the admin/manager can get access to the resource and than assign other permissions).

**2) in alternative to the point 1)** 
It can be useful to have a simple flag (checkbox) that gives to NC-admin the possibility to adopt a "strict permission schema" for at least folders: if a group or user is not explicitily included in the advanced permissions rules, he can not read the resource (or at least can enter inside a folder). In my opinion it is not a panacea for all the use-cases, but can be useful if you have a specific GroupFolder hierarchy where multiple Dept have to get access to specific folders but not to others (e.g. Sales Dept Folder with a sub-folder for each Region: every sales man can get common resources and folders, but get access and read/write/delete/share only the folder where he has explicitily been added - as group or specific user)

**3) Advanced Permission management**
It can be useful to create an advanced permission to give a certain person/group the possibility to manage advanced permissions for "sub folders". It should result in a sort of "read/write/delete/share/manage" schema. E.g. the ICT manager want to give a certain colleague the role as its deputy for specific branches (e.g. branch office, topic area) and this person can manage advanced permissions for other colleagues and people in a given sub-folder structure. Other example, team leaders can manage permissions in the workspace areas for each project to specific team members without having to ask the sys admin to grant access and manage permissions day-by-day.

CURRENT LIMITATION: if I give to a certain group in admin panel the rights to be "admin" for a specific GroupFolder this group will have rights to change the permissions along the complete folder tree, and it means that he can grant himself or to other people permissions to access private data that was intended to be hidden for him. At the moment it is possible to implement a work-around, but it will result in the fact that each sub-folder to make manageable by specific teams, shall be a dedicated GroupFolder into the admin panel, with as a name the path of the level you want to see in the file explorer (e.g. Sales Team, Sales Team/Italy, Sales Team/Italy/Tuscany, Sales Team/Italy/Tuscany/Florence). In my opinion this will be not manegable at all also for small-sized teams.

**4) Advanced Permissions Reporting**
A kind of reporting about advanced permission assignment to admin roles can be very useful. If someone makes changes in the advanced permissions, we (as NC-admin) should be reported in order to react immediately in case of violation.

------
I would be glade if some of this requests will be useful to someone else. Personally I think the project you are developing is great! And it is already good like it is; but for sure I hope such ideas will find your interest to improve it even more for small businesses like us.

**Comment by fschrempf** [comment]
@depasquale First of all, thanks for your extensive feedback. I think it is very important to see how users are using the groupfolders app and what experiences they make.

Though I'm really struggling to make anything of your post because:

1. It is very long and sometimes a bit confusing.
2. Your phrasing and formatting makes it hard to read.
3. You mix different topics in one issue.

Can you please create **separate issues for each topic** and try to be precise about what problems you see? Of course you can also add suggestions for how you would enhance the situation. Please also check for other issues that might already cover these topics.

I will close this issue as in this shape it is not useful for improving the app, but I'm looking forward to get more feedback from you in a manageable way.
