### ISSUE TITLE
Read-only option for specific groups

### ISSUE THREAD

**Issue by dan-nkl** [nextcloud/groupfolders#9]
I would really need and love to see a option for creating different permissions for different groups for one group folder! 
So I can give my team access for company templates they can't change but open and download.
And at the same time I can give the Management the permission to edit the templates or other files in the folder.
To make this work at the moment, I'm using external storages where I can manage this. But it's not the best solution...

To say it simple: I want to share a folder with a group and take the permission from the users to revoke the share.

**Comment by dan-nkl** [comment]
To say it simple: I want to share a folder with a group and take the permission from the users to revoke the share.

**Comment by RiSK1979** [comment]
I would second that request. However I would extend the request: Group Folders should have nearly all the sharing options that "ordinary" folders in NC have (e.g. grant or revoke rights to re-share, share publicly, read-only access, etc.).

**Comment by icewind1991** [comment]
Fixed with 583e4b5

**Comment by RiSK1979** [comment]
Lovely! Thanks for that @icewind1991 .

**Comment by bpcurse** [comment]
Great job people! Thank you very much for this app and the new feature.
Groupfolders should be really integrated in NC as standard.
