### ISSUE TITLE
Group Folder Recreated as User Folders During Upgrade

### ISSUE THREAD

**Issue by ChrisPurves** [nextcloud/groupfolders#90]
When upgrading to Nextcloud 13, Group Folders was disabled since it is a 3rd party app.  During this time each of the clients received a notification saying that the folders had been removed (or something similar) and giving a choice to keep the local files or delete them.  We chose to keep files.  After group folders was re-enabled, the clients synced up after several hours; however, I noticed that many of the clients have a large portion of the group folders files in their personal files directory on the server.  I believe that during the time that group folders was disabled, Nextcloud started syncing the local files on the client to the server as personal files and once Group Folders was enabled, the group folder took over, but leaving a large number of redundant files on the server.

For example, let's say I have a group folder "HR" with file "file1.txt".  It now shows up in the data directory several times as:
__groupfolder/8/file1.txt
user1/files/HR/file1.txt
user2/files/HR/file1.txt
user3/files/HR/file1.txt

I have two questions:

1. How can I delete the files from users' directories?
1. Is there a way to avoid this in the future any time Group Folders is disabled?

**Comment by ChrisPurves** [comment]
If I remove the user from the group folder, then I can delete the local copy on the client, then add the user back to the group; however, this is quite tedious.  Can I delete files directly from the server?

**Comment by icewind1991** [comment]
Currently, the easiest way to remove the files from the user's folder is to delete them manually from the data directory and then use

```
occ files:scan --home-only --all
```

to remove them from the index.

As for preventing this, there isn't really a way if the groupfolders app get's disabled. To prevent it from getting disabled you can either update both the server and the app at the same time or update the app before hand (I usually try to have app releases compatible with multiple server versions)
