### ISSUE TITLE
"Add advanced permission rule" list does not show all users in groups

### ISSUE THREAD

**Issue by hanscomps** [nextcloud/groupfolders#903]
NC 18.0.4 (snap)
Ubuntu 18.04

Recreate:
1. Create group with 10+ users in it
2. Create "Group Folder" and add group from 1.
3. Add admin to "Advanced Permissions"
4. Go to "Gorup Folder and use "Add advanced permission rule"
5. Dropdown list appears, but not all users are listed.
6. Can search/filter the list and find the "lost" users as workaround

**Comment by matejak** [comment]
I can confirm that this is an issue with groupfolders 6.0.6 and NC 9.

**Comment by pierreozoux** [comment]
looks related to https://github.com/nextcloud/groupfolders/issues/675 I'll close this as a duplicate.

Feel free to comment to reopen if you think it is not the same.
