### ISSUE TITLE
User shared Group Folder duplicates

### ISSUE THREAD

**Issue by republicus** [nextcloud/groupfolders#910]
One of my users has, without knowing better, shared with me an an already shared Group Folder.

Now, that Group Folder appears twice in my File's list

![image](https://user-images.githubusercontent.com/47370709/81845480-9c2d6680-951e-11ea-965d-2ee80c640d65.png)

NC 18.0.4
Group Folders 6.0.6

**Comment by mesiah1970-haydar** [comment]
yeah this is another issue, which should be fixed besides the group folder trashbin which is not emptying

**Comment by fschrempf** [comment]
The sharing feature and the groupfolders are two independent ways of making directories accessible for other users. There is currently no way to handle this kind of collision better than showing the directory twice. You should be easily able to unshare the shared directory and only keep the groupfolder. I will close this as "won't fix" for now.
