### ISSUE TITLE
occ scan of group folders is repeated for every user

### ISSUE THREAD

**Issue by tormodvolden** [nextcloud/groupfolders#921]
It seems unnecessary that the periodic occ scan job (occ files:scan --all) scans through the same group folder for every user having access to it.

nextcloud 18.0.4 and groupfolder 6.0.5.

**Comment by pierreozoux** [comment]
looks related to https://github.com/nextcloud/groupfolders/issues/1288

**Comment by fschrempf** [comment]
Closing in favor of #1568 which has some more details.
