### ISSUE TITLE
Name not visible for permission options.

### ISSUE THREAD

**Issue by the-matzup** [nextcloud/groupfolders#922]
The permission options do not have enough space in the menu. It does not matter how large or small I drag the browser window: There's no way to figure out which person or group has permissions set for. The name is always cut off and only the first letters are visible. 

![Bildschirmfoto 2020-05-24 um 14 46 17](https://user-images.githubusercontent.com/47818886/82754543-cfe57780-9dcd-11ea-95c1-1d33a27b8b8f.png)

NC: 18.0.4

**Comment by pierreozoux** [comment]
This is a dupliacte
