### ISSUE TITLE
"File Drop" error

### ISSUE THREAD

**Issue by the-matzup** [nextcloud/groupfolders#923]
Uploading via "File Drop" into a group order causes an error. The alternative permission "Upload and Edit" works without problems. 
(The sharing for "File Drop" was done by a user with all permissions, NC-Admin and as group folder admin.)

![Bildschirmfoto 2020-05-24 um 15 45 45](https://user-images.githubusercontent.com/47818886/82755913-11c6eb80-9dd7-11ea-84f4-2e3a87639287.png)

There are a few entries in the NC log: 
`{"reqId":"Dsf6l77vdhxwYKn2BWFZbwAAAAw","level":3,"time":"2020-05-24T13:45:59+00:00","remoteAddr":"79.xxx.xxx.xx","user":"--","app":"public","method":"PUT","url":"/public.php/webdav/personal-2020-05-24.ics","message":{"Exception":"Error","Message":"Call to a member function getType() on boolean","Code":0,"Trace":[{"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\ServerFactory","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/html/apps/dav/appinfo/v1/publicwebdav.php","line":109,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/public.php","line":81,"args":["/var/www/html/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/Connector/Sabre/ServerFactory.php","Line":156,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0","version":"18.0.4.2","id":"5e34a7aa937b51"}`

and...
`{"reqId":"Dsf6l77vdhxwYKn2BWFZbwAAAAw","level":3,"time":"2020-05-24T13:45:59+00:00","remoteAddr":"79.xxx.xxx.xx","user":"--","app":"core","method":"PUT","url":"/public.php/webdav/personal-2020-05-24.ics","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Files/SimpleFS/SimpleFile.php","line":90,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->","args":[]},{"file":"/var/www/html/lib/private/Template/JSCombiner.php","line":125,"function":"getContent","class":"OC\\Files\\SimpleFS\\SimpleFile","type":"->","args":[]},{"file":"/var/www/html/lib/private/Template/JSCombiner.php","line":102,"function":"isCached","class":"OC\\Template\\JSCombiner","type":"->","args":["merged-template-prepend.js.deps",{"__class__":"OC\\Files\\SimpleFS\\SimpleFolder"}]},{"file":"/var/www/html/lib/private/Template/JSResourceLocator.php","line":115,"function":"process","class":"OC\\Template\\JSCombiner","type":"->","args":["/var/www/html","core/js/merged-template-prepend.json","core"]},{"file":"/var/www/html/lib/private/Template/JSResourceLocator.php","line":71,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\Template\\JSResourceLocator","type":"->","args":["/var/www/html","core/js/merged-template-prepend.json"]},{"file":"/var/www/html/lib/private/Template/ResourceLocator.php","line":78,"function":"doFind","class":"OC\\Template\\JSResourceLocator","type":"->","args":["js/merged-template-prepend"]},{"file":"/var/www/html/lib/private/TemplateLayout.php","line":346,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->","args":[["core/js/dist/main","js/merged-template-prepend","search/js/search","core/l10n/de","files_sharing/l10n/de","files_sharing/js/dist/main","search/l10n/de","search/js/searchprovider","js/files/fileinfo","js/files/client"]]},{"file":"/var/www/html/lib/private/TemplateLayout.php","line":174,"function":"findJavascriptFiles","class":"OC\\TemplateLayout","type":"::","args":[["core/js/dist/main","js/merged-template-prepend","search/js/search","core/l10n/de","files_sharing/l10n/de","files_sharing/js/dist/main","search/l10n/de","search/js/searchprovider","js/files/fileinfo","js/files/client"]]},{"file":"/var/www/html/lib/private/legacy/template.php","line":184,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["error",""]},{"file":"/var/www/html/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"/var/www/html/lib/private/legacy/template.php","line":333,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"/var/www/html/public.php","line":94,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[{"__class__":"Error"},500]}],"File":"/var/www/html/lib/private/Files/Node/File.php","Line":58,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0","version":"18.0.4.2","id":"5e34a7aa937b51"}`

NC 18.0.4

**Comment by ruppo68** [comment]
HI,
same Problem in NC 19.
In Chorm F12 I see 
Uncaught (in promise) TypeError: Cannot read property 'fileList' of undefined
    at Module.29 (client.js:125)
    at o (bootstrap:63)

client.js: var client = OCA.Files.App.fileList.filesClient; 

I think, because the share is only for uploading, i don't get a filelist.

Regards,
Peter R.
