### ISSUE TITLE
Admin who created a group folder can't see the group folder

### ISSUE THREAD

**Issue by bitbonk** [nextcloud/groupfolders#927]
The admin who is the member of the group _Foo_ creates a group folder named _Foo-Test_ and shares it with the group _Foo_. Everybody in the group _Foo_ can see that shared folder and its content, except the admin. The folder is invisible for him, even though he is a member of the group _Foo_ just like everyone else.

**Comment by pierreozoux** [comment]
this is strange, and I can't reproduce.

Which version are you using?

**Comment by pierreozoux** [comment]
Do you use ldap?

Ill close as stale.
