### ISSUE TITLE
No pagination leads to bad performace

### ISSUE THREAD

**Issue by StwBonn** [nextcloud/groupfolders#929]
Like #365 and #233 

No pagination makes it impossible to scale up groupfolders.

Ist there a solution in sight?
Or a workaround?

**Comment by t-markmann** [comment]
Same here.
It takes 15 minutes to load 200 groupfolders in the main view of files app.

**Comment by fschrempf** [comment]
@StwBonn What does this issue add, that is not covered by #365 and #233? Please explain! Otherwise I will close this in favor of the already existing issues.
