### ISSUE TITLE
Groupfolder quota greater 2 GB not stored

### ISSUE THREAD

**Issue by RailsViceRoads** [nextcloud/groupfolders#93]
- NC 13.0.0.14
- Group folders  1.2.0
- different browsers

A quota setting greater 2 GB will not be stored. Steps to reproduce the behaviour:
- Open quota settings and chose "Other..."
- Set quota for a group folder to 4 GB or 4096 MB. The quota will displayed in the usage bar.
- Switch to an other NC app
- Switch back to Group folders. Now you will see 2 GB as quota setting.

In this case 2 GB is really the quota setting for the folder. "Other..." quotas less then 2 GB will working fine.

**Comment by icewind1991** [comment]
Can you try applying https://github.com/nextcloud/groupfolders/commit/a320c7f170404600e65a342dce98ce39f0543072 and see if that fixes the problem for you

**Comment by RailsViceRoads** [comment]
Thx icewind1991. Now it works as expected. I hope this commit will part of the next release, therefore I'm closing this issue.
