### ISSUE TITLE
Take trashbin retention policy into account

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/groupfolders#930]
Since the groupfolders app has its own trash backend, the regular background job for applying the retention policy does not act on files in the group folders trashbin: https://github.com/nextcloud/server/blob/afbd9c4e6ed834e713039f2cff88ba3eec03dadb/apps/files_trashbin/lib/BackgroundJob/ExpireTrash.php#L89

**Comment by freiheitswolke-org** [comment]
Hey,
we opened a bounty on this missing function.
Please spread the voice and contribute as you can:
https://www.bountysource.com/issues/69919948-tashbin-cannot-be-cleared-with-group-folder-data

**Comment by landryb** [comment]
is #1064 fixing that or just a temporary workaround to add to cron ?

**Comment by juliushaertl** [comment]
#1064 is a temporary workaround to clear the whole trashbin, a proper retention implementation is started with #991

**Comment by jngrb** [comment]
Please indicate what the development status is. Also in my project, nextcloud hosting for an NGO, we are in desperate need of a solution and would like how the Nextcloud team wants to proceed and whether we can help getting this fixed.

**Comment by CarlSchwan** [comment]
New PR: https://github.com/nextcloud/groupfolders/pull/1759. It would be great to get some community testing.

**Comment by fschrempf** [comment]
Closing in favor of #1759.

**Comment by pgassmann** [comment]
FYI, group folders 11.1 for Nextcloud 23 is released. `occ groupfolders:expire` will now clean up the trashbin of groupfolders.
