### ISSUE TITLE
GroupFolders subfolder access

### ISSUE THREAD

**Issue by baldemir** [nextcloud/groupfolders#931]
Hi,

I have a file hierarchy shown as in diagram below. Currently when I try to give access to a subfolder to a group, they can't see the subfolder because the group members don't have access to parent folder of that subfolder. I have also shown which groups I would like to give access on diagram. Is it possible with group folders?
![image](https://user-images.githubusercontent.com/7359315/83167677-17933880-a119-11ea-8562-5a46730ead0a.png)

**Comment by fzieris** [comment]
This should be possible with the [advanced permissions](https://github.com/nextcloud/groupfolders#advanced-permissions). The following configuration might work (untested):
* As Admin: Give all three Groups access to the group folder "Language", and enable the advanced permissions.
* For "Language/French": Deny Group 2 and 3 all access
* For "Language/English": Deny Group 3 all access
* For "Language/English/Listening": Allow Group 3 in
* For "Language/English/Speaking/Beginner:" Allow Group 3 in

I don't what happens (from the user perspective) if Group 3 has no read access to Language/English, but to Language/English/Listening. Maybe you need to give them read access to the intermediate folders so the full path remains traversable, but block all sibling folders that should remain hidden.

**Comment by baldemir** [comment]
Thank you for your answer @fzieris, but it's not possible for my case. Because on my instance users are assigned to groups according to invite code they have entered during registration. So there will be lots of groups and tree structure will be much more complex than the diagram I sent. It will be so hard to manage manually. My requirement is simple actually. If i give access to a group to a folder on the tree, the users of that group should see the files below that node. I believe there should be an easy way for this.

**Comment by fzieris** [comment]
From what I understand about group folders, the advanced permissions only work with groups (and members of groups) that generally have permissions for the corresponding group folder. Meaning that you cannot grant some arbitrary user access to some subfolder if that user is not is in a group with (theoretical) top-level access. 

So the setup for your case could be as follows:
 * First, set the base line. For each group folder:
   * In Admin view: Grant all groups access to the group folder and enable advanced permissions.
   * In File view: Block all groups from accessing the group folder.
 * So far, nobody can access anything.
 * For each subfolder that should be accessible to some particular group:
   * In File view: Allow read/write/whatever access for that group.

**Comment by baldemir** [comment]
When I try it user can't display the subfolder. Most probably because of not having permission for parent.

**Comment by Daksol** [comment]
I describe a working example of a master-folder / sub-folder arrangement here
https://github.com/nextcloud/groupfolders/issues/1060

Your setup above is pretty complicated. Notes below will help you configure a two level folder setup. You might be able to collapse your structure to just two levels.
* Grant all rights to Groups 1, 2 and 3 for a top level folder
* Create seven subfolders, one for each unique permission set

Fairly universal rule - if you are someone who can usually do this sort of thing with ease, and are finding it hard - then find a simpler way of administering. Else you can be sure it will break when you change jobs.

---
Subfolders can only have permissions which are a strict subset of those of the parent folder.

So in Group Folders
* Create your top level folder
* Grant that the full set of permissions needed by any of the subfolders you will create
   * So include all the Groups at the top level folder with (say) Create and Delete - say TeamA, TeamB, TeamC
   * Include "ManagersGroup" as those who will be able to make settings with Advanced permissions

So by default the top level folder is Read/write for ManagersGroup, and TeamA, TeamB, TeamC

* Let us assume we now have specific content we want to put into FolderTeamA which only TeamA are allowed to work on, similarly for TeamB and TeamC
* A member of ManagersGroup creates FolderTeamA
* They then include at least two lines via using "Add advanced permission rule"
   * First start by Denying - so have TeamB set with DENY for all access right properties (read, write, etc), and another line with TeamC denied all
   * Then a line for TeamA in which (say) Read, Write, Create, Delete

Tips
* Don't include Group everyone on your top level folder. That is setting yourself up to get locked out later.
* Have a separate ManagersGroup which only sets permissions. Never deny that Group, in case you lock yourself out

**Comment by pierreozoux** [comment]
@baldemir looks like your question was answered, feel free to reopen if you still have doubts.
