### ISSUE TITLE
No Home access after moving shared folders

### ISSUE THREAD

**Issue by MrNoname33** [nextcloud/groupfolders#94]
### Steps to reproduce
1. Create a personal folder.
2. Share the folder to another local user.
3. As admin create a group folder.
4. Move as user the personal folder to the group folder.

### Expected behaviour
The shared folder should be accessable and the user have access to his home folder.

### Actual behaviour
The user who shared and moved that folder has no access to his home folder anymore.

I don't know if this is an error on my system or if is an error in Nextcloud.

## Server configuration detail

**Operating system:** Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.33

**PHP version:** 7.0.25-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 - 13.0.0.14

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.2.1
 - bruteforcesettings: 1.0.3
 - comments: 1.3.0
 - dav: 1.4.6
 - external: 3.0.2
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_pdfviewer: 1.2.0
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - impersonate: 1.0.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.1.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - user_external: 0.4
 - user_saml: 1.4.2
 - workflowengine: 1.3.0
Disabled:
 - contacts
 - encryption
 - files_external
 - tasks
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "10.0.1.30",
        "upload.server.local",
        "upload.server.extern",
        "10.0.1.3"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/upload.server.local",
    "dbtype": "mysql",
    "version": "13.0.0.14",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "enable_previews": true,
    "enabledPreviewProviders": {
        "0": "OC\\Preview\\PNG",
        "1": "OC\\Preview\\JPEG",
        "2": "OC\\Preview\\GIF",
        "3": "OC\\Preview\\SVG",
        "4": "OC\\Preview\\BMP",
        "10": "OC\\Preview\\XBitmap",
        "11": "OC\\Preview\\Illustrator",
        "12": "OC\\Preview\\Postscript",
        "13": "OC\\Preview\\Photoshop",
        "14": "OC\\Preview\\TIFF",
        "30": "OC\\Preview\\Font",
        "50": "OC\\Preview\\PDF",
        "51": "OC\\Preview\\TXT",
        "52": "OC\\Preview\\MSOfficeDoc",
        "53": "OC\\Preview\\MSOfficeXls",
        "54": "OC\\Preview\\OpenDocument",
        "55": "OC\\Preview\\StarOffice",
        "80": "OC\\Preview\\MP3",
        "81": "OC\\Preview\\Movie"
    },
    "skeletondirectory": "",
    "log_type": "file",
    "syslog_tag": "Nextcloud",
    "log_file": "nextcloud.log",
    "loglevel": 2,
    "tempdirectory": "\/var\/www\/nextcloud\/nextcloudtemp",
    "appstore.experimental.enabled": true,
    "updatechecker": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "singleuser": false,
    "logtimezone": "Europe\/Berlin",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "updater.release.channel": "stable",
    "logfile": "\/var\/log\/apache2\/nextcloud.log"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary></summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by ZeikoFr** [comment]
@MrNoname33 HI, is this issue still relevant ?

**Comment by fschrempf** [comment]
I'm also unable to reproduce this. I will close this as stale. @MrNoname33 please open a new issue if required.
