### ISSUE TITLE
Upload limit should be the same as the instance

### ISSUE THREAD

**Issue by SimonDoll** [nextcloud/groupfolders#941]
Expected behavior:
uploads to a group folder follow the same limitations as for regular folders

Observed behavior:
upload size is limited to 2GB files (bigger files crash at 2GB.

Tested on nextcloud snap on raspberry pi 3b+

Is there a setting for this?

**Comment by pcast43** [comment]
Have the same issue with Nextcloud 18 on a server.

Big uploads crash or they never finish if they are sent from the desktop client. 

Any settings that need to be adjusted?

**Comment by fschrempf** [comment]
Closing this as stale. Please comment, reopen or create a new issue if you think this problem still exists. Thanks!
