### ISSUE TITLE
Files View / Latest Files without Groupfolder data

### ISSUE THREAD

**Issue by skillz-xx** [nextcloud/groupfolders#943]
hello!

Since we work mostly with group folders in our teams, users have wondered if there is a capability of showing the recently edited files not just in the activity view, but also in the files / recent fils view in Nextcloud..

Anyone can help with this?

**Comment by thomas-svw** [comment]
Hello,

I have the same problem
https://help.nextcloud.com/t/can-not-see-file-from-group-folders-in-the-menu-recent-on-the-left-side/115722
Is there a plan to fix it?

Best regards

Thomas

**Comment by SabRenaEdpPdP** [comment]
Any update on this ? I searched the forum and all topics are quite old... and it would be very useful for our team to be able to see the recently modified file by others in addotion than by themselves...

**Comment by joshtrichards** [comment]
Related: #1158

**Comment by joshtrichards** [comment]
Confirmed functioning my test bed today. Closing.
