### ISSUE TITLE
Group folder file sharing in Talk breaks Files app: `Call to a member function getCache() on null`

### ISSUE THREAD

**Issue by manu-p** [nextcloud/groupfolders#945]
Hi, 

Already mentioned [here](https://github.com/nextcloud/server/issues/13719) and [here](https://github.com/nextcloud/spreed/issues/1521): sharing a file stored in a group folder sometimes makes the Files app fail.

After others users, we faced this strange behavior with NC 18.0.4 / MySQL 5.7.30 / Apache 2.4.29 / PHP 7.4.6.

When entering the Files App, a message is displayed to the user saying something like (reverse translated in English) "this folder is not available, consult the logs or contact your administrator".
And no folder/file is displayed. Nothing. Just like there's no folders/files anymore (which is not the case).

The system log shows:
`Error	remote	**Error**: Call to a member function getCache() on null

    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 382:
    OCA\Files_Sharing\SharedStorage->getSourceRootInfo()

    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 393:
    OCA\Files_Sharing\SharedStorage->getCache()

    /var/www/nextcloud/lib/private/Files/View.php - line 1746:
    OC\Files\Storage\Wrapper\Wrapper->getCache()

    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 128:
    OC\Files\View->getPath()

    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 477:
    OCA\Files_Sharing\SharedStorage->init()

    <<closure>>
    OCA\Files_Sharing\SharedStorage->getSourceStorage()

    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 506:
    call_user_func_array()

    /var/www/nextcloud/apps/files_sharing/lib/Cache.php - line 94:
    OC\Files\Storage\Wrapper\Wrapper->__call()

    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheJail.php - line 309:
    OCA\Files_Sharing\Cache->getCache()

    /var/www/nextcloud/lib/private/Files/View.php - line 1747:
    OC\Files\Cache\Wrapper\CacheJail->getPathById()

    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 128:
    OC\Files\View->getPath()

    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 112:
    OCA\Files_Sharing\SharedStorage->init()

    /var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php - line 382:
    OCA\Files_Sharing\SharedStorage->getSourceRootInfo()

    /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 393:
    OCA\Files_Sharing\SharedStorage->getCache()

    /var/www/nextcloud/lib/private/Files/View.php - line 1478:
    OC\Files\Storage\Wrapper\Wrapper->getCache()

    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 265:
    OC\Files\View->getDirectoryContent()

    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/TagsPlugin.php - line 227:
    OCA\DAV\Connector\Sabre\Directory->getChildren()

    <<closure>>
    OCA\DAV\Connector\Sabre\TagsPlugin->handleGetProperties()

    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:
    call_user_func_array()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1059:
    Sabre\Event\EventEmitter->emit()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 981:
    Sabre\DAV\Server->getPropertiesByNode()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666:
    Sabre\DAV\Server->getPropertiesIteratorForPath()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 355:
    Sabre\DAV\Server->generateMultiStatus()

    <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind()

    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:
    call_user_func_array()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:
    Sabre\Event\EventEmitter->emit()

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:
    Sabre\DAV\Server->invokeMethod()

    /var/www/nextcloud/apps/dav/lib/Server.php - line 319:
    Sabre\DAV\Server->exec()

    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:
    OCA\DAV\Server->exec()

    /var/www/nextcloud/remote.php - line 165:
    require_once("/var/www/ne ... p")`

The workaround seems to delete entries in the oc_share table, which worked for us today.

As it is suggested [here](https://github.com/nextcloud/spreed/issues/1521#issuecomment-474255696), I'm now reporting the issue to the groupfolder app.

**Comment by t-markmann** [comment]
I had this issue in a customer instance with NC 17.0.3. The symtom that the root of files app is not accessible anymore indeed appeared suddenly and I could not figure out the reason. The customer did not have groupfolders installed. 

- First I disabled _talk_ so the customer could access his files again. 
- OCC files scan did not resolve the issue and did not show any errors. 
- In the nextcloud.log you can find something like "class":"OC\\Files\\View","type":"->","args":[BIGNUMBER]}
- Search for the big number in database table oc_share. Delete those shares.

**Maybe Related**:
I think I was able to reproduce the cause for the bug.
In my test I had a groupname with german umlauts and an asterisk (*). (this might be relevant or not)
This group had access to a groupfolder with a normal name.

I shared a file from that groupfolder with **another group** with umlauts and an asterisk. 
Members of the receiving group were able to edit the file, but Collabora did not save it (error message).
The file owner then deleted the file. In the talk conversation, there is a correct message: User shared a file that has been deleted.
In the files app of the receiving user I now see the old file with a directory icon, wrong last edited and size data.

![grafik](https://user-images.githubusercontent.com/5323995/87228556-4cdea780-c3a2-11ea-83ae-ad685a90c9e7.png)

This was testet with current Apache, PHP7.3, MySQL and Nextcloud 18.0.6.

In the customer instance there was a jpeg file, that had a directory icon and wrong data. After I found it and deleted the shared, the root directory worked fine again. So I think this is related.

**Comment by joshtrichards** [comment]
Is anyone actually still experiencing this issue? I can't pinpoint the exact fix, but I also find it hard to believe this is still a thing given how quiet this issue has been for years now.

**Comment by jospoortvliet** [comment]
Yeah, tons of issues like this have been fixed - and internally we use groupfolders and share them in Talk all day long. I'm pretty darn confident this is working, otherwise half my day I'd be causing this issue ;-)
