### ISSUE TITLE
Not all shares are displayed; "Path is already shared with this user" error when sharing

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/groupfolders#95]
We experience some issues with shares with NC13 and groupfolders 1.2.

If `admin1` shares a subfolder within a groupfolder with `user1` this share is displayed in the info panel as it should. If `admin2` displays the folder info panel he sees no shares. If he then tries to share the file with `user1`, because he thinks `user1` has no access to this folder, a "path is already shared with this user" error message appears because the folder is of course already shared.

It makes no sense to hide this information from `admin2` and it makes the handling of such shares quite horrible.

**Comment by ZeikoFr** [comment]
Hi @lars-becker I didn't not encounter this issue on NC 19 and 20, is it still revelant ?

If the issue is now fix please be free to close the issue.

Regards

**Comment by fschrempf** [comment]
I will close this as stale. @lars-becker If you still experience this with the latest release, please open a new issue.
