### ISSUE TITLE
Too many files in one group folder - NC open the parent folder instead of the selected one?!

### ISSUE THREAD

**Issue by vogych** [nextcloud/groupfolders#950]
As soon as there are too many files in a group folder, nextcloud loads the parent folder after some time. No matter whether it is accessed via web interface, WebDav or MobileApp.
How can I tune nextcloud group folder app so that it can handle many files in one group folder?

Environment docker-nextcloud with mysql, redis, nginx via proxy (letsencrypt) on Windows 10

Find no error message in the logs when nextcloud decides to open the parent folder (instead of the selected one).

The above problem only occurs in connection with the group folder app. Only group folder have this property! :o/
Does anyone have an idea why?

**Comment by pierreozoux** [comment]
Do you still have the issue?
What is too many files? How many?
Can you give us Nc anf gp version?

Thanks

**Comment by fschrempf** [comment]
I will close this as stale due to missing information.
