### ISSUE TITLE
Insufficient space using group folders

### ISSUE THREAD

**Issue by DennisAC** [nextcloud/groupfolders#963]
Dear Team, 
I want to begin to use group folders on my NextCloudPi to distribut some files and got the following topic: 

Sabre\DAV\Exception\InsufficientStorage: Insufficient space in /<destinationPathToFile>, 21901312 required, 4346623 available 
... while uploading to a group folder with unlimitted quota. 

The first file size is right, the size of the available space is definitely not right. the HDD where the file shall be stored is about 420 GB with a usage of 4%. 

The full message in the logfile is

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php - line 137: 
OCA\DAV\Connector\Sabre\QuotaPlugin->checkQuota("/DevBoyz/Hö ... n", 21901312)

<<closure>>
OCA\DAV\Connector\Sabre\QuotaPlugin->beforeMove("uploads/Den ... e", "files/Denni ... 3")
/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: 
call_user_func_array([ OCA\DAV\Co ... "], [ "uploads/D ... "])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 633: 
Sabre\Event\EventEmitter->emit("beforeMove", [ "uploads/D ... "])

<<closure>>
Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})
/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: 
call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: 
Sabre\Event\EventEmitter->emit("method:MOVE", [ Sabre\HTTP ... }])
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: 
Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})
/var/www/nextcloud/apps/dav/lib/Server.php - line 319: 
Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35: 
OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 165: require_once("/var/www/ne ... p")
-- | --

I tried to find a way to the root cause but I ended up in Quotaplugin.php at the freeSpace-Function. 
Finally I wrote following test.php scribt to check the size:

`<?php
$sourcePath='/media/NCHDD'; //directory where the files of nextcloud are stored
if (!is_dir($sourcePath)) {
        // disk_free_space doesn't work on files
        $sourcePath = dirname($sourcePath);
        }
        $space = @disk_free_space($sourcePath);
        if ($space == false || is_null($space)) {
                echo "SPACE_UNKNOWN";
        }
        echo $space;
?>
`
The result was like expected: 
`user@nextcloudpi:~ $ php test.php 
446970970112 user@nextcloudpi:~ $`
--> something about 420 GB available. 

The question for me is, why is there a difference of a factor 1000 between the remaining disk space  and the similar php comment while using group folders? 
Copying the files to a different location in my home directory (independ if the destination directory is shared or not, but located in my home directory instead of a group folder) works very well. But even not using the group folder leads to this Fatal Message. 

### Steps to reproduce
1. using an ext4 FS HDD to store ncdata
2. Defining at least one group folder with limited or unlimited quota (does not matter)
3. share it within a group
4. copying several files to that location (some GB in my case) by drag-and-drop using the web fronted to that location
--> recieving that message after transfer of ~2 GB

### Expected behaviour
Files shall be copied to the group folder like to a folder in my home directory without this FATAL message.

### Actual behaviour
Recieving the FATAL Message in logfile:
Sabre\DAV\Exception\InsufficientStorage: Insufficient space in '<group folder name>'

### Server configuration

**Operating system: ** Nextcloudpi 1.25.0, Raspbian 10 (buster) 

**Web server: **

**Database: ** mySQL

**PHP version: ** 7.3.14-1

**Nextcloud version:** 18.0.6.0

**Updated from an older Nextcloud:** 18.0.3

**Where did you install Nextcloud from:** https://ownyourbits.com/downloads/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary> Accessibility 1.4.0 Offiziell
Activities for shared file downloads, visible to all admins 1.7.0
Activity 2.11.0 Offiziell
Audio Player 2.10.0
Calendar 2.0.3 Offiziell
Carnet 0.22.0
Circles 0.18.7 Offiziell
Collaborative tags 1.8.0 Offiziell
Comments 1.8.0 Offiziell
Contacts 3.3.0 Offiziell
Deleted files 1.8.0 Offiziell
DropIt 0.4.0 
External sites 3.5.0 Offiziell 
Extract 1.2.4 
Federation 1.8.0 Offiziell 
File sharing 1.10.1 Offiziell
First run wizard 2.7.0 Offiziell
Group folders 6.0.6 Offiziell
Group quota 0.1.2 
Log Reader 2.3.0 Offiziell
Mind Map 0.0.22
Monitoring 1.8.0 Offiziell
NCP Preview Generator 102.2.0
News 14.1.11 Offiziell
Nextcloud announcements 1.7.0 Offiziell
NextCloudPi 0.0.1 
Notes 3.5.0 Offiziell
Notifications 2.6.0 Offiziell
Notifications for calendar event updates 1.0.2
Password policy 1.8.0 Offiziell
PDF viewer 1.7.0 Offiziell
Photos 1.0.0 Offiziell
Printer 0.0.3 
Privacy 1.2.0 Offiziell
Quota warning 1.7.0
Recommendations 0.6.0 Offiziell 
Right click 0.15.2 Offiziell
Share by mail 1.8.0 Offiziell
Side menu 1.7.0
Support 1.1.1 Offiziell
Talk 8.0.9 Offiziell
Tasks 0.13.1 Offiziell
Text 2.0.0 Offiziell
Theming 1.9.0 Offiziell
Update notification 1.8.0 Offiziell
Usage survey 1.6.0 Offiziell
Versions 1.11.0 Offiziell
Video player 
</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "",
            "11": "<ipaddr>",
            "12": "mint.spdns.de"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.6.0",
        "overwrite.cli.url": "https:\/\/mint.spdns.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/media\/NCHDD\/ncdata\/tmp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "maintenance": false,
        "logfile": "\/media\/NCHDD\/ncdata\/nextcloud.log",
        "loglevel": "2",
        "log_type": "file",
        "htaccess.RewriteBase": "\/",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

</details>

### Client configuration
**Browser: FireFox**

**Operating system: Linux **

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Jun 09 00:00:03.754518 2020] [ssl:warn] [pid 813:tid 1995727376] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 00:00:03.778898 2020] [mpm_event:notice] [pid 813:tid 1995727376] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Tue Jun 09 00:00:03.779035 2020] [core:notice] [pid 813:tid 1995727376] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 09 17:09:22.892111 2020] [mpm_event:notice] [pid 813:tid 1995727376] AH00491: caught SIGTERM, shutting down
[Tue Jun 09 17:09:47.603415 2020] [ssl:warn] [pid 749:tid 1996378640] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 17:09:47.647872 2020] [ssl:warn] [pid 816:tid 1996378640] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 17:09:47.653878 2020] [mpm_event:notice] [pid 816:tid 1996378640] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Tue Jun 09 17:09:47.654054 2020] [core:notice] [pid 816:tid 1996378640] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 09 17:18:04.204022 2020] [mpm_event:notice] [pid 816:tid 1996378640] AH00491: caught SIGTERM, shutting down
[Tue Jun 09 17:18:19.124583 2020] [ssl:warn] [pid 727:tid 1995862544] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 17:18:19.175253 2020] [ssl:warn] [pid 819:tid 1995862544] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 17:18:19.181188 2020] [mpm_event:notice] [pid 819:tid 1995862544] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Tue Jun 09 17:18:19.181333 2020] [core:notice] [pid 819:tid 1995862544] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 09 17:22:09.208218 2020] [mpm_event:notice] [pid 819:tid 1995862544] AH00491: caught SIGTERM, shutting down
[Tue Jun 09 17:22:25.206831 2020] [ssl:warn] [pid 707:tid 1996190224] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 17:22:25.260808 2020] [ssl:warn] [pid 818:tid 1996190224] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Jun 09 17:22:25.266108 2020] [mpm_event:notice] [pid 818:tid 1996190224] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1d configured -- resuming normal operations
[Tue Jun 09 17:22:25.266243 2020] [core:notice] [pid 818:tid 1996190224] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jun 09 19:58:37.534467 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:39.531777 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:39.860341 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to / failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:39.870797 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:40.021295 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /index.php failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:48.493097 2020] [authz_host:error] [pid 819:tid 1925559328] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:48.493299 2020] [authz_host:error] [pid 819:tid 1749312544] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /js/ncp.js failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:48.493775 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /js/minified.js failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:48.494108 2020] [authz_host:error] [pid 819:tid 1866810400] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /css/ncp.css failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:48.493885 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.382761 2020] [authz_host:error] [pid 819:tid 1749312544] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /css/ncp.css failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.383652 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/toggle.svg failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.383644 2020] [authz_host:error] [pid 819:tid 1866810400] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/loading-small.gif failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.385320 2020] [authz_host:error] [pid 819:tid 1866810400] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/defaults.svg failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.385612 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/poweroff.svg failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.391480 2020] [authz_host:error] [pid 819:tid 1866810400] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /js/ncp.js failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.391851 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /js/minified.js failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.396287 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/reboot.svg failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:49.536382 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/ncp-logo.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.555320 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/poweroff.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.560163 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/search.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.560969 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/nc-button.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.565230 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/dashboard.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.565252 2020] [authz_host:error] [pid 819:tid 1866810400] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/defaults-white.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.565570 2020] [authz_host:error] [pid 819:tid 1749312544] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/wizard.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.565606 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/settings-white.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.565616 2020] [authz_host:error] [pid 819:tid 1925559328] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/info-white.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.574039 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/files.svg failed, reason: unable to get the remote host name, referer: https://nextcloudpi3:4443/css/ncp.css
[Tue Jun 09 19:58:49.997594 2020] [authz_host:error] [pid 819:tid 1766097952] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /ncp-output.php failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:50.081445 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Tue Jun 09 19:58:58.661208 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Tue Jun 09 20:09:54.825695 2020] [authz_host:error] [pid 819:tid 1799668768] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /ncp-launcher.php failed, reason: unable to get the remote host name
[Tue Jun 09 20:09:54.825699 2020] [authz_host:error] [pid 819:tid 1925559328] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/download.svg failed, reason: unable to get the remote host name
[Tue Jun 09 20:09:54.825706 2020] [authz_host:error] [pid 819:tid 1749312544] [client 10.100.0.25:56230] AH01753: access check of 'localhost' to /img/delete.svg failed, reason: unable to get the remote host name

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>
{"reqId":"Xt-a0k5xjZqG0J05icqe9QAAAFQ","level":4,"time":"2020-06-09T18:54:10+00:00","remoteAddr":"10.100.0.25","user":"Dennis","app":"webdav","method":"MOVE","url":"/remote.php/dav/uploads/Dennis/3421017321/.file","message":{"Exception":"Sabre\\DAV\\Exception\\InsufficientStorage","Message":"Insufficient space in /DevBoyz/Zieht aus, 47810667 required, 4346623 available","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php","line":137,"function":"checkQuota","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["/DevBoyz/Zieht aus",47810667]},{"function":"beforeMove","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["uploads/Dennis/3421017321/.file","files/Dennis/DevBoyz/Zieht aus/story 2.mp3"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"},"beforeMove"],["uploads/Dennis/3421017321/.file","files/Dennis/DevBoyz/Zieht aus/story 2.mp3"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":633,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMove",["uploads/Dennis/3421017321/.file","files/Dennis/DevBoyz/Zieht aus/story 2.mp3"]]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3421017321/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3421017321/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3421017321/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3421017321/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":165,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php","Line":174,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)","version":"18.0.6.0"}

{"reqId":"Xt-a0U5xjZqG0J05icqe9AAAAEI","level":4,"time":"2020-06-09T18:54:11+00:00","remoteAddr":"10.100.0.25","user":"Dennis","app":"webdav","method":"MOVE","url":"/remote.php/dav/uploads/Dennis/3141764669/.file","message":{"Exception":"Sabre\\DAV\\Exception\\InsufficientStorage","Message":"Insufficient space in /DevBoyz/, 17358848 required, 4346623 available","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php","line":137,"function":"checkQuota","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["/DevBoyz/",17358848]},{"function":"beforeMove","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["uploads/Dennis/3141764669/.file","files/Dennis/DevBoyz/In Afrika.mp3"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"},"beforeMove"],["uploads/Dennis/3141764669/.file","files/Dennis/DevBoyz/In Afrika.mp3"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":633,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMove",["uploads/Dennis/3141764669/.file","files/Dennis/DevBoyz/In Afrika.mp3"]]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3141764669/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3141764669/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3141764669/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/3141764669/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":165,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php","Line":174,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)","version":"18.0.6.0"}

{"reqId":"Xt-a3fqJm3Nu2H1cfRNpfAAAABc","level":4,"time":"2020-06-09T18:54:22+00:00","remoteAddr":"10.100.0.25","user":"Dennis","app":"webdav","method":"MOVE","url":"/remote.php/dav/uploads/Dennis/1502148602/.file","message":{"Exception":"Sabre\\DAV\\Exception\\InsufficientStorage","Message":"Insufficient space in /DevBoyz/Raspberry Pi/NOOBS, 1763320689 required, 4346623 available","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php","line":137,"function":"checkQuota","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["/DevBoyz/Raspberry Pi/NOOBS",1763320689]},{"function":"beforeMove","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["uploads/Dennis/1502148602/.file","files/Dennis/DevBoyz/Raspberry Pi/NOOBS/NOOBS_v3_0_0.zip"]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"},"beforeMove"],["uploads/Dennis/1502148602/.file","files/Dennis/DevBoyz/Raspberry Pi/NOOBS/NOOBS_v3_0_0.zip"]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":633,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMove",["uploads/Dennis/1502148602/.file","files/Dennis/DevBoyz/Raspberry Pi/NOOBS/NOOBS_v3_0_0.zip"]]},{"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/1502148602/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMove"],[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/1502148602/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MOVE",[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/1502148602/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://nextcloudpi3/remote.php/dav/uploads/Dennis/1502148602/.file","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":165,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/QuotaPlugin.php","Line":174,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)","version":"18.0.6.0"}
</summary>

</details>

**Comment by magix2** [comment]
I guess that I have a similar, but slightly different problem. I set a quota which was reached, so I got the error message of insufficient space, but this error message does not go away, even though I increased the quota.

The log shows:
level: fatal, App:webdav  Insufficient space in /…/*/     * required, 0 available.

There is still plenty of storage on the HDD and the only problem occurs for one group folder.

The GUI (Web browser) confirms the new limit, but I guess that some parts of Nextcloud do not know yet. Can I somehow force to actualize all quota?

**Comment by magix2** [comment]
> I guess that I have a similar, but slightly different problem. I set a quota which was reached, so I got the error message of insufficient space, but this error message does not go away, even though I increased the quota.
> 
> The log shows:
> level: fatal, App:webdav Insufficient space in /…/*/ * required, 0 available.
> 
> There is still plenty of storage on the HDD and the only problem occurs for one group folder.
> 
> The GUI (Web browser) confirms the new limit, but I guess that some parts of Nextcloud do not know yet. Can I somehow force to actualize all quota?

I do not know why, but I kept changing limits multiple times and I have the feeling that changing the limit to unlimited and waiting some time helped to resolve this issue.

**Comment by pierreozoux** [comment]
@DennisAC do you still have the issue? Did you try the workaround?

**Comment by pierreozoux** [comment]
Closing as stale
