### ISSUE TITLE
Can't create new file on nextcloud with onlyoffice

### ISSUE THREAD

**Issue by riffraff2** [nextcloud/groupfolders#966]
Hi,

I tried different installations (centos, docker) and I always got the same result. If i create a onlyoffice document in a group folder and start editing it, when reopen it i got this error message : "The file version has changed. The page will refresh" (original in french : "La version du fichier a été changée. La page sera rechargée"). And when i download the document, i got a error message in Microsoft Word or Excel : "file corrupt".
It works great in a regular folder.

Nextcloud version : 19
Group FOlders: 6.0.6
OnlyOfficeApp : 4.2.0

Thanks

**Comment by dietze** [comment]
Hello. I had the same issue.
At least for browser access you can resolve this by granting "Share" permission to the group on the folder.
Then you are able to create/edit office docs in this group folder or subfolder.

BUT the issue still persists in the Nextcloud Client App (at least on iOS, App version 3.0), where you get error 500.

**Comment by pierreozoux** [comment]
I couldn't reproduce, can you detail a bit more your test to reproduce please?

**Comment by pierreozoux** [comment]
Closing as stale
