### ISSUE TITLE
Add support of Nested Groups

### ISSUE THREAD

**Issue by q-wertz** [nextcloud/groupfolders#969]
**Problem**
When setting up Group folders only groups that are mentioned in the `Groups` columns can be selected in the `Advanced Permissions` column.

**Feature Request**
It would be nice to also be able to select groups that are Members of the groups listed in the `Groups` column. (sorry for that sentence...)
e.g.
'Group1': "Main Group"
'Group2': "Technical Staff" and member of Group1
'Group3': "Non Technical Staff" and member of Group1

1. Add 'Group1' in the `Groups` column.
2. Add 'Group2' in the `Advanced Permissions` column. (Not possible at the moment)

A straight forward implementation maybe is to check members of all groups that are listed in `Groups` and list not only the users (which is done at the moment) but also the groups when setting the `Advanced Permissions`.

**Workaround**
Also add the Group that should have `Advanced Permissions` to the `Groups`.

Note: We use the LDAP Backend for Group and User management.

**Comment by fschrempf** [comment]
@q-wertz Does NC support having groups as members of groups? If yes, how can I configure this? I didn't find any information about this.

**Comment by q-wertz** [comment]
I don't think so. 

# Scenario 1
But when using LDAP this can occur (NC just doesn't know about it) and I think it's a common way to use this possibility there.

I can e.g. make a `project` group and say the `project-leader` group is part of the `project` group. Then I add the project leaders to the `project-leder` group and all normal project participants to the `project` group.

In NC I then would add the `project` group to the group folder and give the `project-leader` group the Advances Permissions

# Scenario 2
Also using usual NC groups a feature like this could be useful.
E.g. Group `project` and group `admins` (can also contain users that are not part of group `project`).
- Then if you could set `admins` in the advanced permissions and only users that are part of `project` and `admins` have the advanced permissions 
- Users only in `admins` don't have any permissions (cannot see the group folder)

So in general may be an `AND` check to get the advanced permissions.
But I also don't know how if this is intuitive. It could happen that there is no overlap between the two groups `project` and `admins` so no one has advanced permissions. Which is not necessarily bad but maybe a warning `Currently no user matches these requirements.` could pop up for clarification when setting the advanced permissions.

**Comment by fschrempf** [comment]
Ok, for scenario 1 if NC doesn't know about the relationship between the groups, how should we handle it in the groupfolders app? Even if we could get the information from the LDAP server I think we wouldn't implement this as LDAP-only feature.

One way to handle this would be to support "groups" and "roles". I'm using Keycloak for user management and it provides this functionality. For your example this would mean there are the roles "project" and "project-leader" and also the groups "project" and "project-leader". The group "project" has the role "project" assigned. The group "project-leader" has the roles "project" and "project-leader" assigned.

For scenario 2: Supporting combination of group memberships could be useful, but I think it would maybe be better to add it to the general group management in NC. Then the logic could be used by other features/apps. Anyway this could be getting quite complex and as you say also counterintuitive.

**Comment by q-wertz** [comment]
Thanks for looking into this :)

I also think both problems should be handled the same way and as NC does not support nested groups directly, another way has to be found why I thought about the "request combination of membership" idea.

> Supporting combination of group memberships could be useful, but I think it would maybe be better to add it to the general group management in NC. Then the logic could be used by other features/apps. Anyway this could be getting quite complex and as you say also counterintuitive.

Can totally understand that. So currently there is no easy way of requesting membership of a user in two (or more) groups from NC core?

**Comment by fschrempf** [comment]
> So currently there is no easy way of requesting membership of a user in two (or more) groups from NC core?

Of course you can assign a user to multiple groups. But you need one assignment for each membership. You can't accumulate multiple group memberships with a single assignment. And that's part of what you are up to if I did understand you correctly (which I'm not sure of).

**Comment by q-wertz** [comment]
I'm not familiar with php or javascript nor the way the permissions are granted by these mappings :sweat_smile: 

So I fully trust your assessment.

**Comment by fschrempf** [comment]
I still have the feeling we are partly talking at crossed purposes, but I will still close this as "won't fix" for now. I don't see any obvious way to handle this in the groupfolders app. If someone else has an idea how to do this feel free to comment. Thanks!
