### ISSUE TITLE
creating groupfolders with name already existing delete it

### ISSUE THREAD

**Issue by acatonne** [nextcloud/groupfolders#970]
Creating a new groupfolder in settings/admin/groupfolders
=> if a folder already exist with the same name, it will be deleted. Files won't appear in trash, so its lost.

=> Testing so we can apply  groupfolders on existing folder

**Comment by Metzlmane** [comment]
If you remove the groupfolder the other one should appear again.
Does this also happen on your instance?

**Comment by wiswedel** [comment]
It doesn't really get deleted, it's just that the 2nd one wins. The first one just doesn't get displayed anymore.

This is not supposed to be an excuse, just a technical background info.

**Comment by ChristophWurst** [comment]
duplicate of https://github.com/nextcloud/groupfolders/issues/648
