### ISSUE TITLE
Group folder name containing a slash ("/") won't be listed in folder list

### ISSUE THREAD

**Issue by noresistence** [nextcloud/groupfolders#977]
A Group folder with a name containing a slash ("/") won't be listed in the folder list.

**Comment by PVince81** [comment]
it will, but the users need to create the parents manually as far as I could tell

For example if the group folder name is "base/one" then all the users need to create the "base" directory, then the folder will magically appear there.

**Comment by icewind1991** [comment]
https://github.com/nextcloud/groupfolders/pull/1380 explains the need to create the base directory in the readme.

I'm assuming that this issue was caused by not creating the base directory, feel free to reopen if this was not the case
