### ISSUE TITLE
Trashbin support

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/groupfolders#99]
I was not able to find something on this on the web. In Nextcloud 12 when i deleted something from a group folder, it showed up in my personal trashbin and i could restore it.

I recently updated to Nextcloud 13 and now when i delete a file from a group folder it doesn't show up in my personal trashbin anymore.

Is this how its supposed to work ? I really need a way to restore files which were accidentally deleted from group folders.

Thanks for your help

**Comment by rogatec** [comment]
This problem occurs also in Nextcloud 13.

How is everyone handling this issue?
If someone deletes a file in a group folder the file is also gone from the file system.
I am currently using rsync to backup the group folder without --delete parameter

**Comment by BloodyIron** [comment]
I've just been testing this app, and honestly, this reason alone makes this app completely a liability for my data.

Consider the following... what if a rogue admin just deletes a group folder? There is no restore, nor file retention, it's just done. What am I supposed to do to protect against this? Or hell, even just accidental "whoops clicked on the wrong one"?

This is COMPLETELY a blocker for me, and I am not going to use this app as a result of this.

This is a useful app _in concept_, but until this gets addressed, this SIGNIFICANTLY compromises data integrity in the nextCloud ecosystem.

**Comment by hriekehof** [comment]
I think its clear that the trashbin is a really needed feature. I'm very happy that someone from nextcloud is working on that :) 👍

**Comment by putt1ck** [comment]
@MorrisJobke is this an enhancement if some version of the functionality was previously available?

**Comment by hriekehof** [comment]
Also in Version 12 the trashbin didn't worked that well. Deleted files only appeard in there for a few minutes. If you forget to restore them directly they were gone.

**Comment by putt1ck** [comment]
@icewind1991 let me know if there's anything we can do to help

**Comment by BloodyIron** [comment]
Well, for me, I just started trialing the app. Since it has no trashbin tie-in, it breaks the whole restore ecosystem baked into nextCloud. As far as I'm concerned, this is _new_ functionality that is needed.

**Comment by gtchm** [comment]
This is EXTREMELY severe. Is it possible to have an ETA for a fix?

**Comment by BloodyIron** [comment]
I agree that this is extremely severe.

**Comment by gtchm** [comment]
At least, can we have a popup that warns for content being forever deleted?

**Comment by BloodyIron** [comment]
@gtchm while I understand why you propose such a thing, I must disagree with it on principle. I think it makes the breaking of the trash bin functionality acceptable. IMO, the fact group folders CAN break the trash bin functionality is a serious problem in-and-of-itself, as it breaks the consistent experience users generally would come to expect.

Adding a warning can make developers complacent about the discrepancy of features, that IMO shouldn't exist in the first place.

A user should _NEVER_ have to worry about whether the trash bin works for the scope they are working in or not.

**Comment by gtchm** [comment]
I understand what you are saying, but I believe we need urgent action on this matter to preserve the usability of this software, which I love, but w/out being able to retrieve accidentally deleted data, it is not usable. Unfortunately I'm not a programmer so I cannot help, but heck, I would be willing to pay to get this sorted. I have no clue on how this work in this community, so I'm asking genuinely... should we put like $50 each so the developer can invest time to fix this problem?

**Comment by pascalBokBok** [comment]
scary stuff. What is the timespan on getting the trashbin?
We will have to migrate back to non-group folders for now.

**Comment by zippytiff** [comment]
hi, just wondering how active this app is?

I just had a deep bug on passwords and i was fixed within 24 hours

ZT

**Comment by terrar** [comment]
Is there a timeline when trashbin and notification will work again?
I would really need this.

**Comment by terrar** [comment]
really?
not to answer is the best way to handle this bug?

**Comment by pascalBokBok** [comment]
@terrar , As another user I can say that mounting a folder on the server as external storage (local) instead solved our problem with missing trashbin and versions. That will basically give you the same as the group folder.

**Comment by ArnY** [comment]
Hello,

Nextcloud is working on it. It requires deep changes. They are planning to release those with NC 15.

**Comment by icewind1991** [comment]
Trashbin and versioning support is currently in master and should work with the latest NC15 rc.

**Comment by hriekehof** [comment]
Works for me too now 👍

**Comment by winstonford** [comment]
version 15.0.2 

I moved a group folder, got 423 lock errors, and the trash immediately grew to consume all disk space:
`/var/snap/nextcloud/common/nextcloud/data/__groupfolders/trash/2`
`19.7 GiB [##########]`

doing 
`nextcloud.occ trashbin:cleanup`
does not empty the above trash.

How do I empty group trash?

**Comment by winstonford** [comment]
One of my machines just connected, begin to sync, and group folders trash instantly grew by 2gb.

`/var/snap/nextcloud/common/nextcloud/data/__groupfolders/trash/2`
`21.9 GiB [##########]`

**Comment by dirkpape** [comment]
this happens for me to. Version 15.0.4

> One of my machines just connected, begin to sync, and group folders trash instantly grew by 2gb.
> 
> `/var/snap/nextcloud/common/nextcloud/data/__groupfolders/trash/2`
> `21.9 GiB [##########]`

this happens for me, too.

**Comment by Beeez** [comment]
Is this a thing at all yet? I had ran out of storage due to a Group Folders trash bin becoming full.

**Comment by biva** [comment]
@icewind1991 I see new messages after this issues has been closed. I hesitate to use GroupFolders in my NC instance, but those messages are showing remaining important issues regarding the trash management: is it really solved? Thanks

**Comment by feutl** [comment]
Seems still not properly integrated.
`trashbin_retention_obligation` does not work for group folders which is not good and fills up the disk.

**Comment by mesiah1970-haydar** [comment]
Hello and Good morning,

yes I agree, the group folders trashbin should expire. Maybe we can achieve this with a extra option in the group folder app, or create a new group folder occ command. It could be something simple, which could help people to get out of the trashbin mess. Please help us!

Rgds

Haydar

**Comment by ntinti** [comment]
Any news about this?

**Comment by mesiah1970-haydar** [comment]
unfortunately not, depends when the developers have time. I cannot accuse them, since they are definitely involved in other projects. Maybe one of them has mercy about us;-)

**Comment by SimJoSt** [comment]
There is a separate issue for this here: https://github.com/nextcloud/groupfolders/issues/345  
Please post comments and experiences regarding this there.
