### ISSUE TITLE
Subfolder created without permission

### ISSUE THREAD

**Issue by Knniff** [nextcloud/groupfolders#996]
A user had read and share permissions through a group in a folder. This user created subfolders and filled them with files which could only be seen by the the same user and not by anyone else. After giving them all permissions nothing changed. After the permission change they created another folder and over the next few minutes all the other folders and files appeared slowly, e.g. first a folder, then the first file in it, then the next etc. 

Using NextCloudPi  v1.26.2 with Nextcloud v17.0.8 and Groupfolders v5.0.5
If the problem is fixed with a newer version, you can just close this issue.

**Comment by pierreozoux** [comment]
Your story is confusing since the begining.

A user with read only access can't create subfolder (or we have a serious bug :) )

About the slowliness, running on raspi might be slow, indeed.

Do you still have issues? If not, please close it. If you do, please try to reexplain, thanks :)

**Comment by Knniff** [comment]
If my memory serves me right, we had a Groupfolder with all rights for every user on the top level and then we restricted subfolders. In one subfolder a user (more specifically the group in which the user was) had only read and share permissions. He messaged me that he had created folders and uploaded files there, but no one besides him could see them. We then gave him full permissions for that folder and we still couldnt the the data. We asked him if he could create another folder, now that he had access and after that the folders and files slowly appeared.
This only happend once so i dont really have any more info about the issue, besides that he most likely used the windows application to create the files and folders.

**Comment by fschrempf** [comment]
Sorry, but also can't make anything of this report at the moment. Without a clearly reproducible series of actions to trigger the behavior I don't really see what can be done. Let's mark this as stale and close it soon if nobody objects.
